### ISSUE TITLE
Loading Minecraft with OpenJ9 crashes upon startup

### ISSUE THREAD

**Issue by Owen1212055** [FabricMC/fabric#1019]
```
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
--
  | at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194)
  | at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
  | at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
  | at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
  | Caused by: java.lang.reflect.InvocationTargetException
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  | at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
  | ... 3 more
  | Caused by: java.lang.ExceptionInInitializerError
  | at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:193)
  | at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:182)
  | at java.base/java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method)
  | at java.base/java.lang.invoke.MethodHandle.getAdditionalBsmArg(MethodHandle.java:935)
  | at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1084)
  | at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries.java:50)
  | at net.minecraft.util.registry.Registry.<clinit>(Registry.java:237)
  | at net.minecraft.Bootstrap.initialize(Bootstrap.java:42)
  | at net.minecraft.client.main.Main.main(Main.java:137)
  | ... 8 more
  | Caused by: java.lang.NullPointerException
  | at net.minecraft.util.registry.BuiltinRegistries.add(BuiltinRegistries.java:88)
  | at net.minecraft.structure.pool.StructurePools.register(StructurePools.java:20)
  | at net.minecraft.structure.pool.StructurePools.<clinit>(StructurePools.java:13)
  | ... 15 more

```
I tried many things to resolve this, such as clearing global and project gradle cache and redoing my workspace twice which yielded no results.

After switching to Hotspot, this issue disappeared entirely. 

Not sure what else to put here. If you need any extra information I will provide.

**Comment by i509VCB** [comment]
This issue occurs with vanilla and is being tracked here:
https://github.com/eclipse/openj9/issues/10356

For now, this mod may help: https://github.com/iczero/fabric-openj9compat
