### ISSUE TITLE
Crash when creating world in 1.16.1

### ISSUE THREAD

**Issue by IronBoi62** [FabricMC/fabric#1022]
CrashLog:

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 17/08/20 16:22
Description: Exception initializing level

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_3815.<clinit>(class_3815.java:52)
	at net.minecraft.class_3813.method_27221(class_3813.java:20)
	at net.minecraft.class_3813.method_16753(class_3813.java:28)
	at net.minecraft.class_3211$class_3212.method_28667(class_3211.java:32)
	at net.minecraft.class_3211$class_3212.method_16655(class_3211.java:23)
	at net.minecraft.class_3195.method_28657(class_3195.java:249)
	at net.minecraft.class_5312.method_28622(class_5312.java:27)
	at net.minecraft.class_2794.method_28508(class_2794.java:268)
	at net.minecraft.class_2794.method_16129(class_2794.java:259)
	at net.minecraft.class_2806.method_16556(class_2806.java:51)
	at net.minecraft.class_2806$$Lambda$1729/1275603581.doWork(Unknown Source)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at net.minecraft.class_3898$$Lambda$6283/188924414.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at net.minecraft.class_3898$$Lambda$6268/1596152229.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3900$$Lambda$6281/1966947494.run(Unknown Source)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [structhelp.mixins.json:StructurePoolBasedGeneratorOuterMixin] from phase [DEFAULT] in config [structhelp.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 36 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> structhelp.mixins.json:StructurePoolBasedGeneratorOuterMixin -> Apply Methods -> (Lnet/minecraft/class_5455;Lnet/minecraft/class_3812;Lnet/minecraft/class_3778$class_3779;Lnet/minecraft/class_2794;Lnet/minecraft/class_3485;Lnet/minecraft/class_2338;Ljava/util/List;Ljava/util/Random;ZZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V:handler$bka000$extractRoomMinMax -> Transform LVT -> var=registryManager -> desc=Lnet/minecraft/class_5455;]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:490)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:523)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:509)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 36 more
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.minecraft.class_5455
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:949)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:909)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformLVT(MixinTargetContext.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:449)
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_3815.<clinit>(class_3815.java:52)
	at net.minecraft.class_3813.method_27221(class_3813.java:20)
	at net.minecraft.class_3813.method_16753(class_3813.java:28)
	at net.minecraft.class_3211$class_3212.method_28667(class_3211.java:32)
	at net.minecraft.class_3211$class_3212.method_16655(class_3211.java:23)
	at net.minecraft.class_3195.method_28657(class_3195.java:249)
	at net.minecraft.class_5312.method_28622(class_5312.java:27)
	at net.minecraft.class_2794.method_28508(class_2794.java:268)
	at net.minecraft.class_2794.method_16129(class_2794.java:259)
	at net.minecraft.class_2806.method_16556(class_2806.java:51)
	at net.minecraft.class_2806$$Lambda$1729/1275603581.doWork(Unknown Source)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at net.minecraft.class_3898$$Lambda$6283/188924414.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at net.minecraft.class_3898$$Lambda$6268/1596152229.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3900$$Lambda$6281/1966947494.run(Unknown Source)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (152,3,40), Chunk: (at 8,0,8 in 9,2; contains blocks 144,0,32 to 159,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:386)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:334)
	at net.minecraft.class_1132.method_3823(class_1132.java:69)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:647)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at net.minecraft.server.MinecraftServer$$Lambda$6175/1606720796.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 59309328 bytes (56 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 2
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.10.1+1.16.1
		appleskin: AppleSkin 1.0.11
		artifice: Artifice 0.8.1+1.16.1
		artofalchemy: Art of Alchemy 1.0.0-rc2+1.16.1
		astromine: Astromine 1.5.2
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		betternether: Better Nether 3.5.4
		betterthanmending: BetterThanMending 1.2.0
		blue_endless_jankson: jankson +
		bunch-o-trinkets: Bunch O' Trinkets 1.0.1
		byg: BYG 1.0.13
		campanion: Campanion 1.1.13+build.35
		cardinal-components-base: Cardinal Components API (base) 2.4.2
		cardinal-components-block: Cardinal Components API (blocks) 2.4.2
		cardinal-components-chunk: Cardinal Components API (chunks) 2.4.2
		cardinal-components-entity: Cardinal Components API (entities) 2.4.2
		cardinal-components-item: Cardinal Components API (items) 2.4.2
		cardinal-components-level: Cardinal Components API (world saves) 2.4.2
		cardinal-components-util: Cardinal Components API (utilities) 2.4.2
		cardinal-components-world: Cardinal Components API (worlds) 2.4.2
		chainmail: Chainmail 0.3.0
		cinderscapes: Cinderscapes 1.0.7+build.43-1.16.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.6.0
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.0.7
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cotton: Cotton 1.0.5
		cotton-cauldron: Cotton Cauldron 1.0.4
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.5
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		creativebuttonmover: Creative Button Mover 0.2.5
		dark-loading-screen: Dark Loading Screen 1.4.2
		dynamicfps: Dynamic FPS 1.1.4
		dynamicsoundfilters: Dynamic Sound Filters 1.1.2+1.16.1
		enderitemod: Enderite Mod 1.1.3
		endreborn: End: Rebellion 1.7
		expandedstorage: ExpandedStorage 5.3.16
		experimentaway: ExperimentAway 1.0.0
		extraalchemy: Extra Alchemy 1.2.1
		extrapieces: Extra Pieces 2.9.0
		fabric: Fabric API 0.17.0+build.386-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-diagonal-panes: Fabric Diagonal Panes 0.3.0
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-furnaces: Fabric Furnaces 1.3.1-1.16.1
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-language-kotlin: Fabric Language Kotlin 1.3.71+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+e83e061c02
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.7+2242e77202
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+be551d3c02
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.1+91fca5cd02
		fabricloader: Fabric Loader 0.9.1+build.205
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fiber: fiber 0.23.0-1
		glassdoor: Glass Doors 1.4.4-1.16
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		illuminations: Illuminations 1.0.5
		indrev: Industrial Revolution 1.4.9-BETA
		inventorysorter: Inventory Sorter 1.7.1-1.16
		itemscroller: Item Scroller 0.15.0-dev.20200630.022843
		jankson: Jankson 3.0.0+j1.2.0
		kyrptconfig: Kytpt Config 1.0.4-1.16
		lambdynlights: LambDynamicLights 1.2.2+1.16.1
		libblockattributes_core: LibBlockAttributes (Core) 0.7.1-pre.4
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.7.1-pre.4
		libblockattributes_items: LibBlockAttributes (Items) 0.7.1-pre.4
		libcd: LibCapableData 2.5.0+1.16.1
		libgui: LibGui 2.2.0+1.16.1
		libstructure: Libstructure 1.3
		linkedstorage: Linked Storage 1.3.6-1.16
		lithium: Lithium 0.5.1
		magna: Magna 1.3.2-1.16.1
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		mambience: MAmbience 2.1.0-1.16
		minecraft: Minecraft 1.16.1
		modmenu: Mod Menu 1.14.5+build.30
		moenchantments: Mo'Enchantments 1.12.4-beta2
		more_gems: More Gems 1.0.48
		mostructures: Mo' Structures 1.0.0-pre2+mc.1.16
		netheritehorsearmor: Netherite Horse Armor 0.4.2-1.16.1
		ninjaphenix-container-lib: NinjaPhenix's Container Library 1.1.5
		okzoomer: Ok Zoomer 4.0.0-alpha.5+1.16.1
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.71
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.5
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.5
		parchment: Parchment 1.0.2+1.15.2
		patchouli: Patchouli 1.16-39-FABRIC
		phosphor: Phosphor 0.6.0+build.7
		playerabilitylib: Pal 1.2.0
		rare-ice: Rare Ice 0.2.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.3.4+build.64
		ringsofascension: Rings of Ascension 1.0.7
		roughlyenoughitems: Roughly Enough Items 4.12.0
		shapes: Shapes 2.0.0+build.10
		sodium: Sodium 0.1.0
		spinnery: Spinnery 3.1.14
		spruceui: SpruceUI 1.5.8
		static-content: Static Content 1.0.0-1.16.1
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		structure-helpers: Structure Helpers 3.0.0
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.4.5+build.88
		terraform: Terraform 2.1.7+build.31
		thallium: Thallium 1.6
		torohealth: ToroHealth Damage Indicators 1.16.1-fabric-1
		trade: Trade 1.1.0
		trapexpansion: Trap Expansion 1.3.2
		trinkets: Trinkets 2.6.4
		vanilla-hammers: Vanilla Hammers 2.0.4-1.16.1
		vanillaexcavators: Vanilla Excavators 1.1.0
		waila: Hwyla 1.9.22
		winged: Winged Mod 1.16-1.2
		wolveswitharmor: Wolves With Armor 1.5.1-1.16.1
		wrenchable: Wrenchable 1.0.0+1.16.1
		xaerominimap: Xaero's Minimap 20.20.0
		xaeroworldmap: Xaero's World Map 1.10.0
	Patchouli open book context: n/a
	Player Count: 0 / 8; []
	Data Packs: vanilla (incompatible), fabric/indrev, fabric/betternether, fabric/lambdynlights, fabric/astromine, fabric/iamverysmart, fabric/bunch-o-trinkets, fabric/techreborn, fabric/fabric-tool-attribute-api-v1, fabric/enderitemod, fabric/rare-ice, fabric/structure-helpers, fabric/mostructures, fabric/endreborn, fabric/expandedstorage, fabric/trapexpansion, fabric/adorn, fabric/extraalchemy, fabric/linkedstorage, fabric/libcd, fabric/vanilla-hammers, fabric/vanillaexcavators, fabric/netheritehorsearmor, fabric/campanion, fabric/wolveswitharmor, fabric/glassdoor, fabric/artofalchemy, fabric/more_gems, fabric/cotton-commons, fabric/winged, fabric/fabric-furnaces, fabric/byg, fabric/cinderscapes, extrapieces:ep_data, linkedstorage:enderstorage
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by haykam821** [comment]
This doesn't seem to be a problem in Fabric API.

**Comment by IronBoi62** [comment]
> This doesn't seem to be a problem in Fabric API.

For what then?

**Comment by ghost** [comment]
Can you try with https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes/files/3027715 and see if that points you in the right direction?

**Comment by IronBoi62** [comment]
> Can you try with https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes/files/3027715 and see if that points you in the right direction?

Sorry for late response. I will try that.

**Comment by uiytt** [comment]
Does this happen without any mods (except fabric-api).
If not, you can assume this is due to one of the mods, your main solution is probably to remove mods one by one until you found the one causing this..

**Comment by i509VCB** [comment]
Closing since this is not an issue with Fabric API and lack of feedback. If you need further assistance, please join the Fabric discord https://discord.gg/v6v4pMv
