### ISSUE TITLE
about intelij

### ISSUE THREAD

**Issue by Succubussix** [FabricMC/fabric#1063]
```
Connected to the target VM, address: '127.0.0.1:54160', transport: 'socket'
[08:12:53] [main/INFO] (FabricLoader) Loading for game Minecraft 1.16.2
[08:12:53] [main/INFO] (Fabric|Loader) [FabricLoader] Loading 41 mods: fabric-screen-handler-api-v1@1.1.0+872498414e, minecraft@1.16.2, fabric-renderer-api-v1@0.3.0+8bcfced84e, fabric-networking-blockentity-v0@0.2.5+b50ffc7b4e, fabric-keybindings-v0@0.2.0+3fa9f7c54e, fabric-command-api-v1@1.0.8+5ce533984e, fabricloader@0.9.3+build.207, fabric-tool-attribute-api-v1@1.2.2+ccce563e4e, fabric-renderer-indigo@0.4.0+8bcfced84e, fabric-structure-api-v1@1.0.1+fb0d9b0e4e, fabric-containers-v0@0.1.8+045df74f4e, fabric-object-builder-api-v1@1.7.0+432ea1884e, fabric-crash-report-info-v1@0.1.2+b7f9825d4e, fabric-events-interaction-v0@0.4.0+e2e6cdad4e, fabric-item-api-v1@1.1.0+29679fd64e, fabric-game-rule-api-v1@1.0.1+91555cd14e, fabric-api-base@0.1.3+12a8474c4e, fabric-rendering-v0@1.1.0+534104904e, fabric-rendering-v1@1.3.0+432ea1884e, fabric-key-binding-api-v1@1.0.1+730711c64e, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d4e, fabric-resource-loader-v0@0.3.1+facf3bbf4e, fabric-textures-v0@1.0.4+eae12eb84e, fabric-content-registries-v0@0.1.9+059ea8664e, fabric-tag-extensions-v0@1.0.3+ac8e8c594e, fabric-rendering-fluids-v1@0.1.11+fb0d9b0e4e, fabric-registry-sync-v0@0.4.5+fcdfdfa14e, fabric-commands-v0@0.2.0+52d308364e, fabric-blockrenderlayer-v1@1.1.4+c6a8ea894e, fabric-lifecycle-events-v1@1.2.0+74cc3b204e, fabric-mining-levels-v0@0.1.2+b764ce994e, fabric-renderer-registries-v1@2.1.0+e2862de64e, fabric-events-lifecycle-v0@0.2.0+16acbe5b4e, fabric-loot-tables-v1@1.0.1+432ea1884e, fabric@0.20.1+build.401-1.16, tomie@1.0.0, fabric-particles-v1@0.2.2+fb0d9b0e4e, fabric-item-groups-v0@0.2.0+438f96364e, fabric-models-v0@0.1.0+dfdb52d64e, fabric-object-builders-v0@0.7.0+432ea1884e, fabric-networking-v0@0.1.10+e00ecb5f4e
[08:12:54] [main/INFO] (mixin) SpongePowered MIXIN Subsystem Version=0.8.1 Source=file:/C:/Users/......./.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.8.1+build.21/94da90bdbee9f95bf6d6c41ca87943419a0b5624/sponge-mixin-0.8.1+build.21.jar Service=Knot/Fabric Env=CLIENT
[08:12:54] [main/INFO] (Fabric|MixinBootstrap) Loaded Fabric development mappings for mixin remapper!
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/io/RecursiveDeleteOption
```

adding guava solves it then next error is 

```
[08:23:17] [main/WARN] (mixin) @Mixin target net/minecraft/tag/Tag$1 is public in fabric-tag-extensions-v0.mixins.json:MixinTagImpl and should be specified in value
[08:23:17] [main/WARN] (mixin) @Mixin target net/minecraft/tag/RequiredTagList$TagWrapper is public in fabric-tag-extensions-v0.mixins.json:MixinTagImpl and should be specified in value
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	... 3 more
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableMap.toImmutableMap(Ljava/util/function/Function;Ljava/util/function/Function;)Ljava/util/stream/Collector;
	at net.minecraft.state.StateManager.method_28484(StateManager.java:64)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at net.minecraft.state.StateManager.<init>(StateManager.java:63)
	at net.minecraft.state.StateManager$Builder.build(StateManager.java:166)
	at net.minecraft.block.Block.<init>(Block.java:190)
	at net.minecraft.block.AirBlock.<init>(AirBlock.java:10)
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:892)
	at net.minecraft.world.gen.surfacebuilder.SurfaceBuilder.<clinit>(SurfaceBuilder.java:87)
	at net.minecraft.world.gen.surfacebuilder.ConfiguredSurfaceBuilders.<clinit>(ConfiguredSurfaceBuilders.java:36)
	at net.minecraft.util.registry.BuiltinRegistries.method_30573(BuiltinRegistries.java:76)
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries.java:97)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries.java:96)
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:555)
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:38)
	at net.minecraft.client.main.Main.main(Main.java:123)
	... 8 more
Disconnected from the target VM, address: '127.0.0.1:54290', transport: 'socket'

Process finished with exit code 1
```

 kind of guava you are using guys?

I'm using  guava 21.0 the latest one which is 29.x doesnt help also that toImmutableMap function is gone.. i choose 21 because i search the repo here and u are using 21

this was working fine at doing eclipse project.. then I switch to intelij ... after i execute 
```
gradlew.bat idea 
```
everything works except for this unknown guava thingy XD whenever u click this
![image](https://user-images.githubusercontent.com/12135498/92315820-02824b80-f01e-11ea-8c67-b754d6628250.png)

.. also take note i dont generate them in the same folder.. i put them on seperate folder just to see.

**Comment by Succubussix** [comment]
xD I clone it again.. from that I enable offline mode. then transfer all the gradle prop. also i needed to invalidate catches restart every time I want it to force to download dependency this dint happen to me on eclipse xD also clicking build will just success doesn't even download if I edit Gradle dependency. I guess i can close this.
