### ISSUE TITLE
Why run normal in dev but build jar will crash

### ISSUE THREAD

**Issue by 2A5F** [FabricMC/fabric#1071]
log
```log
[00:13:10] [main/INFO]: Loading for game Minecraft 1.16.2
[00:13:11] [main/INFO]: [FabricLoader] Loading 48 mods: fabric-renderer-api-v1@0.3.0+8bcfced84e, fabric-screen-handler-api-v1@1.1.0+872498414e, minecraft@1.16.2, fabric-networking-blockentity-v0@0.2.5+b50ffc7b4e, fabric-keybindings-v0@0.2.0+3fa9f7c54e, fabric-command-api-v1@1.0.8+5ce533984e, fabricloader@0.9.3+build.207, fabric-tool-attribute-api-v1@1.2.2+ccce563e4e, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.0, fabric-structure-api-v1@1.0.1+fb0d9b0e4e, fabric-renderer-indigo@0.4.0+8bcfced84e, fabric-containers-v0@0.1.8+045df74f4e, fabric-object-builder-api-v1@1.7.0+432ea1884e, fabric-item-api-v1@1.1.0+29679fd64e, fabric-crash-report-info-v1@0.1.2+b7f9825d4e, fabric-events-interaction-v0@0.4.0+e2e6cdad4e, fabric-game-rule-api-v1@1.0.1+91555cd14e, fabric-language-kotlin@1.4.0+build.1, fabric-api-base@0.1.3+12a8474c4e, fabric-rendering-v0@1.1.0+534104904e, fabric-rendering-v1@1.3.0+432ea1884e, fabric-key-binding-api-v1@1.0.1+730711c64e, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.3.9, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d4e, fabric-resource-loader-v0@0.3.1+facf3bbf4e, fabric-textures-v0@1.0.4+eae12eb84e, necessary@0.2.0, org_jetbrains_kotlin_kotlin-reflect@1.4.0, fabric-content-registries-v0@0.1.9+059ea8664e, fabric-tag-extensions-v0@1.0.3+ac8e8c594e, fabric-rendering-fluids-v1@0.1.11+fb0d9b0e4e, org_jetbrains_kotlin_kotlin-stdlib@1.4.0, fabric-commands-v0@0.2.0+52d308364e, fabric-registry-sync-v0@0.4.5+fcdfdfa14e, fabric-blockrenderlayer-v1@1.1.4+c6a8ea894e, fabric-lifecycle-events-v1@1.2.0+74cc3b204e, fabric-mining-levels-v0@0.1.2+b764ce994e, fabric-renderer-registries-v1@2.1.0+e2862de64e, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.0, fabric-loot-tables-v1@1.0.1+432ea1884e, fabric-events-lifecycle-v0@0.2.0+16acbe5b4e, fabric@0.20.1+build.401-1.16, fabric-particles-v1@0.2.2+fb0d9b0e4e, fabric-models-v0@0.1.0+dfdb52d64e, fabric-item-groups-v0@0.2.0+438f96364e, fabric-networking-v0@0.1.10+e00ecb5f4e, fabric-object-builders-v0@0.7.0+432ea1884e, org_jetbrains_annotations@20.0.0
[00:13:11] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.1 Source=file:/C:/Users/Administrator/Desktop/aa/sub/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[00:13:11] [main/WARN]: Reference map 'necessary-refmap.json' for necessary.mixins.json could not be read. If this is a development environment you can ignore this message
[00:13:16] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'necessary'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(Main.java:93) [intermediary-server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy35.onInitialize(Unknown Source) ~[?:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.fabricmc.loader.util.DefaultLanguageAdapter$1.invoke(DefaultLanguageAdapter.java:122) ~[fabric-server-launch.jar:?]
	at com.sun.proxy.$Proxy35.onInitialize(Unknown Source) ~[?:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more
Caused by: java.lang.UnsupportedOperationException
	at com.sun.nio.zipfs.ZipPath.toFile(ZipPath.java:597) ~[zipfs.jar:1.8.0_131]
	at co.volight.necessary.lang.Lang.reg(Lang.java:24) ~[necessary-0.2.0.jar:?]
	at co.volight.necessary.lang.Lang.reg$default(Lang.java:22) ~[necessary-0.2.0.jar:?]
	at co.volight.necessary.NecKt.init(NecKt.java:19) ~[necessary-0.2.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.fabricmc.loader.util.DefaultLanguageAdapter$1.invoke(DefaultLanguageAdapter.java:122) ~[fabric-server-launch.jar:?]
	at com.sun.proxy.$Proxy35.onInitialize(Unknown Source) ~[?:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more
```
source
```kotlin
@Mixin(ServerPlayNetworkHandler::class)
class LangGetMixin {
    @Inject(at = [At("HEAD")], method = ["Lnet/minecraft/server/network/ServerPlayNetworkHandler;onClientSettings(Lnet/minecraft/network/packet/c2s/play/ClientSettingsC2SPacket;)V"])
    private fun onClientSettings(clientSettingsC2SPacket: ClientSettingsC2SPacket?, info: CallbackInfo) {
        if (clientSettingsC2SPacket == null || clientSettingsC2SPacket !is ClientSettingsC2SPacketWithLanguage) return
        val language = clientSettingsC2SPacket.getLanguage()
        val player = (this as ServerPlayNetworkHandler).player
        PlayerLangInfo.playerLanguage[player.uuid] = language.toLowerCase()
    }
}

@Mixin(ClientSettingsC2SPacket::class)
interface ClientSettingsC2SPacketWithLanguage {
    @Accessor("Lnet/minecraft/network/packet/c2s/play/ClientSettingsC2SPacket;language:Ljava/lang/String;")
    fun getLanguage(): String
}
```

**Comment by modmuss50** [comment]
Your mod here: https://github.com/2A5F/Necessary/blob/4a700159a0eaf4741a495d4235e08eb6462d914a/src/main/kotlin/co/volight/necessary/lang/Lang.kt#L24 is trying to covert a java NIO path to a file. 

This is not a safe assumption to make, thus this crash.

You MUST always use java NIO to read files from a mod jar, or the mod jar its self as it can be loaded from memory via the jar in jar system

**Comment by 2A5F** [comment]
@modmuss50 thanks

**Comment by 2A5F** [comment]
But how to solve this
```
Reference map 'necessary-refmap.json' for necessary.mixins.json could not be read. If this is a development environment you can ignore this message
```

**Comment by 2A5F** [comment]
Solved, Kotlin mixin will not generate refmap.json
