### ISSUE TITLE
[1.14.4] Fabric API 0.23.1 crashes the game with loader version 0.10.6

### ISSUE THREAD

**Issue by anaizy31** [FabricMC/fabric#1157]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 11/9/20 11:16 PM
Description: Tesselating block in world - Indigo Renderer

java.lang.NoSuchMethodError: java.nio.IntBuffer.position(I)Ljava/nio/IntBuffer;
	at net.minecraft.class_287.bufferFast(class_287.java:1166)
	at net.minecraft.class_287.fabric_putQuad(class_287.java:1160)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractQuadRenderer.bufferQuad(AbstractQuadRenderer.java:74)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractQuadRenderer.tesselateSmooth(AbstractQuadRenderer.java:90)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.renderQuad(TerrainFallbackConsumer.java:140)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:99)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:58)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tesselateBlock(TerrainRenderContext.java:75)
	at net.minecraft.class_851.redirect$zbh000$hookChunkBuildTesselate(class_851.java:627)
	at net.minecraft.class_851.method_3652(class_851.java:210)
	at net.minecraft.class_845.method_3615(class_845.java:90)
	at net.minecraft.class_846.method_3627(class_846.java:178)
	at net.minecraft.class_761.method_3273(class_761.java:911)
	at net.minecraft.class_757.method_3178(class_757.java:832)
	at net.minecraft.class_757.method_3188(class_757.java:766)
	at net.minecraft.class_757.method_3192(class_757.java:630)
	at net.minecraft.class_310.method_1523(class_310.java:954)
	at net.minecraft.class_310.method_1514(class_310.java:410)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.class_287.bufferFast(class_287.java:1166)
	at net.minecraft.class_287.fabric_putQuad(class_287.java:1160)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractQuadRenderer.bufferQuad(AbstractQuadRenderer.java:74)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractQuadRenderer.tesselateSmooth(AbstractQuadRenderer.java:90)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.renderQuad(TerrainFallbackConsumer.java:140)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:99)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:58)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)

-- Block being tesselated --
Details:
	Block: Block{minecraft:bedrock}
	Block location: World: (-224,0,-64), Chunk: (at 0,0,0 in -14,-4; contains blocks -224,0,-64 to -209,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tesselateBlock(TerrainRenderContext.java:75)
	at net.minecraft.class_851.redirect$zbh000$hookChunkBuildTesselate(class_851.java:627)
	at net.minecraft.class_851.method_3652(class_851.java:210)
	at net.minecraft.class_845.method_3615(class_845.java:90)
	at net.minecraft.class_846.method_3627(class_846.java:178)
	at net.minecraft.class_761.method_3273(class_761.java:911)
	at net.minecraft.class_757.method_3178(class_757.java:832)
	at net.minecraft.class_757.method_3188(class_757.java:766)

-- Affected level --
Details:
	All players: 1 total; [class_746['player'/1, l='MpServer', x=-216.50, y=4.00, z=-58.50]]
	Chunk stats: Client Chunk Cache: 729, 441
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-224,4,-64), Chunk: (at 0,0,0 in -14,-4; contains blocks -224,0,-64 to -209,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 19 game time, 19 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:421)
	at net.minecraft.class_310.method_1587(class_310.java:1923)
	at net.minecraft.class_310.method_1514(class_310.java:425)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2526116792 bytes (2409 MB) / 3077570560 bytes (2935 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
	Fabric Mods: 
		fabric: Fabric API 0.23.1+1.14
		fabric-api-base: Fabric API Base 0.1.2+28f8190f42
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.1+28f8190f42
		fabric-command-api-v1: Fabric Command API (v1) 1.0.1+b534aa0c42
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+bfd4c99d42
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+28f8190f42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.2+28f8190f42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+28f8190f42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.1+e15ff88642
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+a35b4edd42
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+12fccc5b42
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+a35b4edd42
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+7ce6c57742
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+253decf242
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+85811ffb42
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+12fccc5b42
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.1+28f8190f42
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+c3dba7cb42
		fabric-models-v0: Fabric Models (v0) 0.1.0+933c24c242
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.1+28f8190f42
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e7757afe42
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.0.0+002fcb6542
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.3.0+39c719f942
		fabric-particles-v1: fabric-particles-v1 0.2.1+e9056b2242
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.3+28f8190f42
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+933c24c242
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.14+e15ff88642
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.2+28f8190f42
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.3+28f8190f42
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.2+28f8190f42
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.4+28f8190f42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+d423005742
		fabric-textures-v0: Fabric Textures (v0) 0.1.4+933c24c242
		fabricloader: Fabric Loader 0.10.6+build.214
		minecraft: Minecraft 1.14.4
	Launched Version: MultiMC5
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz

**Comment by i509VCB** [comment]
```
java.lang.NoSuchMethodError: java.nio.IntBuffer.position(I)Ljava/nio/IntBuffer;
```

Hmm this is interesting, I have no idea why a method on nio's IntBuffer would be missing. You are using java 8 so that should not be occurring? Could you provide any additional details about your setup?

**Comment by ramidzkh** [comment]
https://github.com/eclipse/jetty.project/issues/3244 provides an explanation. TL;DR - Compiled against a standard library newer than Java 8, even when emitting Java 8 bytecode

**Comment by i509VCB** [comment]
Seems to be what ramid mentioned after some discussion with modmuss and player, likely occurred while we moved to github actions. The released jars seem to be built using atleast jdk9, probably jdk15 based on how release action is setup.

Modmuss will try to release a fix and new build when he gets some time to fix the release action.

**Comment by i509VCB** [comment]
This has been fixed, please download new fabric api release
