### ISSUE TITLE
NullPointerException when falling out of world.

### ISSUE THREAD

**Issue by nbanyan** [FabricMC/fabric#1158]
Thankfully it doesn't seem to have any impact on the actual game, but our Fabric server gives a NullPointerException when we fall out of the world in the End.

`[12-Nov-2020 00:38:09] [INFO] nbanyan fell out of the world
[12-Nov-2020 00:38:10] [FATAL] Error executing task on Server
[12-Nov-2020 00:38:10] java.lang.NullPointerException: null
[12-Nov-2020 00:38:10] at net.minecraft.class_3204.method_14051(class_3204.java:202) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.class_3898.method_18713(class_3898.java:2734) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.class_3215.method_14096(class_3215.java:467) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.class_3244.method_12063(class_3244.java:931) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.class_2828.method_12272(class_2828.java:122) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.class_2828$class_2829.method_11054(class_2828.java:56) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
[12-Nov-2020 00:38:10] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
[12-Nov-2020 00:43:06] [Prisma] Saving server...
[12-Nov-2020 00:43:06] [INFO] Saving the game (this may take a moment!)
[12-Nov-2020 00:43:06] [INFO] Saved the game
[12-Nov-2020 00:43:28] [INFO] someotherguy fell out of the world
[12-Nov-2020 00:43:29] [FATAL] Error executing task on Server
[12-Nov-2020 00:43:29] java.lang.NullPointerException: null
[12-Nov-2020 00:43:29] at net.minecraft.class_3204.method_14051(class_3204.java:202) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.class_3898.method_18713(class_3898.java:2734) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.class_3215.method_14096(class_3215.java:467) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.class_3244.method_12063(class_3244.java:931) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.class_2828.method_12272(class_2828.java:122) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.class_2828$class_2829.method_11054(class_2828.java:56) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
[12-Nov-2020 00:43:29] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
[12-Nov-2020 00:45:21] [INFO] someotherguy fell out of the world
[12-Nov-2020 00:45:22] [FATAL] Error executing task on Server
[12-Nov-2020 00:45:22] java.lang.NullPointerException: null
[12-Nov-2020 00:45:22] at net.minecraft.class_3204.method_14051(class_3204.java:202) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_3898.method_18713(class_3898.java:2734) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_3215.method_14096(class_3215.java:467) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_3244.method_12063(class_3244.java:931) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_2828.method_12272(class_2828.java:122) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_2828$class_2829.method_11054(class_2828.java:56) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
[12-Nov-2020 00:45:22] [FATAL] Error executing task on Server
[12-Nov-2020 00:45:22] java.lang.NullPointerException: null
[12-Nov-2020 00:45:22] at net.minecraft.class_3204.method_14051(class_3204.java:202) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_3898.method_18713(class_3898.java:2734) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_3215.method_14096(class_3215.java:467) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_3244.method_12063(class_3244.java:931) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_2828.method_12272(class_2828.java:122) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_2828$class_2829.method_11054(class_2828.java:56) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
[12-Nov-2020 00:45:22] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]`

**Comment by i509VCB** [comment]
I don't see anything in the stacktrace leading me to believe anything was changed. Could you include a list of mods?

**Comment by nbanyan** [comment]
At the time we only had Fabric-API, invView, and Lithium installed.
Here's the server startup log from the same day.
`[12:03:03] [main/INFO]: Loading for game Minecraft 1.16.4
[12:03:03] [main/INFO]: [FabricLoader] Loading 44 mods: fabric-screen-handler-api-v1@1.1.0+872498413a, minecraft@1.16.4, fabric-renderer-api-v1@0.3.3+a4467d2a3a, fabric-networking-blockentity-v0@0.2.5+b50ffc7b3a, fabric-keybindings-v0@0.2.0+3fa9f7c53a, fabric-command-api-v1@1.0.9+a4467d2a3a, fabricloader@0.10.6+build.214, fabric-tool-attribute-api-v1@1.2.5+c93221003a, fabric-renderer-indigo@0.4.3+a4467d2a3a, fabric-structure-api-v1@1.1.0+f8ac1db23a, invview@1.1.0-1.16.2+, lithium@0.6.0, fabric-containers-v0@0.1.8+045df74f3a, fabric-object-builder-api-v1@1.9.2+a89534ab3a, fabric-events-interaction-v0@0.4.1+f8ac1db23a, fabric-crash-report-info-v1@0.1.2+b7f9825d3a, fabric-item-api-v1@1.2.0+f8ac1db23a, fabric-game-rule-api-v1@1.0.3+a4467d2a3a, fabric-api-base@0.2.0+9f0fb4b83a, fabric-rendering-v0@1.1.1+f8ac1db23a, fabric-rendering-v1@1.3.1+f8ac1db23a, fabric-key-binding-api-v1@1.0.1+730711c63a, fabric-rendering-data-attachment-v1@0.1.4+f8ac1db23a, fabric-resource-loader-v0@0.3.1+facf3bbf3a, fabric-textures-v0@1.0.5+a4467d2a3a, fabric-content-registries-v0@0.1.9+059ea8663a, fabric-tag-extensions-v0@1.0.3+ac8e8c593a, fabric-rendering-fluids-v1@0.1.12+f8ac1db23a, fabric-biome-api-v1@3.0.0+8367596d3a, fabric-registry-sync-v0@0.6.1+a4467d2a3a, fabric-commands-v0@0.2.0+52d308363a, fabric-blockrenderlayer-v1@1.1.4+c6a8ea893a, fabric-lifecycle-events-v1@1.2.0+74cc3b203a, fabric-mining-levels-v0@0.1.2+b764ce993a, fabric-renderer-registries-v1@2.2.0+f8ac1db23a, fabric-loot-tables-v1@1.0.1+432ea1883a, fabric-events-lifecycle-v0@0.2.0+16acbe5b3a, fabric@0.25.4+1.16, fabric-models-v0@0.1.1+f8ac1db23a, fabric-particles-v1@0.2.2+fb0d9b0e3a, fabric-item-groups-v0@0.2.1+a4467d2a3a, fabric-object-builders-v0@0.7.1+a4467d2a3a, fabric-networking-v0@0.1.10+e00ecb5f3a, lithium-api@0.6.0
[12:03:04] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/data/jar/custom.jar Service=Knot/Fabric Env=SERVER
[12:03:06] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-[12:03:15] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:03:16] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[12:03:16] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[12:03:16] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[12:03:16] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[12:03:16] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[12:03:16] [main/INFO]: Reloading ResourceManager: Default, afk display v1.1.0.zip, anti enderman grief v1.1.0.zip, anti-creeper-grief-master.zip, coordinates hud v1.2.0.zip, durability ping v1.1.0.zip, multiplayer sleep v2.5.2.zip, unlock all recipes v2.0.0.zip, Fabric Tool Attribute API (v1)
[12:03:18] [Worker-Main-12/INFO]: Loaded 7 recipes
[12:03:19] [Worker-Main-12/INFO]: Loaded 1000 advancements
[12:03:21] [main/INFO]: Applied 0 biome modifications to 0 of 79 new biomes in 1.562 ms
[12:03:21] [Server thread/INFO]: Starting minecraft server version 1.16.4
[12:03:21] [Server thread/INFO]: Loading properties
[12:03:21] [Server thread/INFO]: Default game type: SURVIVAL
[12:03:21] [Server thread/INFO]: Generating keypair
[12:03:22] [Server thread/INFO]: Starting Minecraft server on 139.99.139.72:25565
[12:03:22] [Server thread/INFO]: Using epoll channel type
[12:03:22] [Server thread/INFO]: Preparing level "world"
[12:03:23] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[12:03:26] [Server thread/INFO]: Preparing spawn area: 0%
[12:03:26] [Server thread/INFO]: Preparing spawn area: 0%
[12:03:26] [Server thread/INFO]: Preparing spawn area: 0%
[12:03:26] [Server thread/INFO]: Preparing spawn area: 0%
[12:03:26] [Server thread/INFO]: Preparing spawn area: 0%
[12:03:26] [Server thread/INFO]: Preparing spawn area: 0%
[12:03:26] [Server thread/INFO]: Preparing spawn area: 0%
[12:03:26] [Server thread/INFO]: Preparing spawn area: 0%
[12:03:27] [Server thread/INFO]: Preparing spawn area: 17%
[12:03:28] [Server thread/INFO]: Time elapsed: 5709 ms
[12:03:28] [Server thread/INFO]: Done (6.298s)! For help, type "help"`

**Comment by i509VCB** [comment]
Hmm the only thing I could see causing that issue is lithium or inv view. I would try updating those mods.

If you do have further questions please ask on discord since this issue tracker is for fabric api and not issues with mods.

**Comment by wh0oo** [comment]
Im seeing the same thing,

`Error executing task on Server
java.lang.NullPointerException: null
        at net.minecraft.class_3204.method_14051(class_3204.java:202) ~[intermediary-server.jar:?]
        at net.minecraft.class_3898.method_18713(class_3898.java:914) ~[intermediary-server.jar:?]
        at net.minecraft.class_3215.method_14096(class_3215.java:460) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12063(class_3244.java:953) ~[intermediary-server.jar:?]
        at net.minecraft.class_2828.method_12272(class_2828.java:122) ~[intermediary-server.jar:?]
        at net.minecraft.class_2828$class_2829.method_11054(class_2828.java:56) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:103) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:723) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:259) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
`

this is the latest fabricmc and modloader. i am using 2 mods that are lightweight and only kickoff when someone joins.
