### ISSUE TITLE
game crashes when i open it.

### ISSUE THREAD

**Issue by Melafefon7Hamutz** [FabricMC/fabric#1159]
when i open the game with fabric loader 1.16.4 it works fine but when i put the fabric api file in the mods folder it crashes the game.
crash report:

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 20:02 11/11/20
Description: Initializing game

net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'client' provided by 'fabric-renderer-indigo'
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193)
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:272)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101)
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186)
	... 13 more
Caused by: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
	at java.util.Properties.loadConvert(Properties.java:574)
	at java.util.Properties.load0(Properties.java:390)
	at java.util.Properties.load(Properties.java:341)
	at net.fabricmc.fabric.impl.client.indigo.Indigo.<clinit>(Indigo.java:105)
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193)
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:272)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44)

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.4
	OptiFine jar version: OptiFine_1.16.4_HD_U_G5
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:\Users\User\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.4_HD_U_G5\Optifine-mapped.jar
	OptiFabric error: <None>
Stacktrace:
	at net.minecraft.class_128.handler$zee000$fillSystemDetails(class_128.java:523)
	at net.minecraft.class_128.<init>(class_128.java:55)
	at net.minecraft.class_128.method_560(class_128.java:417)
	at net.minecraft.client.main.Main.main(Main.java:183)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- Initialization --
Details:

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7181441000 bytes (6848 MB) / 8959033344 bytes (8544 MB) up to 17179869184 bytes (16384 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.3.1
		carpet: Carpet Mod in Fabric 1.4.12
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.2
		fabric: Fabric API 0.25.4+1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b83a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+8367596d3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea893a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a3a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308363a
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f3a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8663a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db23a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b3a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db23a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b203a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1883a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce993a
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db23a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b3a
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f3a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab3a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a3a
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a3a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a3a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db23a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db23a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db23a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db23a
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db23a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf3a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498413a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db23a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c593a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a3a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+c93221003a
		fabricloader: Fabric Loader 0.10.6+build.214
		inventoryprofiles: Inventory Profiles 0.4.2
		itemscroller: Item Scroller 0.15.0-dev.20200912.221805
		litematica: Litematica 0.0.0-dev.20200913.215807
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		minecraft: Minecraft 1.16.4
		mm: Manningham Mills 2.1
		optifabric: OptiFabric 1.8.0
		shulkerboxtooltip: Shulker Box Tooltip 2.3.3+1.16.4
	Launched Version: fabric-loader-0.10.6+build.214-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0

**Comment by i509VCB** [comment]
Could you delete your `./config/fabric/indigo-renderer.properties` file and try to run the game again?

**Comment by Melafefon7Hamutz** [comment]
> Could you delete your `./config/fabric/indigo-renderer.properties` file and try to run the game again?

Worked!

**Comment by ManannJoshi** [comment]
can you tell the whole file directory?

**Comment by ManannJoshi** [comment]
same issue with me

**Comment by MKUKPL** [comment]
> can you tell the whole file directory?

its in AppData\Roaming\.minecraft\config\fabric
