### ISSUE TITLE
Install failure, /home/$user doesn't exist

### ISSUE THREAD

**Issue by LiSongMWO** [FabricMC/fabric#1160]
I'm trying to install fabric on my dedicated linux MC server. I put the universal jar installer in the minecraft folder and ran: ` sudo -u minecraft java -jar fabric-installer-0.6.1.51.jar server -dir . -mcversion 1.16.4`

And get:

```
Loading Fabric Installer: 0.6.1.51
Using latest loader version
Installing Fabric Loader 0.10.6+build.214(1.16.4) on the server
Exception in thread "main" java.lang.RuntimeException: Failed to install Server
        at net.fabricmc.installer.Main.main(Main.java:102)
Caused by: java.io.IOException: Could not create /home/minecraft/.cache/fabric-installer/libraries!
        at net.fabricmc.installer.server.ServerInstaller.install(ServerInstaller.java:50)
        at net.fabricmc.installer.server.ServerHandler.installCli(ServerHandler.java:63)
        at net.fabricmc.installer.Main.main(Main.java:100)
```

Minecraft is installed under `/opt/minecraft-1.16.4/` and ran as user `minecraft`. The user `minecraft` is a system user with non existent home directory `/home/minecraft` and with shell set to `/bin/nologin`.  There are multiple minecraft instances running under this user.

The install script tries to install something into the user's home folder. This limits the use of multiple different minecraft versions and is likely to fail with systems that are securely configured (e.g. service accounts don't have home directories).

**Comment by LiSongMWO** [comment]
My bad, didn't realize the installer was a different project.
