### ISSUE TITLE
How to run on tlantcher?

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#1190]
Hello, i complied a mod which i was develuping. i tried compilling it and tried running it on tlancher and i got this error : 
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'modid'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: modid:Icecream
	at net.minecraft.class_2960.<init>(class_2960.java:41)
	at net.minecraft.class_2960.<init>(class_2960.java:50)
	at net.fabricmc.example.ExampleMod.onInitialize(ExampleMod.java:15)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2211/257344160.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
```
code : 

[fabric-example-mod-master.zip](https://github.com/FabricMC/fabric/files/5614077/fabric-example-mod-master.zip)

**Comment by NikunjChiluvuri** [comment]
sorry wrong repo

**Comment by pluiedev** [comment]
TLauncher is not supported here as it enables piracy of the game. Please use another legitimate launcher, such as the vanilla launcher, MultiMC or GDLauncher.

**Comment by YTG1234** [comment]
Stop. This is not the correct repo and I don't think anyone will want to help you with this (plus your mod has so many wrong things - have you read the wiki?).
