### ISSUE TITLE
Elytras can cause the game to crash when custom armor renderers are used.

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#1225]
```
[14:40:11] [main/FATAL] (Minecraft) Reported exception thrown!
net.minecraft.util.crash.CrashException: Rendering entity in world
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:505) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1007) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:624) [minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:187) [minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.6-v2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.6-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.6-v2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.NoSuchFieldError: armorModelProvider
	at net.minecraft.item.Item.fabric_getArmorModelProvider(Item.java:2036) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.fabricmc.fabric.impl.client.rendering.ArmorRenderingRegistryImpl.getArmorModel(ArmorRenderingRegistryImpl.java:58) ~[fabric-rendering-v1-1.4.0+6a2618f53a@net.fabricmc.yarn.1_16_4.1.16.4+build.6-v2.jar:?]
	at net.fabricmc.fabric.api.client.rendering.v1.ArmorRenderingRegistry.getArmorModel(ArmorRenderingRegistry.java:115) ~[fabric-rendering-v1-1.4.0+6a2618f53a@net.fabricmc.yarn.1_16_4.1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.handler$zhe001$selectArmorModel(ArmorFeatureRenderer.java:1088) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.getArmor(ArmorFeatureRenderer.java:95) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.render(ArmorFeatureRenderer.java:35) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.render(ArmorFeatureRenderer.java:29) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.render.entity.LivingEntityRenderer.render(LivingEntityRenderer.java:128) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer.java:63) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer.java:44) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:255) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.method_29977(InventoryScreen.java:128) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:823) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.drawEntity(InventoryScreen.java:128) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.gui.screen.ingame.CreativeInventoryScreen.drawBackground(CreativeInventoryScreen.java:683) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen.java:92) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen.java:45) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.gui.screen.ingame.CreativeInventoryScreen.render(CreativeInventoryScreen.java:595) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:492) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.6-v2.jar:?]
	... 11 more
	```

**Comment by ghost** [comment]
Geckolib issue, closing for now.
