### ISSUE TITLE
[Boot Crash] version 0.29.0 incompatible with OptiFabric

### ISSUE THREAD

**Issue by platinorum** [FabricMC/fabric#1248]
Minecraft **1.16.4** crashes every time (before showing the loading screen) when **OptiFabric** is installed in the _mods_ folder!

### **temp fix:**
it works if you downgrade fabric API to _[1.16.4] Fabric API **0.28.4**_

**Comment by i509VCB** [comment]
We need a crash log in order to know what is going on here.

This might be the new render events also conflicting with optifine. You may need to consult with optifabric to fix it.

**Comment by BotiBoster** [comment]
22:56:37.498
launcher
main
Preparing to launch minecraft client for fabric-loader-0.10.8-1.16.4
22:56:38.536
launcher
main
Checking installations.
22:56:38.544
launcher
main
Minecraft client fabric-loader-0.10.8-1.16.4 is ready to start.
22:56:38.544
launcher
main
Starting!
22:56:38.618
launcher
main
Using default game log configuration client-1.12.xml (outputs XML)
22:56:39.215
FabricLoader
main
Loading for game Minecraft 1.16.4
22:56:39.556
Fabric|Loader
ForkJoinPool-1-worker-2
The mod "infinityfix" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 22 column 11
22:56:39.693
Fabric|Loader
ForkJoinPool-1-worker-11
The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
22:56:39.720
Fabric|Loader
ForkJoinPool-1-worker-1
Non-Fabric mod JAR at "C:\Users\alber\AppData\Roaming\.minecraft\mods\preview_OptiFine_1.16.4_HD_U_G6_pre5.jar", ignoring
22:56:39.726
Fabric|Loader
ForkJoinPool-1-worker-8
The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
22:56:39.727
Fabric|Loader
ForkJoinPool-1-worker-4
The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
22:56:39.762
Fabric|Loader
ForkJoinPool-1-worker-8
The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
22:56:39.767
Fabric|Loader
ForkJoinPool-1-worker-13
The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
22:56:39.866
Fabric|Loader
main
[FabricLoader] Loading 96 mods: fabric-renderer-api-v1@0.4.0+cbe9176f3a, fabric-keybindings-v0@0.2.0+6a2618f53a, roughlyenoughitems-api@5.8.10, terrestria@2.1.5+build.28, notenoughcrashes@2.1.4+1.16.4, fabricloader@0.10.8, fabric-structure-api-v1@1.1.3+cbe9176f3a, firstperson@1.3.0, falling_tree@2.8.1, fabric-containers-v0@0.1.9+a03e98793a, fabric-dimensions-v1@2.0.1+9a6c75813a, fabric-object-builder-api-v1@1.9.2+6a2618f53a, betternether@5.0.4, fabric-game-rule-api-v1@1.0.5+cbe9176f3a, bettercaves@1.16.2-1.0.3, fabric-api-base@0.2.0+ab87788d3a, fallingleaves@1.2, terraform-config-api-v1@1.0.0+build.1, xaeroworldmap@1.11.6, mm@2.1, fabric-rendering-data-attachment-v1@0.1.4+6a2618f53a, yungsapi@1.16.4-Fabric-1, upstream@1.0.1, terraform-surfaces-api-v1@1.0.0+build.1, fabric-textures-v0@1.0.5+6a2618f53a, fabric-rendering-fluids-v1@0.1.12+6a2618f53a, waila@1.9.22, terraform-dirt-api-v1@1.0.0+build.1, fabric-blockrenderlayer-v1@1.1.4+6a2618f53a, fabric-lifecycle-events-v1@1.2.0+ffb68a873a, traverse@3.2.0+build.17, terraform-wood-api-v1@1.0.0+build.1, fabric-renderer-registries-v1@2.2.0+6a2618f53a, fabric-loot-tables-v1@1.0.1+6a2618f53a, fabric@0.29.0+1.16, fabric-particles-v1@0.2.3+cbe9176f3a, fabric-networking-v0@0.3.1+2a4333d33a, terraform-biome-builder-api-v1@1.0.0+build.1, fabric-screen-handler-api-v1@1.1.0+6a2618f53a, cleancut@mc1.16-2.1-fabric, roughlyenoughitems-default-plugin@5.8.10, minecraft@1.16.4, fabric-networking-blockentity-v0@0.2.7+a03e98793a, tk_valoeghese_zoesteriaconfig@1.3.2, repurposed_structures@1.16.4-1.7.3, modmenu@1.14.13+build.19, illuminations@1.4, cloth-basic-math@0.5.1, fabric-command-api-v1@1.0.9+6a2618f53a, betterdroppeditems@1.2.4-1.16.2, fabric-tool-attribute-api-v1@1.2.5+6a2618f53a, roughlyenoughitems-runtime@5.8.10, fabric-renderer-indigo@0.4.3+6a2618f53a, angerable-patch@1.1.0-1.16.4, terraform-tree-api-v1@1.0.1+build.2, unearthed@1.0.5, smoothboot@1.16.4-1.3.2, cloth-client-events-v0@1.4.5, voyager@1.0.0, fabric-events-interaction-v0@0.4.1+6a2618f53a, fabric-crash-report-info-v1@0.1.2+b7f9825d3a, roughlyenoughitems@5.8.10, fabric-item-api-v1@1.2.0+6a2618f53a, loadcatcher@2.0.0, mostructures@1.0.1+mc.1.16.4, fabric-entity-events-v1@1.0.0+79b23bee3a, fabric-rendering-v0@1.1.1+6a2618f53a, infinityfix@1.1.0, fabric-key-binding-api-v1@1.0.1+730711c63a, fabric-rendering-v1@1.5.0+c26373133a, cloth-config2@4.8.3, terraform-overworld-biome-extensions-api-v1@1.0.0+build.1, fabric-resource-loader-v0@0.4.0+552549d53a, autoconfig1u@3.3.1, fabric-content-registries-v0@0.2.0+e77439c73a, fabric-tag-extensions-v0@1.1.0+e77439c73a, optifabric@1.8.13, fabric-biome-api-v1@3.1.0+2e23b97c3a, itemmodelfix@0.2.4, fabric-commands-v0@0.2.1+cbe9176f3a, fabric-registry-sync-v0@0.7.3+be155ae23a, lightoverlay@5.5.4, fabric-mining-levels-v0@0.1.2+6a2618f53a, byg@1.1.3, fabric-networking-api-v1@1.0.0+4358fbc63a, cinderscapes@1.3.0+build.51, fabric-events-lifecycle-v0@0.2.0+6a2618f53a, rpg-hud@3.8.1, xaerobetterpvp@20.30.0, libstructure@1.5, fabric-models-v0@0.2.0+cbe9176f3a, fabric-item-groups-v0@0.2.2+cbe9176f3a, bettermineshafts@1.16.4-1.0, betterend@0.8.5-beta, fabric-object-builders-v0@0.7.1+6a2618f53a, terraform-shapes-api-v1@1.0.0+build.1
22:56:39.868
Fabric|Loader
main
Mod `cleancut` (mc1.16-2.1-fabric) does not respect SemVer - comparison support is limited.
22:56:39.945
mixin
main
SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/alber/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
22:56:41.060
Smooth Boot
main
Smooth Boot config initialized
22:56:41.950
launcher
main

Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:286)
	at net.minecraft.class_128.method_559(class_128.java:101)
	at net.minecraft.class_128.<init>(class_128.java:54)
	at net.minecraft.class_128.method_24305(class_128.java:425)
	at net.minecraft.client.main.Main.main(Main.java:135)
	... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onRenderParticles(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in fabric-rendering-v1.mixins.json:MixinWorldRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-rendering-v1-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 18 more
22:56:41.950
monitor
Process Monitor
Process crashed with exit code 1

**Comment by BotiBoster** [comment]
This is my log using the 29.0 api and optifabric

**Comment by ghost** [comment]
same thing here, newest version of fabric api instantly crashes with Optifabric giving an exit code 0

**Comment by zml2008** [comment]
Yeah, this is an optifabric issue to fix -- some of the places the new Fabric API targets are modified by optifine in an incompatible way. https://github.com/Chocohead/OptiFabric/issues/130 and https://github.com/Chocohead/OptiFabric/issues/128 are already open on the optifabric side.
