### ISSUE TITLE
Fabric api api-0.29.2+1.16.jar crashing on 1.16.4

### ISSUE THREAD

**Issue by juliocoliveira** [FabricMC/fabric#1257]
I downloaded the latest version and its crashing with the loader 10.8.
I had to use older version 0.26.0+1.16

**Comment by Player3324** [comment]
We just released .3 which may help? Please provide a crash report if it still happens.

**Comment by SoyBerrugo** [comment]
Still Happens. MC 1.16.4 No problem with V 0.28.4. Minecraft log, no crash report:

MultiMC version: 0.6.11-1430

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:286)
	at net.minecraft.class_128.method_559(class_128.java:101)
	at net.minecraft.class_128.<init>(class_128.java:54)
	at net.minecraft.class_128.method_24305(class_128.java:425)
	at net.minecraft.client.main.Main.main(Main.java:135)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onRenderParticles(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in fabric-rendering-v1.mixins.json:MixinWorldRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-rendering-v1-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 26 more
Exiting with -1
Process exited with code -1.

**Comment by juliocoliveira** [comment]
Tested with fabric-api-0.29.3+1.16.jar still crashing with no crash report, exit code: 0

**Comment by Blobanium** [comment]
I Have this same issue also, it apparently is something to do with the rendering (Particles more precisely), as u can see in my logs.

![Capture](https://user-images.githubusercontent.com/45613796/103689946-d681c300-4f48-11eb-9003-931369e89102.PNG)

**Comment by OverlordsIII** [comment]
Are you running your mods with optifabric?

**Comment by juliocoliveira** [comment]
I am

**Comment by Blobanium** [comment]
i suspected that it was optifabric the is the issue, but i havent tested that out yet so yeah

**Comment by OverlordsIII** [comment]
Yea it's a problem with optifabric atm

**Comment by juliocoliveira** [comment]
The issue was with the optifabric older version optifabric-1.8.5.jar, tested with the latest optifabric-1.8.16.jar and fabric-api-0.29.3+1.16.jar and is working fine.
