### ISSUE TITLE
could not execute entrypoint stage 'main' due to errors, provided by 'fabric-tool-attribute-api-v1'

### ISSUE THREAD

**Issue by Fran9705** [FabricMC/fabric#1265]
Hello, I'm pretty new in minecraft or coding, today I installed Fabric on minecraft and put the latest 1.16.3 API in the mods folder, still minecraft continues crashing due "could not execute entrypoint stage 'main' due to errors, provided by 'fabric-tool-attribute-api-v1'"
This is the crash report:
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 1/12/21 7:43 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-tool-attribute-api-v1'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at djw.<init>(SourceFile:423)
	at net.minecraft.client.main.Main.main(SourceFile:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_1922
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:348)
		at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
		at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
		at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
		at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
		at net.fabricmc.loader.EntrypointStorage$$Lambda$2187/582024830.get(Unknown Source)
		at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1922
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 20 more
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_2378
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:348)
		at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
		at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
		at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
		at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
		at net.fabricmc.loader.EntrypointStorage$$Lambda$2187/582024830.get(Unknown Source)
		at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2378
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 20 more
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_1937
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:348)
		at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
		at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
		at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
		at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
		at net.fabricmc.loader.EntrypointStorage$$Lambda$2187/582024830.get(Unknown Source)
		at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1937
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 20 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_2960
	at net.fabricmc.fabric.api.tool.attribute.v1.FabricToolTags.register(FabricToolTags.java:39)
	at net.fabricmc.fabric.api.tool.attribute.v1.FabricToolTags.<clinit>(FabricToolTags.java:29)
	at net.fabricmc.fabric.impl.tool.attribute.ToolHandlers.onInitialize(ToolHandlers.java:38)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2186/1869424711.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2960
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at djw.<init>(SourceFile:423)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 733850040 bytes (699 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.11.0-1.16.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by Juuxel** [comment]
Which launcher are you using? There's something very weird going on.

(The stacktrace shows `at djw.(SourceFile:423)`, which means intermediaries aren't loaded at all (or they are incomplete, which I doubt).)

**Comment by Leo40Git** [comment]
`Java Version: 1.8.0_51, Oracle Corporation` implies the Vanilla launcher, IIRC.  
~~How did we break compatibility with the Vanilla launcher?!~~

**Comment by Fran9705** [comment]
> Which launcher are you using? There's something very weird going on.
> 
> (The stacktrace shows `at djw.(SourceFile:423)`, which means intermediaries aren't loaded at all (or they are incomplete, which I doubt).)

I'm using the normal minecraft launcher

**Comment by SomeoneInParticular** [comment]
Which version of Fabric API are you using? It seems fresh installs of version `0.27.1+1.16` (the version I tested) are bugged, and gave me a nearly identical error. Updating to version `0.29.3+1.16` fixed the problem perfectly (and doesn't appear to have any major conflicts with any code you may have already developed).

**Comment by LemmaEOF** [comment]
For Readability's sake, here's yarnifications of the names in the crash log:
`net.minecraft.class_1922` - > `net.minecraft.world.BlockView`
`net.minecraft.class_2378` -> `net.minecraft.util.registry.Registry`
`net.minecraft.class_1937` -> `net.minecraft.world.World`
`net.minecraft.class_2960` -> `net.minecraft.util.Identifier`

this seems to be a *very* fucked classpath, as all these classes are pretty core to Minecraft functionality. The stacktrace thing Juuz pointed out implies that the environment may not have ben obfuscated - try reinstalling Fabric loader and see if that helps?

**Comment by bradcarnage** [comment]
Discovered this thread after having a similar if not the same issue.
Upgrading to 0.29.3+1.16 has solved my issue and I can only assume the same for OP.

**Comment by NedNiseYT** [comment]
have same issue, but im using 1.17.1, what should i do? (exit code -1 btw)

**Comment by Technici4n** [comment]
@NedNiseYT please open a new issue and post the crash log there.

Closing this as it appears to be solved.
