### ISSUE TITLE
Starting Coding of a Mod, but Minecraft is not loading up

### ISSUE THREAD

**Issue by nikhiltur** [FabricMC/fabric#1279]
I'm starting coding of a mod using the fabric-example-mod template, and I just finished customizing fabric.mod.json and creating the new java file, but when I try to launch this error happens and the game crashes. I have very little experience so I have no idea what's going on.

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 1/23/21, 5:59 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'blockcompression'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
EntrypointUtils.java:53
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
EntrypointUtils.java:36
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
EntrypointClient.java:32
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:437)
MinecraftClient.java:437
	at net.minecraft.client.main.Main.main(Main.java:177)
Main.java:177
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
NativeMethodAccessorImpl.java:62
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
DelegatingMethodAccessorImpl.java:43
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Method.java:566
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
MinecraftGameProvider.java:226
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
Knot.java:139
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
KnotClient.java:27
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Main.java:86
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'blockcompression'
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:186)
EntrypointStorage.java:186
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
EntrypointUtils.java:50
	... 12 more
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: com.d3rpym00.blockCompression
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:47)
DefaultLanguageAdapter.java:47
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
EntrypointStorage.java:112
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
EntrypointStorage.java:99
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
EntrypointStorage.java:184
	... 14 more
Caused by: java.lang.ClassNotFoundException: com.d3rpym00.blockCompression
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
BuiltinClassLoader.java:581
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
ClassLoaders.java:178
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
ClassLoader.java:521
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
KnotClassLoader.java:168
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
ClassLoader.java:521
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
Class.java:398
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
DefaultLanguageAdapter.java:45
	... 17 more
2

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
EntrypointUtils.java:53
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
EntrypointUtils.java:36
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
EntrypointClient.java:32
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:437)
MinecraftClient.java:437

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
Main.java:177
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        Operating System: Windows 10 (amd64) version 10.0
	Java Version: 11.0.8, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 448092976 bytes (427 MB) / 1248854016 bytes (1191 MB) up to 4280287232 bytes (4082 MB)
	CPUs: 12
	JVM Flags: 3 total; -Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=localhost:55057,server=n,suspend=y
	Fabric Mods: 
		blockcompression: Block Compression ${1.0}
		fabric: Fabric API 0.29.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+8004b36d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.2.0+cbe9176f3a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+cbe9176f3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+c26373133a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.1+0d4d7e343a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.11.0
		java: Java HotSpot(TM) 64-Bit Server VM 11
		minecraft: Minecraft 1.16.5
	Launched Version: Fabric
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

It also says that Minecraft failed to verify authentication before the crash report.

**Comment by i509VCB** [comment]
> Caused by: java.lang.ClassNotFoundException: com.d3rpym00.blockCompression

Have you verified your `main` entrypoint in your `fabric.mod.json` points to the correct class

**Comment by nikhiltur** [comment]
> 
> 
> > Caused by: java.lang.ClassNotFoundException: com.d3rpym00.blockCompression
> 
> Have you verified your `main` entrypoint in your `fabric.mod.json` points to the correct class

It does point to the correct class, I just verified.

**Comment by i509VCB** [comment]
So your class is at `com.d3rpym00.blockCompression` To me it wounds like it should be `com.d3rpym00.BlockCompression`. Could you screenshot in IDE so I can cross verify

**Comment by nikhiltur** [comment]
Yes, here is the screenshot.
<img width="1859" alt="error" src="https://user-images.githubusercontent.com/77403538/105617715-0aad0e80-5da6-11eb-94ba-899709d5b7f2.PNG">

**Comment by i509VCB** [comment]
That entrypoint value doesn't point fully to the class but instead just to the package.

The value should be `com.d3rpym00.blockCompression.blockCompression`

**Comment by nikhiltur** [comment]
Oh ok, I changed it and it works now, thanks!
