### ISSUE TITLE
MMC wont load up, no error just a load of code.

### ISSUE THREAD

**Issue by SkyySonic** [FabricMC/fabric#1302]
Trying to load up Valhelsia 3 with MMC and i get

[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-networking-blockentity-v0.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-screen-handler-api-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-lifecycle-events-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-containers-v0.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-rendering-data-attachment-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-renderer-indigo.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-structure-api-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-item-api-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-events-interaction-v0.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-loot-tables-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-object-builder-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-screen-api-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-dimensions-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-renderer-registries-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-textures-v0.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-registry-sync-v0.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config bookdupe.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-models-v0.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-blockrenderlayer-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-renderer-api-v1.debughud.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-containers-v0.accurate.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-rendering-fluids-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-biome-api-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-resource-loader-v0.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-game-rule-api-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-networking-api-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-particles-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-object-builders-v0.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-tag-extensions-v0.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-tool-attribute-api-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-rendering-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-item-groups-v0.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-content-registries-v0.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-command-api-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-crash-report-info-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-entity-events-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-key-binding-api-v1.mixins.json does not specify "minVersion" property
[06:06:03] [main/ERROR] [mixin/]: Mixin config fabric-renderer-api-v1.mixins.json does not specify "minVersion" property
Exiting with -1
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.SecurityException: class "org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source)
	at java.lang.ClassLoader.preDefineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.initializeTransformers(KnotClassDelegate.java:76)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:135)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	... 8 more

**Comment by HastumeM** [comment]
I think Valhestia 3 is a forge modpack, not fabric...

**Comment by Technici4n** [comment]
Fabric and forge are not compatible, you can't just add fabric API to a forge pack.
