### ISSUE TITLE
entrypoint.minecraft.hooks

### ISSUE THREAD

**Issue by StepbroAl** [FabricMC/fabric#1313]
_whenever i load up minecraft i get an error saying

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2/13/21 4:31 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'kibe'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_3929
		at net.fabricmc.fabric.api.client.screenhandler.v1.ScreenRegistry.register(ScreenRegistry.java:66)
		at me.shedaniel.architectury.registry.fabric.MenuRegistryImpl.registerScreenFactory(MenuRegistryImpl.java:73)
		at me.shedaniel.architectury.registry.MenuRegistry.registerScreenFactory(MenuRegistry.java)
		at com.oroarmor.netherite_plus.screen.NetheritePlusScreenHandlers.initializeClient(NetheritePlusScreenHandlers.java:38)
		at com.oroarmor.netherite_plus.client.NetheritePlusClientModFabric.onInitializeClient(NetheritePlusClientModFabric.java:44)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$3283/1470658475.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_3929
		at net.fabricmc.fabric.api.client.screenhandler.v1.ScreenRegistry.register(ScreenRegistry.java:66)
		at ninjaphenix.expandedstorage.client.ExpandedStorageClient.onInitializeClient(ExpandedStorageClient.java:83)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$3283/1470658475.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_3929
		at net.fabricmc.fabric.api.client.screenhandler.v1.ScreenRegistry.register(ScreenRegistry.java:66)
		at ru.betterend.registry.EndScreens.register(EndScreens.java:9)
		at ru.betterend.client.BetterEndClient.onInitializeClient(BetterEndClient.java:22)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$3283/1470658475.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy51.onInitializeClient(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$3283/1470658475.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.util.DefaultLanguageAdapter$1.invoke(DefaultLanguageAdapter.java:122)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.HackedMixinTransformer.transform(HackedMixinTransformer.java:38)
	at org.spongepowered.asm.mixin.transformer.HackedMixinTransformer.transformClass(HackedMixinTransformer.java:27)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.HackedMixinTransformer.transformClassBytes(HackedMixinTransformer.java:12)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.EarlyKnotClassDelegate.getPostMixinClassByteArray(EarlyKnotClassDelegate.java:10)
	at net.fabricmc.loader.launch.knot.UnsafeKnotClassLoader.loadClass(UnsafeKnotClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_3929.<clinit>(class_3929.java:90)
	at net.fabricmc.fabric.api.client.screenhandler.v1.ScreenRegistry.register(ScreenRegistry.java:66)
	at io.github.lucaargolo.kibe.blocks.ContainerInfo.initClient(ContainerInfo.java:88)
	at io.github.lucaargolo.kibe.blocks.BlockInfo.initClient(BlockInfo.java:116)
	at io.github.lucaargolo.kibe.blocks.BlockCompendiumKt.initBlocksClient(BlockCompendiumKt.java:201)
	at io.github.lucaargolo.kibe.KibeModKt.initClient(KibeModKt.java:112)
	... 19 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyLimit(I)I in limitless.mixins.json:anvil.AnvilScreenMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap limitless-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 34 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1135851232 bytes (1083 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 2
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		anvil_fix: AnvilFix 1.2.1-1.16
		appleskin: AppleSkin 1.0.11
		architectury: Architectury 1.3.85
		artifice: Artifice 0.13.1+1.16.2-rc1
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autofish: Autofish 0.9.2
		betterend: Better End 0.8.8-beta
		betterthanmending: BetterThanMending 1.2.0
		blockus: Blockus 2.0.1+1.16.4
		bowinfinityfix: Bow Infinity Fix rv9
		byg: BYG 1.1.3
		cardinal-components-base: Cardinal Components API (base) 2.5.0
		cardinal-components-entity: Cardinal Components API (entities) 2.5.0
		chainmail: Chainmail 0.5.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-config2: Cloth Config v4 4.8.3
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		commonformatting: common formatting 0.0.0
		dynamicentry: dynamic entry 0.1.3
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		editsign: Edit Sign 2.2.0
		expandedstorage: ExpandedStorage 5.6.31
		fabric: Fabric API 0.29.2+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+8004b36d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-furnaces: Fabric Furnaces 1.3.3-1.16.4
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.2.0+cbe9176f3a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+cbe9176f3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+c26373133a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricasmtools: Fabric ASM tools 0.3.2
		fabricloader: Fabric Loader 0.11.1
		falling_tree: FallingTree 2.10.0
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.0.1
		grossfabrichacks: GrossFabricHacks 0.8.3
		jankson: Jankson 3.0.0+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kibe: Kibe 1.6.1-BETA
		lapisreserve: Lapis Reserve 1.0.6
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		limitless: limitless 1.0.2
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		mesh: Mesh 0.6.1-alpha.21+1.16.4
		mesh_api: Mesh API 0.6.1-alpha.21+1.16.4
		minecraft: Minecraft 1.16.4
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 1.14.12+build.18
		multi_item_lin: Multi Item Lin 1.0.0
		net_bytebuddy_byte-buddy-agent: byte-buddy-agent 1.10.18
		net_gudenau_lib_unsafe: unsafe 1.3.4
		netherite_plus: Netherite Plus Mod 1.3.8-1.16.5
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		oro_config: OroArmor Config unspecified
		phormat: phormat 0.1.3
		phosphor: Phosphor 0.6.0+build.7
		playerabilitylib: Pal 1.2.1
		roughlyenoughitems: Roughly Enough Items 5.8.9
		roughlyenoughitems-api: REI (API) 5.8.9
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.9
		roughlyenoughitems-runtime: REI (Runtime) 5.8.9
		rpgz: RPGZ 0.4.2
		slight-gui-modifications: 'Slight' GUI Modifications 1.6.0
		sodium: Sodium 0.1.0
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-3
		trinkets: Trinkets 2.6.7
		user11681_reflect: reflect 0.13.4
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		xaerominimap: Xaero's Minimap 21.3.0
	Launched Version: fabric-loader-0.11.1-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>_

**Comment by liach** [comment]
Your `limitless` mod failed to patch minecraft when the code to patch was requested by `kibe` mod.

Try update your `limitness` mod first; if it still crashes report to author and temporary remove this mod

**Comment by StepbroAl** [comment]
> Your `limitless` mod failed to patch minecraft when the code to patch was requested by `kibe` mod.
> 
> Try update your `limitness` mod first; if it still crashes report to author and temporary remove this mod

thank you

**Comment by liach** [comment]
Assuming that you have solved this problem, so closing. If you still have questions feel free to comment
