### ISSUE TITLE
NPE when joining servers with a blank mod [urgent?]

### ISSUE THREAD

**Issue by xpple** [FabricMC/fabric#1326]
Whenever one joins a server with a blank (NOTE 1) client-sided Fabric mod, this NPE is thrown

``` 
[23:35:27] [main/FATAL] (Minecraft) Error executing task on Client
java.lang.NullPointerException: null
at net.minecraft.scoreboard.Scoreboard.removeTeam(Scoreboard.java:199) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
at net.minecraft.client.network.ClientPlayNetworkHandler.onTeam(ClientPlayNetworkHandler.java:2156) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
at net.minecraft.network.packet.s2c.play.TeamS2CPacket.apply(TeamS2CPacket.java:122) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
at net.minecraft.network.packet.s2c.play.TeamS2CPacket.apply(TeamS2CPacket.java:16) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:21) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:144) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:118) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:103) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1015) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:681) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
at net.minecraft.client.main.Main.main(Main.java:215) [minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.4-v2.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1@net.fabricmc.yarn.1_16_5.1.16.5+build.4-v2.jar:?]
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1@net.fabricmc.yarn.1_16_5.1.16.5+build.4-v2.jar:?]
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1@net.fabricmc.yarn.1_16_5.1.16.5+build.4-v2.jar:?]
at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```
Along with this error, this warning is also common and is being spammed in the console:
```
[23:30:26] [main/WARN] (Minecraft) Received passengers for unknown entity
```
With this warning sometimes also comes an `IllegalStateException` which says: `Invalid entity data item type for field 20 on entity SomeEntity[...]`

These errors do not occur once, they are being spammed in the console by an incredible amount.

After six hours of wasted debugging time, I came to the conclusion it must be a Fabric bug.

NOTE 1:
That is, only a main class and a fabric.mod.json, and all the other default files. The Fabric versions are:
```
dependencies {
    minecraft "com.mojang:minecraft:1.16.5"
    mappings "net.fabricmc:yarn:1.16.5+build.4:v2"
    modImplementation "net.fabricmc:fabric-loader:0.11.1"
            
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.30.3+1.16"
}
minecraft_version=1.16.5
yarn_mappings=1.16.5+build.4
loader_version=0.11.1

fabric_version=0.30.3+1.16
```

**Comment by modmuss50** [comment]
Does it work without fabric api?

**Comment by xpple** [comment]
> Does it work without fabric api?

Well the mod won't load without it

**Comment by modmuss50** [comment]
Ok, does it work without your mod then?

**Comment by xpple** [comment]
You mean loading up Minecraft with just the Fabric API?

**Comment by modmuss50** [comment]
Yes, without your mod. Need to elimate as may varibles as possible to try and figure out whats going on.

**Comment by xpple** [comment]
Tried it, yes. Even without my mod I'm getting the errors. Seems like Fabric API is the culprit here.

**Comment by modmuss50** [comment]
Now try vanilla please.

**Comment by xpple** [comment]
Alright, give me two minutes.

**Comment by xpple** [comment]
That's crazy! It still happens!

**Comment by modmuss50** [comment]
Seems like the server is sending a bad packet.

**Comment by xpple** [comment]
Could very well be, although it happens on almost every server. This is the vanilla log: https://pastebin.com/sUWvpbBd with a whole bunch of errors

**Comment by modmuss50** [comment]
Its not a vanilla server. Make sure your server software is updated.

**Comment by xpple** [comment]
That's Hypixel...
