### ISSUE TITLE
Minecraft Crashes Whenever I Try To Run The Orgins Mod

### ISSUE THREAD

**Issue by TuftyManager79** [FabricMC/fabric#1334]
Whenever I try to start the fabric loader with the origins mod installed it brings up this error code.

List of mods:
Fabric api
origins
origins classes
staff of building
vanilla death chest

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'origins'!
Exit Code: -1

here is the full error report

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2/23/21 6:46 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'origins'!
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
at net.minecraft.class_310.(class_310.java:437)
at net.minecraft.client.main.Main.main(Main.java:177)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1:
at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:74)
at me.sargunvohra.mcmods.autoconfig1u.serializer.Toml4jConfigSerializer.deserialize(Toml4jConfigSerializer.java:55)
at me.sargunvohra.mcmods.autoconfig1u.ConfigManager.load(ConfigManager.java:52)
at me.sargunvohra.mcmods.autoconfig1u.ConfigManager.(ConfigManager.java:25)
at me.sargunvohra.mcmods.autoconfig1u.AutoConfig.register(AutoConfig.java:45)
at io.github.apace100.origins.OriginsClient.onInitializeClient(OriginsClient.java:53)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2709/821141889.accept(Unknown Source)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
... 11 more
Caused by: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1:
at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:140)
at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:107)
at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:72)
... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Render thread
Stacktrace:
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
at net.minecraft.class_310.(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.main.Main.main(Main.java:177)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
Minecraft Version: 1.16.5
Minecraft Version ID: 1.16.5
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1325509656 bytes (1264 MB) / 2046820352 bytes (1952 MB) up to 2147483648 bytes (2048 MB)
CPUs: 12
JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
Fabric Mods:
autoconfig1u: Auto Config v1 Updated 3.2.2
cardinal-components-base: Cardinal Components API (base) 2.7.1
cardinal-components-entity: Cardinal Components API (entities) 2.7.1
cloth-basic-math: Cloth Basic Math 0.5.1
cloth-config2: Cloth Config v4 4.8.1
com_electronwill_night-config_core: core 3.6.0
com_electronwill_night-config_toml: toml 3.6.0
com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
fabric: Fabric API 0.30.3+1.16
fabric-api-base: Fabric API Base 0.2.1+9354966b7d
fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
fabricloader: Fabric Loader 0.11.2
fallflyinglib: FallFlyingLib 1.1.0
java: Java HotSpot(TM) 64-Bit Server VM 8
minecraft: Minecraft 1.16.5
origins: Origins 0.4.7
reach-entity-attributes: Reach Entity Attribute 1.0.1
staffofbuilding: Staff of Building 1.2.5-1.16.5
vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
Launched Version: fabric-loader-0.11.2-1.16.5
Backend library: LWJGL version 3.2.2 build 10
Backend API: NO CONTEXT
GL Caps:
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fabric'
Type: Client (map_client.txt)
CPU:

**Comment by haykam821** [comment]
It looks like one of your configuration files is invalid. Try looking in the `.minecraft/config` to find a TOML file, and correct the error, or delete the entire file to generate a new one.

**Comment by haykam821** [comment]
Duplicate of #1333; also off-topic for Fabric API.

**Comment by TuftyManager79** [comment]
@haykam821 sorry about making that duplicate, I thought I was posting in the issues section, but then i realized it was in discussions, so I reposted in issues.    deleting old one now.

**Comment by haykam821** [comment]
No, you shouldn't be posting this in an issue. I'm not sure if general mod support is allowed in discussions but it's generally a better place for this type of problem.

**Comment by TuftyManager79** [comment]
> It looks like one of your configuration files is invalid. Try looking in the `.minecraft/config` to find a TOML file, and correct the error, or delete the entire file to generate a new one.

Thank you for the feedback I will try that and close the issue if it works

**Comment by TuftyManager79** [comment]
> It looks like one of your configuration files is invalid. Try looking in the `.minecraft/config` to find a TOML file, and correct the error, or delete the entire file to generate a new one.

Thank you so much, that fixed the issue... i was trying to fix this by myself for weeks.
