### ISSUE TITLE
Game crashes with error code 0 when using fabric api with optifabric

### ISSUE THREAD

**Issue by Maharaji221** [FabricMC/fabric#1335]
The game launches just fine using optifine and optifabric together, however when I add in any version of the fabric API, I get an unexpected error. The output log always shows as follows, regardless of the version of fabric API I use:

Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onRenderParticles(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in fabric-rendering-v1.mixins.json:MixinWorldRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-rendering-v1-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 18 more

Can anyone explain why it works fine without the API, but crashes with it. I'd very much like to be able to use litematica and optifine at the same time

**Comment by OroArmor** [comment]
dont use optifine. its not fully supported by fabric

**Comment by Maharaji221** [comment]
What should I use as a replacement? I'm using OptiFabric alongside
Optifine, and it runs perfectly fine, but when I add the Fabric API (in
order to run malalib, litematica,etc)  the game crashes, launcher gives the
error code 0, and the output console shows the lines I posted previously

**Comment by OroArmor** [comment]
if you need performance, sodium/lithium/phosphor are going to boost your fps and performance way more than optifine

**Comment by Maharaji221** [comment]
Are those interchangeable, or do they synergize with each other?
Honestly, I mostly like having no fog and easy zoom

**Comment by OroArmor** [comment]
all three work together

**Comment by OroArmor** [comment]
you can also use tweakeroo to add the zoom as sodium doesn't have it built in

**Comment by deltanedas** [comment]
many mods exist for zoom and removing fog

**Comment by Maharaji221** [comment]
It works!! Thank you for your help.
Now, for the lightning round: what do I need to be able to install BSL shaders with these mods enabled?

**Comment by Prospector** [comment]
Currently there's no fabric mods that support OptiFine shaders

**Comment by actuallyasmartname** [comment]
> It works!! Thank you for your help.
> Now, for the lightning round: what do I need to be able to install BSL shaders with these mods enabled?

Sadly, there is no way to add Optifine shaders to Sodium (read Shaders section of this gist: gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754). However, it is possible to add shaders without Sodium with a mod called Iris, which is in the Shaders section in the gist I linked.
