### ISSUE TITLE
Cannot start my Fabric Minecraft server

### ISSUE THREAD

**Issue by funtimewaffle** [FabricMC/fabric#1348]
I'm not a coder, the only 'coding experience' I've ever had was working through dumb code.org puzzles for my computer class. So I understand about 0.1% of this crash report I keep getting upon attempting to start up my Minecraft server. 

For some background info, I'm currently using Server.pro to host my server, and they had no option to automatically set up Fabric anywhere. So I took to a YouTube tutorial that basically just told me to switch the server jar to Fabric's server jar. It worked fine when I ran it on it's own, but as soon as I added a mod to it, the server refused to start. I figured out that the mod just needed Fabric API, so I installed the exact specific version of API that it asked for. But that just ended up even worse off than without the API. Here's what the console tells me any time I try to power on the server:

[main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'blade'!
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[custom.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[custom.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[custom.jar:?]
at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [custom.jar:?]
at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [custom.jar:?]
at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [custom.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [custom.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [custom.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [custom.jar:?]
Caused by: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
at vini2003.xyz.blade.Blade.<clinit>(Blade.java:19) ~[b6f96af1-ea23-4dee-8de3-706bee644baf.jar:?]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[custom.jar:?]
at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112) ~[custom.jar:?]
at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99) ~[custom.jar:?]
at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184) ~[custom.jar:?]
at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37) ~[custom.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[custom.jar:?]
... 17 more
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[custom.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[custom.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
at vini2003.xyz.blade.Blade.<clinit>(Blade.java:19) ~[b6f96af1-ea23-4dee-8de3-706bee644baf.jar:?]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[custom.jar:?]
at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112) ~[custom.jar:?]
at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99) ~[custom.jar:?]
at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184) ~[custom.jar:?]
at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37) ~[custom.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[custom.jar:?]
... 17 more

...I have no idea what any of this means. Like I said, not a coder, so I'm hoping to get some help on what the problem is. Maybe it's my mod, maybe it's the API, maybe it's just Server.pro, maybe I'm an idiot and it's a really simple solution. The one thing I do know though, is that I sure as hell have no idea what's wrong.

**Comment by YanisBft** [comment]
It seems that the mod you added (which is?) needs the Kotlin language adapter: https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin
