### ISSUE TITLE
Game was working fine for a while, then computer crashed and now minecraft crashes immediately after boot, before even opening the minecraft window.

### ISSUE THREAD

**Issue by greg-samuels** [FabricMC/fabric#1350]
Using MC/Fabric version 1.16.5, will attatch a screenshot with my modlist, here's the crashlog/error message.

"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'reborncore'!
Exit Code: -1"

"---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 08/03/21 10:29
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'reborncore'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	Suppressed: com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
		at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913)
		at com.google.gson.Gson.fromJson(Gson.java:887)
		at com.google.gson.Gson.fromJson(Gson.java:852)
		at com.google.gson.Gson.fromJson(Gson.java:801)
		at com.google.gson.Gson.fromJson(Gson.java:773)
		at reborncore.common.config.Configuration.setup(Configuration.java:69)
		at reborncore.common.config.Configuration.<init>(Configuration.java:52)
		at techreborn.TechReborn.onInitialize(TechReborn.java:73)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2238/1590351968.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
Caused by: com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at reborncore.common.config.Configuration.setup(Configuration.java:69)
	at reborncore.common.config.Configuration.<init>(Configuration.java:52)
	at reborncore.RebornCore.onInitialize(RebornCore.java:72)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2238/1590351968.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3915516448 bytes (3734 MB) / 4798283776 bytes (4576 MB) up to 7516192768 bytes (7168 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bedspreads: Bedspreads 1.3.1-1.16.4
		biome_locator: Biome Locator 1.1.2
		blue_endless_jankson: jankson 1.2.0
		cardinal-components-base: Cardinal Components API (base) 2.7.9
		cardinal-components-entity: Cardinal Components API (entities) 2.7.9
		cardinal-components-item: Cardinal Components API (items) 2.7.9
		cloth-api: Cloth API 1.5.47
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-common-events-v1: Cloth Common Events v1 1.5.47
		cloth-config2: Cloth Config v4 4.11.14
		cloth-datagen-api-v1: Cloth Datagen v1 1.5.47
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.5.47
		cloth-scissors-api-v1: Cloth Scissors API v1 1.5.47
		cloth-utils-v1: Cloth Utils v1 1.5.47
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		computercraft: CC:T for Fabric 1.91.2
		couplings: Couplings 1.3.3
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		easiervillagertrading: EasierVillagerTrading 1.16.5-fabric0.30.0-1.5.4
		fabric: Fabric API 0.30.3+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric Api Lookup API (v1) 1.0.0+8f91dfb63a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.2
		fallflyinglib: FallFlyingLib 1.1.0
		fasttransferlib: Fast Transfer Lib 0.2.2
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 0.2.8
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		harvest: Harvest 1.2.12
		indrev: Industrial Revolution 1.8.11-BETA
		inventorysorter: Inventory Sorter 1.7.7-1.16
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		javax_vecmath_vecmath: vecmath 1.5.2
		kyrptconfig: Kytpt Config 1.1.6-1.16
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		libgui: LibGui 3.3.5+1.16.5
		lithium: Lithium 0.6.4
		magna: Magna 1.4.3-1.16.2
		minecraft: Minecraft 1.16.5
		modmenu: Mod Menu 1.16.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		origins: Origins 0.4.7
		origins-classes: Origins: Classes 1.1.1
		patchouli: Patchouli 1.16.4-50-FABRIC
		phosphor: Phosphor 0.7.1+build.11
		pling: Pling 1.3.0
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.7.2+build.132
		roughlyenoughitems: Roughly Enough Items 5.10.183
		roughlyenoughitems-api: REI (API) 5.10.183
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.10.183
		roughlyenoughitems-runtime: REI (Runtime) 5.10.183
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.8.1+build.211
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		voxelmap: VoxelMap 1.10.15
		waila: Hwyla 1.9.22
		xp_storage: XP Storage 1.4+1.16.5
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.11.2-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>"
![image](https://user-images.githubusercontent.com/80255118/110310189-25f07800-7ffa-11eb-9ef4-d7a19f662de6.png)

**Comment by Noaaan** [comment]
Seems like bad configs with RebornCore. Try wiping configs for both TechReborn and RebornCore.
Also some of your mods are marked as Forge mods, like NamePain. It is likely these will not load.

**Comment by greg-samuels** [comment]
not sure, because all mods were working before, will delete forge marked mods now, how do I wipe configs for TechReborn and RebornCore?

**Comment by Noaaan** [comment]
Delete their respective config files in the configs folder. It is located in .minecraft/configs for your instance.

**Comment by greg-samuels** [comment]
Came up with a few other messages similar to the first, deleted config files according to which mod was specified, all fixed now! Thank you!
