### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'pehkui'! Exit Code: -1 

### ISSUE THREAD

**Issue by TheHuntHunter** [FabricMC/fabric#1362]
I have tried opening the most recent fabric loader today but it suddenly decided to stop working for some reason? Here is the log:
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 3/11/21 9:36 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'pehkui'!
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
at djz.(SourceFile:437)
at net.minecraft.client.main.Main.main(SourceFile:177)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_4970$class_2251
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
at net.fabricmc.loader.EntrypointStorage$$Lambda$73/644052207.get(Unknown Source)
at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_4970$class_2251
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 20 more
Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_1657
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
at net.fabricmc.loader.EntrypointStorage$$Lambda$73/644052207.get(Unknown Source)
at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1657
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 20 more
Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_2596
at com.qouteall.immersive_portals.ModMain.init(ModMain.java:33)
at com.qouteall.hiding_in_the_bushes.ModEntry.onInitialize(ModEntry.java:13)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2257/2055495569.accept(Unknown Source)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2596
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 15 more
Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_3494
at io.github.apace100.originsclasses.OriginsClasses.onInitialize(OriginsClasses.java:22)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2257/2055495569.accept(Unknown Source)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3494
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 14 more
Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_2960
at net.fabricmc.fabric.api.tool.attribute.v1.FabricToolTags.register(FabricToolTags.java:39)
at net.fabricmc.fabric.api.tool.attribute.v1.FabricToolTags.(FabricToolTags.java:29)
at net.fabricmc.fabric.impl.tool.attribute.ToolHandlers.onInitialize(ToolHandlers.java:38)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2257/2055495569.accept(Unknown Source)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2960
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 16 more
Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_2960
at moriyashiine.extraorigins.common.network.packet.BoneMealPacket.(BoneMealPacket.java:18)
at moriyashiine.extraorigins.common.ExtraOrigins.onInitialize(ExtraOrigins.java:15)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2257/2055495569.accept(Unknown Source)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2960
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 15 more
Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_1922
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
at net.fabricmc.loader.EntrypointStorage$$Lambda$73/644052207.get(Unknown Source)
at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1922
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 20 more
Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_179
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
at net.fabricmc.loader.EntrypointStorage$$Lambda$73/644052207.get(Unknown Source)
at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_179
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 20 more
Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_1269
at me.sargunvohra.mcmods.autoconfig1u.ConfigManager.lambda$new$1(ConfigManager.java:22)
at me.sargunvohra.mcmods.autoconfig1u.ConfigManager$$Lambda$2265/295203971.apply(Unknown Source)
at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:47)
at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.(ArrayBackedEvent.java:38)
at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:46)
at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:42)
at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:57)
at me.sargunvohra.mcmods.autoconfig1u.ConfigManager.(ConfigManager.java:21)
at me.sargunvohra.mcmods.autoconfig1u.AutoConfig.register(AutoConfig.java:45)
at me.sargunvohra.mcmods.autoconfig1u.example.ExampleInit.onInitialize(ExampleInit.java:15)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2257/2055495569.accept(Unknown Source)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1269
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 23 more
Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_1297
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
at net.fabricmc.loader.EntrypointStorage$$Lambda$73/644052207.get(Unknown Source)
at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1297
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 20 more
Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_2378
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
at net.fabricmc.loader.EntrypointStorage$$Lambda$73/644052207.get(Unknown Source)
at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2378
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 20 more
Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_2960
at net.fabricmc.fabric.impl.networking.NetworkingImpl.(NetworkingImpl.java:40)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
at net.fabricmc.loader.EntrypointStorage$$Lambda$73/644052207.get(Unknown Source)
at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2960
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 21 more
Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_1937
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
at net.fabricmc.loader.EntrypointStorage$$Lambda$73/644052207.get(Unknown Source)
at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1937
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 20 more
Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_1802
at com.misterpemodder.shulkerboxtooltip.impl.ShulkerBoxTooltip.(ShulkerBoxTooltip.java:50)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
at net.fabricmc.loader.EntrypointStorage$$Lambda$73/644052207.get(Unknown Source)
at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1802
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 21 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_2314
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
at net.fabricmc.loader.EntrypointStorage$$Lambda$73/644052207.get(Unknown Source)
at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2314
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Render thread
Stacktrace:
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
at djz.(SourceFile:437)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.main.Main.main(SourceFile:177)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
Minecraft Version: 1.16.5
Minecraft Version ID: 1.16.5
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1094999832 bytes (1044 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
CPUs: 12
JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
Launched Version: fabric-loader-0.11.1-1.16.5
Backend library: LWJGL version 3.2.2 build 10
Backend API: NO CONTEXT
GL Caps:
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fabric'
Type: Client (map_client.txt)
CPU:

**Comment by i509VCB** [comment]
There is an issue with your launcher/the game launching. If it's TLauncher then please use a different launcher.

**Comment by TheHuntHunter** [comment]
> There is an issue with your launcher/the game launching. If it's TLauncher then please use a different launcher.

It is purely the fabric launcher

**Comment by i509VCB** [comment]
In that case I would make a new instance (use installer) and try with that one.

**Comment by TheHuntHunter** [comment]
> In that case I would make a new instance (use installer) and try with that one.

That did it, thank you so much!!!!

**Comment by misaka4694** [comment]
I had the same problem, no improvement after changing the launcher

**Comment by zKingfox309** [comment]
> In that case I would make a new instance (use installer) and try with that one.

I had the same problem but your suggestion on fixing it didn't work either that or i just pretty much doing something wrong/stupid on understanding
