### ISSUE TITLE
Server crashes when starting 

### ISSUE THREAD

**Issue by Swiftform** [FabricMC/fabric#1363]
C:\Users\camos\Desktop\New folder>java -jar fabric-server-launch.jar
[12:09:51] [main/INFO]: Loading for game Minecraft 1.16.5
[12:09:51] [ForkJoinPool-1-worker-1/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[12:09:52] [ForkJoinPool-1-worker-2/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[12:09:52] [ForkJoinPool-1-worker-1/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[12:09:52] [ForkJoinPool-1-worker-1/WARN]: Non-Fabric mod JAR at "C:\Users\camos\Desktop\New folder\mods\upgrade_aquatic-1.16.5-3.0.1.jar", ignoring
[12:09:52] [main/WARN]: Warnings were found!
 - Mod 'Villager Fix' (villagerfix) recommends version 1.14.6 or later of mod modmenu, which is missing!
         - You must install version 1.14.6 or later of modmenu.
 - Mod 'AnvilFix' (anvil_fix) recommends any version of mod modmenu, which is missing!
         - You must install any version of modmenu.
 - Mod 'Colormatic' (colormatic) recommends version 1.12.0 or later of mod modmenu, which is missing!
         - You must install version 1.12.0 or later of modmenu.
[12:09:52] [main/INFO]: [FabricLoader] Loading 126 mods: fallflyinglib@1.1.0, fabric-keybindings-v0@0.2.1+ca58154a7d, roughlyenoughitems-api@5.10.184, fabricloader@0.11.2, org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.1.0, hydrogen@0.2, mesh_api@0.6.1-alpha.21+1.16.4, fabric-dimensions-v1@2.0.6+9354966b7d, immersive-cursedness@1.2.1, java@8, timecraft@0.4.3, cotton-client-commands@1.0.1+1.16-rc1, fabric-game-rule-api-v1@1.0.6+ca58154a7d, adventurez@1.1.7, fabric-api-base@0.2.1+9354966b7d, villagernames@1.6.0, fiber@0.23.0-2, alloys@1.1.0, villagerfix@1.4.1+1.16.2, fabrication@1.3.4, randompatches@2.4.5-fabric, org_jetbrains_kotlin_kotlin-stdlib@1.4.31, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, terraform-wood-api-v1@1.0.2, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.31, fabric@0.32.0+1.16, pride@1.0.0+1.16, anvil_fix@1.2.1-1.16, dawn@1.7, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, fabric-screen-handler-api-v1@1.1.5+9354966b7d, repurposed_structures@1.16.5-1.8.7, wild_explorer@1.3.2, phosphor@0.7.1+build.11, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.31, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, roughlyenoughitems-runtime@5.10.184, angerable-patch@1.1.0-1.16.4, terraform-tree-api-v1@1.0.5, cloth-client-events-v0@1.5.47, voyager@1.0.0, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-language-kotlin@1.5.0+kotlin.1.4.31, overworld_two@1.0.4, origins@0.6.1, fabric-key-binding-api-v1@1.0.4+9354966b7d, nourish@1.2.1, fabric-language-scala@1.0.0, cloth-config2@4.11.14, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.4.2, fabric-resource-loader-v0@0.4.2+ca58154a7d, org_jetbrains_kotlin_kotlin-reflect@1.4.31, cardinal-components-entity@2.7.1, architectury@1.8.131, colormatic@2.2.8+mc.1.16.3, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, cardinal-components-base@2.7.1, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fallingtree@2.10.2, krypton@0.1.2, earthtojavamobs@1.6.1+1.16.4, fabric-models-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, terraform-shapes-api-v1@1.0.4, fabric-renderer-api-v1@0.4.1+ca58154a7d, craftpresence@1.7.6, savemystronghold@1.16.4-1.0, fabric-structure-api-v1@1.1.4+ca58154a7d, allure@1.2.8, lithium@0.6.4, fabric-containers-v0@0.1.11+9354966b7d, fabric-object-builder-api-v1@1.9.4+9354966b7d, terraform-config-api-v1@1.0.2, org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.1.0, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, terraform-surfaces-api-v1@1.0.2, campanion@1.3.5, fabric-textures-v0@1.0.6+ca58154a7d, com_electronwill_night-config_core@3.6.3, lazydfu@0.1.2, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, starlight@0.0.2, reach-entity-attributes@1.0.1, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, traverse@3.3.2, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric-particles-v1@0.2.4+ca58154a7d, autoconfigtoml@1.0.0-fabric, nofade@1.16.5-1.0.1, terraform-biome-builder-api-v1@1.0.3, roughlyenoughitems-default-plugin@5.10.184, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, bedrockwaters@1.4.3+1.16.4, minecraft@1.16.5, physicsmod@1.0.0, fabric-command-api-v1@1.1.0+f9b3753b7d, jankson@3.0.1+j1.2.0, cloth-basic-math@0.5.1, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-renderer-indigo@0.4.4+ca58154a7d, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.4.2, com_electronwill_night-config_toml@3.6.3, fiber2cloth@3.0.1, roughlyenoughitems@5.10.184, fabric-item-api-v1@1.2.1+ca58154a7d, libgui@3.0.0-beta.1+1.16.2-rc2, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, terraform-overworld-biome-extensions-api-v1@1.0.2, mesh@0.6.1-alpha.21+1.16.4, autoconfig1u@3.3.1, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fastfurnace@2.3, appleskin@1.0.11, zoob@3.0.0, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, libstructure@1.5, fabric-object-builders-v0@0.7.2+ca58154a7d
[12:09:52] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/camos/Desktop/New%20folder/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[12:09:56] [main/INFO]: Loaded configuration file for Lithium: 80 options available, 1 override(s) found
[12:09:56] [main/INFO]: [Fabrication] Reloading configs...
[12:09:56] [main/INFO]: [Fabrication] Loading of features.ini done in 31.22 ms with 0 warnings
[12:09:56] [main/WARN]: Overriding InjectionInfo for @Inject with com.unascribed.fabrication.support.injection.FailsoftCallbackInjectionInfo (previously org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo)
[12:09:56] [main/WARN]: Overriding InjectionInfo for @ModifyArg with com.unascribed.fabrication.support.injection.FailsoftModifyArgInjectionInfo (previously org.spongepowered.asm.mixin.injection.struct.ModifyArgInjectionInfo)
[12:09:56] [main/WARN]: Overriding InjectionInfo for @ModifyArgs with com.unascribed.fabrication.support.injection.FailsoftModifyArgsInjectionInfo (previously org.spongepowered.asm.mixin.injection.struct.ModifyArgsInjectionInfo)
[12:09:56] [main/WARN]: Overriding InjectionInfo for @Redirect with com.unascribed.fabrication.support.injection.FailsoftRedirectInjectionInfo (previously org.spongepowered.asm.mixin.injection.struct.RedirectInjectionInfo)
[12:09:56] [main/WARN]: Overriding InjectionInfo for @ModifyVariable with com.unascribed.fabrication.support.injection.FailsoftModifyVariableInjectionInfo (previously org.spongepowered.asm.mixin.injection.struct.ModifyVariableInjectionInfo)
[12:09:56] [main/WARN]: Overriding InjectionInfo for @ModifyConstant with com.unascribed.fabrication.support.injection.FailsoftModifyConstantInjectionInfo (previously org.spongepowered.asm.mixin.injection.struct.ModifyConstantInjectionInfo)
[12:09:56] [main/WARN]: Reference map 'pride-refmap.json' for pride.mixins.json could not be read. If this is a development environment you can ignore this message
[12:09:56] [main/WARN]: Error loading class: net/minecraft/class_761 (java.lang.ClassNotFoundException: net/minecraft/class_761)
[12:09:56] [main/WARN]: @Mixin target net.minecraft.class_761 was not found allure.mixins.json:WorldRendererMixin
[12:09:56] [main/WARN]: Error loading class: net/minecraft/class_634 (java.lang.ClassNotFoundException: net/minecraft/class_634)
[12:09:56] [main/WARN]: @Mixin target net.minecraft.class_634 was not found allure.mixins.json:ClientPlayNetworkHandlerMixin
[12:09:57] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[12:09:57] [main/WARN]: Error loading class: net/minecraft/class_746 (java.lang.ClassNotFoundException: net/minecraft/class_746)
[12:09:57] [main/WARN]: @Mixin target net.minecraft.class_746 was not found architectury.mixins.json:PlayerAttackInvoker
[12:09:57] [main/WARN]: Error loading class: net/minecraft/class_745 (java.lang.ClassNotFoundException: net/minecraft/class_745)
[12:09:57] [main/WARN]: @Mixin target net.minecraft.class_745 was not found architectury.mixins.json:PlayerAttackInvoker
[12:09:57] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[12:09:57] [main/WARN]: Error loading class: net/minecraft/class_2535$1 (java.lang.ClassNotFoundException: net/minecraft/class_2535$1)
[12:09:57] [main/WARN]: @Mixin target net/minecraft/class_2535$1 was not found randompatches.mixins.json:timeouts.ChannelInitializerMixin
[12:09:57] [main/WARN]: Trying to reflect-hack into the class-loader so we can define our own classes in an unrestricted loader...
[12:09:57] [main/WARN]: ** The JVM might warn you with something nasty! **
[12:09:57] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenImmutableMapEntry' (url: jar:file:/C:/Users/camos/Desktop/New%20folder/mods/hydrogen-fabric-mc1.16.5-0.2.jar!/com/google/common/collect/HydrogenImmutableMapEntry.class)
[12:09:57] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenImmutableReferenceHashMap' (url: jar:file:/C:/Users/camos/Desktop/New%20folder/mods/hydrogen-fabric-mc1.16.5-0.2.jar!/com/google/common/collect/HydrogenImmutableReferenceHashMap.class)
[12:09:57] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenEntrySet' (url: jar:file:/C:/Users/camos/Desktop/New%20folder/mods/hydrogen-fabric-mc1.16.5-0.2.jar!/com/google/common/collect/HydrogenEntrySet.class)
[12:09:57] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenEntrySetIterator' (url: jar:file:/C:/Users/camos/Desktop/New%20folder/mods/hydrogen-fabric-mc1.16.5-0.2.jar!/com/google/common/collect/HydrogenEntrySetIterator.class)
[12:09:57] [main/INFO]: [Mesh]: Send Reinforcements!
[12:09:58] [main/ERROR]: Injection error: LVT in net/minecraft/class_1642::method_5874(Lnet/minecraft/class_3218;Lnet/minecraft/class_1309;)V has incompatible changes at opcode 93 in callback net/minecraft/class_1642::addZombieNameTag.
Expected: [Lnet/minecraft/class_1646;, Lnet/minecraft/class_1641;]
   Found: [D, Lnet/minecraft/class_1646;]
[12:10:02] [main/WARN]: Method overwrite conflict for method_17310 in starlight.mixins.json:common.lightengine.ServerLightingProviderMixin, previously written by me.jellysquid.mods.phosphor.mixin.chunk.light.MixinServerLightingProvider. Skipping method.
[12:10:03] [main/INFO]: [Fabrication] Loading of yeet_recipes.ini done in 585.1 ?s with 0 warnings
[12:10:03] [main/INFO]: [Fabrication] Loading of dimensional_tools.ini done in 2.818 ms with 0 warnings
[12:10:03] [main/INFO]: [Fabrication] Loading of gear_components.ini done in 11.51 ms with 0 warnings
[12:10:03] [main/INFO]: [Fabrication] Loading of item_despawn.ini done in 490.6 ?s with 0 warnings
[12:10:04] [main/INFO]: Origins 0.6.1 is initializing. Have fun!
[12:10:04] [main/INFO]: Compression will use Java, encryption will use Java
[12:10:04] [main/INFO]: [Earth2Java] Mod loaded! Enjoy :D
[12:10:05] [main/INFO]: [BedrockWaters] BedrockWaters initialized!
[12:10:05] [main/INFO]: [BedrockWaters] Modifying vanilla biome water attributes...
[12:10:05] [main/INFO]: [BedrockWaters] Finished!
[12:10:05] [main/INFO]: Initalizing VillagerFix!
[12:10:05] [main/INFO]: Krypton is now accelerating your Minecraft server's networking stack ?
[12:10:05] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:10:06] [main/WARN]: Ambiguity between arguments [experience, add] and [experience, lvlAmount] with inputs: [add]
[12:10:06] [main/WARN]: Ambiguity between arguments [experience, query] and [experience, lvlAmount] with inputs: [query]
[12:10:06] [main/WARN]: Ambiguity between arguments [experience, set] and [experience, lvlAmount] with inputs: [set]
[12:10:06] [main/WARN]: Ambiguity between arguments [experience, amount] and [experience, lvlAmount] with inputs: [0, -123, 123]
[12:10:06] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[12:10:06] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[12:10:06] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[12:10:06] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[12:10:06] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[12:10:06] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (AdventureZ, Alloys, AnvilFix, Repurposed Structures, Wild Explorer, Fabric Tool Attribute API (v1), Origins, Nourish, Earth2Java, Allure, Campanion, Traverse, Monster Of The Ocean Depths)
[12:10:07] [Worker-Main-1/INFO]: Loaded 7 recipes
[12:10:07] [Worker-Main-1/INFO]: Loaded 1190 advancements
[12:10:07] [Worker-Main-1/INFO]: Finished loading powers from data files. Registry contains 65 powers.
[12:10:07] [Worker-Main-1/INFO]: Finished loading origins from data files. Registry contains 11 origins.
[12:10:07] [Worker-Main-1/INFO]: Trying to read layer file: origins:origin
[12:10:07] [Worker-Main-1/INFO]: Finished loading origin layers from data files. Read 1 layers.
[12:10:08] [main/INFO]: Applied 1326 biome modifications to 109 of 110 new biomes in 117.8 ms
[12:10:08] [main/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[12:10:09] [Server thread/INFO]: Starting minecraft server version 1.16.5
[12:10:09] [Server thread/INFO]: Loading properties
[12:10:09] [Server thread/INFO]: Default game type: SURVIVAL
[12:10:09] [Server thread/INFO]: Generating keypair
[12:10:09] [Server thread/INFO]: Starting Minecraft server on *:25565
[12:10:09] [Server thread/INFO]: Using default channel type
[12:10:09] [Server thread/INFO]: Preparing level "world"
[12:10:10] [Worker-Main-2/WARN]: Worker-Main-2 died
java.lang.IllegalArgumentException: Trying to propagate light update before 1 radius neighbours ready
        at ca.spottedleaf.starlight.common.light.StarLightEngine.setupCaches(StarLightEngine.java:195) ~[starlight-fabric-0.0.2.jar:?]
        at ca.spottedleaf.starlight.common.light.StarLightEngine.blocksChangedInChunk(StarLightEngine.java:430) ~[starlight-fabric-0.0.2.jar:?]
        at ca.spottedleaf.starlight.common.light.StarLightInterface.propagateChanges(StarLightInterface.java:457) ~[starlight-fabric-0.0.2.jar:?]
        at net.minecraft.class_3568.method_15563(class_3568.java:1093) ~[intermediary-server.jar:?]
        at net.minecraft.class_3227.method_14277(class_3227.java:176) ~[intermediary-server.jar:?]
        at net.minecraft.class_3227.method_19505(class_3227.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_3846.method_16907(class_3846.java:94) ~[intermediary-server.jar:?]
        at net.minecraft.class_3846.method_16900(class_3846.java:137) ~[intermediary-server.jar:?]
        at net.minecraft.class_3846.run(class_3846.java:105) ~[intermediary-server.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:1.8.0_271]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_271]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_271]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_271]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_271]
[12:10:10] [Worker-Main-2/ERROR]: Caught exception in thread Thread[Worker-Main-2,5,main]
java.lang.IllegalArgumentException: Trying to propagate light update before 1 radius neighbours ready
        at ca.spottedleaf.starlight.common.light.StarLightEngine.setupCaches(StarLightEngine.java:195) ~[starlight-fabric-0.0.2.jar:?]
        at ca.spottedleaf.starlight.common.light.StarLightEngine.blocksChangedInChunk(StarLightEngine.java:430) ~[starlight-fabric-0.0.2.jar:?]
        at ca.spottedleaf.starlight.common.light.StarLightInterface.propagateChanges(StarLightInterface.java:457) ~[starlight-fabric-0.0.2.jar:?]
        at net.minecraft.class_3568.method_15563(class_3568.java:1093) ~[intermediary-server.jar:?]
        at net.minecraft.class_3227.method_14277(class_3227.java:176) ~[intermediary-server.jar:?]
        at net.minecraft.class_3227.method_19505(class_3227.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_3846.method_16907(class_3846.java:94) ~[intermediary-server.jar:?]
        at net.minecraft.class_3846.method_16900(class_3846.java:137) ~[intermediary-server.jar:?]
        at net.minecraft.class_3846.run(class_3846.java:105) ~[intermediary-server.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:1.8.0_271]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_271]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_271]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_271]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_271]
        
        
        I don't know what happened.

**Comment by Swiftform** [comment]
I also deleted the mod tic tac and it stopped working, after I added tic tac back, it started working. I deleted tic tac so it could be compatible with origins.
