### ISSUE TITLE
some sort of bug (is it the API?)

### ISSUE THREAD

**Issue by GaelTOHA** [FabricMC/fabric#1382]
So, it has happened to me for a while, only my first ever installation worked, it also seems to affect only snapshots. I only use Fabric for Sodium since my pc is too bad to run anything else. I also don't have any experience with Java, that's why I'm here. I'm also new to GitHub so don't expect a  lot from me.

**Crash on 21w11a:**
22:14:08.457
Fabric|Loader
main
A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: fabric requires {minecraft @ [~1.16.2-alpha.20.28.a]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:180)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:177)
	... 5 more
22:23:48.980
monitor
Process Monitor
Process crashed with exit code 1

**Crash on 1.15.2**
22:31:51.623
Fabric|Loader
main
A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: modmenu requires {minecraft @ [>=1.16-]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:180)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:177)
	... 5 more
22:31:58.731
monitor
Process Monitor
Process crashed with exit code 1

**Comment by OroArmor** [comment]
you have the fabric api for 1.16.2. download the API for 21w11a and it also looks like mod menu wants to be updated as well
