### ISSUE TITLE
Game crashes when opening creative menu

### ISSUE THREAD

**Issue by Ardvark8op** [FabricMC/fabric#139]
Whenever I open the creative inventory, game crashes with this error
`java.lang.NoSuchMethodError: net.minecraft.client.gui.widget.ButtonWidget: method <init>(IIIILjava/lang/String;)V not found
	at net.fabricmc.fabric.impl.itemgroup.FabricCreativeGuiComponents$ItemGroupButtonWidget.<init>(FabricCreativeGuiComponents.java:49)
	at net.minecraft.client.gui.ingame.CreativePlayerInventoryScreen.handler$onInitialized$zzd000(CreativePlayerInventoryScreen.java:1156)
	at net.minecraft.client.gui.ingame.CreativePlayerInventoryScreen.init(CreativePlayerInventoryScreen.java:343)
	at net.minecraft.client.gui.Screen.init(Screen.java:331)
	at net.minecraft.client.MinecraftClient.openScreen(MinecraftClient.java:822)
	at net.minecraft.client.gui.ingame.PlayerInventoryScreen.init(PlayerInventoryScreen.java:48)
	at net.minecraft.client.gui.Screen.init(Screen.java:331)
	at net.minecraft.client.MinecraftClient.openScreen(MinecraftClient.java:822)
	at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient.java:1507)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1399)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:916)
	at net.minecraft.client.MinecraftClient.start(MinecraftClient.java:410)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
`

**Comment by Daomephsta** [comment]
Please provide more details about your setup. Mods installed, fabric-loader version, etc.

**Comment by modmuss50** [comment]
Closing this as I think it was due to an outdated fabric version, and no response.
