### ISSUE TITLE
Fabric Networking API causes network errors when server query is enabled.

### ISSUE THREAD

**Issue by Martmists-GH** [FabricMC/fabric#1449]
The issue is that ClientConnection.addon is expected to always implement NetworkHandlerExtensions, but this interface is not added to ServerQueryNetworkHandler.

<details><summary>latest.log [error]</summary><code><pre>[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: java.lang.ClassCastException: class net.minecraft.class_3251 cannot be cast to class net.fabricmc.fabric.impl.networking.NetworkHandlerExtensions (net.minecraft.class_3251 and net.fabricmc.fabric.impl.networking.NetworkHandlerExtensions are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @3b6ddd1d)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at net.minecraft.class_2535.handler$zhe000$handleDisconnect(class_2535.java:588)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at net.minecraft.class_2535.channelInactive(class_2535.java)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[13:53:49] [Netty Epoll Server IO #1/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:834)</pre></code></details>

**Comment by Player3324** [comment]
Thanks for the report, this should be fixed in https://github.com/FabricMC/fabric/commit/e3c9d0625eaa610a4befd9195a83db4481829cc9

**Comment by Technici4n** [comment]
It should be fixed by Fabric API 0.34.2, otherwise please reopen.
