### ISSUE TITLE
internal server error, kicked on player join.

### ISSUE THREAD

**Issue by LordDecay26** [FabricMC/fabric#1472]
uh, not even sure if Fabric is the issue, but it's the only thing i can figure given the circumstances

modpack being ran is the 1.16.5 BesmirchmentPSM modpack version 3.0.2

> [02.06 14:38:07] [Server] [Server thread/INFO]: GandalfTheDanke joined the game
[02.06 14:38:07] [Server] [Server thread/WARN]: Failed to handle packet for /68.204.225.130:56751
[02.06 14:38:07] [Server] java.lang.NullPointerExceptionnull
[02.06 14:38:07] [Server] 	at net.minecraft.class_1928.method_8355(class_1928.java:185) ~[intermediary-1.16.5.jar:?]
[02.06 14:38:07] [Server] 	at net.minecraft.class_3324.handler$zpl000$sendWorldInfoMixin(class_3324.java:5463) ~[intermediary-1.16.5.jar:?]
[02.06 14:38:07] [Server] 	at net.minecraft.class_3324.method_14606(class_3324.java) ~[intermediary-1.16.5.jar:?]
[02.06 14:38:07] [Server] 	at net.minecraft.class_3324.method_14570(class_3324.java:227) ~[intermediary-1.16.5.jar:?]
[02.06 14:38:07] [Server] 	at net.minecraft.class_3248.method_14384(class_3248.java:113) ~[intermediary-1.16.5.jar:?]
[02.06 14:38:07] [Server] 	at net.minecraft.class_3248.redirect$clc000$handlePlayerJoin(class_3248.java:562) ~[intermediary-1.16.5.jar:?]
[02.06 14:38:07] [Server] 	at net.minecraft.class_3248.method_18785(class_3248.java:65) ~[intermediary-1.16.5.jar:?]
[02.06 14:38:07] [Server] 	at net.minecraft.class_2535.method_10754(class_2535.java:228) ~[intermediary-1.16.5.jar:?]
[02.06 14:38:07] [Server] 	at net.minecraft.class_3242.method_14357(class_3242.java:173) ~[intermediary-1.16.5.jar:?]
[02.06 14:38:07] [Server] 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882) ~[intermediary-1.16.5.jar:?]
[02.06 14:38:07] [Server] 	at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-1.16.5.jar:?]
[02.06 14:38:07] [Server] 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-1.16.5.jar:?]
[02.06 14:38:07] [Server] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-1.16.5.jar:?]
[02.06 14:38:07] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-1.16.5.jar:?]
[02.06 14:38:07] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
[02.06 14:38:08] [Disconnect] GandalfTheDanke has disconnected, reasonInternal server error
[02.06 14:38:08] [Server] [Server thread/INFO]: GandalfTheDanke left the game

**Comment by liach** [comment]
What mods do you have? Can try to find which mod adds `sendWorldInfoMixin`

**Comment by LordDecay26** [comment]
i was kinda hoping someone could tell me. im running the modpack BesmirchmentPSM which has over 200 mods i dont have time to sift through every single one.

**Comment by Technici4n** [comment]
I don't think this is a Fabric API issue. Please report modpack issues to the modpack developers.

**Comment by LordDecay26** [comment]
i am the modpack developer

**Comment by LordDecay26** [comment]
it's okay, issue sorted out on my own.
