### ISSUE TITLE
Unable to launch the game

### ISSUE THREAD

**Issue by luketeam5** [FabricMC/fabric#1510]
When starting the game I get an error:
![image](https://user-images.githubusercontent.com/40070133/122816916-93899100-d2d7-11eb-9272-66869d935895.png)
And error: 
```
[21:27:47] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Mod 'Minecraft' (minecraft) requires version 16 or later of mod 'Java HotSpot(TM) 64-Bit Server VM' (java), but a non-matching version is present: 8!
	 - You must install version 16 or later of 'Java HotSpot(TM) 64-Bit Server VM' (java).
	 - Mod 'Java HotSpot(TM) 64-Bit Server VM' (java) v8 is being loaded from the user's mod directory.
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:342) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
I'm running the game without any mods on the newest java version.
I'm also on the newest version of Fabric.

I also tried reinstalling Minecraft.

**Comment by liach** [comment]
You are running with java 8. This should be a problem with your vanilla launcher profile; make sure you clear the java executable or set it explicitly to a java 16 installation. That executable setting doesn't care if you have installed latest java 16 etc on your machine if you don't point to it explicitly.

**Comment by luketeam5** [comment]
Hello, sorry for the late response.

I already did that and I still have the same issue. I also tried uninstalling java and Minecraft but that didn't help either.
Also, I'm able to run normal vanilla Minecraft without problems.

**Comment by liach** [comment]
Follow the steps here https://github.com/FabricMC/fabric/issues/1512#issuecomment-867301401
but look at the "java executable"; if it is not empty, click &times; to clear it.
Also make sure your vanilla launcher is up-to-date.

**Comment by luketeam5** [comment]
Thank you! 

For anyone else having the same issue on the MultiMC launcher you can fix it by following these steps:
First of all download java 16 here: https://www.oracle.com/java/technologies/javase-jdk16-downloads.html


1. Select the instance and click on "Edit Instance" 
![image](https://user-images.githubusercontent.com/40070133/123516538-e6c75f00-d69c-11eb-86ca-704012d5ef15.png)
2. Go to settings TAB and click on java
![image](https://user-images.githubusercontent.com/40070133/123516565-02326a00-d69d-11eb-8330-6d6f64a119fb.png)
3. Click on `Browse...` and navigate to `C:\Program Files\Java\jdk-16.0.1\bin` and find file `javaw.exe` and select it. 
4. You're finished and you can now play with Fabric
