### ISSUE TITLE
Crash on Fabric loader 0.4.4

### ISSUE THREAD

**Issue by Madis0** [FabricMC/fabric#154]
Fabric API 0.2.7 build 127 crashes the game if used with the Fabric loader 0.4.4 build 136 on Minecraft 1.14. 
It did work correctly on the previous version of the loader.
<details>
<summary>Crash log</summary>

```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 26.04.19 13:42
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors!
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:36)
	at cvi.av(SourceFile)
	at cvi.b(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.NullPointerException
		at net.fabricmc.fabric.impl.network.ClientSidePacketRegistryImpl.onRegister(ClientSidePacketRegistryImpl.java:71)
		at net.fabricmc.fabric.impl.network.PacketRegistryImpl.register(PacketRegistryImpl.java:57)
		at net.fabricmc.fabric.impl.FabricAPIClientInitializer.onInitializeClient(FabricAPIClientInitializer.java:44)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at java.util.ArrayList.forEach(ArrayList.java:1257)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:36)
	at cvi.av(SourceFile)

-- Initialization --
Details:
Stacktrace:
	at cvi.b(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14
	Operating System: Linux (amd64) version 4.19.34-1-MANJARO
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1076819288 bytes (1026 MB) / 1342177280 bytes (1280 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.4.4+build.136-1.14+build.3
	LWJGL: 3.2.1 build 12
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>
```

</details>

**Comment by asiekierka** [comment]
Which exact build of 0.4.3 worked fine? It's a curious issue, as you're not the first one to run into it, but I can't narrow it down.

**Comment by Madis0** [comment]
Seems like I was using 0.4.2 build 132 previously.

**Comment by AK9Official** [comment]
Loader 0.4.3 Build 134 works fine. Everything above that crashes the game on launch.

**Comment by asiekierka** [comment]
Fixed.
