### ISSUE TITLE
Fabric keeps reloading texture packs. (Removed all mods, changed os, uninstalled minecraft and reinstalled it)

### ISSUE THREAD

**Issue by eshankiyer** [FabricMC/fabric#1561]
Repeating error:
Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot read field "scriptManager" because "dev.latvian.kubejs.server.ServerScriptManager.instance" is null
at Not Enough Crashes deobfuscated stack trace.(1.17+build.13)
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71)
at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
at net.minecraft.resource.SimpleResourceReload.method_18367(SimpleResourceReload:70)
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem:179)
at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:166)
at net.minecraft.client.util.Window.swapBuffers(Window:310)
at net.minecraft.client.MinecraftClient.render(MinecraftClient:1137)
at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
at net.minecraft.client.main.Main.main(Main:217)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:567)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NullPointerException: Cannot read field "scriptManager" because "dev.latvian.kubejs.server.ServerScriptManager.instance" is null
at dev.latvian.kubejs.script.ScriptType.lambda$static$1(ScriptType.java:21)
at dev.latvian.kubejs.event.EventJS.post(EventJS.java:31)
at dev.latvian.kubejs.server.TagEventJS.post(TagEventJS.java:380)
at dev.latvian.kubejs.core.TagCollectionKJS.customTagsKJS(TagCollectionKJS.java:20)
at net.minecraft.tag.TagGroupLoader.handler$ccj000$customTags(TagGroupLoader:525)
at net.minecraft.tag.TagGroupLoader.loadTags(TagGroupLoader:73)
at io.github.queerbric.inspecio.resource.InspecioResourceReloader.reload(InspecioResourceReloader.java:51)
at net.minecraft.resource.SynchronousResourceReloader.method_29490(SynchronousResourceReloader:15)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
... 230 more
18:30:06.365
Reloading ResourceManager: Default, Runtime Resource Packebe:pack, Fabric Mods (Fabric Key Bindings (v0), Not Enough Crashes, KubeJS, Fabric Loader, Satin, Hydrogen, Fabric Dimensions API (v1), ToroHealth Damage Indicators, megane, Fabric Game Rule API (v1), Fabric API Base, Xaero's World Map, megane-vanilla, LambDynamicLights, Cloud, Litematica, EasierVillagerTrading, Fabric BlockRenderLayer Registration (v1), Carpet Extra, Fabric API, Fabric Networking (v0), Pling, Chat Up!, Fabric API Lookup API (v1), Fabric Screen Handler API (v1), CleanCut, Mod Menu, Better Beds, Sodium Extra, Fabrishot, Blur (Fabric), Fabric Tool Attribute API (v1), Chunky, Reese's Sodium Options, Fabric Crash Report Info (v1), Fabric Events Interaction (v0), wthit, spark, megane-base, Fabric Language Kotlin, LibZoomer, Inspecio, Cull Leaves, Fabric Key Binding API (v1), Better Biome Blend, Cloth Config v4, Better Third Person, Fabric Resource Loader (v0), megane-runtime, MaLiLib, AntiGhost, WorldEdit, Enhanced Block Entities, Fabric Registry Sync (v0), Fabric Commands (v0), Auth Me, DimensionalThreading, Light Overlay, Fabric Mining Levels (v0), Fabric Networking API (v1), FallingTree, Krypton, Fabric Models (v0), Fabric Item Groups (v0), Fabric Renderer API (v1), GBfabrictools, Fabric Structure API (v1), Lithium, Fabric Containers (v0), Fabric Object Builder API (v1), Manningham Mills, Fabric Rendering Data Attachment (v1), Capes, Fabric Textures (v0), Fabric Rendering Fluids (v1), LazyDFU, Fabric Lifecycle Events (v1), Sodium, Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Dynamic FPS, Carpet Mod, Fabric Particles (v1), No Fade, FastChest, Fabric Networking Block Entity (v0), Ok Zoomer, Simple Voice Chat, Fabric Command API (v1), Fabric Screen API (v1), Better Dropped Items, Fabric Renderer - Indigo, Smooth Boot, Roughly Enough Items, Fabric Item API (v1), 'Slight' GUI Modifications, Fabric Entity Events (v1), Xaero's Minimap, Fabric Rendering (v0), Fabric Rendering (v1), SpruceUI, EntityCulling-Fabric, Auto Config v1 Updated, Inventory HUD +, Fabric Content Registries (v0), Fabric Tag Extensions (v0), Indium, Fabric Biome API (v1), FastFurnace, Item Model Fix, Runtime Resource Pack, cAn i MiNe thIS bLOCk?, AppleSkin, BetterF3, Fabric Events Lifecycle (v0), Horse Info, Fabric Object Builders (v0)), KubeJS Resource Pack [assets]
Replies

**Comment by warjort** [comment]
````
Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot read field "scriptManager" because
"dev.latvian.kubejs.server.ServerScriptManager.instance" is null
````

I would say report it to kubejs, but 1.17 is not supported by them, yet...
https://www.curseforge.com/minecraft/mc-mods/kubejs-fabric/files/3355296
