### ISSUE TITLE
[Error in Server Console]

### ISSUE THREAD

**Issue by itsdinkd** [FabricMC/fabric#1657]
1.17.1
fabric 0.37.2

During start up i am getting this

[00:12:23] [main/ERROR]: Exception reading ./world/level.dat
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[fabric-server-launch.jar:?]
        at com.google.common.collect.ImmutableCollection$ArrayBasedBuilder.add(ImmutableCollection.java:477) ~[fabric-server-launch.jar:?]
        at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:758) ~[fabric-server-launch.jar:?]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at net.minecraft.class_1966.<init>(MixinBiomeSource.java:40) ~[intermediary-server.jar:?]
        at net.minecraft.class_4766.<init>(class_4766.java:106) ~[intermediary-server.jar:?]
        at net.minecraft.class_4766.<init>(class_4766.java:102) ~[intermediary-server.jar:?]
        at com.mojang.datafixers.util.Function6.lambda$null$4(Function6.java:18) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult$Instance.ap3(DataResult.java:337) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.decode(RecordCodecBuilder.java:321) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.EitherMapCodec.decode(EitherMapCodec.java:30) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapDecoder$4.decode(MapDecoder.java:94) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$null$1(KeyDispatchCodec.java:67) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[intermediary-server.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$2(KeyDispatchCodec.java:58) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[intermediary-server.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:56) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[intermediary-server.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[intermediary-server.jar:?]
        at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.decode(RecordCodecBuilder.java:323) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$null$1(KeyDispatchCodec.java:67) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[intermediary-server.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$2(KeyDispatchCodec.java:58) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[intermediary-server.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:56) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[intermediary-server.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[intermediary-server.jar:?]
        at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$3.decode(RecordCodecBuilder.java:249) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[intermediary-server.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[intermediary-server.jar:?]
        at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_5382$class_5506$1.method_31155(class_5382.java:225) ~[intermediary-server.jar:?]
        at net.minecraft.class_5382.method_29763(class_5382.java:152) ~[intermediary-server.jar:?]
        at net.minecraft.class_5382.method_29762(class_5382.java:123) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[intermediary-server.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[intermediary-server.jar:?]
        at net.minecraft.class_5382.method_29755(class_5382.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_5380.method_29743(class_5380.java:35) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[intermediary-server.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[intermediary-server.jar:?]
        at net.minecraft.class_5380.decode(class_5380.java:35) ~[intermediary-server.jar:?]
        at com.mojang.serialization.Decoder$2.decode(Decoder.java:63) ~[intermediary-server.jar:?]
        at com.mojang.serialization.Codec$2.decode(Codec.java:71) ~[intermediary-server.jar:?]
        at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.decode(RecordCodecBuilder.java:324) ~[intermediary-server.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[intermediary-server.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
        at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[intermediary-server.jar:?]
        at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[intermediary-server.jar:?]
        at com.mojang.serialization.Decoder$1.decode(Decoder.java:49) ~[intermediary-server.jar:?]
        at com.mojang.serialization.Codec$2.decode(Codec.java:71) ~[intermediary-server.jar:?]
        at com.mojang.serialization.Decoder.decode(Decoder.java:22) ~[intermediary-server.jar:?]
        at com.mojang.serialization.Decoder.parse(Decoder.java:26) ~[intermediary-server.jar:?]
        at net.minecraft.class_32.method_29010(class_32.java:120) ~[intermediary-server.jar:?]
        at net.minecraft.class_32.method_29582(class_32.java:224) ~[intermediary-server.jar:?]
        at net.minecraft.class_32.method_26998(class_32.java:187) [intermediary-server.jar:?]
        at net.minecraft.class_32$class_5143.method_27013(class_32.java:341) [intermediary-server.jar:?]
        at net.minecraft.server.Main.main(MixinMain.java:163) [intermediary-server.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]

**Comment by warjort** [comment]
This area is for bug reports of the Fabric API. It is not a support forum. 
Take your question to the discord or the discussions tab.

I can tell you that there is error reading the world generation settings stored in your saved data.
````at net.minecraft.class_32.method_29010(class_32.java:120)````
```` METHOD method_29010 readGeneratorProperties````

So when when you repost your question elsewhere include as much information as possible about what mods you have that modify world generation.

**Comment by liach** [comment]
> `at net.minecraft.class_1966.(MixinBiomeSource.java:40) ~[intermediary-server.jar:?]`

This may be a clue.
