### ISSUE TITLE
Error when sleeping on the latest version (0.39.1)

### ISSUE THREAD

**Issue by CyanNex** [FabricMC/fabric#1670]
When running a fabric server in a development environment, the player gets disconnected when attempting to sleep in a bed. This can be reproduced just by using the [fabric example mod](https://github.com/FabricMC/fabric-example-mod) and bumping the fabric version to 0.39.1. The issue does not appear on version 0.38.2.

The following error is shown in the console
```
 net.minecraft.util.crash.CrashException: Ticking player
	at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity.java:530) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.39-v2.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.tick(ServerPlayNetworkHandler.java:212) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.39-v2.jar:?]
	at net.minecraft.network.ClientConnection.tick(ClientConnection.java:238) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.39-v2.jar:?]
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo.java:183) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.39-v2.jar:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:902) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.39-v2.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:335) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.39-v2.jar:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:831) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.39-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:697) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.39-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.39-v2.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.Optional net.minecraft.entity.player.PlayerEntity.method_18398()'
	at net.minecraft.entity.player.PlayerEntity.redirect$zeb000$redirectDaySleepCheck(PlayerEntity.java:2340) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.39-v2.jar:?]
	at net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity.java:262) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.39-v2.jar:?]
	at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity.java:466) ~[minecraft-1.17.1-mapped-net.fabricmc.yarn-1.17.1+build.39-v2.jar:?]
	... 9 mor
```

**Comment by modmuss50** [comment]
I have a possible fix for this, going to test it.

**Comment by modmuss50** [comment]
Im releasing 0.39.2 with a fix for this. Thanks for reporting.
