### ISSUE TITLE
Fatal error when accessing a registry

### ISSUE THREAD

**Issue by Indi-Code** [FabricMC/fabric#168]
I tried to access `Registry.ITEM`.
All I did was access it in the `onInitialization()` method of `ModInitializer`

```
"C:\Program Files\Java\jdk1.8.0_181\bin\java.exe" -Dfabric.development=true "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3\lib\idea_rt.jar=63843:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_181\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\rt.jar;C:\Users\mccra\Documents\Programming\minecraft\fabric\1.14\core\build\classes\kotlin\main;C:\Users\mccra\Documents\Programming\minecraft\fabric\1.14\core\build\resources\main;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk8\1.3.30\459999be0d6ac844dd3d2ca85c2daf14deb5f7f0\kotlin-stdlib-jdk8-1.3.30.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-reflect\1.3.30\b5aa87d4a75c9635915e4189f687e92ce375c054\kotlin-reflect-1.3.30.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-coroutines-jdk8\1.2.0\80e0ae6fac48a78bfad45ae3e23117df82f8aaf8\kotlinx-coroutines-jdk8-1.2.0.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-coroutines-core\1.2.0\934716ae1a5a09db4420e63679d097a523b24e43\kotlinx-coroutines-core-1.2.0.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk7\1.3.30\bf0edcf669e446e0d903a0681190d1e3df969ac4\kotlin-stdlib-jdk7-1.3.30.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\atomicfu\0.12.3\16896c746f44e8862b26cd139027580e65d36343\atomicfu-0.12.3.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.3.30\9ea98e65c246d34de9af59c104ad9bdea4908ee\kotlin-stdlib-1.3.30.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.jetbrains\annotations\16.0.3\62c7299ced2a089cc541726c6d763da9417604a0\annotations-16.0.3.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-common\1.3.30\989a125fdb6e4d0d75a016032e03e1e3b57a13d\kotlin-stdlib-common-1.3.30.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\atomicfu-common\0.12.3\b09ed1e1b1a0996e0a3b6c454797d44788a21747\atomicfu-common-0.12.3.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\net.fabricmc\yarn\1.14+build.3\bf59c4f3355c962a4e25d4fb767a6dd27831c8df\yarn-1.14+build.3.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\com.mojang\patchy\1.1\aef610b34a1be37fa851825f12372b78424d8903\patchy-1.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\oshi-project\oshi-core\1.1\9ddf7b048a8d701be231c0f4f95fd986198fd2d8\oshi-core-1.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\net.java.dev.jna\jna\4.4.0\cb208278274bf12ebdb56c61bd7407e6f774d65a\jna-4.4.0.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\net.java.dev.jna\platform\3.4.0\e3f70017be8100d3d6923f50b3d2ee17714e9c13\platform-3.4.0.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\com.ibm.icu\icu4j-core-mojang\51.2\63d216a9311cca6be337c1e458e587f99d382b84\icu4j-core-mojang-51.2.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\com.mojang\javabridge\1.0.22\6aa6453aa99a52a5cd91749da1af6ab70e082ab3\javabridge-1.0.22.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\net.sf.jopt-simple\jopt-simple\5.0.3\cdd846cfc4e0f7eefafc02c0f5dce32b9303aa2a\jopt-simple-5.0.3.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\io.netty\netty-all\4.1.25.Final\d0626cd3108294d1d58c05859add27b4ef21f83b\netty-all-4.1.25.Final.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\com.google.guava\guava\21.0\3a3d111be1be1b745edfa7d91678a12d7ed38709\guava-21.0.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-lang3\3.5\6c6c702c89bfff3cd9e80b04d668c5e190d588c6\commons-lang3-3.5.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\commons-io\commons-io\2.5\2852e6e05fbb95076fc091f6d1780f1f8fe35e0f\commons-io-2.5.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\commons-codec\commons-codec\1.10\4b95f4897fa13f2cd904aee711aeafc0c5295cd8\commons-codec-1.10.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\net.java.jinput\jinput\2.0.5\39c7796b469a600f72380316f6b1f11db6c2c7c4\jinput-2.0.5.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\net.java.jutils\jutils\1.0.0\e12fe1fda814bd348c1579329c86943d2cd3c6a6\jutils-1.0.0.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\com.mojang\brigadier\1.0.17\c6b7dc51dd44379cc751b7504816006e9be4b1e6\brigadier-1.0.17.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\com.mojang\datafixerupper\2.0.24\944c24a8519981847ffb36c6dcd059d96fcb4b0\datafixerupper-2.0.24.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\com.google.code.gson\gson\2.8.0\c4ba5371a29ac9b2ad6129b1d39ea38750043eff\gson-2.8.0.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\com.mojang\authlib\1.5.25\9834cdf236c22e84b946bba989e2f94ef5897c3c\authlib-1.5.25.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-compress\1.8.1\a698750c16740fd5b3871425f4cb3bbaa87f529d\commons-compress-1.8.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpclient\4.3.3\18f4247ff4572a074444572cee34647c43e7c9c7\httpclient-4.3.3.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\commons-logging\commons-logging\1.1.3\f6f66e966c70a83ffbdb6f17a0919eaf7c8aca7f\commons-logging-1.1.3.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpcore\4.3.2\31fbbff1ddbf98f3aa7377c94d33b0447c646b6e\httpcore-4.3.2.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\it.unimi.dsi\fastutil\8.2.1\5ad88f325e424f8dbc2be5459e21ea5cab3864e9\fastutil-8.2.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-api\2.8.1\e801d13612e22cad62a3f4f3fe7fdbe6334a8e72\log4j-api-2.8.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-core\2.8.1\4ac28ff2f1ddf05dae3043a190451e8c46b73c31\log4j-core-2.8.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\com.mojang\realms\1.14.14\93a4cea4eeb81b0d8c042fe46977e670f3b036ac\realms-1.14.14.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl\3.2.1\2bb514e444994c6fece99a21f76e0c90438e377f\lwjgl-3.2.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl\3.2.1\e799d06b8969db0610e68776e0eff4b6191098bd\lwjgl-3.2.1-natives-windows.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-jemalloc\3.2.1\7a0c583fcbec32b15784f846df536e1837d83666\lwjgl-jemalloc-3.2.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-jemalloc\3.2.1\3c869b3d7638c800b7039cd859d064658643ad6e\lwjgl-jemalloc-3.2.1-natives-windows.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-openal\3.2.1\dc7ff2dabb40a141ee9bf2e326d9b1b19f3278fb\lwjgl-openal-3.2.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-openal\3.2.1\92fb931e65c637cea209ad5c3ffebd1b325ed41d\lwjgl-openal-3.2.1-natives-windows.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-opengl\3.2.1\57008c2374c5bc434b18adfef3f3653ee450ee18\lwjgl-opengl-3.2.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-opengl\3.2.1\80954961b31084d7b4f2f041d6b5a799a774c880\lwjgl-opengl-3.2.1-natives-windows.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-glfw\3.2.1\27abb7f64894b61cad163791acd8113f0b21296\lwjgl-glfw-3.2.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-glfw\3.2.1\def7c58ad2e1cb258d6d73be181ffab8ef8bd5\lwjgl-glfw-3.2.1-natives-windows.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-stb\3.2.1\31f5eb5fce3791d58ec898bc5c1867d76d781ba1\lwjgl-stb-3.2.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-stb\3.2.1\d100bfd2b0d03223a043cfcb64a2dfd2bb7f4c61\lwjgl-stb-3.2.1-natives-windows.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\com.mojang\text2speech\1.11.3\f378f889797edd7df8d32272c06ca80a1b6b0f58\text2speech-1.11.3.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\com.mojang\text2speech\1.11.3\c0b242c0091be5acbf303263c7eeeaedd70544c7\text2speech-1.11.3-natives-windows.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\net.fabricmc\tiny-mappings-parser\0.1.1.8\bddca0cd742d060de8b8dd0f22ca8d32f648fb85\tiny-mappings-parser-0.1.1.8.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\net.fabricmc\sponge-mixin\0.7.11.23\1a4dddae0dbef2894a98187e891038097e1729c4\sponge-mixin-0.7.11.23.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\net.fabricmc\tiny-remapper\0.1.0.33\2224108967a55a8f9b6a02811d2586cd02596691\tiny-remapper-0.1.0.33.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\net.fabricmc\fabric-loader-sat4j\2.3.5.4\f8fe5353909430b5845ae24ea1e01d83f12ad916\fabric-loader-sat4j-2.3.5.4.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\com.google.jimfs\jimfs\1.1\8fbd0579dc68aba6186935cc1bee21d2f3e7ec1c\jimfs-1.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm\7.1\fa29aa438674ff19d5e1386d2c3527a0267f291e\asm-7.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-analysis\7.1\379e0250f7a4a42c66c5e94e14d4c4491b3c2ed3\asm-analysis-7.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-commons\7.1\431dc677cf5c56660c1c9004870de1ed1ea7ce6c\asm-commons-7.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-tree\7.1\a3662cf1c1d592893ffe08727f78db35392fa302\asm-tree-7.1.jar;C:\Users\mccra\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-util\7.1\5b0b0f8cdb6c90582302ffcf5c20447206122f48\asm-util-7.1.jar;C:\Users\mccra\.gradle\caches\fabric-loom\minecraft-1.14-mapped-3.jar;C:\Users\mccra\Documents\Programming\minecraft\fabric\1.14\core\.gradle\loom-cache\remapped_mods\net.fabricmc.yarn.3.net.fabricmc.fabric-0.2.7+build.127.jar;C:\Users\mccra\Documents\Programming\minecraft\fabric\1.14\core\.gradle\loom-cache\remapped_mods\net.fabricmc.yarn.3.net.fabricmc.fabric-loader-0.4.2+build.132.jar;C:\Users\mccra\Documents\Programming\minecraft\fabric\1.14\core\.gradle\loom-cache\remapped_mods\net.fabricmc.yarn.3.net.fabricmc.fabric-language-kotlin-1.3.30-SNAPSHOT.jar" net.fabricmc.loader.launch.knot.KnotClient --assetIndex 1.14 --assetsDir C:\Users\mccra\.gradle\caches\fabric-loom\assets
[18:30:12] [ForkJoinPool-1-worker-2/WARN]: Mod ID fabric uses outdated schema version: 0 < 1
[18:30:12] [main/INFO]: [FabricLoader] Loading 4 mods: fabric@0.2.7+build.127, fabricloader@0.4.2+build.132, fabric-language-kotlin@1.3.30+build.2, potatocore@1.0.0
[18:30:12] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/mccra/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.7.11.23/1a4dddae0dbef2894a98187e891038097e1729c4/sponge-mixin-0.7.11.23.jar Service=Knot/Fabric Env=CLIENT
[18:30:13] [main/INFO]: Loaded Fabric development mappings for mixin remapper!
[18:30:13] [main/INFO]: Compatibility level set to JAVA_8
[18:30:13] [main/ERROR]: Mixin config net.fabricmc.fabric.mixins.client.json does not specify "minVersion" property
[18:30:13] [main/ERROR]: Mixin config net.fabricmc.fabric.mixins.common.json does not specify "minVersion" property
[18:30:13] [main/INFO]: Remapping refMap net.fabricmc.fabric.refmap.json using remapper chain
[18:30:13] [main/INFO]: Remapping refMap net.fabricmc.fabric.refmap.json using remapper chain
[18:30:15] [main/INFO]: Setting user: Player866
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 4/29/19 6:30 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:41)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.client.MinecraftClient.init(MinecraftClient.java)
	at net.minecraft.client.MinecraftClient.start(MinecraftClient.java:368)
	at net.minecraft.client.main.Main.main(Main.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:117)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access class net.minecraft.recipe.cooking.CookingRecipeSerializer$RecipeFactory from class net.minecraft.recipe.RecipeSerializer
		at net.minecraft.recipe.RecipeSerializer.<clinit>(RecipeSerializer.java:55)
		at net.minecraft.util.registry.Registry.method_17797(Registry.java:158)
		at net.minecraft.util.registry.Registry.method_10238(Registry.java:234)
		at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:671)
		at net.minecraft.util.registry.Registry.<clinit>(Registry.java:233)
		at com.indicode.fabric.potatocore.Potatocore.onInitialize(Potatocore.kt:17)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:34)
		at java.util.ArrayList.forEach(ArrayList.java:1257)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:32)
		... 10 more
	Caused by: java.lang.IllegalAccessError: tried to access class net.minecraft.recipe.cooking.CookingRecipeSerializer$RecipeFactory from class net.minecraft.recipe.RecipeSerializer
		... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:41)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.client.MinecraftClient.init(MinecraftClient.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.MinecraftClient.start(MinecraftClient.java:368)
	at net.minecraft.client.main.Main.main(Main.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:117)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 607772808 bytes (579 MB) / 1505230848 bytes (1435 MB) up to 3782737920 bytes (3607 MB)
	JVM Flags: 0 total; 
	Fabric Mods: 
		fabric: 0.2.7+build.127
		fabric-language-kotlin: 1.3.30+build.2
		fabricloader: 0.4.2+build.132
		potatocore: 1.0.0
	Launched Version: Fabric
	LWJGL: 3.2.1 build 12
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\mccra\Documents\Programming\minecraft\fabric\1.14\core\run\.\crash-reports\crash-2019-04-29_18.30.39-client.txt

Process finished with exit code -1
```

**Comment by asiekierka** [comment]
This is a weird Heisenbug which fixes itself randomly, and never appears again. I wish I could help you...

**Comment by Indi-Code** [comment]
Well that's dissapointing... Should I just try to make a new project repeatedly, until I get one that dosen't fail? Clear it from the gradle cache? Just looking for suggestions here cause' this is really annoying...

**Comment by asiekierka** [comment]
We literally don't know. Everyone who had this problem (a) could not reproduce it, (b) reported that the problem mysteriously disappeared - and we have literally no clue.

**Comment by Indi-Code** [comment]
Thanks anyway :) Guess I'll just try to make a minimap :P

**Comment by asiekierka** [comment]
ACTUALLY

I've had a revelation. Could you try Loader +build.145?

**Comment by Indi-Code** [comment]
> 
> 
> ACTUALLY
> 
> I've had a revelation. Could you try Loader +build.145?

Thanks @asiekierka! Whatever happened in that update magically fixed it!
