### ISSUE TITLE
Initial world generation fails on 21w38a

### ISSUE THREAD

**Issue by CyanNex** [FabricMC/fabric#1739]
Updating the [fabric example mod](https://github.com/FabricMC/fabric-example-mod) to 21w38a and running a server causes an error when world generation starts.

Versions used:
```
minecraft_version=21w38a
yarn_mappings=21w38a+build.1
loader_version=0.11.7
fabric_version=0.40.4+1.18
```

Full stacktrace:
```
Exception in thread "main" [20:11:39] [main/INFO] (Minecraft) [STDERR]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	... 3 more
[20:11:39] [main/INFO] (Minecraft) [STDERR]: Caused by: java.lang.NoSuchFieldError: a
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.biome.source.BiomeSource$class_6543.hashCode(BiomeSource.java:54)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.HashMap.hash(HashMap.java:340)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1195)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.biome.source.BiomeSource.<init>(BiomeSource.java:69)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.biome.source.BiomeSource.<init>(BiomeSource.java:44)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.biome.source.MultiNoiseBiomeSource.<init>(MultiNoiseBiomeSource.java:53)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.biome.source.MultiNoiseBiomeSource$Preset.method_31088(MultiNoiseBiomeSource.java:127)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.biome.source.MultiNoiseBiomeSource$Preset.getBiomeSource(MultiNoiseBiomeSource.java:146)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.dimension.DimensionType.createNetherGenerator(DimensionType.java:216)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.dimension.DimensionType.createDefaultDimensionOptions(DimensionType.java:222)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.gen.GeneratorOptions.fromProperties(GeneratorOptions.java:214)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.dedicated.ServerPropertiesHandler.method_37371(ServerPropertiesHandler.java:91)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.Main.main(Main.java:179)
[20:11:39] [main/INFO] (Minecraft) [STDERR]: 	... 8 more
```

**Comment by modmuss50** [comment]
I assume you are using an outdated version of loom (0.9?) You need to use 0.10 for 1.18, please update and then run `./gradlew build --refresh-dependencies` to regenerate your mc jar.

**Comment by CyanNex** [comment]
Oh sorry, my bad, that appears to have fixed it. Thanks

**Comment by modmuss50** [comment]
Great thanks, Might be worth us adding something to prevent this from happening.
