### ISSUE TITLE
conflicting versions

### ISSUE THREAD

**Issue by SpirinW** [FabricMC/fabric#1769]
i tried loading the game(worked)
loading any siglepayer world gets stuck on joining world. I tried to do the same thing with just vanila and it worked normally.
I will add the latest log file contents:
[15:06:29] [main/INFO]: Loading for game Minecraft 1.17.1
[15:06:29] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b446313, also found 0.3.0+a02b44633d, 0.3.0+a02b446318
 - Conflicting versions found for fabric-lifecycle-events-v1: used 1.4.4+a02b446313, also found 1.4.4+a02b446318
 - Conflicting versions found for fabric-screen-api-v1: used 1.0.4+198a96213d, also found 1.0.4+cbda931818
[15:06:29] [main/INFO]: [FabricLoader] Loading 58 mods:
	- bbor@2.4-1.17.1
	- fabric@0.40.6+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.3.0+cbda931818
	- fabric-biome-api-v1@3.2.0+cbda931818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+cbda931818
	- fabric-content-registries-v0@0.3.0+cbda931818
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.2.3+87cc6e4c18
	- fabric-events-interaction-v0@0.4.10+fc40aa9d18
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+cbda931818
	- fabric-item-api-v1@1.2.4+cbda931818
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+cbda931818
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-lifecycle-events-v1@1.4.4+a02b446313
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.13+cbda931818
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+cbda931818
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.11+7931163218
	- fabric-renderer-api-v1@0.4.4+cbda931818
	- fabric-renderer-indigo@0.4.8+cbda931818
	- fabric-renderer-registries-v1@3.2.4+7931163218
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446318
	- fabric-rendering-fluids-v1@0.1.14+4658223018
	- fabric-rendering-v0@1.1.5+7931163218
	- fabric-rendering-v1@1.9.0+7931163218
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+198a96213d
	- fabric-screen-handler-api-v1@1.1.8+cbda931818
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.2.1+b06cb95b18
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.4.0+7931163218
	- fabricloader@0.11.6
	- itemscroller@0.15.0-dev.20210707.005506
	- java@16
	- litematica@0.0.0-dev.20210707.011234
	- malilib@0.10.0-dev.23
	- minecraft@1.17.1
	- minihud@0.19.0-dev.20211006.014748
	- modmenu@2.0.4
	- quickcarpet@3.2.0
	- quickcarpet-api@1.1.0
	- tweakeroo@0.10.0-dev.20210912.004443
	- worldedit@7.2.6-beta-02+2e45a20
[15:06:30] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/%d0%92%d0%bb%d0%b0%d0%b4%d0%b8%d1%81%d0%bb%d0%b0%d0%b2/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[15:06:30] [main/INFO]: Compatibility level set to JAVA_16
[15:06:31] [main/WARN]: [quickcarpet] detected, disabling UPDATE mixin com.sk89q.worldedit.fabric.mixin.MixinWorldChunkSetBlockHook
[15:06:31] [main/INFO]: Applying Fabric API Registry Sync workaround
[15:06:31] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[15:06:34] [main/WARN]: Method overwrite conflict for getLanguage in quickcarpet.mixins.json:core.ServerPlayerEntityMixin, previously written by com.sk89q.worldedit.fabric.mixin.MixinServerPlayerEntity. Skipping method.
[15:06:44] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:06:45] [Render thread/INFO]: Setting user: Restless__
[15:06:45] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zzn000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[15:06:47] [Render thread/INFO]: Got request to register class com.sk89q.worldedit.fabric.FabricPlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@27574ba9]
[15:06:47] [Render thread/INFO]: WorldEdit for Fabric (version 7.2.6-beta-02+2e45a20) is loaded
[15:06:48] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[15:06:49] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[15:06:53] [Render thread/INFO]: Narrator library for x64 successfully loaded
[15:06:53] [Render thread/INFO]: Reloading ResourceManager: Default, Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), Fabric Loader, Fabric Transfer API (v1), BoundingBoxOutlineReloaded, Fabric Structure API (v1), Fabric Containers (v0), Fabric Object Builder API (v1), Fabric Dimensions API (v1), Fabric Game Rule API (v1), QuickCarpet, Fabric API Base, Fabric Rendering Data Attachment (v1), QuickCarpet API, Fabric Textures (v0), Tweakeroo, Fabric Rendering Fluids (v1), Litematica, Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), MiniHUD, Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), Fabric Networking (v0), Fabric API Lookup API (v1), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Mod Menu, Fabric Command API (v1), Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Item API (v1), Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Fabric Resource Loader (v0), MaLiLib, Fabric Content Registries (v0), Fabric Tag Extensions (v0), WorldEdit, Fabric Biome API (v1), Fabric Registry Sync (v0), Fabric Commands (v0), Item Scroller, Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Item Groups (v0), Fabric Models (v0), Fabric Object Builders (v0)), VanillaTweaks_r968309.zip
[15:06:55] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[15:06:55] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[15:06:55] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[15:06:55] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[15:06:55] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[15:06:55] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[15:06:55] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[15:06:55] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[15:06:56] [Render thread/WARN]: Invalid item 'minecraft:nether_portal'
[15:06:56] [Render thread/WARN]: Invalid item 'minecraft:frosted_ice'
[15:06:56] [Render thread/WARN]: Invalid item 'minecraft:end_portal'
[15:07:03] [Worker-Main-5/WARN]: Texture minecraft:block/lever_base_on with size 8x8 limits mip level from 4 to 3
[15:07:03] [Worker-Main-5/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 3, because of minimum power of two: 8
[15:07:08] [Render thread/INFO]: OpenAL initialized.
[15:07:08] [Render thread/INFO]: Sound engine started
[15:07:09] [Render thread/INFO]: Created: 1024x1024x3 minecraft:textures/atlas/blocks.png-atlas
[15:07:09] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[15:07:09] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[15:07:09] [Render thread/INFO]: Created: 2048x1024x4 minecraft:textures/atlas/shield_patterns.png-atlas
[15:07:09] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[15:07:09] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[15:07:09] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[15:07:12] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[15:07:12] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[15:07:12] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[15:07:21] [Render thread/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinCloneCommand->@ModifyConstant::getBlockCountLimit(I)I with priority 999, already redirected by quickcarpet.mixins.json:commands.CloneCommandMixin->@ModifyConstant::fillLimit(I)I with priority 1000
[15:07:21] [Render thread/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinCloneCommand->@ModifyConstant::getBlockCountLimit(I)I with priority 999, already redirected by quickcarpet.mixins.json:commands.CloneCommandMixin->@ModifyConstant::fillLimit(I)I with priority 1000
[15:07:21] [Render thread/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinFillCommand->@ModifyConstant::getBlockCountLimit(I)I with priority 999, already redirected by quickcarpet.mixins.json:commands.FillCommandMixin->@ModifyConstant::fillLimit(I)I with priority 1000
[15:07:21] [Render thread/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinFillCommand->@ModifyConstant::getBlockCountLimit(I)I with priority 999, already redirected by quickcarpet.mixins.json:commands.FillCommandMixin->@ModifyConstant::fillLimit(I)I with priority 1000
[15:07:21] [Render thread/INFO]: Registering commands with com.sk89q.worldedit.fabric.FabricPlatform
[15:07:21] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:07:21] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:07:21] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[15:07:21] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[15:07:21] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:07:21] [Render thread/INFO]: Reloading ResourceManager: Default, skyblockDatapack, Fabric Mods (QuickCarpet, Fabric Tool Attribute API (v1)), Default
[15:07:22] [Worker-Main-4/ERROR]: Couldn't parse data file skyblock:ocean/head_hunter from skyblock:advancements/ocean/head_hunter.json
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 20 column 75 path $.criteria.creeper_head.conditions.items[0].items[1]
	at net.minecraft.class_3518.method_15267(class_3518.java:495) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3518.method_15276(class_3518.java:532) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_4309.method_20731(class_4309.java:47) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_4309.method_18789(class_4309.java:21) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_4080.method_18791(class_4080.java:11) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 20 column 75 path $.criteria.creeper_head.conditions.items[0].items[1]
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:476) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:730) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[gson-2.8.0.jar:?]
	at net.minecraft.class_3518.method_15267(class_3518.java:493) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	... 11 more
[15:07:26] [Render thread/INFO]: Loaded 7 recipes
[15:07:26] [Render thread/WARN]: Found validation problem in {minecraft:entities/enderman}.pools[0].entries[0]: Unknown loot table called vanilla:entities/enderman
[15:07:27] [Render thread/INFO]: Loaded 1268 advancements
[15:07:27] [Render thread/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 2.657 ms
[15:07:27] [Render thread/WARN]: Adding minecraft:beehive to saved/remote registry.
[15:07:27] [Render thread/WARN]: Adding minecraft:sculk_sensor to saved/remote registry.
[15:07:27] [Render thread/WARN]: Adding carpet:crafting_table to saved/remote registry.
[15:07:27] [Render thread/WARN]: [fabric-registry-sync] Could not find the following registries: minecraft:biome_source_type, minecraft:dimension_type, minecraft:structure_piece, minecraft:carver, minecraft:decorator, minecraft:structure_feature, minecraft:surface_builder, minecraft:feature, minecraft:structure_pool_element, minecraft:biome, minecraft:chunk_generator_type, minecraft:structure_processor
[15:07:27] [Render thread/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[15:07:29] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:07:29] [Server thread/INFO]: Starting integrated minecraft server version 1.17.1
[15:07:29] [Server thread/INFO]: Generating keypair
[15:07:30] [Server thread/INFO]: create world dimension: minecraft:overworld (seed: 2331713264264927020)
[15:07:30] [Server thread/INFO]: create world dimension: minecraft:the_nether (seed: 2331713264264927020)
[15:07:30] [Server thread/INFO]: create world dimension: minecraft:the_end (seed: 2331713264264927020)
[15:07:30] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[15:07:31] [Render thread/INFO]: Preparing spawn area: 0%
[15:07:31] [Render thread/INFO]: Preparing spawn area: 0%
[15:07:32] [Render thread/INFO]: Preparing spawn area: 0%
[15:07:32] [Render thread/INFO]: Preparing spawn area: 0%
[15:07:33] [Render thread/INFO]: Preparing spawn area: 2%
[15:07:33] [Render thread/INFO]: Preparing spawn area: 10%
[15:07:34] [Render thread/INFO]: Preparing spawn area: 11%
[15:07:35] [Render thread/INFO]: Preparing spawn area: 15%
[15:07:35] [Render thread/INFO]: Preparing spawn area: 23%
[15:07:36] [Render thread/INFO]: Preparing spawn area: 52%
[15:07:36] [Render thread/INFO]: Preparing spawn area: 52%
[15:07:40] [Render thread/INFO]: Time elapsed: 8967 ms
[15:07:44] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 4096ms or 81.92 ticks behind
[15:07:44] [Server thread/INFO]: Changing view distance to 13, from 10
[15:07:46] [Server thread/INFO]: Restless__[local:E:9969cdf3] logged in with entity id 4 at (3.727693909168513, 0.5, 10.032974407428688)
[15:07:47] [Server thread/INFO]: Restless__ joined the game
[15:07:49] [Render thread/WARN]: Invalid item 'minecraft:nether_portal'
[15:07:49] [Render thread/WARN]: Invalid item 'minecraft:frosted_ice'
[15:07:49] [Render thread/WARN]: Invalid item 'minecraft:end_portal'
[15:07:49] [Server thread/INFO]: Saving and pausing game...
[15:07:49] [Render thread/INFO]: (Re-)creating the schematic world...
[15:07:49] [Render thread/INFO]: Schematic world created: fi.dy.masa.litematica.world.WorldSchematic@7bdcbf96
[15:07:49] [Render thread/INFO]: Using 3 total BufferBuilder caches
[15:07:49] [Render thread/INFO]: [STDOUT]: sending register for [carpet:rules, carpet:pubsub]
[15:07:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Skyblock 1.17_4.09.1]'/minecraft:overworld
[15:07:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Skyblock 1.17_4.09.1]'/minecraft:the_nether
[15:07:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Skyblock 1.17_4.09.1]'/minecraft:the_end
[15:07:51] [Render thread/INFO]: Loaded 410 advancements

**Comment by warjort** [comment]
There is no actual error shown in this log.

But the warnings beginning:
````
[15:07:21] [Render thread/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinCloneCommand->@ModifyConstant::getBlockCountLimit(I)I with priority 999, already redirected by quickcarpet.mixins.json:commands.CloneCommandMixin->@ModifyConstant::fillLimit(I)I with priority 1000
````
suggest a mod conflict between tweakeroo and quickcarpet.
