### ISSUE TITLE
[MultiMC] crashes even without using any mods

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#1774]
The normal Minecraft launcher works just fine, but when using MultiMC it just crashes

```
MultiMC version: 0.6.13-2519


Launched instance in online mode
Authentication server is online

authserver.mojang.com resolves to:
    [65.9.160.71]

session.minecraft.net resolves to:
    [34.192.50.106, 52.44.210.220, 3.234.0.54]

textures.minecraft.net resolves to:
    [13.227.220.121, 13.227.220.56, 13.227.220.16, 13.227.220.127]

api.mojang.com resolves to:
    [65.9.184.95]


Minecraft folder is:
/mnt/hdd_1/instances/minecraft/multi-mc/21w41a/.minecraft


Java path is:
/usr/lib/jvm/java-16-openjdk/bin/java


Checking Java version...
Java is version 16.0.2, using 64-bit architecture, from N/A.


AMD Ryzen 5 3600 6-Core Processor
NVIDIA Corporation TU106 [GeForce RTX 2060 Rev. A] (rev a1)

Subsystem: Gigabyte Technology Co., Ltd Device 402b

Kernel driver in use: nvidia

OpenGL version string: 4.6.0 NVIDIA 470.74

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  /mnt/hdd_1/instances/minecraft/multi-mc/21w41a/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /home/maximilian/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /home/maximilian/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /home/maximilian/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /home/maximilian/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /home/maximilian/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /home/maximilian/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /home/maximilian/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /home/maximilian/.local/share/multimc/libraries/com/mojang/blocklist/1.0.5/blocklist-1.0.5.jar
  /home/maximilian/.local/share/multimc/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  /home/maximilian/.local/share/multimc/libraries/com/github/oshi/oshi-core/5.7.5/oshi-core-5.7.5.jar
  /home/maximilian/.local/share/multimc/libraries/net/java/dev/jna/jna/5.8.0/jna-5.8.0.jar
  /home/maximilian/.local/share/multimc/libraries/net/java/dev/jna/jna-platform/5.8.0/jna-platform-5.8.0.jar
  /home/maximilian/.local/share/multimc/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home/maximilian/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.14.1/log4j-slf4j18-impl-2.14.1.jar
  /home/maximilian/.local/share/multimc/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  /home/maximilian/.local/share/multimc/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /home/maximilian/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home/maximilian/.local/share/multimc/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /home/maximilian/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home/maximilian/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home/maximilian/.local/share/multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home/maximilian/.local/share/multimc/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/maximilian/.local/share/multimc/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /home/maximilian/.local/share/multimc/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  /home/maximilian/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home/maximilian/.local/share/multimc/libraries/com/mojang/authlib/3.1.36/authlib-3.1.36.jar
  /home/maximilian/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/maximilian/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/maximilian/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/maximilian/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/maximilian/.local/share/multimc/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  /home/maximilian/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar
  /home/maximilian/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar
  /home/maximilian/.local/share/multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /home/maximilian/.local/share/multimc/libraries/net/fabricmc/intermediary/21w41a/intermediary-21w41a.jar
  /home/maximilian/.local/share/multimc/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  /home/maximilian/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar
  /home/maximilian/.local/share/multimc/libraries/net/fabricmc/tiny-remapper/0.6.0/tiny-remapper-0.6.0.jar
  /home/maximilian/.local/share/multimc/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar
  /home/maximilian/.local/share/multimc/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  /home/maximilian/.local/share/multimc/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
  /home/maximilian/.local/share/multimc/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  /home/maximilian/.local/share/multimc/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  /home/maximilian/.local/share/multimc/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  /home/maximilian/.local/share/multimc/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  /home/maximilian/.local/share/multimc/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  /home/maximilian/.local/share/multimc/libraries/net/fabricmc/fabric-loader/0.11.7/fabric-loader-0.11.7.jar
  /home/maximilian/.local/share/multimc/libraries/com/mojang/minecraft/21w41a/minecraft-21w41a-client.jar

Native libraries:
  /home/maximilian/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
  /home/maximilian/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
  /home/maximilian/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
  /home/maximilian/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar
  /home/maximilian/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
  /home/maximilian/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar
  /home/maximilian/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar
  /home/maximilian/.local/share/multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar

Params:
  --username  --version MultiMC5 --gameDir /mnt/hdd_1/instances/minecraft/multi-mc/21w41a/.minecraft --assetsDir /home/maximilian/.local/share/multimc/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType snapshot

Window size: max (if available)

Java Arguments:
[-Xms512m, -Xmx8192m, -Duser.language=en]


Minecraft process ID: 9950


Using onesix launcher.

[10:46:38] [main/INFO]: Loading for game Minecraft 21w41a
[10:46:38] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: error remapping game jar /home/maximilian/.local/share/multimc/libraries/com/mojang/minecraft/21w41a/minecraft-21w41a-client.jar
	at net.fabricmc.loader.launch.common.FabricLauncherBase.deobfuscate(FabricLauncherBase.java:120)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:117)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more
Caused by: java.nio.file.FileSystemException: /mnt/hdd_1/instances/minecraft/multi-mc/21w41a/.minecraft/.fabric/remappedJars/minecraft-1.18-alpha.21.41.a/zipfstmp13012234079408636776.tmp: Operation not permitted
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:275)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:297)
	at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2159)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.sync(ZipFileSystem.java:1844)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.lambda$close$9(ZipFileSystem.java:474)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.close(ZipFileSystem.java:473)
	at net.fabricmc.tinyremapper.OutputConsumerPath.close(OutputConsumerPath.java:226)
	at net.fabricmc.loader.launch.common.FabricLauncherBase.deobfuscate0(FabricLauncherBase.java:186)
	at net.fabricmc.loader.launch.common.FabricLauncherBase.deobfuscate(FabricLauncherBase.java:118)
	... 10 more
Exiting with -1
Process exited with code 255.
```

**Comment by warjort** [comment]
````
Caused by: java.nio.file.FileSystemException: /mnt/hdd_1/instances/minecraft/multi-mc/21w41a/.minecraft/.fabric/remappedJars/minecraft-1.18-alpha.21.41.a/zipfstmp13012234079408636776.tmp: 
Operation not permitted

	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:297)
````

Your problem is the user running the minecraft process does not have the rights to set the file permissions for this temporary file.
