### ISSUE TITLE
having issues launching fabric on 1.16.5 after installing java 17

### ISSUE THREAD

**Issue by Kaimetsu17** [FabricMC/fabric#1803]
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	... 2 more
Caused by: java.lang.UnsupportedClassVersionError: net/fabricmc/fabric/api/event/EventFactory has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:170)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_2370.<init>(class_2370.java:52)
	at net.minecraft.class_2378.<clinit>(class_2378.java:102)
	at net.minecraft.class_2966.method_12851(class_2966.java:42)
	at net.minecraft.client.main.Main.main(Main.java:137)
	... 7 more
[2021-11-05-7.log.gz](https://github.com/FabricMC/fabric/files/7484581/2021-11-05-7.log.gz)

**Comment by modmuss50** [comment]
One of the mods you have installed is pulling in fabric-api-base for 1.17, I expect one of the mods you have installed is designed for 1.17 minecraft.

You are using Minecraft 1.16 that will run on Java 8. Even though I expect you have installed Java 17 on your system the game is still beign ran with Java 8.  Do note that the Minecraft launcher will now not allow you to use Java 16/17 with Minecraft 1.16 or lower.

**Comment by Kaimetsu17** [comment]
it was thank you, one of the origin mods that said it was for 1.16.5 apparently had an update to allow it to run in 1.17
