### ISSUE TITLE
 Failed to read accessWidener file from mod fabric-object-builder-api-v1

### ISSUE THREAD

**Issue by CoderThomasB** [FabricMC/fabric#1826]
I just started a new and fresh fabric mod but I'm having this error when I try to build it:
```
Exception in thread "main" java.lang.RuntimeException: Failed to read accessWidener file from mod fabric-object-builder-api-v1
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:451)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:122)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (intermediary) does not match current runtime namespace (named)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:281)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:90)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:449)
	... 4 more
```
Here is my gradle:
```
plugins {
    id 'fabric-loom' version '0.10-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // PSA: Some older mods, compiled on Loom 0.2.1, might have outdated Maven POMs.
    // You may need to force-disable transitiveness on them.
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

def targetJavaVersion = 16
tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release = targetJavaVersion
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    archivesBaseName = project.archives_base_name
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            // add all the jars that should be included when publishing to maven
            artifact(remapJar) {
                builtBy remapJar
            }
            artifact(sourcesJar) {
                builtBy remapSourcesJar
            }
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}

```

**Comment by Jab125** [comment]
try invalidating caches

**Comment by CoderThomasB** [comment]
> try invalidating caches

Yep, that fixed it! I just deleted the .gradle, .idea and build folders.

**Comment by agolaandthor** [comment]
how can i do that?

**Comment by CoderThomasB** [comment]
> How can I do that?

If you are using Intellij, there will be a folder on the left panel with the names `.gradle`, `.idea` and `build`. Move them to your trash and try rebuilding your project using the run button.

**Comment by TOLGA1004** [comment]
dude, where are those files?

**Comment by CoderThomasB** [comment]
> dude, where are those files?

Can you elaborate on what files you are talking about?

**Comment by fairwarier** [comment]
hrlp me please i cant run wurst from this error what do i do?
