### ISSUE TITLE
First Time Fabric User

### ISSUE THREAD

**Issue by Shmeepicuss** [FabricMC/fabric#1831]
This might be an easy fix, I've no idea though. I've got a couple of friends that use the exact same mods, though everytime I try to run the game, it boots me out. This is my first time using Fabric, used to use Forge frequently so all this is new to me.

Crash text listed below.

Mods:
  [✔️] AdvancedChat-3.2.0-1.16.5
  [✔️] bobby-1.2.0
  [✔️] cloth-config-4.12.41-fabric
  [✔️] dashloader-1.4.5
  [✔️] fabric-api-0.42.0+1.16
  [✔️] lithium-fabric-mc1.16.5-0.6.6
  [✔️] malilib-fabric-1.16.4-0.10.0-dev.21+arne.5
  [✔️] modmenu-1.16.22
  [✔️] okzoomer-4.0.1+1.16.2
  [✔️] phosphor-fabric-mc1.16.3-0.7.2+build.12
  [✔️] seamless-loading-screen-1.3.4+1.16.2
  [✔️] sodium-extra-mc1.16.5-0.3.5
  [✔️] sodium-fabric-mc1.16.5-0.2.0+build.4
  [✔️] stendhal-1.1.0

Params:
  --username  --version MultiMC5 --gameDir C:/Users/dgkyr/OneDrive/Desktop/MultiMC/instances/1.16.5/.minecraft --assetsDir C:/Users/dgkyr/OneDrive/Desktop/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 26052

Using onesix launcher.

[20:03:14] [main/INFO]: Loading for game Minecraft 1.16.5
[20:03:15] [main/WARN]: Warnings were found!
 - Mod 'Sodium Extra' (sodium-extra) recommends any version of reeses-sodium-options, which is missing!
	 - You should install any version of reeses-sodium-options for the optimal experience.
[20:03:15] [main/INFO]: Loading 74 mods:
	- advancedchat 3.2.0-1.16.5
	- bobby 1.2.0
	- cloth-basic-math 0.6.0
	- cloth-config2 4.12.41
	- com_typesafe_config 1.4.1
	- confabricate 2.0.3+4.0.0
	- dashloader 1.4.5
	- fabric 0.42.0+1.16
	- fabric-api-base 0.4.0+3cc0f0907d
	- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d
	- fabric-biome-api-v1 3.1.13+3cc0f0907d
	- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d
	- fabric-command-api-v1 1.1.3+3cc0f0907d
	- fabric-commands-v0 0.2.3+3cc0f0907d
	- fabric-containers-v0 0.1.12+3cc0f0907d
	- fabric-content-registries-v0 0.2.5+3cc0f0907d
	- fabric-crash-report-info-v1 0.1.4+3cc0f0907d
	- fabric-dimensions-v1 2.0.8+3cc0f0907d
	- fabric-entity-events-v1 1.2.4+3cc0f0907d
	- fabric-events-interaction-v0 0.4.5+3cc0f0907d
	- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d
	- fabric-game-rule-api-v1 1.0.7+3cc0f0907d
	- fabric-item-api-v1 1.2.2+3cc0f0907d
	- fabric-item-groups-v0 0.3.1+3cc0f0907d
	- fabric-key-binding-api-v1 1.0.5+3cc0f0907d
	- fabric-keybindings-v0 0.2.2+3cc0f0907d
	- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d
	- fabric-loot-tables-v1 1.0.3+3cc0f0907d
	- fabric-mining-levels-v0 0.1.4+3cc0f0907d
	- fabric-models-v0 0.3.1+3cc0f0907d
	- fabric-networking-api-v1 1.0.5+3cc0f0907d
	- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d
	- fabric-networking-v0 0.3.3+3cc0f0907d
	- fabric-object-builder-api-v1 1.9.6+3cc0f0907d
	- fabric-object-builders-v0 0.7.3+3cc0f0907d
	- fabric-particles-v1 0.2.5+3cc0f0907d
	- fabric-registry-sync-v0 0.7.6+3cc0f0907d
	- fabric-renderer-api-v1 0.4.5+3cc0f0907d
	- fabric-renderer-indigo 0.4.5+3cc0f0907d
	- fabric-renderer-registries-v1 2.3.1+3cc0f0907d
	- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d
	- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d
	- fabric-rendering-v0 1.1.3+3cc0f0907d
	- fabric-rendering-v1 1.6.1+3cc0f0907d
	- fabric-resource-loader-v0 0.4.8+3cc0f0907d
	- fabric-screen-api-v1 1.0.1+3cc0f0907d
	- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d
	- fabric-structure-api-v1 1.1.12+3cc0f0907d
	- fabric-tag-extensions-v0 1.1.2+3cc0f0907d
	- fabric-textures-v0 1.0.7+3cc0f0907d
	- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d
	- fabric-transfer-api-v1 1.5.0+3cc0f0907d
	- fabricloader 0.12.0
	- fiber 0.23.0-2
	- io_activej_activej-codegen 4.2
	- io_activej_activej-serializer 4.2
	- io_leangen_geantyref_geantyref 1.3.11
	- java 8
	- lithium 0.6.6
	- malilib 0.10.0-dev.21+arne.5
	- minecraft 1.16.5
	- modmenu 1.16.22
	- net_gudenau_lib_unsafe 1.4.1
	- okzoomer 4.0.1+1.16.2
	- org_slf4j_slf4j-api 1.7.29
	- org_spongepowered_configurate-core 4.0.0
	- org_spongepowered_configurate-extra-dfu4 4.0.0
	- org_spongepowered_configurate-gson 4.0.0
	- org_spongepowered_configurate-hocon 4.0.0
	- phosphor 0.7.2+build.12
	- seamless_loading_screen 1.3.4
	- sodium 0.2.0+build.4
	- sodium-extra 0.3.5
	- stendhal 1.1.0
[20:03:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/dgkyr/OneDrive/Desktop/MultiMC/libraries/net/fabricmc/sponge-mixin/0.10.2+mixin.0.8.4/sponge-mixin-0.10.2+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[20:03:15] [main/INFO]: Loaded configuration file for Lithium: 80 options available, 0 override(s) found
[20:03:15] [main/INFO]: Loaded configuration file for Sodium: 24 options available, 2 override(s) found
[20:03:15] [main/WARN]: Force-disabling mixin 'features.gui.fast_loading_screen.MixinLevelLoadingScreen' as rule 'mixin.features.gui.fast_loading_screen' (added by mods [seamless_loading_screen]) disables it and children
[20:03:15] [main/WARN]: Force-disabling mixin 'features.model.MixinMultipartBakedModel' as rule 'mixin.features.model' (added by mods [dashloader]) disables it and children
[20:03:15] [main/WARN]: Catching java.lang.ClassNotFoundException: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen
java.lang.ClassNotFoundException: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassBytes(MixinServiceKnot.java:65) ~[fabric-loader-0.12.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:76) ~[fabric-loader-0.12.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:71) ~[fabric-loader-0.12.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:2022) [sponge-mixin-0.10.2+mixin.0.8.4.jar:0.10.2+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1018) [sponge-mixin-0.10.2+mixin.0.8.4.jar:0.10.2+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1008) [sponge-mixin-0.10.2+mixin.0.8.4.jar:0.10.2+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:896) [sponge-mixin-0.10.2+mixin.0.8.4.jar:0.10.2+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:869) [sponge-mixin-0.10.2+mixin.0.8.4.jar:0.10.2+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:781) [sponge-mixin-0.10.2+mixin.0.8.4.jar:0.10.2+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:539) [sponge-mixin-0.10.2+mixin.0.8.4.jar:0.10.2+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [sponge-mixin-0.10.2+mixin.0.8.4.jar:0.10.2+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.10.2+mixin.0.8.4.jar:0.10.2+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.10.2+mixin.0.8.4.jar:0.10.2+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.10.2+mixin.0.8.4.jar:0.10.2+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.10.2+mixin.0.8.4.jar:0.10.2+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) [fabric-loader-0.12.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133) [fabric-loader-0.12.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-loader-0.12.0.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_251]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:566) [fabric-loader-0.12.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.12.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[20:03:15] [main/WARN]: Error loading class: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen (java.lang.ClassNotFoundException: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen)
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Minecraft has crashed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:571)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 8 more
Caused by: java.lang.IllegalArgumentException
	at com.google.gson.internal.$Gson$Preconditions.checkArgument(.java:46)
	at com.google.gson.GsonBuilder.registerTypeAdapter(GsonBuilder.java:497)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	... 10 more

**Comment by Shmeepicuss** [comment]
Tacking on that Auth, Session, Skins and API all have red X's next to them as well on the MultiMC launcher.
