### ISSUE TITLE
Crash when switching Fabric Loader version 

### ISSUE THREAD

**Issue by andreasdc** [FabricMC/fabric#1833]
On 1.11.7 I don't have crash, when I switch to 1.12.5 or 1.12.0 I can't run the game with mods.

[09:50:16] [main/INFO]: Done initializing StacktraceDeobfuscator
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Minecraft has crashed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:571)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 8 more
Caused by: java.lang.IllegalArgumentException
	at com.google.gson.internal.$Gson$Preconditions.checkArgument(.java:46)
	at com.google.gson.GsonBuilder.registerTypeAdapter(GsonBuilder.java:497)
	at net.minecraft.client.main.Main.main(Main.java:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	... 10 more
Exiting with -1

**Comment by warjort** [comment]
````
Caused by: java.lang.IllegalArgumentException
at com.google.gson.internal.$Gson$Preconditions.checkArgument(.java:46)
at com.google.gson.GsonBuilder.registerTypeAdapter(GsonBuilder.java:497)
at net.minecraft.client.main.Main.main(Main.java:120)
````

This error is not very informative, but it looks like minecraft is trying to register its json type adapters
but they have the wrong types (it is doing instanceof checks).

This is most likely to happen if there is more than one version of google's gson.jar somewhere in your classpath or mods
and both are getting used at the same time, causing the conflict .
(In java, two different versions of the same class loaded from different classloaders are not the same type even though they have the same name).

Hard to help more without additional information.

If you are reporting a bug, this issue belongs against the fabric loader project:
https://github.com/FabricMC/fabric-loader
This project is for the modding api.

**Comment by warjort** [comment]
> On 1.11.7 I don't have crash, when I switch to 1.12.5 or 1.12.0 I can't run the game with mods.

Try running the game without any mods, i.e. only the fabric loader. 
If that works, add the mods back individually until you find the problem mod.

**Comment by andreasdc** [comment]
Found the incompatible mod, sadly it doesn't show exactly what causes this from the beginning.
