### ISSUE TITLE
Failed to store chunk - java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by ezrareeves** [FabricMC/fabric#1875]
After upgrading my 1.17.1 server to 1.18 I started getting these errors.
happens every 15 minutes or so even with no mods loaded, just fabric.

[16:44:23] [IO-Worker-54/ERROR]: Failed to store chunk [1, -2]
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
at net.minecraft.class_2487.method_10713(class_2487.java:163) ~[intermediary-server-1.18.jar:?]
at net.minecraft.class_2487.method_10555(class_2487.java:476) ~[intermediary-server-1.18.jar:?]
at net.minecraft.class_2487.method_10713(class_2487.java:165) ~[intermediary-server-1.18.jar:?]
at net.minecraft.class_2499.method_10713(class_2499.java:128) ~[intermediary-server-1.18.jar:?]
at net.minecraft.class_2487.method_10555(class_2487.java:476) ~[intermediary-server-1.18.jar:?]
at net.minecraft.class_2487.method_10713(class_2487.java:165) ~[intermediary-server-1.18.jar:?]
at net.minecraft.class_2499.method_10713(class_2499.java:128) ~[intermediary-server-1.18.jar:?]
at net.minecraft.class_2487.method_10555(class_2487.java:476) ~[intermediary-server-1.18.jar:?]
at net.minecraft.class_2487.method_10713(class_2487.java:165) ~[intermediary-server-1.18.jar:?]
at net.minecraft.class_2507.method_10631(class_2507.java:118) ~[intermediary-server-1.18.jar:?]
at net.minecraft.class_2507.method_10628(class_2507.java:83) ~[intermediary-server-1.18.jar:?]
at net.minecraft.class_2867.method_23726(class_2867.java:79) ~[intermediary-server-1.18.jar:?]
at net.minecraft.class_4698.method_23701(class_4698.java:174) ~[intermediary-server-1.18.jar:?]
at net.minecraft.class_4698.method_23719(class_4698.java:164) ~[intermediary-server-1.18.jar:?]
at net.minecraft.class_3847$class_3907.run(class_3847.java:59) [intermediary-server-1.18.jar:?]
at net.minecraft.class_3846.method_16907(class_3846.java:91) [intermediary-server-1.18.jar:?]
at net.minecraft.class_3846.method_16900(class_3846.java:146) [intermediary-server-1.18.jar:?]
at net.minecraft.class_3846.run(class_3846.java:102) [intermediary-server-1.18.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by James103** [comment]
Does this happen on a pure vanilla server? In order words, can you try reproducing this using a separate server instance of Minecraft 1.18 that is not modded in any way?

**Comment by ezrareeves** [comment]
I tried running the same server without fabric and the error stopped.

**Comment by ezrareeves** [comment]
It seems more  sporadic than I thought it was though.  I only let it run for about an hour in vanilla . It's possible that it just didn't happen during that hour.

Last night I thought it might have stopped because it went 4 hours without happening  but then it started again.

**Comment by ezrareeves** [comment]
With a longer test without fabric I see it happen in pure vanilla as well. :(

**Comment by ezrareeves** [comment]
[13:11:55] [IO-Worker-97/ERROR]: Failed to store chunk [1, -2]
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
	at oc.a(SourceFile:163) ~[server-1.18.jar:?]
	at oc.a(SourceFile:476) ~[server-1.18.jar:?]
	at oc.a(SourceFile:165) ~[server-1.18.jar:?]
	at oi.a(SourceFile:128) ~[server-1.18.jar:?]
	at oc.a(SourceFile:476) ~[server-1.18.jar:?]
	at oc.a(SourceFile:165) ~[server-1.18.jar:?]
	at oi.a(SourceFile:128) ~[server-1.18.jar:?]
	at oc.a(SourceFile:476) ~[server-1.18.jar:?]
	at oc.a(SourceFile:165) ~[server-1.18.jar:?]
	at om.a(SourceFile:118) ~[server-1.18.jar:?]
	at om.a(SourceFile:83) ~[server-1.18.jar:?]
	at crb.a(SourceFile:79) ~[server-1.18.jar:?]
	at cqy.a(SourceFile:174) ~[server-1.18.jar:?]
	at cqy.a(SourceFile:164) ~[server-1.18.jar:?]
	at aum$b.run(SourceFile:59) [server-1.18.jar:?]
	at auk.g(SourceFile:91) [server-1.18.jar:?]
	at auk.a(SourceFile:146) [server-1.18.jar:?]
	at auk.run(SourceFile:102) [server-1.18.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by ch-yx** [comment]
https://bugs.mojang.com/browse/MC-243796
