### ISSUE TITLE
Fabric server crushed on startup 1.17.1

### ISSUE THREAD

**Issue by SherkeyXD** [FabricMC/fabric#1887]
logs:
[06:00:07] [INFO] [FabricLoader/GameProvider]: Loading for game Minecraft 1.17.1
[06:00:09] [main/INFO]: Loading for game Minecraft 1.17.1
[06:00:09] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.2.1+cf39a74318 recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
         - You should install any version of fabric-textures-v0 for the optimal experience.
[06:00:09] [main/INFO]: Loading 59 mods:
        - bannerpp 2.0.4+mc.1.17-rc1 via botania
        - botania 1.17.1-421-FABRIC
        - cardinal-components-base 3.0.0 via trinkets
        - cardinal-components-block 3.0.0 via botania
        - cardinal-components-entity 3.0.0 via trinkets
        - cloth-basic-math 0.6.0 via cloth-config2
        - cloth-config2 5.1.40
        - expandedstorage 7.3.1
        - fabric 0.44.0+1.17
        - fabric-api-base 0.4.0+cf39a74318 via fabric
        - fabric-api-lookup-api-v1 1.4.0+cb9053d118 via fabric
        - fabric-biome-api-v1 3.2.2+cf39a74318 via fabric
        - fabric-command-api-v1 1.1.4+cf39a74318 via fabric
        - fabric-commands-v0 0.2.3+cf39a74318 via fabric
        - fabric-containers-v0 0.1.13+cf39a74318 via fabric
        - fabric-content-registries-v0 0.4.1+3447790d18 via fabric
        - fabric-crash-report-info-v1 0.1.6+cf39a74318 via fabric
        - fabric-dimensions-v1 2.0.13+cf39a74318 via fabric
        - fabric-entity-events-v1 1.4.1+377137cc18 via fabric
        - fabric-events-interaction-v0 0.4.12+e99fbe1218 via fabric
        - fabric-events-lifecycle-v0 0.2.4+cf39a74318 via fabric
        - fabric-game-rule-api-v1 1.0.8+cf39a74318 via fabric
        - fabric-item-api-v1 1.3.0+6617390918 via fabric
        - fabric-item-groups-v0 0.3.2+cf39a74318 via fabric
        - fabric-lifecycle-events-v1 1.4.6+0392f3a618 via fabric
        - fabric-loot-tables-v1 1.0.5+cf39a74318 via fabric
        - fabric-mining-level-api-v1 1.0.3+cf39a74318 via fabric
        - fabric-mining-levels-v0 0.1.6+cf39a74318 via fabric
        - fabric-networking-api-v1 1.0.14+cf39a74318 via fabric
        - fabric-networking-blockentity-v0 0.2.12+cf39a74318 via fabric
        - fabric-networking-v0 0.3.3+cf39a74318 via fabric
        - fabric-object-builder-api-v1 1.11.0+f907116918 via fabric
        - fabric-object-builders-v0 0.7.7+cf39a74318 via fabric
        - fabric-particles-v1 0.2.5+cf39a74318 via fabric
        - fabric-registry-sync-v0 0.7.13+cf39a74318 via fabric
        - fabric-rendering-data-attachment-v1 0.1.6+cf39a74318 via fabric
        - fabric-rendering-fluids-v1 0.2.1+cf39a74318 via fabric
        - fabric-resource-loader-v0 0.4.10+f09604ce18 via fabric
        - fabric-screen-handler-api-v1 1.1.9+cf39a74318 via fabric
        - fabric-structure-api-v1 1.1.15+cf39a74318 via fabric
        - fabric-tag-extensions-v0 1.2.3+cf39a74318 via fabric
        - fabric-tool-attribute-api-v1 1.3.2+cf39a74318 via fabric
        - fabric-transfer-api-v1 1.5.3+cf39a74318 via fabric
        - fabricloader 0.12.8
        - fiber 0.23.0-2 via botania
        - java 16
        - lithium 0.7.5
        - majobroom 1.1
        - minecraft 1.17.1
        - ninjaphenix_container_lib 1.2.5
        - no_null_processors 1.0.0+1.17.1
        - noexpensive 1.17-Fabric-1.2.0
        - omega-config 1.0.8 via repurposed_structures
        - patchouli ${version}
        - phosphor 0.8.0
        - reach-entity-attributes 2.1.1 via botania
        - repurposed_structures 2.5.7+1.17.1
        - step-height-entity-attribute 1.0.0 via botania
        - trinkets 3.0.4
[06:00:09] [main/WARN]: Mod `patchouli` (${version}) does not respect SemVer - comparison support is limited.
[06:00:10] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/root/fabric/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=SERVER
[06:00:10] [main/INFO]: Compatibility level set to JAVA_16
[06:00:10] [main/INFO]: Loaded configuration file for Lithium: 87 options available, 0 override(s) found
[06:00:11] [main/WARN]: Error loading class: net/minecraft/class_471 (java.lang.ClassNotFoundException: net/minecraft/class_471)
[06:00:11] [main/WARN]: @Mixin target net.minecraft.class_471 was not found noexpensive.mixins.json:AnvilScreenMixin
[06:00:11] [main/WARN]: Error loading class: net/minecraft/world/item/crafting/UpgradeRecipe (java.lang.ClassNotFoundException: net/minecraft/world/item/crafting/UpgradeRecipe)
[06:00:11] [main/WARN]: @Mixin target net.minecraft.world.item.crafting.UpgradeRecipe was not found patchouli.mixins.json:AccessorSmithingRecipe
[06:00:12] [main/WARN]: Error loading class: net/minecraft/class_481 (java.lang.ClassNotFoundException: net/minecraft/class_481)
[06:00:12] [main/WARN]: @Mixin target net.minecraft.class_481 was not found trinkets.mixins.json:CreativeInventoryScreenMixin
exit
[06:00:30] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zfb000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[06:00:31] [main/INFO]: [STDOUT]: Loading: maxMoveSpeed
[06:00:31] [main/INFO]: [STDOUT]: double
[06:00:31] [main/INFO]: [STDOUT]: Loading: requireXpLevel
[06:00:31] [main/INFO]: [STDOUT]: boolean
[06:00:31] [main/INFO]: [STDOUT]: Loading: autoThirdPersonView
[06:00:31] [main/INFO]: [STDOUT]: boolean
[06:00:31] [main/INFO]: [STDOUT]: Hello NoExpensive world!
[06:00:33] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'botania'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.8.jar:?]
        at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.8.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.8.jar:?]
        Suppressed: java.lang.NoClassDefFoundError: net/minecraftforge/fml/loading/FMLEnvironment
                at vazkii.patchouli.common.base.Patchouli.<clinit>(Patchouli.java:32) ~[Patchouli-1.17.1-57.jar:?]
                at java.lang.Class.forName0(Native Method) ~[?:?]
                at java.lang.Class.forName(Class.java:466) ~[?:?]
                at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.12.8.jar:?]
                at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.12.8.jar:?]
                at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.12.8.jar:?]
                at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.8.jar:?]
                at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.8.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.8.jar:?]
                at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
                at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.8.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.8.jar:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
                at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.8.jar:?]
        Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.loading.FMLEnvironment
                at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
                at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.8.jar:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
                ... 22 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/network/chat/Component
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at vazkii.patchouli.api.PatchouliAPI.lambda$static$0(PatchouliAPI.java:33) ~[Patchouli-1.17.1-57.jar:?]
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:160) ~[intermediary-server.jar:?]
        at vazkii.patchouli.api.PatchouliAPI.get(PatchouliAPI.java:47) ~[Patchouli-1.17.1-57.jar:?]
        at vazkii.botania.common.core.handler.ConfigHandler.onConfigLoad(ConfigHandler.java:282) ~[Botania-1.17.1-421-FABRIC.jar:?]
        at vazkii.botania.common.core.handler.ConfigHandler.setupConfig(ConfigHandler.java:51) ~[Botania-1.17.1-421-FABRIC.jar:?]
        at vazkii.botania.common.core.handler.ConfigHandler.setup(ConfigHandler.java:66) ~[Botania-1.17.1-421-FABRIC.jar:?]
        at vazkii.botania.common.Botania.onInitialize(Botania.java:108) ~[Botania-1.17.1-421-FABRIC.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.8.jar:?]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.network.chat.Component
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.8.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at vazkii.patchouli.api.PatchouliAPI.lambda$static$0(PatchouliAPI.java:33) ~[Patchouli-1.17.1-57.jar:?]
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:160) ~[intermediary-server.jar:?]
        at vazkii.patchouli.api.PatchouliAPI.get(PatchouliAPI.java:47) ~[Patchouli-1.17.1-57.jar:?]
        at vazkii.botania.common.core.handler.ConfigHandler.onConfigLoad(ConfigHandler.java:282) ~[Botania-1.17.1-421-FABRIC.jar:?]
        at vazkii.botania.common.core.handler.ConfigHandler.setupConfig(ConfigHandler.java:51) ~[Botania-1.17.1-421-FABRIC.jar:?]
        at vazkii.botania.common.core.handler.ConfigHandler.setup(ConfigHandler.java:66) ~[Botania-1.17.1-421-FABRIC.jar:?]
        at vazkii.botania.common.Botania.onInitialize(Botania.java:108) ~[Botania-1.17.1-421-FABRIC.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.8.jar:?]
        ... 15 more

**Comment by SherkeyXD** [comment]
By the way, what is "fabric-textures-v0" ? I can't find it on curseforge.

**Comment by warjort** [comment]
Looks like there is something wrong with your patchouli jar.

It is trying to reference a deobfuscated minecraft name
````
Caused by: java.lang.NoClassDefFoundError: net/minecraft/network/chat/Component
at java.lang.Class.forName0(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:375) ~[?:?]
at vazkii.patchouli.api.PatchouliAPI.lambda$static$0(PatchouliAPI.java:33) ~[Patchouli-1.17.1-57.jar:?]
````

It also doesn't have a proper version number in its fabric.mod.json
````[06:00:09] [main/WARN]: Mod patchouli (${version}) does not respect SemVer - comparison support is limited.````

**Comment by warjort** [comment]
> By the way, what is "fabric-textures-v0" ? I can't find it on curseforge.

The fabric api mod is really many smaller mods bundled together.
https://github.com/FabricMC/fabric/blob/1.17/settings.gradle

You should already have it if you are using ````fabric 0.44.0+1.17````
Very strange.

**Comment by warjort** [comment]
The textures mod is in fabric api jar downloaded from curseforge:
````
$ jar -tf fabric-api-0.44.0+1.17.jar | grep textures
META-INF/jars/fabric-textures-v0-1.0.7+cf39a74318.jar
````

**Comment by warjort** [comment]
````[Patchouli-1.17.1-57.jar:?]````

If you look at fabric patchouli on curseforge there is no 57 build - I guess it was removed because it was broken?
https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric/files

**Comment by warjort** [comment]
I should read what the message actually says instead of just the part you quoted. :-)
````
Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.2.1+cf39a74318 recommends any version of fabric-textures-v0, 
which is disabled for this environment (client/server only)!
- You should install any version of fabric-textures-v0 for the optimal experience.
````

You are running a server, so it won't load the textures mod. It is client only.

````
at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
````
