### ISSUE TITLE
1.18 Modded Minecraft Crash Report

### ISSUE THREAD

**Issue by warypumpkin** [FabricMC/fabric#1888]
Hello! I am new to modding. 

The mods I'm trying to use are Fabric, Optifabric, Optifine, Xaero's Minimap, and Xaero's Worldmap, all of which I have downloaded the newest versions compatible with 1.18. I get this same crash report when trying to open single-player worlds, multiplayer worlds, and Minecraft realms.

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 12/5/21, 5:00 PM
Description: Unexpected error

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_6850 failed
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136)
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
at net.minecraft.class_761.method_3269(class_761.java:3415)
at net.minecraft.class_761.method_22710(class_761.java:1721)
at net.minecraft.class_757.method_3188(class_757.java:1531)
at net.minecraft.class_757.method_3192(class_757.java:1155)
at net.minecraft.class_310.method_1523(class_310.java:1117)
at net.minecraft.class_310.method_1514(class_310.java:733)
at net.minecraft.client.main.Main.main(Main.java:236)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229)
... 17 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-rendering-data-attachment-v1.mixins.json:client.MixinChunkRendererRegionBuilder] from phase [DEFAULT] in config [fabric-rendering-data-attachment-v1.mixins.json] from mod [fabric-rendering-data-attachment-v1] FAILED during APPLY
at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
... 20 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on fabric-rendering-data-attachment-v1.mixins.json:client.MixinChunkRendererRegionBuilder->@Inject::create(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;IIII[[Lnet/minecraft/class_6850$class_6851;)V from mod fabric-rendering-data-attachment-v1! Expected (Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;IIII[[Lnet/minecraft/class_6850$class_6851;)V [INJECT Applicator Phase -> fabric-rendering-data-attachment-v1.mixins.json:client.MixinChunkRendererRegionBuilder -> Apply Injections -> -> Inject -> fabric-rendering-data-attachment-v1.mixins.json:client.MixinChunkRendererRegionBuilder->@Inject::create(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;IIII[[Lnet/minecraft/class_6850$class_6851;)V from mod fabric-rendering-data-attachment-v1]
at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:565)
at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:495)
at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1374)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Render thread
Stacktrace:
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136)
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
at net.minecraft.class_761.method_3269(class_761.java:3415)
at net.minecraft.class_761.method_22710(class_761.java:1721)
at net.minecraft.class_757.method_3188(class_757.java:1531)

-- Affected level --
Details:
All players: 1 total; [class_746['wary_pumpkin'/181, l='ClientLevel', x=3.50, y=77.00, z=9.50]]
Chunk stats: 2209, 529
Level dimension: minecraft:overworld
Level spawn location: World: (0,77,0), Section: (at 0,13,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Level time: 9 game time, 9 day time
Server brand: fabric
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.class_638.method_8538(class_638.java:517)
at net.minecraft.class_310.method_1587(class_310.java:2402)
at net.minecraft.class_310.method_1514(class_310.java:757)
at net.minecraft.client.main.Main.main(Main.java:236)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
Reload number: 1
Reload reason: initial
Finished: Yes
Packs: Default, Fabric Mods

-- System Details --
Details:
Minecraft Version: 1.18
Minecraft Version ID: 1.18
Operating System: Windows 10 (amd64) version 10.0
Java Version: 17.0.1, Microsoft
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
Memory: 901413888 bytes (859 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
CPUs: 12
Processor Vendor: AuthenticAMD
Processor Name: AMD Ryzen 5 3600 6-Core Processor
Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
Microarchitecture: Zen 2
Frequency (GHz): 3.60
Number of physical packages: 1
Number of physical CPUs: 6
Number of logical CPUs: 12
Graphics card #0 name: AMD Radeon RX 5600 XT
Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
Graphics card #0 VRAM (MB): 4095.00
Graphics card #0 deviceId: 0x731f
Graphics card #0 versionInfo: DriverVersion=30.0.13033.1000
Memory slot #0 capacity (MB): 8192.00
Memory slot #0 clockSpeed (GHz): 3.20
Memory slot #0 type: DDR4
Memory slot #1 capacity (MB): 8192.00
Memory slot #1 clockSpeed (GHz): 3.20
Memory slot #1 type: DDR4
Virtual memory max (MB): 21685.67
Virtual memory used (MB): 18770.68
Swap memory total (MB): 5376.00
Swap memory used (MB): 65.34
JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
Fabric Mods:
fabric: Fabric API 0.44.0+1.18
fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
fabricloader: Fabric Loader 0.12.8
java: OpenJDK 64-Bit Server VM 17
minecraft: Minecraft 1.18
mm: Manningham Mills 2.3
optifabric: OptiFabric 1.12.7
xaerominimap: Xaero's Minimap 21.22.3
xaeroworldmap: Xaero's World Map 1.18.6
Launched Version: fabric-loader-0.12.8-1.18
Backend library: LWJGL version 3.2.2 build 10
Backend API: AMD Radeon RX 5600 XT GL version 3.2.14761 Core Profile Forward-Compatible Context 21.11.1 30.0.13033.1000, ATI Technologies Inc.
Window size: 854x480
GL Caps: Using framebuffer using OpenGL 3.2
GL debug messages:
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
Type: Integrated Server (map_client.txt)
Graphics mode: fancy
Resource Packs: vanilla
Current Language: English (US)
CPU: 12x AMD Ryzen 5 3600 6-Core Processor
Server Running: true
Player Count: 1 / 8; [class_3222['wary_pumpkin'/181, l='ServerLevel[New World]', x=3.50, y=77.00, z=9.50]]
Data Packs: vanilla, Fabric Mods
OptiFine Version: OptiFine_1.18_HD_U_H3_pre8
OptiFine Build: 20211205-181141
Render Distance Chunks: 20
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: BSL_v8.1.01.zip
OpenGlVersion: 3.2.14761 Core Profile Forward-Compatible Context 21.11.1 30.0.13033.1000
OpenGlRenderer: AMD Radeon RX 5600 XT
OpenGlVendor: ATI Technologies Inc.
CpuCount: 12

-- OptiFabric --
Details:
OptiFine jar designed for: 1.18
OptiFine jar version: OptiFine_1.18_HD_U_H3_pre8
OptiFine jar status: Valid OptiFine installer
OptiFine remapped jar: C:/Users/Paris/AppData/Roaming/.minecraft/.optifine/OptiFine_1.18_HD_U_H3_pre8/Optifine-mapped.jar
OptiFabric error: <None>

**Comment by JosephYapYEEEEEEEEEEEEEEEEEEEEEEEEEEEET** [comment]
try uninstall optifine and optifabric, and install sodium and iris

**Comment by warjort** [comment]
According to these, optifabric hasn't been updated to work with optifine pre8

https://github.com/Chocohead/OptiFabric/issues/492
https://github.com/Chocohead/OptiFabric/issues/491

You should report optifine issues on that project.

**Comment by warypumpkin** [comment]
> 

Switching from Optifine pre8 to Optifine pre7 ended up working, thank you so much!
