### ISSUE TITLE
`Uncaught exception in thread "main"` when trying to start 1.18.1 server; Fabric ver. 0.12.12-1

### ISSUE THREAD

**Issue by ghotiPhoti** [FabricMC/fabric#1929]
This error message appears when I try to run the auto-generated script in the server folder

`[20:32:36] [ERROR] [FabricLoader/]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:68)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)
Caused by: java.lang.RuntimeException: Error invoking MC server bundler: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.processBundlerJar(MinecraftGameProvider.java:321)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:206)
        at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:172)
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:125)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
        ... 5 more
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider$1.loadClass(MinecraftGameProvider.java:277)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.processBundlerJar(MinecraftGameProvider.java:297)
        ... 10 more`

This line in particular caught my eye and I think it has something to do with me using a newer version but i have no clue if I can even roll back to a newer Java version.

`Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

**Comment by deirn** [comment]
Minecraft 1.18 needs Java 17 to run. You used Java 8, so it won't work.

**Comment by ghotiPhoti** [comment]
yep, installing it fixed the issues, thank you!
