### ISSUE TITLE
Failed to launch Minecraft 1.18.1 Server

### ISSUE THREAD

**Issue by Peter-JY** [FabricMC/fabric#1971]
I don't know how the question is, but cmd gave me these:

> Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:340)
        at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:282)
        at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:321)
        at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:234)
        at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:762)
        at java.base/java.util.jar.JarFile.ensureInitialization(JarFile.java:1033)
        at java.base/java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:72)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:883)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:848)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:780)
        at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:675)

I deleted the `FABRIC1.SF` and `FABRIC1.RSA` in `fabric-server-launch.jar\META-INF`, then it can run properly for a while.
And it shows this to me:
> Unpacking 1.18.1/server-1.18.1.jar (versions:1.18.1) to versions\1.18.1\server-1.18.1.jar
Unpacking com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar (libraries:com.github.oshi:oshi-core:5.8.2) to libraries\com\github\oshi\oshi-core\5.8.2\oshi-core-5.8.2.jar
Unpacking com/google/code/gson/gson/2.8.8/gson-2.8.8.jar (libraries:com.google.code.gson:gson:2.8.8) to libraries\com\google\code\gson\gson\2.8.8\gson-2.8.8.jar
Unpacking com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar (libraries:com.google.guava:failureaccess:1.0.1) to libraries\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar
Unpacking com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar (libraries:com.google.guava:guava:31.0.1-jre) to libraries\com\google\guava\guava\31.0.1-jre\guava-31.0.1-jre.jar
Unpacking com/mojang/authlib/3.2.38/authlib-3.2.38.jar (libraries:com.mojang:authlib:3.2.38) to libraries\com\mojang\authlib\3.2.38\authlib-3.2.38.jar
Unpacking com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar (libraries:com.mojang:brigadier:1.0.18) to libraries\com\mojang\brigadier\1.0.18\brigadier-1.0.18.jar
Unpacking com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar (libraries:com.mojang:datafixerupper:4.0.26) to libraries\com\mojang\datafixerupper\4.0.26\datafixerupper-4.0.26.jar
Unpacking com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar (libraries:com.mojang:javabridge:1.2.24) to libraries\com\mojang\javabridge\1.2.24\javabridge-1.2.24.jar
Unpacking commons-io/commons-io/2.11.0/commons-io-2.11.0.jar (libraries:commons-io:commons-io:2.11.0) to libraries\commons-io\commons-io\2.11.0\commons-io-2.11.0.jar
Unpacking io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar (libraries:io.netty:netty-all:4.1.68.Final) to libraries\io\netty\netty-all\4.1.68.Final\netty-all-4.1.68.Final.jar
Unpacking it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar (libraries:it.unimi.dsi:fastutil:8.5.6) to libraries\it\unimi\dsi\fastutil\8.5.6\fastutil-8.5.6.jar
Unpacking net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar (libraries:net.java.dev.jna:jna:5.9.0) to libraries\net\java\dev\jna\jna\5.9.0\jna-5.9.0.jar
Unpacking net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar (libraries:net.java.dev.jna:jna-platform:5.9.0) to libraries\net\java\dev\jna\jna-platform\5.9.0\jna-platform-5.9.0.jar
Unpacking net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar (libraries:net.sf.jopt-simple:jopt-simple:5.0.4) to libraries\net\sf\jopt-simple\jopt-simple\5.0.4\jopt-simple-5.0.4.jar
Unpacking org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar (libraries:org.apache.commons:commons-lang3:3.12.0) to libraries\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar
Unpacking org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar (libraries:org.apache.logging.log4j:log4j-api:2.14.1) to libraries\org\apache\logging\log4j\log4j-api\2.14.1\log4j-api-2.14.1.jar
Unpacking org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar (libraries:org.apache.logging.log4j:log4j-core:2.14.1) to libraries\org\apache\logging\log4j\log4j-core\2.14.1\log4j-core-2.14.1.jar
Unpacking org/apache/logging/log4j/log4j-slf4j18-impl/2.14.1/log4j-slf4j18-impl-2.14.1.jar (libraries:org.apache.logging.log4j:log4j-slf4j18-impl:2.14.1) to libraries\org\apache\logging\log4j\log4j-slf4j18-impl\2.14.1\log4j-slf4j18-impl-2.14.1.jar
Unpacking org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar (libraries:org.slf4j:slf4j-api:1.8.0-beta4) to libraries\org\slf4j\slf4j-api\1.8.0-beta4\slf4j-api-1.8.0-beta4.jar
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[16:00:54] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[16:00:55] [INFO] [FabricLoader/GameRemap]: Fabric is preparing JARs on first launch, this may take a few seconds...
[16:01:01] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[16:01:01] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[16:01:01] [main/INFO]: Loading 3 mods:
        - fabricloader 0.12.12
        - java 17
        - minecraft 1.18.1
[16:01:01] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/D:/000/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[16:01:12] [main/ERROR]: Failed to load properties from file: server.properties
[16:01:12] [main/WARN]: Failed to load eula.txt
[16:01:12] [main/INFO]: You need to agree to the EULA in order to run the server. Go to eula.txt for more info.

I changed Eula.txt, and it can work properly.

Tips: I run the server in the dictionary `D:\000`

**Comment by warjort** [comment]
The eula.txt part is normal for minecraft servers.

The first error about the signature says the jar file has been modified in someway from the version built by fabric.
Make sure you use the version provided by fabric.
Using modified versions from somewhere else could for example mean you are using something infected with a virus.

**Comment by Peter-JY** [comment]
I used `fabric-installer-0.6.1.45.exe` to install that server. And it has that issue.

**Comment by Peter-JY** [comment]
That installer was download at ‏‎16:50:53 in ‎2021‎-11-26, according to Windows's `explore.exe`.

**Comment by Technici4n** [comment]
Does this happen if you download the latest installer version again and try again?

**Comment by Peter-JY** [comment]
No. The latest installer can download the proper Fabric (without `FABRIC1.SF` and `FABRIC1.RSA`)
Thank you very much.
: )
