### ISSUE TITLE
A mod crash on startup

### ISSUE THREAD

**Issue by Nightmare1938** [FabricMC/fabric#2105]
Hello I am having a problem and I don't know how to fix it, please help:

[15:14:21] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kambrik'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:159) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kambrik'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:157) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: java.lang.ExceptionInInitializerError
	at io.ejekta.kambrik.internal.KambrikMod.idOf(KambrikMod.kt:30) ~[Kambrik-3.1.0-1.18.jar:?]
	at io.ejekta.kambrik.logging.KambrikMarkers.createIdMarker(KambrikMarkers.kt:16) ~[Kambrik-3.1.0-1.18.jar:?]
	at io.ejekta.kambrik.logging.KambrikMarkers.<clinit>(KambrikMarkers.kt:12) ~[Kambrik-3.1.0-1.18.jar:?]
	at io.ejekta.kambrik.internal.KambrikPrelaunch.handleCustomEntryData(KambrikPrelaunch.kt:31) ~[Kambrik-3.1.0-1.18.jar:?]
	at io.ejekta.kambrik.internal.KambrikPrelaunch.onPreLaunch(KambrikPrelaunch.kt:18) ~[Kambrik-3.1.0-1.18.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:157) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2588 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2960.<clinit>(class_2960.java:25) ~[client-intermediary.jar:?]
	at io.ejekta.kambrik.internal.KambrikMod.idOf(KambrikMod.kt:30) ~[Kambrik-3.1.0-1.18.jar:?]
	at io.ejekta.kambrik.logging.KambrikMarkers.createIdMarker(KambrikMarkers.kt:16) ~[Kambrik-3.1.0-1.18.jar:?]
	at io.ejekta.kambrik.logging.KambrikMarkers.<clinit>(KambrikMarkers.kt:12) ~[Kambrik-3.1.0-1.18.jar:?]
	at io.ejekta.kambrik.internal.KambrikPrelaunch.handleCustomEntryData(KambrikPrelaunch.kt:31) ~[Kambrik-3.1.0-1.18.jar:?]
	at io.ejekta.kambrik.internal.KambrikPrelaunch.onPreLaunch(KambrikPrelaunch.kt:18) ~[Kambrik-3.1.0-1.18.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:157) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2960.<clinit>(class_2960.java:25) ~[client-intermediary.jar:?]
	at io.ejekta.kambrik.internal.KambrikMod.idOf(KambrikMod.kt:30) ~[Kambrik-3.1.0-1.18.jar:?]
	at io.ejekta.kambrik.logging.KambrikMarkers.createIdMarker(KambrikMarkers.kt:16) ~[Kambrik-3.1.0-1.18.jar:?]
	at io.ejekta.kambrik.logging.KambrikMarkers.<clinit>(KambrikMarkers.kt:12) ~[Kambrik-3.1.0-1.18.jar:?]
	at io.ejekta.kambrik.internal.KambrikPrelaunch.handleCustomEntryData(KambrikPrelaunch.kt:31) ~[Kambrik-3.1.0-1.18.jar:?]
	at io.ejekta.kambrik.internal.KambrikPrelaunch.onPreLaunch(KambrikPrelaunch.kt:18) ~[Kambrik-3.1.0-1.18.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:157) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method owo(Ljava/lang/String;)Ljava/lang/String; in indrev.mixins.json:aprilfools.MixinTranslatableText from mod indrev failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap indrev-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2960.<clinit>(class_2960.java:25) ~[client-intermediary.jar:?]
	at io.ejekta.kambrik.internal.KambrikMod.idOf(KambrikMod.kt:30) ~[Kambrik-3.1.0-1.18.jar:?]
	at io.ejekta.kambrik.logging.KambrikMarkers.createIdMarker(KambrikMarkers.kt:16) ~[Kambrik-3.1.0-1.18.jar:?]
	at io.ejekta.kambrik.logging.KambrikMarkers.<clinit>(KambrikMarkers.kt:12) ~[Kambrik-3.1.0-1.18.jar:?]
	at io.ejekta.kambrik.internal.KambrikPrelaunch.handleCustomEntryData(KambrikPrelaunch.kt:31) ~[Kambrik-3.1.0-1.18.jar:?]
	at io.ejekta.kambrik.internal.KambrikPrelaunch.onPreLaunch(KambrikPrelaunch.kt:18) ~[Kambrik-3.1.0-1.18.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:157) ~[fabric-loader-0.13.3.jar:?]
	... 2 more

**Comment by warjort** [comment]
````
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method owo(Ljava/lang/String;)Ljava/lang/String; 
in indrev.mixins.json:aprilfools.MixinTranslatableText from mod indrev failed injection
````
Not a fabric api issue:
https://github.com/GabrielOlvH/Industrial-Revolution/issues/434
