### ISSUE TITLE
Cannot run optifine and optifabric without getting a crash(1.18.2)

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#2114]
The crash: https://imgur.com/a/kHtvaqR

**Comment by AlphaMode** [comment]
How is this even related to fabric api?
Also please send the full log not a image

**Comment by ghost** [comment]
Well I'm not really sure what the exact source of the problem may be but I switched recently from forge api to fabric.

The log:


21:08:44.733
launcher
main
Preparing to launch minecraft client for fabric-loader-0.13.3-1.18.2
21:08:44.734
launcher
main
Prepared asset index
21:08:45.635
launcher
main
Have 3105 total files to check or download
21:08:49.308
launcher
main
Minecraft client fabric-loader-0.13.3-1.18.2 is ready to start.
21:08:49.308
launcher
main
Starting!
21:08:49.308
launcher
main
Nothing to download!
21:08:49.308
launcher
main
Downloading Java Runtime java-runtime-beta:17.0.1.12.1
21:08:49.592
launcher
main
Extracting 8 files!
21:08:51.488
launcher
main
Using default game log configuration client-1.12.xml (outputs XML)
21:08:52.770
FabricLoader/GameProvider
main
Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
21:08:53.240
FabricLoader
main
Loading 57 mods:
	- architectury 4.1.39
	- betterthirdperson 1.7.2
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57 via morevillagers-fabric
	- fabric 0.48.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.5.7+d7c144a860 via fabric
	- fabric-biome-api-v1 8.0.3+801ec85b60 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.2+d82b939260 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.13+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.3.3+691a79b560 via fabric
	- fabric-item-groups-v0 0.3.10+3ac43d9560 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-lifecycle-events-v1 2.0.2+2540745460 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.0.4+d1027f7d60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.0.3+40c91ec860 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.4.17+d8c7b9ae60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.2+d1027f7d60 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.1.14+40c91ec860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.5.14+cca23f9360 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+40c91ec860 via fabric
	- fabricloader 0.13.3
	- java 17
	- journeymap-fabric 5.8.1beta3
	- litematica 0.11.1
	- malilib 0.12.1
	- minecraft 1.18.2
	- mm 2.3 via optifabric
	- morevillagers-fabric 3.2.0-SNAPSHOT
	- optifabric 1.13.0
	- roughlyenoughitems 8.0.442
	- wildfire_gender 2.9
21:08:53.278
FabricLoader/Metadata
main
Mod `journeymap-fabric` (5.8.1beta3) does not respect SemVer - comparison support is limited.
21:08:53.416
FabricLoader/Mixin
main
SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/antre/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
21:08:53.560
FabricLoader/Mixin
main
Compatibility level set to JAVA_16
21:08:53.711
FabricLoader/Mixin
main
Compatibility level set to JAVA_17
21:08:53.278
FabricLoader/Metadata
main
Mod `journeymap-fabric` (5.8.1beta3) does not respect SemVer - comparison support is limited.
21:08:57.370
FabricLoader/Mixin
main
Injection warning: LVT in net/minecraft/class_757::method_3192(FJZ)V has incompatible changes at opcode 606 in callback journeymap.mixins.json:client.GameRendererMixin->@Inject::renderDrawScreenPre(FJZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IILnet/minecraft/class_4587;)V from mod journeymap-fabric.
 Expected: [I, I, Lnet/minecraft/class_4587;]
    Found: [I, I, Lnet/minecraft/class_1041;]
Available: [I, I, Lnet/minecraft/class_1041;, F, Lnet/minecraft/class_1159;, Lnet/minecraft/class_4587;, Lnet/minecraft/class_4587;, Ljava/lang/Throwable;, Lnet/minecraft/class_128;, Lnet/minecraft/class_129;]

21:08:57.371
FabricLoader/Mixin
main
Injection warning: LVT in net/minecraft/class_757::method_3192(FJZ)V has incompatible changes at opcode 626 in callback journeymap.mixins.json:client.GameRendererMixin->@Inject::renderDrawScreenPost(FJZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IILnet/minecraft/class_4587;)V from mod journeymap-fabric.
 Expected: [I, I, Lnet/minecraft/class_4587;]
    Found: [I, I, Lnet/minecraft/class_1041;]
Available: [I, I, Lnet/minecraft/class_1041;, F, Lnet/minecraft/class_1159;, Lnet/minecraft/class_4587;, Lnet/minecraft/class_4587;, Ljava/lang/Throwable;, Lnet/minecraft/class_128;, Lnet/minecraft/class_129;]
21:08:57.372
FabricLoader
main
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.method_568(class_128.java:173)
	at net.minecraft.class_128.method_24305(class_128.java:343)
	at net.minecraft.client.main.Main.main(Main.java:151)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:292)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method renderDrawScreenPre(FJZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IILnet/minecraft/class_4587;)V in journeymap.mixins.json:client.GameRendererMixin from mod journeymap-fabric failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap journeymap-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more
21:08:57.807
monitor
Process Monitor
Process crashed with exit code 1
