### ISSUE TITLE
[22w14a, FAPI 0.49.6+1.19] ExceptionInInitializerError "Not bootstrapped" 

### ISSUE THREAD

**Issue by quiqueck** [FabricMC/fabric#2115]
I am trying to build my Mod against the latest snapshot and do get this exception on startup:

``` 
[14:24:02] [main/ERROR] (FabricLoader) Minecraft has crashed!
 net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.network.syncher.EntityDataSerializers.<clinit>(EntityDataSerializers.java:173) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.world.entity.Entity.<clinit>(Entity.java:217) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:136) ~[minecraft-project-@-merged-named.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 3 more
Caused by: java.lang.IllegalArgumentException: Not bootstrapped (called from registry ResourceKey[minecraft:root / minecraft:root])
	at net.minecraft.server.Bootstrap.createBootstrapException(Bootstrap.java:119) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.Bootstrap.checkBootstrapCalled(Bootstrap.java:112) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.core.Registry.<init>(Registry.java:381) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.core.WritableRegistry.<init>(WritableRegistry.java:10) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.core.MappedRegistry.<init>(MappedRegistry.java:63) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:137) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.syncher.EntityDataSerializers.<clinit>(EntityDataSerializers.java:173) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.world.entity.Entity.<clinit>(Entity.java:217) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:136) ~[minecraft-project-@-merged-named.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 3 more
```

The exception occurs before my `onInitialize`-Method get's called. Do you maybe have any Idea what I might be doing wrong?

**Comment by modmuss50** [comment]
This is a vanilla bug that I havent had a chance to report yet. Its caused by running the game in offline mode. Addding a uuid run arg will fix it.

`--uuid=123`

**Comment by quiqueck** [comment]
Thanks for the quick reply :)
