### ISSUE TITLE
loader constraint violation: when resolving field "BUILT_IN_EXCEPTIONS" CRASH

### ISSUE THREAD

**Issue by itsMarkiS** [FabricMC/fabric#2118]
The game keeps crashing and doesnt even starts..... how can i fix it? tried removig a lot of mods but nothing happened

Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.LinkageError: loader constraint violation: when resolving field "BUILT_IN_EXCEPTIONS" of type com.mojang.brigadier.exceptions.BuiltInExceptionProvider, the class loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @66565121 of the current class, net.minecraft.class_155, and the class loader 'app' for the field's defining class, com.mojang.brigadier.exceptions.CommandSyntaxException, have different Class objects for type com.mojang.brigadier.exceptions.BuiltInExceptionProvider (net.minecraft.class_155 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @66565121, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @39fcbef6; com.mojang.brigadier.exceptions.CommandSyntaxException is in unnamed module of loader 'app')
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.LinkageError: loader constraint violation: when resolving field "BUILT_IN_EXCEPTIONS" of type com.mojang.brigadier.exceptions.BuiltInExceptionProvider, the class loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @66565121 of the current class, net.minecraft.class_155, and the class loader 'app' for the field's defining class, com.mojang.brigadier.exceptions.CommandSyntaxException, have different Class objects for type com.mojang.brigadier.exceptions.BuiltInExceptionProvider (net.minecraft.class_155 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @66565121, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @39fcbef6; com.mojang.brigadier.exceptions.CommandSyntaxException is in unnamed module of loader 'app')
	at net.minecraft.class_155.<clinit>(class_155.java:214)
	at net.minecraft.class_3797.<init>(class_3797.java:38)
	at net.minecraft.class_3797.<clinit>(class_3797.java:21)
	at fudge.notenoughcrashes.fabric.StacktraceDeobfuscator.<clinit>(StacktraceDeobfuscator.java:29)
	at net.minecraft.client.main.Main.handler$bjd000$asSoonAsPossible(Main.java:517)
	at net.minecraft.client.main.Main.main(Main.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	... 2 more

**Comment by warjort** [comment]
Post your logs/latest.log

I don't believe your shown error is the real error.
````
Caused by: java.lang.LinkageError: loader constraint violation: when resolving field "BUILT_IN_EXCEPTIONS" of type com.mojang.brigadier.exceptions.BuiltInExceptionProvider, the class loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @66565121 of the current class, net.minecraft.class_155, 
and the class loader 'app' for the field's defining class, com.mojang.brigadier.exceptions.CommandSyntaxException, have different Class objects for type com.mojang.brigadier.exceptions.BuiltInExceptionProvider (net.minecraft.class_155 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @66565121, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @39fcbef6; com.mojang.brigadier.exceptions.CommandSyntaxException is in unnamed module of loader 'app')
at net.minecraft.class_155.(class_155.java:214)
at net.minecraft.class_3797.(class_3797.java:38)
at net.minecraft.class_3797.(class_3797.java:21)
at fudge.notenoughcrashes.fabric.StacktraceDeobfuscator.(StacktraceDeobfuscator.java:29)
at net.minecraft.client.main.Main.handler$bjd000$asSoonAsPossible(Main.java:517)
at net.minecraft.client.main.Main.main(Main.java)
````
This appears to be not enough crashes trying to get the Minecraft version and running into some conflict in the classloading (same class loaded from 2 different classloaders).
Try removing that mod to see if it gives a more informative error.
