### ISSUE TITLE
java.lang.NumberFormatException: empty String

### ISSUE THREAD

**Issue by lazytspo** [FabricMC/fabric#2126]
Dear creators of fabric. i have a problem that refuses Minecraft to launch when fabric loader is installed.

Minecraft Version: 1.18.2
Fabric Loader Version: 0.13.3-1.18.2
"latest.log" File: https://pastebin.com/BJXCVhKq

**Comment by warjort** [comment]
This is not a fabric issue.

The full error message is:
````
[14:38:48] [Render thread/WARN]: Invalid floating point value for option textBackgroundOpacity = 
java.lang.NumberFormatException: empty String
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
	at net.minecraft.class_315$2.method_33678(class_315.java:429) [client-intermediary.jar:?]
````
Which means your options.txt in your minecraft folder is corrupted. 
But this is just a warning, it should not stop the game loading.

You can try renaming your options.txt to options.save (or whatever) and minecraft will recreate it with default values.

**Comment by lazytspo** [comment]
oh!

**Comment by apple502j** [comment]
See also https://bugs.mojang.com/browse/MC-149050
