### ISSUE TITLE
Minecraft Crashing while loading (The game crashed whilst initializing game Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_4184 failed Exit Code: -1)

### ISSUE THREAD

**Issue by chillytwastaken** [FabricMC/fabric#2136]
Using Fabric 1.14.4, latest version (0.13.3).
Mods: Fabric API, Pehkui, Immersive Portals.

I suspect that this is probably Pehkui, but might be IP aswell.

**Comment by chillytwastaken** [comment]
Full crash report: ---- Minecraft Crash Report ----
// My bad.

Time: 4/15/22 9:02 PM
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_4184 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_757.<init>(class_757.java:176)
	at net.minecraft.class_310.method_1503(class_310.java:563)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 14 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [pehkui.mixins.json:client.CameraMixin] from phase [DEFAULT] in config [pehkui.mixins.json] from mod [pehkui] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 17 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("CONSTANT") on net/minecraft/class_4184::clipToSpaceModifyOffset with priority 1000 cannot inject into net/minecraft/class_4184::method_19318(D)D merged by com.qouteall.immersive_portals.mixin_client.MixinCamera with priority 1000 [PREINJECT Applicator Phase -> pehkui.mixins.json:client.CameraMixin -> Prepare Injections ->  -> constant$zmd000$clipToSpaceModifyOffset(F)F -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_757.<init>(class_757.java:176)
	at net.minecraft.class_310.method_1503(class_310.java:563)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1050010536 bytes (1001 MB) / 1912602624 bytes (1824 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.28.5+1.14
		fabric-api-base: Fabric API Base 0.1.2+de26dc4942
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.2+4ea4772942
		fabric-command-api-v1: Fabric Command API (v1) 1.0.2+4ea4772942
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+4ea4772942
		fabric-containers-v0: Fabric Containers (v0) 0.1.4+4ea4772942
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+4ea4772942
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+4ea4772942
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.2+4ea4772942
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+4ea4772942
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+4ea4772942
		fabric-item-api-v1: Fabric Item API (v1) 1.1.1+4ea4772942
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+4ea4772942
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+4ea4772942
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+4ea4772942
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+4ea4772942
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.2+4ea4772942
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+4ea4772942
		fabric-models-v0: Fabric Models (v0) 0.1.1+4ea4772942
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+4ea4772942
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.2+4ea4772942
		fabric-networking-v0: Fabric Networking (v0) 0.2.1+4ea4772942
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.0.1+4ea4772942
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.3.1+4ea4772942
		fabric-particles-v1: fabric-particles-v1 0.2.2+4ea4772942
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.4+4ea4772942
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.2+4ea4772942
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.16+4ea4772942
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+4ea4772942
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.4+4ea4772942
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.3+4ea4772942
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.5+4ea4772942
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.4+4ea4772942
		fabric-textures-v0: Fabric Textures (v0) 0.1.5+4ea4772942
		fabricloader: Fabric Loader 0.13.3
		immersive_portals: Immersive Portals 0.30
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kanos_config: Kanos Config 0.2.0+1.14.4-1.19
		minecraft: Minecraft 1.14.4
		pehkui: Pehkui 3.2.2+1.14.4-1.19
	Launched Version: fabric-loader-0.13.3-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: Intel(R) HD Graphics 530 GL version 4.6.0 - Build 26.20.100.8142, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz

**Comment by chillytwastaken** [comment]
> Using Fabric 1.14.4, latest version (0.13.3). Mods: Fabric API, Pehkui, Immersive Portals.
> 
> I suspect that this is probably Pehkui, but might be IP aswell.

I really want to play with Pehkui, assuming that is the problem, so I would appreciate any fixes that don't include deleting Pehkui.

**Comment by Linguardium** [comment]
yes, it is immersive portals and pehkui not being compatible with eachother

**Comment by chillytwastaken** [comment]
> yes, it is immersive portals and pehkui not being compatible with eachother

So I need to get a different version of pehkui?

**Comment by chillytwastaken** [comment]
> yes, it is immersive portals and pehkui not being compatible with eachother

I think I have found a solution, which is just using the Forge version of the mod. Hopefully this will work. I am currently downloading the mods.
