### ISSUE TITLE
Fabric registry sync api breaking

### ISSUE THREAD

**Issue by 2ndDerivative** [FabricMC/fabric#2150]
got this guy upon trying to delete a world from my game. Idk what it means but I am quite sure it's not a mod issue

[23:04:08] [Render thread/ERROR] (FabricLoader/Mixin) Mixin apply for mod fabric-registry-sync-v0 failed fabric-registry-sync-v0.mixins.json:MixinLevelStorageSession from mod fabric-registry-sync-v0 -> net.minecraft.world.level.storage.LevelStorage$Session: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field field_23768 was not located in the target class net.minecraft.world.level.storage.LevelStorage$Session. Using refmap fabric-registry-sync-v0-refmap.json
 org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_23768 was not located in the target class net.minecraft.world.level.storage.LevelStorage$Session. Using refmap fabric-registry-sync-v0-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:399) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:302) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:206) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:144) ~[fabric-loader-0.14.0.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.level.storage.LevelStorage.createSession(LevelStorage.java:318) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.delete(WorldListWidget.java:464) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.method_20170(WorldListWidget.java:450) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.screen.ConfirmScreen.method_37054(ConfirmScreen.java:56) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:40) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget.java:16) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget.java:120) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:27) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:94) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:495) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:94) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Mouse.method_22686(Mouse.java:165) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:103) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Mouse.method_22684(Mouse.java:165) ~[minecraft-project-@-merged-named.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) [lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1153) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:724) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [minecraft-project-@-merged-named.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:75) [fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.0.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]

**Comment by warjort** [comment]
````
[23:04:08] [Render thread/ERROR] (FabricLoader/Mixin) Mixin apply for mod fabric-registry-sync-v0 failed 
fabric-registry-sync-v0.mixins.json:MixinLevelStorageSession from mod fabric-registry-sync-v0 -> net.minecraft.world.level.storage.LevelStorage$Session: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException 
@shadow field field_23768 was not located in the target class net.minecraft.world.level.storage.LevelStorage$Session. 
Using refmap fabric-registry-sync-v0-refmap.json
````
This looks like a bug in the mixin processor or the fabric loader which tells it what to do rather than the fabric api.

It is looking for the intermediate name ````field_23768```` in the inner class LevelStorage.Session which fails.

It is clear from other parts of your stacktrace that you are in a development/deofuscated environment where the field is called ````directory````.

**Comment by warjort** [comment]
What version of minecraft/yarn/fabric api are you using - post your logs/latest.log?
That field changed type in a recent 1.19 snapshot, it was a java nio path.
https://github.com/FabricMC/yarn/blob/22a86199bdb4290b1564015582c6a87d44f747d0/mappings/net/minecraft/world/level/storage/LevelStorage.mapping#L52
This might be a cause if you have mismatched versions?
