### ISSUE TITLE
Game crashes when world loads 100%  | not sure what's causing it

### ISSUE THREAD

**Issue by datablank17** [FabricMC/fabric#2156]
---- Minecraft Crash Report ----
// My bad.

Time: 4/23/22, 7:04 PM
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
	at eu.pb4.polymer.impl.networking.PolymerServerProtocol.sendSyncPackets(PolymerServerProtocol.java:255)
	at net.minecraft.class_3324.localvar$dlp000$polymer_setupHandler(class_3324.java:7450)
	at net.minecraft.class_3324.method_14570(class_3324.java:169)
	at net.minecraft.class_3248.method_33800(class_3248.java:130)
	at net.minecraft.class_3248.md80e21c$lambda$polymer_prePlayHandshakeHackfest$0$0(class_3248.java:1531)
	at eu.pb4.polymer.impl.networking.PolymerHandshakeHandlerImplLogin.method_12082(PolymerHandshakeHandlerImplLogin.java:141)
	at net.minecraft.class_2827.method_12266(class_2827.java:15)
	at net.minecraft.class_2827.method_11054(class_2827.java:6)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756)
	at net.minecraft.class_1255.method_5383(class_1255.java:110)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "dev.onyxstudios.cca._generated_.GeneratedComponentContainer.get$automatone$world_data_provider()" because "<parameter1>" is null
	at dev.onyxstudios.cca._generated_.ComponentType$automatone$world_data_provider.getInternal(Unknown Source)
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.get(ComponentKey.java:83)
	at baritone.Baritone.<init>(Baritone.java:119)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_1657_13562080.<init>(Unknown Source)
	at dev.onyxstudios.cca._generated_.GeneratedContainerFactory_EntityImpl_class_1657_13562080.createContainer(Unknown Source)
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:58)
	at net.minecraft.class_1297.handler$zpo000$initDataTracker(class_1297.java:10538)
	at net.minecraft.class_1297.<init>(class_1297.java:288)
	at net.minecraft.class_1309.<init>(class_1309.java:237)
	at net.minecraft.class_1657.<init>(class_1657.java:199)
	at eu.pb4.polymer.impl.entity.InternalEntityHelpers$1.<init>(InternalEntityHelpers.java:72)
	at eu.pb4.polymer.impl.entity.InternalEntityHelpers.<clinit>(InternalEntityHelpers.java:72)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 940032000 bytes (896 MiB) / 3351248896 bytes (3196 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: unknown
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9664
	Graphics card #1 name: NVIDIA GeForce GTX 1650
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f91
	Graphics card #1 versionInfo: DriverVersion=30.0.15.1215
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 35137.38
	Virtual memory used (MB): 20318.41
	Swap memory total (MB): 2551.59
	Swap memory used (MB): 73.73
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		additionalentityattributes: Additionalentityattributes 1.0.0+1.18.1
		amecsapi: Amecs API 1.3.3+mc1.18-pre1
		amplified_nether: Amplified Nether for Fabric 1.0.1
		apoli: Apoli 2.2.4
		appleskin: AppleSkin 2.3.0+mc1.18.1
		architectury: Architectury 3.8.51
		aspects: Aspects 1.0.5
		automatone: Automatone 0.5.0
		backslot: BackSlot 1.2.5
		bclib: BCLib 1.3.5
		betterthirdperson: Better Third Person 1.6.0
		bewitchment: Bewitchment 1.18-15
		blabber: Blabber 0.1.2
		calio: Calio 1.4.2
		cardinal-components-base: Cardinal Components API (base) 4.1.2
		cardinal-components-entity: Cardinal Components API (entities) 4.1.2
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.1.2
		cardinal-components-world: Cardinal Components API (worlds) 4.1.2
		chat_heads: Chat Heads 0.6.0
		chime: Chime 1.2.0-SNAPSHOT
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		clumps: Clumps 8.0.0+5
		collective-fabric: Collective (Fabric) 4.9
		com_typesafe_config: config 1.4.1
		confabricate: confabricate 2.2.0-SNAPSHOT+4.1.1
		controlling: Controlling For Fabric 9.0+15
		croptopia: Croptopia 1.8.3
		croptosis: Croptosis 1.4.2
		darkrites: Dark Rites 1.18.1-1
		decorative_blocks: Decorative Blocks 2.0.4
		doubledoors-fabric: Double Doors (Fabric) 3.1
		effective: Effective 1.2
		enchdesc: EnchantmentDescriptions 9.0.13
		end_origins: End Origins 1.0.0
		explorerscompass: Explorer's Compass 1.18.1-2.0.3-fabric
		extra_classes_origins: Extra Classes - Origins 1.0.0
		extrakeybinds: ThatRobins Extra Origins Keybinds 1.18-0.1.0
		extraorigins: Extra Origins 1.18-9
		fabric: Fabric API 0.46.6+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.9+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.7+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.7+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.12+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.5+737332ce65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.13+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.15+8906aafd65
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.9+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.9+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.10+c329913d65
		fabricloader: Fabric Loader 0.14.0
		fallingtree: FallingTree 3.2.1
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.1
		firstperson: FirstpersonModel 2.1.0
		foxboi_two: Kitsune 1.1.2
		hologram-api: Hologram API 0.2.1+1.18-pre5
		illuminations: Illuminations 1.10.2
		impersonate: Impersonate 2.4.1
		indium: Indium 1.0.2-alpha3+mc1.18.1
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.2.0-pre
		java: OpenJDK 64-Bit Server VM 17
		kanos_config: Kanos Config 0.2.0+1.14.4-1.19
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lank: Lankasters Origins 1.0.0
		lithium: Lithium 0.7.8
		locki: Locki 0.7.0
		mermaid: Mod 1.0.0
		minecraft: Minecraft 1.18.1
		moborigins: Mob Origins 1.8.0
		modmenu: Mod Menu 3.0.1
		mostructures: Mo' Structures 1.3.1+1.18.1
		mousetweaks: Mouse Tweaks 2.22
		mushroomorigins: Mushroom Origins 1.2
		naturescompass: Nature's Compass 1.18.1-2.0.3-fabric
		notenoughanimations: NotEnoughAnimations 1.6.0
		nullscape: Nullscape for Fabric 1.1
		omega-config: OmegaConfig 1.2.3-1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		origins: Origins 1.3.2
		origins-classes: Origins: Classes 1.2.4
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		pandemonium: Requiem: Pandemonium 2.0.0-beta.7
		pandemoniumapi: Requiem: Pandemonium-API 2.0.0-beta.7
		patchouli: Patchouli 1.18.1-65-FABRIC
		pehkui: Pehkui 3.2.2+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.5.0
		polymer: Polymer (Core) 0.2.0-beta.27+1.18.1
		polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0-beta.27+1.18.1
		pride: Pride Lib 1.1.0+1.17
		rammling: Goat Origin 1.0.0
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		requiem: Requiem 2.0.0-beta.7
		requiem-core: Requiem-Core 2.0.0-beta.7
		requiemapi: Requiem-API 2.0.0-beta.7
		roughlyenoughitems: Roughly Enough Items 7.4.450
		satin: Satin 1.7.2
		seedfix: Seed Fix 1.0.0
		server_translations_api: Server Translations API 1.4.8+1.18-pre1
		sgui: sgui 1.0.0+1.18.1
		skinlayers: 3d Skin Layers 1.4.3-mc1.18.2
		sodium: Sodium 0.4.0-alpha6+build.14
		spruceui: SpruceUI 3.3.0+1.17
		starterkit-fabric: Starter Kit (Fabric) 3.1
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 2.0.12
		trinkets: Trinkets 3.2.0
		universal-graves: Universal Graves 2.0.0-rc.5+1.18.1
		villagernames: Villager Names 3.0.3
		voicechat: Simple Voice Chat 1.18.1-2.2.32
		waystones: Waystones 2.4.1
		witherborn_origins: witherborn origins 1.0.0
		wthit: wthit 4.5.5
		xaerominimap: Xaero's Minimap 22.3.0
		xaeroworldmap: Xaero's World Map 1.20.3.1
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by warjort** [comment]
````
Caused by: java.lang.NullPointerException: Cannot invoke "dev.onyxstudios.cca.generated.GeneratedComponentContainer.get$automatone$world_data_provider()" because "" is null
at dev.onyxstudios.cca.generated.ComponentType$automatone$world_data_provider.getInternal(Unknown Source)
at dev.onyxstudios.cca.api.v3.component.ComponentKey.get(ComponentKey.java:83)
at baritone.Baritone.(Baritone.java:119)
at dev.onyxstudios.cca.generated.GeneratedComponentContainer_EntityImpl_class_1657_13562080.(Unknown Source)
at dev.onyxstudios.cca.generated.GeneratedContainerFactory_EntityImpl_class_1657_13562080.createContainer(Unknown Source)
at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:58)
at net.minecraft.class_1297.handler$zpo000$initDataTracker(class_1297.java:10538)
at net.minecraft.class_1297.(class_1297.java:288)
at net.minecraft.class_1309.(class_1309.java:237)
at net.minecraft.class_1657.(class_1657.java:199)
at eu.pb4.polymer.impl.entity.InternalEntityHelpers$1.(InternalEntityHelpers.java:72)
at eu.pb4.polymer.impl.entity.InternalEntityHelpers.(InternalEntityHelpers.java:72)
````

This is not a fabric issue.

The error shows "polymer" trying to send data for an entity from the "automatone" mod over the network.
But this fails when it tries to access some "cardinal components" data for that entity.

You should report this to the automatone project, they are most likely responsible for this problem.
