### ISSUE TITLE
Crash on loading in 22w17a with Fabric 0.13.3 with no mods

### ISSUE THREAD

**Issue by Flexico** [FabricMC/fabric#2178]
[08:43:27] [main/INFO]: Loading Minecraft 22w17a with Fabric Loader 0.13.3
[08:43:28] [main/WARN]: Incomplete remapped file found! This means that the remapping process failed on the previous launch. If this persists, make sure to let us at Fabric know!
[08:43:28] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[08:43:30] [main/ERROR]: Uncaught exception in thread "main"
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Unsupported class file major version 63
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199) ~[asm-9.2.jar:9.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180) ~[asm-9.2.jar:9.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166) ~[asm-9.2.jar:9.2]
	at net.fabricmc.tinyremapper.TinyRemapper.analyze(TinyRemapper.java:571) ~[tiny-remapper-0.8.1.jar:0.8.1]
	at net.fabricmc.tinyremapper.TinyRemapper.access$400(TinyRemapper.java:73) ~[tiny-remapper-0.8.1.jar:0.8.1]
	at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:525) ~[tiny-remapper-0.8.1.jar:0.8.1]
	at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:521) ~[tiny-remapper-0.8.1.jar:0.8.1]
	at java.nio.file.Files.walkFileTree(Files.java:2811) ~[?:?]
	at java.nio.file.Files.walkFileTree(Files.java:2882) ~[?:?]
	at net.fabricmc.tinyremapper.TinyRemapper.readFile(TinyRemapper.java:521) ~[tiny-remapper-0.8.1.jar:0.8.1]
	at net.fabricmc.tinyremapper.TinyRemapper.access$200(TinyRemapper.java:73) ~[tiny-remapper-0.8.1.jar:0.8.1]
	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:492) ~[tiny-remapper-0.8.1.jar:0.8.1]
	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:488) ~[tiny-remapper-0.8.1.jar:0.8.1]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more

**Comment by warjort** [comment]
````
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Unsupported class file major version 63
at org.objectweb.asm.ClassReader.(ClassReader.java:199) ~[asm-9.2.jar:9.2]
````

63 is java 19. 
Try it with java 17 until object web's asm library supports java 19.

**Comment by modmuss50** [comment]
You need to use loader 0.14.4 with the 1.19 snapshots. It is currently a beta so must be manually selected in the installer.
