### ISSUE TITLE
SHA-256 digest error for net/fabricmc/loader/impl/launch/knot/KnotClient.class

### ISSUE THREAD

**Issue by Enaium** [FabricMC/fabric#2219]
minecraft_version=1.14.4
yarn_mappings=1.14.4+build.18
loader_version=0.14.5
fabric_version=0.28.5+1.14

```
Exception in thread "main" java.lang.SecurityException: SHA-256 digest error for net/fabricmc/loader/impl/launch/knot/KnotClient.class
	at java.base/sun.security.util.ManifestEntryVerifier.verify(ManifestEntryVerifier.java:240)
	at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:247)
	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:234)
	at java.base/java.util.jar.JarVerifier$VerifierStream.read(JarVerifier.java:480)
	at java.base/jdk.internal.loader.Resource.getBytes(Resource.java:126)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getBytes(URLClassPath.java:893)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:859)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:85)
```

**Comment by Enaium** [comment]
Delete FABRIC1.RSA FABRIC1.SF MANIFEST.MF

**Comment by modmuss50** [comment]
Deleting those files isnt the fix... What launcher are you using? What operating system are you using?

**Comment by Enaium** [comment]
Deleting these files did solve it

IntelliJ IDEA 2022.1.1 (Ultimate Edition)
Build #IU-221.5591.52, built on May 11, 2022
For educational use only.
Runtime version: 11.0.14.1+1-b2043.45 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1966M
Cores: 16

**Comment by Enaium** [comment]
1.17+ does not have this issue
