### ISSUE TITLE
Custom End biomes crash

### ISSUE THREAD

**Issue by haykam821** [FabricMC/fabric#2292]
When using the Fabric API test mod in the End (`/execute in the_end run tp @s 0 256 2000`):

```
java.lang.IllegalStateException: seed isn't set, ChunkGenerator hook not working?
	at net.fabricmc.fabric.impl.biome.TheEndBiomeData$Overrides.getSampler(TheEndBiomeData.java:163)
	at net.fabricmc.fabric.impl.biome.TheEndBiomeData$Overrides.pick(TheEndBiomeData.java:155)
	at net.fabricmc.fabric.impl.biome.TheEndBiomeData$Overrides.pick(TheEndBiomeData.java:136)
	at net.minecraft.class_2169.handler$zzd000$getWeightedEndBiome(class_2169.java:546)
	at net.minecraft.class_2169.method_38109(class_2169.java:71)
	at net.minecraft.class_3195.method_41613(class_3195.java:145)
	at net.minecraft.class_3195.method_41614(class_3195.java:124)
	at net.minecraft.class_2794.method_41044(class_2794.java:636)
	at net.minecraft.class_2794.method_41041(class_2794.java:589)
```

**Comment by modmuss50** [comment]
Can you provide a test mod/code to help reproduce this? As far as I know the existing example mod is working?

**Comment by haykam821** [comment]
The test mod is not working. The outer area of the End must be loaded for the biomes added by the test mod to generate.

**Comment by modmuss50** [comment]
Ah ok, we need to make this fail fast. 👍
