### ISSUE TITLE
on build.gradle refresh, fabric registry module is not remapping fully

### ISSUE THREAD

**Issue by ianm1647** [FabricMC/fabric#2304]
```
Status ERROR: org.eclipse.jdt.core code=4 Could not retrieve declared methods org.eclipse.jdt.internal.compiler.problem.AbortCompilation: Pb(324) The type net.minecraft.class_2960 cannot be resolved. It is indirectly referenced from required .class files
Could not remap fabric-content-registries-v0-3.0.16+9ff28f40a9-sources.jar fully! 
```

i didnt know if anyone could help me understand why this is happening
but its causing the dev client to not be launchable

**Comment by ianm1647** [comment]
```
 net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'net.minecraft.util.Identifier net.minecraft.util.registry.RegistryKey.method_29177()'
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.util.Identifier net.minecraft.util.registry.RegistryKey.method_29177()'
	at net.minecraft.util.registry.SimpleRegistry.handler$zbd000$setPre(SimpleRegistry.java:651) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry.java) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry.java:87) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.registry.SimpleRegistry.add(SimpleRegistry.java:135) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.registry.Registry.create(Registry.java:389) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.registry.Registry.create(Registry.java:381) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.registry.Registry.create(Registry.java:365) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:203) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:50) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:154) ~[minecraft-project-@-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.7.jar:?]
	... 3 more
```

this is the error for the launch

**Comment by modmuss50** [comment]
What loom version are you using? You can find it at the top of your build.gradle file?

**Comment by ianm1647** [comment]
ohhhh okay thats the problem , i didn't change it from 0.11 to 0.12

**Comment by ianm1647** [comment]
> ```
>  net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'net.minecraft.util.Identifier net.minecraft.util.registry.RegistryKey.method_29177()'
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.7.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.7.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.7.jar:?]
> 	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
> Caused by: java.lang.NoSuchMethodError: 'net.minecraft.util.Identifier net.minecraft.util.registry.RegistryKey.method_29177()'
> 	at net.minecraft.util.registry.SimpleRegistry.handler$zbd000$setPre(SimpleRegistry.java:651) ~[minecraft-project-@-merged-named.jar:?]
> 	at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry.java) ~[minecraft-project-@-merged-named.jar:?]
> 	at net.minecraft.util.registry.SimpleRegistry.set(SimpleRegistry.java:87) ~[minecraft-project-@-merged-named.jar:?]
> 	at net.minecraft.util.registry.SimpleRegistry.add(SimpleRegistry.java:135) ~[minecraft-project-@-merged-named.jar:?]
> 	at net.minecraft.util.registry.Registry.create(Registry.java:389) ~[minecraft-project-@-merged-named.jar:?]
> 	at net.minecraft.util.registry.Registry.create(Registry.java:381) ~[minecraft-project-@-merged-named.jar:?]
> 	at net.minecraft.util.registry.Registry.create(Registry.java:365) ~[minecraft-project-@-merged-named.jar:?]
> 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:203) ~[minecraft-project-@-merged-named.jar:?]
> 	at net.minecraft.Bootstrap.initialize(Bootstrap.java:50) ~[minecraft-project-@-merged-named.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:154) ~[minecraft-project-@-merged-named.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.7.jar:?]
> 	... 3 more
> ```
> 
> this is the error for the launch

im still experiencing the same crash though

**Comment by modmuss50** [comment]
Now that you have updated, try running `./gradlew --refresh-dependencies` to refresh all the files, I think you might be in a broken state.

**Comment by ianm1647** [comment]
okay its fixed now, thank you!
