### ISSUE TITLE
Failed to read accessWidener file from mod fabric-object-builder-api-v1 in 1.19 build 4

### ISSUE THREAD

**Issue by CodeCraftPlugin** [FabricMC/fabric#2354]
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod fabric-object-builder-api-v1
    at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
    at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: net.fabricmc.mapping.reader.v2.MappingParseException: Error on line "    m    (Ldhq$a;Lgt;)V    b    method_
this is the error coming when i try to run my game 
if this error is already reported then please ignore it

**Comment by warjort** [comment]
Can you post the full error, you appear to have truncated it?
The actual format should have a concluding "! following by the real error.
https://github.com/FabricMC/tiny-mappings-parser/blob/750be4e7395397fa5fc558d492e2b6c219e4d570/src/main/java/net/fabricmc/mapping/reader/v2/TinyV2Factory.java#L92

From what I can tell it is complaining about some bad mapping in fabric-object-builder-api-v1's accesswidener
The method shown looks like it is still in minecraft's obfuscated mapping.
I think Ldhg$a; is the TreeDecorator$Generator and Lgt; is BlockPos
But the aw file has no mention of those classes.
https://github.com/FabricMC/fabric/blob/1.19/fabric-object-builder-api-v1/src/main/resources/fabric-object-builder-api-v1.accesswidener

**Comment by CodeCraftPlugin** [comment]
this is the only error that is coming

**Comment by warjort** [comment]
Post your logs/latest.log
