### ISSUE TITLE
Cannot Launch Modpack due to Error

### ISSUE THREAD

**Issue by Jmanistan** [FabricMC/fabric#2392]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mythicmounts'!
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
    at net.minecraft.class_310.<init>(class_310.java:457)
    at net.minecraft.client.main.Main.main(Main.java:179)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
    at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NullPointerException: Cannot read field "speed" because the return value of "java.util.HashMap.get(Object)" is null
    at com.yahoo.chirpycricket.mythicmounts.entity.MountEntity.calcSpeedStat(MountEntity.java:637)
    at com.yahoo.chirpycricket.mythicmounts.entity.MountEntity.createMountAttributes(MountEntity.java:595)
    at com.yahoo.chirpycricket.mythicmounts.registery.Entities$EntityMapEntry.doServerRegistration(Entities.java:330)
    at com.yahoo.chirpycricket.mythicmounts.registery.Entities.doServerInit(Entities.java:261)
    at com.yahoo.chirpycricket.mythicmounts.MythicMounts.onInitialize(MythicMounts.java:24)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
    ... 11 more

**Comment by warjort** [comment]
Check you have the latest version, then report this to the mythic mounts mod
