### ISSUE TITLE
Game crashes whenever I launch 

### ISSUE THREAD

**Issue by sidph0** [FabricMC/fabric#2410]
---- Minecraft Crash Report ----
// My bad.

Time: 7/20/22, 9:08 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'clientcommands'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ExceptionInInitializerError
	at net.earthcomputer.clientcommands.ClientCommands.onInitializeClient(ClientCommands.java:24)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 16 more
Caused by: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "net.earthcomputer.clientcommands.script.ScriptManager.ENGINE" is null
	at net.earthcomputer.clientcommands.script.ScriptManager.addBuiltinVariables(ScriptManager.java:157)
	at net.earthcomputer.clientcommands.script.ScriptManager.<clinit>(ScriptManager.java:61)
	... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1347135800 bytes (1284 MB) / 2222981120 bytes (2120 MB) up to 17179869184 bytes (16384 MB)
	CPUs: 16
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m -Xmx16384m
	Fabric Mods: 
		antighost: AntiGhost 1.14.4-fabric0.4.23-1.1.1
		carpet: Carpet Mod in Fabric 1.2.0
		carpet-extra: Carpet Extra 1.3.5
		clientcommands: Client Commands 2.3.7-pre1
		cloth-config2: Cloth Config v2 1.8
		cotton-client-commands: Cotton Client Commands 0.4.2+1.14.3-SNAPSHOT
		fabric: Fabric API 0.28.5+1.14
		fabric-api-base: Fabric API Base 0.1.2+de26dc4942
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.2+4ea4772942
		fabric-command-api-v1: Fabric Command API (v1) 1.0.2+4ea4772942
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+4ea4772942
		fabric-containers-v0: Fabric Containers (v0) 0.1.4+4ea4772942
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+4ea4772942
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+4ea4772942
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.2+4ea4772942
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+4ea4772942
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+4ea4772942
		fabric-item-api-v1: Fabric Item API (v1) 1.1.1+4ea4772942
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+4ea4772942
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+4ea4772942
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+4ea4772942
		fabric-language-kotlin: Fabric Language Kotlin 1.3.50+build.2
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+4ea4772942
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.2+4ea4772942
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+4ea4772942
		fabric-models-v0: Fabric Models (v0) 0.1.1+4ea4772942
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+4ea4772942
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.2+4ea4772942
		fabric-networking-v0: Fabric Networking (v0) 0.2.1+4ea4772942
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.0.1+4ea4772942
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.3.1+4ea4772942
		fabric-particles-v1: fabric-particles-v1 0.2.2+4ea4772942
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.4+4ea4772942
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.2+4ea4772942
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.16+4ea4772942
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+4ea4772942
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.4+4ea4772942
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.3+4ea4772942
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.5+4ea4772942
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.4+4ea4772942
		fabric-textures-v0: Fabric Textures (v0) 0.1.5+4ea4772942
		fabricloader: Fabric Loader 0.14.8
		fiber: fiber 0.23.0-2
		itemscroller: Item Scroller 0.15.0-dev.20190806.191755
		java: OpenJDK 64-Bit Server VM 17
		litematica: Litematica 0.0.0-dev.20191222.014040
		malilib: MaLiLib 0.10.0-dev.20+arne.2
		minecraft: Minecraft 1.14.4
		minecraftcapes: MinecraftCapes Mod 11.0.1
		minihud: MiniHUD 0.19.0-dev.20200424.001737
		multiconnect-api: MultiConnect API 1.0.1
		okzoomer: Ok Zoomer 4.0.0+1.14.4
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.50
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.50
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.50
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.0
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 2.2
		tweakeroo: Tweakeroo 0.10.0-dev.20191218.170529
	Launched Version: 1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: Cannot read field "field_1887" because "this.field_1690" is null
	Current Language: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_1076.method_4669()" because "this.field_1717" is null
	CPU: <unknown>

**Comment by Linguardium** [comment]
this does not appear to be an issue with fabric api but appears to be a mod issue with Client Commands
