### ISSUE TITLE
cant load black hole mod any help please?

### ISSUE THREAD

**Issue by mariohany534** [FabricMC/fabric#2442]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, version 0.30.0 or later.
Unmet dependency listing:
	 - Mod 'Black Hole' (blackhole) 1.0.1+1.16.5 requires version 0.30.0+1.16 or later of fabric, which is missing!
	 - Mod 'Myron' (myron) 1.5.1 requires version 0.29.0 or later of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by mariohany534** [comment]
and wth is myron i didnt install that mod

**Comment by mariohany534** [comment]
just found out that i dont have fabric api with the mods lol
