### ISSUE TITLE
fabric-networking-api-v1 in fabricAPI causes Latest Fabric version to crash.

### ISSUE THREAD

**Issue by 3pical** [FabricMC/fabric#2460]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2022-08-11 20:43:53
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-networking-api-v1'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'fabric-networking-api-v1'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 17 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3248 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:68)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 18 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 28 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-networking-api-v1.mixins.json:ServerLoginNetworkHandlerMixin from mod fabric-networking-api-v1] from phase [DEFAULT] in config [fabric-networking-api-v1.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 31 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_14162 was not located in the target class net.minecraft.class_3248. Using refmap fabric-networking-api-v1-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 31 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.18.16-200.fc36.x86_64
	Java Version: 17.0.1, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 1016615424 bytes (969 MiB) / 2126512128 bytes (2028 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 3 3200G with Radeon Vega Graphics
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Device
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 4098.00
	Graphics card #0 deviceId: 0x743f
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 16160.51
	Virtual memory used (MB): 5560.66
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 2.62
	JVM Flags: 2 total; -Xms1024m -Xmx4096m
	Fabric Mods: 
		fabric-api: Fabric API 0.59.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.10+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.8+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.16+83a8659290
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.19+9ff28f4090
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.0+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.10+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.6+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.27+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.33+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.2+83a8659290
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.4+bd0a0d4a90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.7+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.29+a6d2f78590
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.17+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.27+9ff28f4090
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.27+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.20+1899036190
			fabric-item-api-v1: Fabric Item API (v1) 1.5.6+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.27+6bee109e90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.19+9ff28f4090
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.17+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+83a8659290
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.5+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.2+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.13+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.16+9ff28f4090
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.3+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.20+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.10+7675279690
			fabric-particles-v1: Fabric Particles (v1) 1.0.9+dc39553a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.23+23c4cfef90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.9+84f79e9d90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.11+5187d39f90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.19+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.13+9ff28f4090
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.6+9ff28f4090
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.21+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.15+9ff28f4090
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.10+e62f51a390
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.0+6bee109e90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.25+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.12+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.19+9ff28f4090
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.10+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.2.0+1e232e1390
		fabricloader: Fabric Loader 0.14.9
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.2
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by warjort** [comment]
This is an issue with polymc, if you change the minecraft version. see https://github.com/PolyMC/PolyMC/issues/1042

You need to "edit instance" click on versions and also change the "intermediary mappings" to be the correct version
If you can't get it to work ask on their discord.
