### ISSUE TITLE
Fabric can't lanch: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-networking-api-v1'!

### ISSUE THREAD

**Issue by pengtao6993** [FabricMC/fabric#2491]
I can't launch after adding some new mods.HELP!
Crash Report:
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-networking-api-v1'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:443)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'fabric-networking-api-v1'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3248 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:68)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 18 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-networking-api-v1.mixins.json:ServerLoginNetworkHandlerMixin from mod fabric-networking-api-v1] from phase [DEFAULT] in config [fabric-networking-api-v1.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 21 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Redirect annotation on handlePlayerJoin could not find any targets matching 'Lnet/minecraft/class_3248;method_18784()V' in net.minecraft.class_3248. Using refmap fabric-networking-api-v1-refmap.json [PREINJECT Applicator Phase -> fabric-networking-api-v1.mixins.json:ServerLoginNetworkHandlerMixin from mod fabric-networking-api-v1 -> Prepare Injections ->  -> redirect$zpi000$handlePlayerJoin(Lnet/minecraft/class_3248;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.RedirectInjectionInfo.<init>(RedirectInjectionInfo.java:44)
	at jdk.internal.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:443)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:高级 Windows 32 基本 API:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:用户体验控件库:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS 客户端 API DLL:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP 帮助程序 API:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT 基本 API 客户端 DLL:10.0.25186.1000 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT 基本 API 客户端 DLL:10.0.25186.1000 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.2205.7 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:用于 Windows 的 Microsoft OLE:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows 性能数据助手 DLL:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:远程过程调用运行时:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell 公用 DLL:10.0.25190.1001 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:多用户 Windows 用户 API 客户端 DLL:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP 服务:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32 位 DLL:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:应用程序兼容性客户端库:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows 加密基元库:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:用于 Windows 的 Microsoft COM:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP 客户端服务:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 客户端:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec 用户模式 API:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		instrument.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		java.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		javaw.exe:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		jemalloc.dll
		jimage.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		jli.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		jna6197164971097691799.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
		jvm.dll:Java HotSpot(TM) 64-Bit server VM:17.0.1.0:Oracle Corporation
		kernel.appcore.dll:AppModel API Host:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		management_ext.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 服务提供程序:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:电子邮件命名填充提供程序:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		nio.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT 层 DLL:10.0.25186.1000 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows 系统性能对象 DLL:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP 命名空间提供程序:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:外壳简易实用工具库:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		svml.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
		win32u.dll:Win32u:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows 基本类型 DLL:10.0.25192.1000 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.25182.1000 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:Java(TM) Platform SE binary:17.0.1.0:Oracle Corporation
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 486237200 bytes (463 MiB) / 968884224 bytes (924 MiB) up to 4831838208 bytes (4608 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: unknown
	Frequency (GHz): 1.70
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 4000
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 2112.00
	Graphics card #0 deviceId: 0x0166
	Graphics card #0 versionInfo: DriverVersion=10.18.10.4252
	Graphics card #1 name: NVIDIA GeForce GT 740M
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x0fdf
	Graphics card #1 versionInfo: DriverVersion=25.21.14.2531
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 16269.55
	Virtual memory used (MB): 8977.38
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 146.00
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx4608m
	Fabric Mods: 
		architectury: Architectury 5.12.44
		badpackets: Bad Packets 0.1.2
		betterbiomeblend: Better Biome Blend 1.19-1.3.6-fabric
		betterfpsdist: Better FPS distance Mod 1.19-1.9
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
			fabric-api-base: Fabric API Base 0.4.9+e62f51a395
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.1+3082331495
		cloth-config: Cloth Config v8 8.0.75
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		creativecore: CreativeCore (Fabric) 2.7.2
		durabilityviewer: Giselbaers Durability Viewer 1.19-fabric0.53.3-1.10.3
			crowdin-translate: CrowdinTranslate 1.4+1.19
			gbfabrictools: GBfabrictools 1.3.4+1.19
		ecs: Elytra/Chestplate Swapper 1.2.1-MC1.19
		ellemes_container_lib: Ellemes' Container Library 2.0.1
		enderitemod: Enderite Mod 1.4.1
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		expandedstorage: Expanded Storage 8.0.1
		fabric: Fabric API 0.58.0+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39fa9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e0a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.7+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.9
		farmersdelight: Farmer's Delight 1.19-1.3.3
		ferritecore: FerriteCore 4.2.1
		firstperson: FirstpersonModel 2.1.2
		flytre_lib: FlytreLib 1.8.8
		ftblibrary: FTB Library 1900.3.8-build.135
		ftbultimine: FTB Ultimine 1900.3.4-build.58
		homing_ender_eye: Homing Ender Eye 1.2.0
		infinitemusic: Infinite Music 1.6.2
		inventorio: Inventorio 1.8.0
		inventoryprofilesnext: Inventory Profiles Next 1.6.2
		iris: Iris 1.2.6
			org_anarres_jcpp: jcpp 1.4.14
		itemphysic: ItemPhysic (Fabric) 1.6.3
		java: Java HotSpot(TM) 64-Bit Server VM 17
		litematica: Litematica 0.12.0
		lithium: Lithium 0.8.1
		lucky: Lucky Block 1.19-13.0
		malilib: MaLiLib 0.13.0
		mcwifipnp: LAN World Plug-n-Play 1.5.6
		midnightlib: MidnightLib 0.6.0
		minecraft: Minecraft 1.19
		minihud: MiniHUD 0.23.0
		modmenu: Mod Menu 4.0.4
		moremcmeta: MoreMcmeta 1.19-3.0.5
		neat: Neat 1.19-32-FABRIC
		netherite_nugget: Netherite Nuggets 1.5.0
		nme: Not Mutually Exclusive 1.0.0
		noexpensive: NoExpensive 1.19-Fabric-1.4.0
		notenoughanimations: NotEnoughAnimations 1.6.1
		pipe: Pipe 1.8.5
		presencefootsteps: Presence Footsteps 1.6.1
			kirin: Kirin UI 1.11.0
		rad: Reload Audio Driver 1.0.2
		repurposed_structures: Repurposed Structures 6.1.1+1.19
		sit: Sit 1.19-20
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		spawnermod: Enhanced Mob Spawners 1.2.0
		starlight: Starlight 1.1.1+fabric.ae22326
		stoneholm: Stoneholm 1.4.4
		travelersbackpack: Traveler's Backpack 1.19-8.0.3
		tweakeroo: Tweakeroo 0.14.0
		villagespawnpoint-fabric: Village Spawn Point (Fabric) 2.0
		wthit: wthit 5.9.0
		xaerominimap: Xaero's Minimap 22.12.0
		xaeroworldmap: Xaero's World Map 1.26.1
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by apple502j** [comment]
Seems like there is a mod for 1.19.1 in your mod folder.

**Comment by starfrost013** [comment]
>10.0.25192.1000

lol.
