### ISSUE TITLE
Crash "Could not execute entrypoint stage 'main'"

### ISSUE THREAD

**Issue by Mishqutin** [FabricMC/fabric#269]
So I wanted to install CC:Tweaked from [Here](https://minecraft.curseforge.com/projects/cc-tweaked). Latest file for 1.14.2 with Fabric. Downloaded Fabric and installed 1.14.2 build 7 and got a crash. Later tried with build 2 and game also crashed. When I removed the mod from .minecraft/mods it got up successfully.

I'm using SKLauncher. Here's the crash report:
```
---- Minecraft Crash Report ----
// You're mean.

Time: 12.06.19 18:46
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/network/ServerSidePacketRegistry
		at dan200.computercraft.shared.network.NetworkHandler.setup(NetworkHandler.java:50)
		at dan200.computercraft.shared.proxy.ComputerCraftProxyCommon.setup(ComputerCraftProxyCommon.java:56)
		at dan200.computercraft.ComputerCraft.onInitialize(ComputerCraft.java:199)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at java.util.ArrayList.forEach(Unknown Source)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 11 more
	Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.network.ServerSidePacketRegistry
		at java.net.URLClassLoader.findClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:160)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 483270144 bytes (460 MB) / 1207959552 bytes (1152 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: fabric-loader-0.4.8+build.155-1.14.2+build.2
	LWJGL: 3.2.1 build 12
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>
```

**Comment by asiekierka** [comment]
Install Fabric API.

**Comment by Mishqutin** [comment]
I have `fabric-api-0.3.0+build.183.jar` in my mods folder.

**Comment by asiekierka** [comment]
It doesn't appear to have loaded, though. In addition, SKLauncher is not on our list of supported launchers - have you tried with one of the supported launchers?

**Comment by Mishqutin** [comment]
I will try in a while.

**Comment by Mishqutin** [comment]
Uhhhh, looks like I'm too poor for this game. I used to play on cracked launchers :/ See ya.

**Comment by dresiarz** [comment]
niggers

**Comment by asiekierka** [comment]
Please do not use our stance on piracy as an excuse to post offensive comments.
