### ISSUE TITLE
Fabric 1.19.3 pre-2 does not work with mods installed (No error message)

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#2713]
Fabric 1.19.3 pre-2 does not work with mods installed (No error message)

Mods Installed:

3D Skin Layers
Better Mount Hud
Chat Up
Clumps
Continuity
Fabric API 0.67.3
Ferritecore 5.0.3
Indium 1.0.9
Item Model Fix 1.0.3
LazyDFU
No Chat Reports 1.19.3 pre-2 v1.16.0
No Report Button 1.2.0
Smooth Boot 1.7.1
Sodium 0.4.4
Starlight 1.1.1
Techno Model 1.0.2 (For Technoblade Pig)
View DIstance Fix 1.0.0

All of these mods are using the latest versions that are available.

I found the latest log file.

[19:04:50] [main/INFO]: Loading Minecraft 1.19.3-pre2 with Fabric Loader 0.14.10
[19:04:50] [main/WARN]: Warnings were found!
 - Mod 'Item Model Fix' (itemmodelfix) 1.0.3+1.19 recommends any version of modmenu, which is missing!
	 - You should install any version of modmenu for the optimal experience.
 - Mod 'Item Model Fix' (itemmodelfix) 1.0.3+1.19 recommends any version of cloth-config2, which is missing!
	 - You should install any version of cloth-config2 for the optimal experience.
[19:04:50] [main/INFO]: Loading 68 mods:
	- bettermounthud 1.2.0
	- chat-up 2.1
	- clumps 9.0.0+11
	- continuity 2.0.1+1.19
	- fabric-api 0.67.3+1.19.3
	- fabric-api-base 0.4.18+faff3b848f via fabric-api
	- fabric-api-lookup-api-v1 1.6.17+49abcf7e8f via fabric-api
	- fabric-biome-api-v1 11.0.6+65e415cb8f via fabric-api
	- fabric-block-api-v1 1.0.3+12bfe4ea8f via fabric-api
	- fabric-blockrenderlayer-v1 1.1.27+c6af733c8f via fabric-api
	- fabric-client-tags-api-v1 1.0.8+49abcf7e8f via fabric-api
	- fabric-command-api-v1 1.2.18+f71b366f8f via fabric-api
	- fabric-command-api-v2 2.1.14+49abcf7e8f via fabric-api
	- fabric-commands-v0 0.2.35+df3654b38f via fabric-api
	- fabric-containers-v0 0.1.43+df3654b38f via fabric-api
	- fabric-content-registries-v0 3.4.10+49abcf7e8f via fabric-api
	- fabric-convention-tags-v1 1.1.8+2894d6df8f via fabric-api
	- fabric-crash-report-info-v1 0.2.12+aeb40ebe8f via fabric-api
	- fabric-data-generation-api-v1 11.0.0+65e415cb8f via fabric-api
	- fabric-dimensions-v1 2.1.38+48349a3f8f via fabric-api
	- fabric-entity-events-v1 1.5.4+b83334a08f via fabric-api
	- fabric-events-interaction-v0 0.4.35+c6af733c8f via fabric-api
	- fabric-events-lifecycle-v0 0.2.37+df3654b38f via fabric-api
	- fabric-game-rule-api-v1 1.0.28+2894d6df8f via fabric-api
	- fabric-item-api-v1 2.1.2+8c8428108f via fabric-api
	- fabric-item-group-api-v1 2.1.5+8c8428108f via fabric-api
	- fabric-key-binding-api-v1 1.0.28+aaaf9d338f via fabric-api
	- fabric-keybindings-v0 0.2.26+df3654b38f via fabric-api
	- fabric-lifecycle-events-v1 2.2.7+2894d6df8f via fabric-api
	- fabric-loot-api-v2 1.1.16+75e982118f via fabric-api
	- fabric-loot-tables-v1 1.1.20+9e7660c68f via fabric-api
	- fabric-message-api-v1 5.0.11+6ede1da98f via fabric-api
	- fabric-mining-level-api-v1 2.1.27+49abcf7e8f via fabric-api
	- fabric-models-v0 0.3.24+11ba9c3b8f via fabric-api
	- fabric-networking-api-v1 1.2.13+28ac448f8f via fabric-api
	- fabric-networking-v0 0.3.30+df3654b38f via fabric-api
	- fabric-object-builder-api-v1 5.1.5+49abcf7e8f via fabric-api
	- fabric-particles-v1 1.0.17+fbde993d8f via fabric-api
	- fabric-registry-sync-v0 2.0.0+260856468f via fabric-api
	- fabric-renderer-api-v1 2.0.6+91f53ef58f via fabric-api
	- fabric-renderer-indigo 0.6.22+11ba9c3b8f via fabric-api
	- fabric-renderer-registries-v1 3.2.27+df3654b38f via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.22+48349a3f8f via fabric-api
	- fabric-rendering-fluids-v1 3.0.15+3067f4638f via fabric-api
	- fabric-rendering-v0 1.1.30+df3654b38f via fabric-api
	- fabric-rendering-v1 1.11.6+49abcf7e8f via fabric-api
	- fabric-resource-conditions-api-v1 2.2.0+280be3ab8f via fabric-api
	- fabric-resource-loader-v0 0.10.2+f6c919d68f via fabric-api
	- fabric-screen-api-v1 1.0.36+8c8428108f via fabric-api
	- fabric-screen-handler-api-v1 1.3.9+49abcf7e8f via fabric-api
	- fabric-sound-api-v1 1.0.6+75e982118f via fabric-api
	- fabric-transfer-api-v1 2.1.10+28ac448f8f via fabric-api
	- fabric-transitive-access-wideners-v1 2.1.0+0efcd39b8f via fabric-api
	- fabricloader 0.14.10
	- ferritecore 5.0.3
	- indium 1.0.9+mc1.19.2
	- itemmodelfix 1.0.3+1.19
	- java 17
	- lazydfu 0.1.3
	- minecraft 1.19.3-beta.2
	- nochatreports 1.19.3-pre2-v1.16.0
	- noreportbutton 1.2.0
	- org_joml_joml 1.10.4 via sodium
	- skinlayers 1.5.2-mc1.19.1
	- smoothboot 1.19-1.7.1
	- sodium 0.4.4+build.18
	- starlight 1.1.1+fabric.ae22326
	- technomodel 1.0.2
[19:04:50] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/notpi/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[19:04:50] [main/INFO]: Compatibility level set to JAVA_17
[19:04:50] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 0 override(s) found
[19:04:50] [main/WARN]: Error loading class: net/minecraft/class_1059$class_4007 (java.lang.ClassNotFoundException: net/minecraft/class_1059$class_4007)
[19:04:50] [main/WARN]: @Mixin target net.minecraft.class_1059$class_4007 was not found continuity.mixins.json:SpriteAtlasTextureDataMixin from mod continuity
[19:04:50] [main/WARN]: Error loading class: net/minecraft/class_4581 (java.lang.ClassNotFoundException: net/minecraft/class_4581)
[19:04:50] [main/WARN]: @Mixin target net.minecraft.class_4581 was not found sodium.mixins.json:core.matrix.MixinMatrix3f from mod sodium
[19:04:50] [main/WARN]: Error loading class: net/minecraft/class_1159 (java.lang.ClassNotFoundException: net/minecraft/class_1159)
[19:04:50] [main/WARN]: @Mixin target net.minecraft.class_1159 was not found sodium.mixins.json:core.matrix.MixinMatrix4f from mod sodium
[19:04:50] [main/WARN]: Error loading class: net/minecraft/class_1058$class_5790 (java.lang.ClassNotFoundException: net/minecraft/class_1058$class_5790)
[19:04:50] [main/WARN]: @Mixin target net.minecraft.class_1058$class_5790 was not found sodium.mixins.json:features.texture_tracking.MixinSpriteAnimation from mod sodium
[19:04:50] [main/WARN]: Error loading class: net/minecraft/class_1058$class_4728 (java.lang.ClassNotFoundException: net/minecraft/class_1058$class_4728)
[19:04:50] [main/WARN]: @Mixin target net.minecraft.class_1058$class_4728 was not found sodium.mixins.json:features.texture_updates.MixinSpriteInterpolated from mod sodium
[19:04:50] [main/WARN]: Error loading class: net/minecraft/class_1059$class_4007 (java.lang.ClassNotFoundException: net/minecraft/class_1059$class_4007)
[19:04:50] [main/WARN]: Error loading class: net/minecraft/class_1058$class_4727 (java.lang.ClassNotFoundException: net/minecraft/class_1058$class_4727)
[19:04:50] [main/WARN]: Error loading class: net/minecraft/class_1059$class_4007 (java.lang.ClassNotFoundException: net/minecraft/class_1059$class_4007)
[19:04:50] [main/INFO]: Smooth Boot config initialized
[19:04:51] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath: [jar:file:/C:/Users/notpi/AppData/Roaming/.minecraft/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar!/oshi.properties, jar:file:/C:/Users/notpi/AppData/Roaming/.minecraft/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar!/oshi.properties]
[19:04:51] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath: [jar:file:/C:/Users/notpi/AppData/Roaming/.minecraft/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar!/oshi.architecture.properties, jar:file:/C:/Users/notpi/AppData/Roaming/.minecraft/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar!/oshi.architecture.properties]
[19:04:52] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.10.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2358.method_10199(class_2358.java:325) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[fabric-loader-0.14.10-1.19.3-pre2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.10-1.19.3-pre2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
	... 2 more
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at java.lang.Class.getDeclaredField(Class.java:2602) ~[?:?]
	at malte0811.ferritecore.impl.BlockStateCacheImpl.lambda$static$1(BlockStateCacheImpl.java:36) ~[ferritecore-5.0.3-fabric.jar:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar:?]
	at malte0811.ferritecore.impl.BlockStateCacheImpl.deduplicateCachePre(BlockStateCacheImpl.java:56) ~[ferritecore-5.0.3-fabric.jar:?]
	at net.minecraft.class_4970$class_4971.handler$zjn000$cacheStateHead(class_4970.java:1193) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1132) ~[client-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:325) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[fabric-loader-0.14.10-1.19.3-pre2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.10-1.19.3-pre2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
	... 2 more

**Comment by Technici4n** [comment]
Looks like a ferrite core issue. Make sure you use a version compatible with 1.19.3 (if it exists at all).

**Comment by ghost** [comment]
> Looks like a ferrite core issue. Make sure you use a version compatible with 1.19.3 (if it exists at all).

I removed FerriteCore from my mods folder, still the same issue. I have found that it is an active issue for FerriteCore. [Issue](https://github.com/malte0811/FerriteCore/issues/98)
