### ISSUE TITLE
[Suggestion] remove error Block

### ISSUE THREAD

**Issue by 1a2s3d4f1** [FabricMC/fabric#276]
If a error block in map,fabric will not remove it  The game is crash  
Add  remove error block entity and block entity config  
There config default: false

could you add a command （/fabric tps）to show server tps? 
forge tps command:
`Dim  0 (overworld) : Mean tick time: 0.590 ms. Mean TPS: 20.000`

some crash log
--------------------------------
`Description: Ticking block entity

java.lang.NoClassDefFoundError: alexiil.mc.lib.attributes.item.impl.PartialInventoryFixedWrapper
	at com.hrznstudio.galacticraft.blocks.machines.compressor.CompressorBlock.method_10123(CompressorBlock.java:39)
	at net.minecraft.class_2818.method_12208(class_2818.java:393)
	at net.minecraft.class_2818.method_12201(class_2818.java:416)
	at net.minecraft.class_1937.method_8321(class_1937.java:825)
	at com.hrznstudio.galacticraft.blocks.special.aluminumwire.WireUtils.getAdjacentWires(WireUtils.java:110)
	at com.hrznstudio.galacticraft.blocks.special.aluminumwire.WireNetwork.blockPlacedLogic(WireNetwork.java:87)
	at com.hrznstudio.galacticraft.blocks.special.aluminumwire.WireNetwork.blockPlaced(WireNetwork.java:81)
	at com.hrznstudio.galacticraft.api.entity.WireBlockEntity.onPlaced(WireBlockEntity.java:24)
	at com.hrznstudio.galacticraft.blocks.special.aluminumwire.AluminumWireBlockEntity.method_16896(AluminumWireBlockEntity.java:19)
	at net.minecraft.class_1937.method_18471(class_1937.java:625)
	at net.minecraft.class_3218.method_18765(class_3218.java:402)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:827)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:764)
	at net.minecraft.class_1132.method_3748(class_1132.java:128)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632)
	at java.lang.Thread.run(Thread.java:813)
Caused by: java.lang.ClassNotFoundException: alexiil.mc.lib.attributes.item.impl.PartialInventoryFixedWrapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:591)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:946)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:891)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:874)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:874)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.hrznstudio.galacticraft.blocks.machines.compressor.CompressorBlock.method_10123(CompressorBlock.java:39)
	at net.minecraft.class_2818.method_12208(class_2818.java:393)
	at net.minecraft.class_2818.method_12201(class_2818.java:416)
	at net.minecraft.class_1937.method_8321(class_1937.java:825)
	at com.hrznstudio.galacticraft.blocks.special.aluminumwire.WireUtils.getAdjacentWires(WireUtils.java:110)
	at com.hrznstudio.galacticraft.blocks.special.aluminumwire.WireNetwork.blockPlacedLogic(WireNetwork.java:87)
	at com.hrznstudio.galacticraft.blocks.special.aluminumwire.WireNetwork.blockPlaced(WireNetwork.java:81)
	at com.hrznstudio.galacticraft.api.entity.WireBlockEntity.onPlaced(WireBlockEntity.java:24)
	at com.hrznstudio.galacticraft.blocks.special.aluminumwire.AluminumWireBlockEntity.method_16896(AluminumWireBlockEntity.java:19)
`

**Comment by Chocohead** [comment]
Whilst your crash will most likely be fixed from adding [AlexIIL's Lib Block Attritbutes](https://github.com/AlexIIL/LibBlockAttributes/releases), if you reach the point where a world is completely trapped in a crash loop there is [Lettuce Not Crash](https://minecraft.curseforge.com/projects/lettuce-not-crash) which is a small mod which acts like your suggested config option turned on.

TPS has already been suggested (by yourself no less) in #268
