### ISSUE TITLE
It failed to start the Fabric Server

### ISSUE THREAD

**Issue by L0ckLi** [FabricMC/fabric#2765]
Hello, i am trying to start Fabric server on 1.18.2, when I start it , it crashed 
Here's the log 
[23:10:41] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.11
[23:10:41] [ForkJoinPool-1-worker-2/WARN]: Mod com_github_isaiahpatton_specialsource uses the version master-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'master'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[23:10:41] [main/INFO]: Loading 47 mods:
	- cardboard 59
	- carpet 1.4.65
	- carpet-extra 1.4.72
	- com_github_isaiahpatton_specialsource master-SNAPSHOT via cardboard
	- fabric-api 0.67.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric-api
	- fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric-api
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric-api
	- fabric-block-api-v1 1.0.0+ee3621fc60 via fabric-api
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric-api
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric-api
	- fabric-containers-v0 0.1.23+d7c144a860 via fabric-api
	- fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric-api
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric-api
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric-api
	- fabric-data-generation-api-v1 3.0.2+9fcb91d260 via fabric-api
	- fabric-dimensions-v1 2.1.20+489d6f8260 via fabric-api
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric-api
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric-api
	- fabric-events-lifecycle-v0 0.2.20+d7c144a860 via fabric-api
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric-api
	- fabric-item-api-v1 1.6.0+d8cf4e5a60 via fabric-api
	- fabric-item-groups-v0 0.3.14+91896a4960 via fabric-api
	- fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric-api
	- fabric-loot-api-v2 1.1.0+1997ad1260 via fabric-api
	- fabric-loot-tables-v1 1.1.2+e747827960 via fabric-api
	- fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric-api
	- fabric-networking-api-v1 1.0.23+2d30af4b60 via fabric-api
	- fabric-networking-v0 0.3.10+b4f4f6cd60 via fabric-api
	- fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric-api
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric-api
	- fabric-registry-sync-v0 0.9.11+bb2e047760 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.8+ee3621fc60 via fabric-api
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric-api
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric-api
	- fabric-screen-handler-api-v1 1.2.2+1f6558e860 via fabric-api
	- fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric-api
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric-api
	- fabricloader 0.14.11
	- icommon 1.18
	- java 17
	- magiclib 0.5.37
	- magiclib-1_18_2 0.5.37 via magiclib
	- minecraft 1.18.2
	- more-statistics 2.2.0
	- syncmatica 1.18.2-0.3.2
[23:10:41] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/User/Documents/Minecraft/Minecraft%20Server/1.18.2%20Fabric/%e6%96%b0%e5%a2%9e%e8%b3%87%e6%96%99%e5%a4%be/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[23:10:42] [main/INFO]: Compatibility level set to JAVA_16
[23:10:42] [main/INFO]: Compatibility level set to JAVA_17
[23:10:42] [main/INFO]: Please wait, Scanning plugins for events...
[23:10:43] [main/INFO]: Found: 45 (Took: 1288ms)
[23:10:43] [main/INFO]: Loading Libraries...
[23:10:43] [main/INFO]: Debug: Loading library paper-api-1.17-dev.jar
[23:10:43] [main/INFO]: Debug: Loading library sqlite-jdbc-3.21.0.1.jar
[23:10:43] [main/INFO]: Debug: Loading library mysql-connector-java-5.1.46.jar
[23:10:43] [main/INFO]: Debug: Loading library commons-lang-2.6.jar
[23:10:43] [main/INFO]: Debug: Loading library commons-collections4-4.4.jar
[23:10:43] [main/INFO]: Debug: Loading library commons-collections-3.2.1.jar
[23:10:44] [main/INFO]: =======================================================
[23:10:44] [main/INFO]:  iCommon - Isaiah's common library for mods.
[23:10:44] [main/INFO]:  Copyright (c) 2018-2021 by Isaiah. Running on MC 1.18.2
[23:10:44] [main/INFO]: =======================================================
[23:10:44] [main/INFO]: Applying mixin: MixinMinecraftServer...
[23:10:44] [main/INFO]: Applying mixin: R1_18.MixinEntity...
[23:10:44] [main/INFO]: Applying mixin: R1_18.MixinPlayer...
[23:10:44] [main/INFO]: Applying mixin: R1_18.MixinBlockEntity...
[23:10:44] [main/INFO]: Applying mixin: R1_18.MixinChestBlockEntity...
[23:10:44] [main/INFO]: Applying mixin: R1_18.MixinCampfireBlockEntity...
[23:10:44] [main/INFO]: Applying mixin: R1_18.MixinScreenHandler...
[23:10:44] [main/INFO]: Applying mixin: R1_18.MixinChunkGenerator...
[23:10:44] [main/INFO]: Applying mixin: R1_18.MixinPersistentStateManager...
[23:10:44] [main/INFO]: Applying mixin: R1_18.MixinPlayerManager...
[23:10:44] [main/INFO]: Applying mixin: R1_18.MixinHeighttmap...
[23:10:44] [main/INFO]: Applying mixin: R1_18.MixinWorld_18...
[23:10:46] [main/WARN]: Failed to add PDH Counter: \Paging File(_Total)\% Usage, Error code: 0xC0000BB8
[23:10:46] [main/WARN]: Failed to add counter for PDH counter: \Paging File(_Total)\% Usage
[23:10:46] [main/WARN]: Disabling further attempts to query Paging File.
[23:10:47] [main/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[23:10:54] [main/INFO]: Added custom statistic minecraft:break_bedrock
[23:10:54] [main/INFO]: Added custom statistic minecraft:ender_pearl_one_cm
[23:10:54] [main/INFO]: Added custom statistic minecraft:firework_boost
[23:10:54] [main/INFO]: Added custom statistic minecraft:mend_durability
[23:10:54] [main/INFO]: Added custom statistic minecraft:summon_phantom
[23:10:54] [main/INFO]: More Statistics enabled with 5 new statistics
[23:10:56] [main/INFO]: 
[23:10:56] [main/INFO]: Cardboard - CardboardPowered.org
[23:10:56] [main/INFO]: 
[23:10:56] [main/INFO]: Registered '6' iCommon events.
[23:10:57] [main/INFO]: Reflection working: false
[23:10:57] [main/INFO]: Cardboard mod Loaded.
[23:10:58] [main/INFO]: iCommon Mod initialized.
[23:10:58] [main/INFO]: [MagicLib for 1.18.2]: Mod initialized - Version: 0.5.37
[23:10:58] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-networking-v0'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.11.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.11.jar:?]
	Suppressed: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3244 failed
		at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$1(ServerPlayConnectionEvents.java:35) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-525c81630e392b81.jar:?]
		at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:57) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
		at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:53) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
		at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:44) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
		at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:63) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
		at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.<clinit>(ServerPlayConnectionEvents.java:35) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-525c81630e392b81.jar:?]
		at net.fabricmc.fabric.impl.registry.sync.FabricRegistryInit.onInitialize(FabricRegistryInit.java:29) ~[fabric-registry-sync-v0-0.9.11+bb2e047760-fbb275649c664f8f.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.11.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.11.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.11.jar:?]
		at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.11.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.11.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.11.jar:?]
		at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.11.jar:?]
	Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3244 failed
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.11.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.11.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.11.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.11.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
		... 15 more
	Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.11.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.11.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.11.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.11.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
		... 15 more
	Caused by: org.spongepowered.asm.util.throwables.LVTGeneratorError: Could not locate method metadata for method_31286 generating LVT in net/minecraft/class_3244
		at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:336) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.preInject(CallbackInjector.java:479) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at org.spongepowered.asm.mixin.injection.code.Injector.preInject(Injector.java:258) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.preInject(InjectionInfo.java:436) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1371) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.11.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.11.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.11.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.11.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
		... 15 more
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3244 failed
	at net.fabricmc.fabric.api.networking.v1.S2CPlayChannelEvents.lambda$static$1(S2CPlayChannelEvents.java:36) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-525c81630e392b81.jar:?]
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:57) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:53) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
	at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:44) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
	at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:63) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
	at net.fabricmc.fabric.api.networking.v1.S2CPlayChannelEvents.<clinit>(S2CPlayChannelEvents.java:36) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-525c81630e392b81.jar:?]
	at net.fabricmc.fabric.impl.networking.OldNetworkingHooks.onInitialize(OldNetworkingHooks.java:27) ~[fabric-networking-v0-0.3.10+b4f4f6cd60-8c59cd6ca5b10e37.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.11.jar:?]
	... 7 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3244 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.fabric.api.networking.v1.S2CPlayChannelEvents.lambda$static$1(S2CPlayChannelEvents.java:36) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-525c81630e392b81.jar:?]
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:57) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:53) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
	at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:44) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
	at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:63) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
	at net.fabricmc.fabric.api.networking.v1.S2CPlayChannelEvents.<clinit>(S2CPlayChannelEvents.java:36) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-525c81630e392b81.jar:?]
	at net.fabricmc.fabric.impl.networking.OldNetworkingHooks.onInitialize(OldNetworkingHooks.java:27) ~[fabric-networking-v0-0.3.10+b4f4f6cd60-8c59cd6ca5b10e37.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.11.jar:?]
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.fabric.api.networking.v1.S2CPlayChannelEvents.lambda$static$1(S2CPlayChannelEvents.java:36) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-525c81630e392b81.jar:?]
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:57) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:53) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
	at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:44) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
	at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:63) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
	at net.fabricmc.fabric.api.networking.v1.S2CPlayChannelEvents.<clinit>(S2CPlayChannelEvents.java:36) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-525c81630e392b81.jar:?]
	at net.fabricmc.fabric.impl.networking.OldNetworkingHooks.onInitialize(OldNetworkingHooks.java:27) ~[fabric-networking-v0-0.3.10+b4f4f6cd60-8c59cd6ca5b10e37.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.11.jar:?]
	... 7 more
Caused by: org.spongepowered.asm.util.throwables.LVTGeneratorError: Could not locate method metadata for method_31286 generating LVT in net/minecraft/class_3244
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:336) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.preInject(CallbackInjector.java:479) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.preInject(Injector.java:258) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.preInject(InjectionInfo.java:436) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1371) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.fabric.api.networking.v1.S2CPlayChannelEvents.lambda$static$1(S2CPlayChannelEvents.java:36) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-525c81630e392b81.jar:?]
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:57) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:53) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
	at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:44) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
	at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:63) ~[fabric-api-base-0.4.4+d7c144a860-45f497f00c102704.jar:?]
	at net.fabricmc.fabric.api.networking.v1.S2CPlayChannelEvents.<clinit>(S2CPlayChannelEvents.java:36) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-525c81630e392b81.jar:?]
	at net.fabricmc.fabric.impl.networking.OldNetworkingHooks.onInitialize(OldNetworkingHooks.java:27) ~[fabric-networking-v0-0.3.10+b4f4f6cd60-8c59cd6ca5b10e37.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.11.jar:?]
	... 7 more

**Comment by apple502j** [comment]
While the log says Fabric API is crashing, it is unlikely that it is the real cause.

Can you try removing cardboard?
