### ISSUE TITLE
Error when connecting to servers with Paper plugin installed

### ISSUE THREAD

**Issue by Datsjive** [FabricMC/fabric#278]
I server I play on recently installed Paper, and now attempting to connect to the main server returns 'failed to validate multiplayer chunk data: 0x3cff0da'.

**Comment by Boundarybreaker** [comment]
Is there any further log?

**Comment by Datsjive** [comment]
The server in question uses a multiworld system, so attempts to enter the main world leave the error I listed before kicking you back to the waiting room. I am unaware of how a log can be recovered from this scenario.

**Comment by asiekierka** [comment]
Any reproduction route for us?

**Comment by SquirrelKiev** [comment]
Hi, get this same issue on MultiMC. Here's an error log if that helps. 

```
[08:58:11] [main/ERROR]: Writing packet:
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@5ace491 rejected from java.util.concurrent.ThreadPoolExecutor@7a2b0101[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1000]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.AbstractExecutorService.submit(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Unknown Source) ~[?:1.8.0_221]
	at com.replaymod.recording.packet.PacketListener.saveMetaData(PacketListener.java:117) ~[replaymod-1.14.4-2.2.0-b7.jar:?]
	at com.replaymod.recording.packet.PacketListener.save(PacketListener.java:154) ~[replaymod-1.14.4-2.2.0-b7.jar:?]
	at com.replaymod.recording.handler.RecordingEventHandler.onPlayerJoin(RecordingEventHandler.java:87) ~[replaymod-1.14.4-2.2.0-b7.jar:?]
	at net.minecraft.class_634.handler$recordOwnJoin$zgl000(class_634.java:3329) ~[intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_634.method_11113(class_634.java) ~[intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_2703.method_11721(class_2703.java:153) ~[intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_2703.method_11054(class_2703.java:18) ~[intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:33) ~[intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:170) [intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:135) [intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) [intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:915) [intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:410) [intermediary-minecraft-1.14.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) [intermediary-minecraft-1.14.4-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178) [fabric-loader-0.6.2+build.166.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131) [fabric-loader-0.6.2+build.166.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.6.2+build.166.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

```

**Comment by i509VCB** [comment]
Could anyone provide the name of the plugin used for multi world on paper? I was going to test it a bit.

**Comment by YanisBft** [comment]
@i509VCB https://dev.bukkit.org/projects/multiverse-core

**Comment by i509VCB** [comment]
Closing due to lack of feedback. If this is still an issue, please open a new issue with reproduction steps.
