### ISSUE TITLE
Crash game with fabric-api-0.3.0+build.185

### ISSUE THREAD

**Issue by Timmmy001** [FabricMC/fabric#280]
Crash game:
fabric-api-0.3.0+build.185.jar
fabric-loader-1.14.3-pre4+build2

I hope is help you at your development.

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 23.06.19 12:12
Description: Starting integrated server

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:179)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:142)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:223)
at net.minecraft.class_1132.<init>(class_1132.java:52)
at net.minecraft.class_310.method_1559(class_310.java:1603)
at net.minecraft.class_528$class_4272.method_20174(class_528.java:380)
at net.minecraft.class_528$class_4272.method_20164(class_528.java:311)
at net.minecraft.class_528$class_4272.mouseClicked(class_528.java:257)
at net.minecraft.class_350.mouseClicked(class_350.java:322)
at net.minecraft.class_4069.mouseClicked(class_4069.java:27)
at net.minecraft.class_312.method_1611(class_312.java:86)
at net.minecraft.class_312$$Lambda$1865/1492905182.run(Unknown Source)
at net.minecraft.class_437.wrapScreenError(class_437.java:441)
at net.minecraft.class_312.method_1601(class_312.java:86)
at net.minecraft.class_312$$Lambda$1554/1506480352.invoke(Unknown Source)
at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
at org.lwjgl.system.JNI.invokeV(Native Method)
at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
at net.minecraft.class_1041.method_16001(class_1041.java:425)
at net.minecraft.class_1041.method_15998(class_1041.java:283)
at net.minecraft.class_310.method_15994(class_310.java:1023)
at net.minecraft.class_310.method_1523(class_310.java:976)
at net.minecraft.class_310.method_1514(class_310.java:411)
at net.minecraft.client.main.Main.main(Main.java:154)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-loot-tables-v1.mixins.json:MixinLootManager] from phase [DEFAULT] in config [fabric-loot-tables-v1.mixins.json] FAILED during APPLY
at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
... 32 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Inject annotation on handler$apply$zbc000 could not find any targets matching 'method_14491' in the target class net.minecraft.class_60. Using refmap fabric-loot-tables-v1-refmap.json
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:421)
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:172)
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:159)
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:151)
at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:44)
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:472)
at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1180)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:930)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:318)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281)
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
... 32 more

 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:179)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:142)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:223)
at net.minecraft.class_1132.<init>(class_1132.java:52)

-- Starting integrated server --
Details:
Level ID: Neue Welt_1_14_3
Level Name: Neue Welt_1.14.3
Stacktrace:
at net.minecraft.class_310.method_1559(class_310.java:1603)
at net.minecraft.class_528$class_4272.method_20174(class_528.java:380)
at net.minecraft.class_528$class_4272.method_20164(class_528.java:311)
at net.minecraft.class_528$class_4272.mouseClicked(class_528.java:257)
at net.minecraft.class_350.mouseClicked(class_350.java:322)
at net.minecraft.class_4069.mouseClicked(class_4069.java:27)
at net.minecraft.class_312.method_1611(class_312.java:86)
at net.minecraft.class_312$$Lambda$1865/1492905182.run(Unknown Source)

-- Affected screen --
Details:
Screen name: net.minecraft.class_526
Stacktrace:
at net.minecraft.class_437.wrapScreenError(class_437.java:441)
at net.minecraft.class_312.method_1601(class_312.java:86)
at net.minecraft.class_312$$Lambda$1554/1506480352.invoke(Unknown Source)
at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
at org.lwjgl.system.JNI.invokeV(Native Method)
at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
at net.minecraft.class_1041.method_16001(class_1041.java:425)
at net.minecraft.class_1041.method_15998(class_1041.java:283)
at net.minecraft.class_310.method_15994(class_310.java:1023)
at net.minecraft.class_310.method_1523(class_310.java:976)
at net.minecraft.class_310.method_1514(class_310.java:411)
at net.minecraft.client.main.Main.main(Main.java:154)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
Minecraft Version: 1.14.3 Pre-Release 4
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1460024528 bytes (1392 MB) / 1979711488 bytes (1888 MB) up to 2147483648 bytes (2048 MB)
JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
Fabric Mods:
fabric: Fabric API 0.3.0+build.185
fabric-api-base: fabric-api-base 0.1.0+59147463
fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c52
fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c52
fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+05f11b75
fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+59147463
fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+59147463
fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+59147463
fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+59147463
fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c
fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0
fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+59147463
fabric-models-v0: fabric-models-v0 0.1.0+59147463
fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c52
fabric-networking-v0: fabric-networking-v0 0.1.2+200eb5c2
fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9fe2f882
fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+baba33ba
fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.0+02a46d5b
fabric-renderer-indigo: fabric-renderer-indigo 0.1.7+029ec62e
fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b
fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c2
fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e
fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+59147463
fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+c189dc5c
fabric-textures-v0: fabric-textures-v0 0.1.4+792c1c35
fabricloader: Fabric Loader 0.4.8+build.155
Launched Version: fabric-loader-0.4.8+build.155-1.14.3-pre4+build.2
LWJGL: 3.2.2 build 10
OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.86, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fabric'
Type: Client (map_client.txt)
Resource Packs: vanilla, file/Ozocraft 1.14 BETA.zip
Current Language: Deutsch (Deutschland)
CPU: 16x AMD Ryzen 7 1700X Eight-Core Processor

**Comment by MrPurple6411** [comment]
Fabric api 185 does not work with 1.14.3


Use 181as it works fine.

**Comment by MrPurple6411** [comment]
Loot tables system got changed in the api at 182 for 1.14.2 then became incompatible with the new changes made in 1.14.3

**Comment by asiekierka** [comment]
Fixed in 1.14.3 API builds.
