### ISSUE TITLE
Cannot start game using Fabric 0.14.12 and Minecraft 1.19.3

### ISSUE THREAD

**Issue by logandhillon** [FabricMC/fabric#2853]
I have been programming a Fabric-based mod, and have reached a roadblock. The game crashes **immediately** after booting. I have tried practically everything, and all help is appreciated.

I'm pretty sure that this is a Fabric issue and not my mod, as I cleared my onInitialize() method, and nothing changed.

Here is my log:
```log
[17:36:20] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[17:36:20] [main/INFO] (FabricLoader) Loading 46 mods:
	- fabric-api 0.72.0+1.19.3
	- fabric-api-base 0.4.20+afca2f3e85
	- fabric-api-lookup-api-v1 1.6.19+49abcf7e85
	- fabric-biome-api-v1 12.1.0+b5d379b085
	- fabric-block-api-v1 1.0.4+e022e5d185
	- fabric-blockrenderlayer-v1 1.1.29+c6af733c85
	- fabric-client-tags-api-v1 1.0.11+1134c5b885
	- fabric-command-api-v2 2.2.0+3fc4752e85
	- fabric-content-registries-v0 3.5.0+1d37d50285
	- fabric-convention-tags-v1 1.2.1+8e4e694f85
	- fabric-crash-report-info-v1 0.2.13+aeb40ebe85
	- fabric-data-generation-api-v1 11.1.4+1134c5b885
	- fabric-dimensions-v1 2.1.40+48349a3f85
	- fabric-entity-events-v1 1.5.6+b83334a085
	- fabric-events-interaction-v0 0.4.39+3baeb27a85
	- fabric-game-rule-api-v1 1.0.29+99f9db8085
	- fabric-gametest-api-v1 1.1.16+1134c5b885
	- fabric-item-api-v1 2.1.8+1134c5b885
	- fabric-item-group-api-v1 2.1.11+1134c5b885
	- fabric-key-binding-api-v1 1.0.30+bc01e09785
	- fabric-lifecycle-events-v1 2.2.9+23a79c8a85
	- fabric-loot-api-v2 1.1.19+75e9821185
	- fabric-message-api-v1 5.0.13+6ede1da985
	- fabric-mining-level-api-v1 2.1.30+49abcf7e85
	- fabric-models-v0 0.3.26+11ba9c3b85
	- fabric-networking-api-v1 1.2.16+4017a8cb85
	- fabric-object-builder-api-v1 5.3.0+85f102ee85
	- fabric-particles-v1 1.0.19+f1e4495b85
	- fabric-recipe-api-v1 1.0.0+5176f73d85
	- fabric-registry-sync-v0 2.0.4+1134c5b885
	- fabric-renderer-api-v1 2.2.0+9f179aa185
	- fabric-renderer-indigo 0.7.0+9f179aa185
	- fabric-rendering-data-attachment-v1 0.3.24+afca2f3e85
	- fabric-rendering-fluids-v1 3.0.17+f1e4495b85
	- fabric-rendering-v1 1.12.0+6dc0edd785
	- fabric-resource-conditions-api-v1 2.2.2+1134c5b885
	- fabric-resource-loader-v0 0.10.4+a91e48b785
	- fabric-screen-api-v1 1.0.40+f1e4495b85
	- fabric-screen-handler-api-v1 1.3.12+99f9db8085
	- fabric-sound-api-v1 1.0.7+75e9821185
	- fabric-transfer-api-v1 2.1.14+ccd377ba85
	- fabric-transitive-access-wideners-v1 2.3.0+5b9a588b85
	- fabricloader 0.14.12
	- java 17
	- minecraft 1.19.3
	- mo_food 0.5-BETA+1.19.3
[17:36:21] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Logan/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/c1dc27696aa4006e492c2485c9ccbcb26045a971/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:36:21] [main/INFO] (FabricLoader/Mixin) Loaded Fabric development mappings for mixin remapper!
[17:36:21] [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_16
[17:36:21] [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_17
[17:36:29] [main/INFO] (Minecraft) Building optimized datafixer
[17:36:36] [Render thread/INFO] (Minecraft) Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:36:36] [Render thread/ERROR] (Minecraft) Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.16.29.jar:?]
	at net.minecraft.client.MinecraftClient.createUserApiService(MinecraftClient.java:709) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:504) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:185) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:56) ~[minecraft-project-@-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:87) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.16.29.jar:?]
	... 10 more
[17:36:36] [Render thread/INFO] (Minecraft) Setting user: Player838
[17:36:37] [Render thread/INFO] (Indigo) [Indigo] Registering Indigo renderer!
[17:36:38] [Render thread/INFO] (Minecraft) Backend library: LWJGL version 3.3.1 SNAPSHOT
[17:36:44] [Render thread/INFO] (Minecraft) Narrator library for x64 successfully loaded
[17:36:45] [Render thread/INFO] (Minecraft) Reloading ResourceManager: vanilla, Fabric Mods (Fabric Loader, Fabric Rendering Data Attachment (v1), Fabric Game Test API (v1), Fabric Key Binding API (v1), Fabric Renderer - Indigo, Fabric Object Builder API (v1), Fabric Resource Loader (v0), Fabric Models (v0), Fabric Screen API (v1), Fabric Dimensions API (v1), Fabric Item API (v1), Mo' Food, Fabric Content Registries (v0), Fabric API Lookup API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Sound API (v1), Fabric Transfer API (v1), Fabric Game Rule API (v1), Fabric Particles (v1), Fabric Screen Handler API (v1), Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric API Base, Fabric Biome API (v1), Fabric Client Tags, Fabric Recipe API (v1), Fabric Rendering Fluids (v1), Fabric Transitive Access Wideners (v1), Fabric Events Interaction (v0), Fabric Rendering (v1), Fabric Entity Events (v1), Fabric API, Fabric Loot API (v2), Fabric Item Group API (v1), Fabric Convention Tags, Fabric Lifecycle Events (v1), Fabric Networking API (v1), Fabric Resource Conditions API (v1), Fabric Command API (v2), Fabric Block API (v1), Fabric Renderer API (v1), Fabric Message API (v1), Fabric Registry Sync (v0), Fabric Mining Level API (v1))
[17:36:45] [Render thread/ERROR] (Minecraft) Unhandled game exception
java.lang.IllegalStateException: Some intrusive holders were not registered: [Reference{null=air}, Reference{null=air}]
	at net.minecraft.registry.SimpleRegistry.freeze(SimpleRegistry.java:358) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.registry.Registries.freezeRegistries(Registries.java:227) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.registry.Registries.bootstrap(Registries.java:212) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.handler$zjj001$onStart(MinecraftClient.java:5272) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:743) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:220) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:56) ~[minecraft-project-@-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
[17:36:45] [Render thread/INFO] (Minecraft) Stopping!
[17:36:45] [Realms Notification Availability checker #1/INFO] (Minecraft) Could not authorize you against Realms server: Invalid session id
[17:36:46] [Worker-Main-8/WARN] (Minecraft) Exception loading blockstate definition: 'mo_food:blockstates/cheese_pizza.json' missing model for variant: 'mo_food:cheese_pizza#bites=4'
[17:36:46] [Worker-Main-8/WARN] (Minecraft) Exception loading blockstate definition: 'mo_food:blockstates/cheese_pizza.json' missing model for variant: 'mo_food:cheese_pizza#bites=6'
[17:36:46] [Worker-Main-8/WARN] (Minecraft) Exception loading blockstate definition: 'mo_food:blockstates/cheese_pizza.json' missing model for variant: 'mo_food:cheese_pizza#bites=5'
[17:36:46] [Worker-Main-8/WARN] (Minecraft) Exception loading blockstate definition: 'mo_food:blockstates/pepperoni_pizza.json' missing model for variant: 'mo_food:pepperoni_pizza#bites=6'
[17:36:46] [Worker-Main-8/WARN] (Minecraft) Exception loading blockstate definition: 'mo_food:blockstates/pepperoni_pizza.json' missing model for variant: 'mo_food:pepperoni_pizza#bites=5'
[17:36:46] [Worker-Main-8/WARN] (Minecraft) Exception loading blockstate definition: 'mo_food:blockstates/pepperoni_pizza.json' missing model for variant: 'mo_food:pepperoni_pizza#bites=4'
[17:36:48] [Render thread/ERROR] (Minecraft) Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.client.texture.TextureManager.close(TextureManager.java:173) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.close(MinecraftClient.java:1041) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.stop(MinecraftClient.java:1015) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:56) ~[minecraft-project-@-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]```

**Comment by apple502j** [comment]
Make sure you register all instances of Block, Item, etc, and do not call those constructors unless you register them immediately.

**Comment by Daomephsta** [comment]
See #2394 for an explanation of the problem and how to fix it.
An empty `onInitialize()` does not mean your mod does nothing.  
If you create new Item instances and assign them to static fields in your ModInitializer, that code runs when Fabric loads your ModInitializer, not when `onInitialize()` is called.
