### ISSUE TITLE
Crash on start 1.14.3

### ISSUE THREAD

**Issue by paulthetic** [FabricMC/fabric#287]
No idea what's going on, any help is appreciated. Thought Optifine would be working fine now with the update.

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 7/3/19 4:44 PM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:179)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_761.<init>(class_761.java:285)
	at net.minecraft.class_310.method_1503(class_310.java:570)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method handler$rebuildChunk$zbk000(FFFLnet/minecraft/class_842;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_849;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;Lnet/minecraft/class_852;Ljava/util/Set;Lnet/minecraft/class_853;[ZLjava/util/Random;Lnet/minecraft/class_776;Ljava/util/Iterator;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lnet/minecraft/class_2248;Lnet/minecraft/class_1921;)V in demesne.common.json:ChunkRendererMixin failed injection check, (0/1) succeeded. Using refmap demesne-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1203)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:939)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:323)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:179)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_761.<init>(class_761.java:285)
	at net.minecraft.class_310.method_1503(class_310.java:570)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1377663192 bytes (1313 MB) / 2382364672 bytes (2272 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 10 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx4096M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		blue_endless_jankson: jankson 1.1.2
		cloth: Cloth Events 0.3.1+build.23
		cloth-config2: Cloth Config v2 0.3.1
		cosmeticarmorslots: Cosmetic Armor Slots 1.1.2
		cotton: Cotton 0.8.3-pre+1.14.3
		crochet: Crochet 1.0.4
		demesne: Demesne 1.14.2-2.2.5-FABRIC
		durabilityviewer: Giselbaers Durability Viewer 1.14-fabric0.2.7-1.5
		fabric: Fabric API 0.3.0+build.188
		fabric-api-base: fabric-api-base 0.1.0+59147463
		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb
		fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c52
		fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c52
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+05f11b75
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+59147463
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+59147463
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+59147463
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+f0d56800
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+43028fa6
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+bdffbb2c
		fabric-models-v0: fabric-models-v0 0.1.0+59147463
		fabric-networking: fabric-networking 0.1.0+93af775a
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c52
		fabric-networking-v0: fabric-networking-v0 0.1.2+200eb5c2
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+39ff57de
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+f0d56800
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.0+02a46d5b
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.7+029ec62e
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c2
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+59147463
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+c189dc5c
		fabric-textures-v0: fabric-textures-v0 0.1.4+792c1c35
		fabricloader: Fabric Loader 0.4.8+build.155
		fermion: Fermion 0.6.3+build.37
		gbfabrictools: GBfabrictools 1.0.0
		inca: Inca 1.0.4
		inventorysorter: Inventory Sorter 1.2.2
		libcd: LibCapableData 1.2.1+1.14.3
		mm: Manningham Mills 1.6
		modmenu: Mod Menu 1.6.2-92
		net_fabricmc_stitch: stitch 0.2.1.61
		optifabric: Optifabric 0.3.2
		org_slf4j_slf4j-api: slf4j-api 1.7.26
		org_slf4j_slf4j-simple: slf4j-simple 1.7.26
		org_zeroturnaround_zt-zip: zt-zip 1.13
		roughlyenoughitems: Roughly Enough Items 2.9.6+build.135
		tbo: TheBiomeOverhaul 1.2.0
		trees-do-not-float: Trees Do Not Float 1.2.0+build.25
		voxelmap: VoxelMap 1.9.11
		wildworld: Wild World 1.0.0
	Launched Version: 1.14.3
	LWJGL: 3.2.2 build 10
	OpenGL: AMD Radeon HD 7600G GL version 4.5.13399 Compatibility Profile Context 15.200.1065.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x AMD A8-4555M APU with Radeon(tm) HD Graphics 
	OptiFine Version: OptiFine_1.14.3_HD_U_F1
	OptiFine Build: 20190628-120456
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.200.1065.0
	OpenGlRenderer: AMD Radeon HD 7600G
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by liach** [comment]
update demesne mod.
