### ISSUE TITLE
game crash on loading world munu 1.19.4 fabric api 23w05a log below

### ISSUE THREAD

**Issue by Danjhop4** [FabricMC/fabric#2882]
---- Minecraft Crash Report ----
// My bad.

Time: 2023-02-02 17:44:55
Description: Rendering screen

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_525 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_528.method_43454(class_528.java:163)
	at net.minecraft.class_528.method_44678(class_528.java:124)
	at net.minecraft.class_528.method_25394(class_528.java:115)
	at net.minecraft.class_526.method_25394(class_526.java:118)
	at net.minecraft.class_437.method_47413(class_437.java:121)
	at net.minecraft.class_757.method_3192(class_757.java:929)
	at net.minecraft.class_310.method_1523(class_310.java:1200)
	at net.minecraft.class_310.method_1514(class_310.java:789)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 17 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-resource-loader-v0.client.mixins.json:CreateWorldScreenMixin from mod fabric-resource-loader-v0] from phase [DEFAULT] in config [fabric-resource-loader-v0.client.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 20 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onScanPacks could not find any targets matching 'Lnet/minecraft/class_525;method_30296()Lcom/mojang/datafixers/util/Pair;' in net.minecraft.class_525. Using refmap client-fabric-resource-loader-v0-refmap.json [PREINJECT Applicator Phase -> fabric-resource-loader-v0.client.mixins.json:CreateWorldScreenMixin from mod fabric-resource-loader-v0 -> Prepare Injections ->  -> handler$zij000$onScanPacks(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor60.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_528.method_43454(class_528.java:163)
	at net.minecraft.class_528.method_44678(class_528.java:124)
	at net.minecraft.class_528.method_25394(class_528.java:115)
	at net.minecraft.class_526.method_25394(class_526.java:118)
	at net.minecraft.class_437.method_47413(class_437.java:121)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_526
	Mouse location: Scaled: (257, 117). Absolute: (514.000000, 234.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:929)
	at net.minecraft.class_310.method_1523(class_310.java:1200)
	at net.minecraft.class_310.method_1514(class_310.java:789)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2400)
	at net.minecraft.class_310.method_1514(class_310.java:808)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 23w05a
	Minecraft Version ID: 23w05a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1276784992 bytes (1217 MiB) / 1744830464 bytes (1664 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: DriverVersion=30.0.101.3111
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 22734.49
	Virtual memory used (MB): 12632.18
	Swap memory total (MB): 6656.00
	Swap memory used (MB): 108.98
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.73.2+1.19.4
			fabric-api-base: Fabric API Base 0.4.23+ae26bc35a5
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.22+49abcf7ea5
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.2+a1ccd7bfa5
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d1a5
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.32+c6af733ca5
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.14+1134c5b8a5
			fabric-command-api-v1: Fabric Command API (v1) 1.2.24+f71b366fa5
			fabric-command-api-v2: Fabric Command API (v2) 2.2.3+3fc4752ea5
			fabric-commands-v0: Fabric Commands (v0) 0.2.41+df3654b3a5
			fabric-containers-v0: Fabric Containers (v0) 0.1.49+df3654b3a5
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.3+1d37d502a5
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.4+8e4e694fa5
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebea5
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.2.2+a1ccd7bfa5
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.43+48349a3fa5
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.9+a1ccd7bfa5
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.42+a1ccd7bfa5
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.46+df3654b3a5
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.32+a1ccd7bfa5
			fabric-item-api-v1: Fabric Item API (v1) 2.1.12+28efac3da5
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.14+1134c5b8a5
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.31+bc01e097a5
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.29+df3654b3a5
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.12+23a79c8aa5
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.22+75e98211a5
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.26+9e7660c6a5
			fabric-message-api-v1: Fabric Message API (v1) 5.0.16+6ede1da9a5
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.33+49abcf7ea5
			fabric-models-v0: Fabric Models (v0) 0.3.29+11ba9c3ba5
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.19+a1ccd7bfa5
			fabric-networking-v0: Fabric Networking (v0) 0.3.36+df3654b3a5
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.2+81af046ea5
			fabric-particles-v1: Fabric Particles (v1) 1.0.22+f1e4495ba5
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.3+a1ccd7bfa5
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.7+a1ccd7bfa5
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.3+9f179aa1a5
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.3+9f179aa1a5
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.32+df3654b3a5
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.27+afca2f3ea5
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.20+f1e4495ba5
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.35+df3654b3a5
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.3+a1ccd7bfa5
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.3+1134c5b8a5
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.7+a1ccd7bfa5
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.43+f1e4495ba5
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.15+a1ccd7bfa5
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e98211a5
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.17+ccd377baa5
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.2+a1ccd7bfa5
		fabricloader: Fabric Loader 0.14.13
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.4-alpha.23.5.a
	Launched Version: fabric-loader-0.14.13-23w05a
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) Iris(R) Xe Graphics GL version 3.2.0 - Build 30.0.101.3111, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 8x 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

**Comment by modmuss50** [comment]
Update Fabric API. You are using `0.73.2+1.19.4` for 23w04a, you want `0.73.3+1.19.4` for 23w05a.

**Comment by Danjhop4** [comment]
that was non existent when i looked
