### ISSUE TITLE
Crash on startup with no specific mod named

### ISSUE THREAD

**Issue by iMoobert** [FabricMC/fabric#2886]
I just got around to updating all of my mods to their final 1.18.2 versions, and that required me updating both my fabric loader and iris as well, so I just used the most recent fabric file, 0.14.14 and created the new profile for the 1.18.2 version. I then did the same thing with iris.

I'm now getting this error message on startup and I don't know enough about coding to understand this since it isn't giving clear indicators as to what's wrong- is anyone able to help?

-----

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'quilt_command'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'quilt_command'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	... 2 more
Caused by: java.lang.ExceptionInInitializerError
	at org.quiltmc.qsl.command.impl.PreLaunchInitializer.onPreLaunch(PreLaunchInitializer.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 4 more
Caused by: java.lang.RuntimeException: Failed to load Classloader fields
	at org.quiltmc.qsl.base.impl.PreLaunchHacks.<clinit>(PreLaunchHacks.java:49)
	... 6 more
Caused by: java.lang.NoSuchMethodException: net.fabricmc.loader.impl.launch.knot.KnotClassLoader.addURL(java.net.URL)
	at java.base/java.lang.Class.getMethod(Class.java:2227)
	at org.quiltmc.qsl.base.impl.PreLaunchHacks.<clinit>(PreLaunchHacks.java:46)
	... 6 more

------

**Comment by apple502j** [comment]
Please ensure all mods are for Fabric 1.18.2. I think you have mods for other platform in it.

**Comment by iMoobert** [comment]
Ah! Yes! Thank you so much, oh my god lol

Apparently OKZoomer changed into a quilt mod and the file name wasn't changed; spent like 2 hours troubleshooting my mods individually

phew, again thank you, wouldn't have figured that out otherwise
