### ISSUE TITLE
Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by gamerpotion** [FabricMC/fabric#2924]
Hi, I noticed an update on Fabric API recenly. 
I have been running a modpack for Fabric (DarkRPG) - https://www.curseforge.com/minecraft/modpacks/darkrpg
fabric-api-0.73.2+1.19.3.jar
0.14.14

On the server, it crashes randomly with below message. Just wanted to check is this linked to Fabric API ?  I cant see any mods mentioned in the errors

```---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2023-02-22 04:57:18
Description: Accessing LegacyRandomSource from multiple threads

java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.class_5798.method_33564(class_5798.java:84)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:33)
	at net.minecraft.class_3532.method_32751(class_3532.java:946)
	at net.minecraft.class_1948.method_8657(class_1948.java:411)
	at net.minecraft.class_1948.method_8663(class_1948.java:208)
	at net.minecraft.class_1948.method_27821(class_1948.java:201)
	at net.minecraft.class_3215.method_14161(class_3215.java:377)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:322)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_5798.method_33564(class_5798.java:84)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:33)
	at net.minecraft.class_3532.method_32751(class_3532.java:946)
	at net.minecraft.class_1948.method_8657(class_1948.java:411)
	at net.minecraft.class_1948.method_8663(class_1948.java:208)
	at net.minecraft.class_1948.method_27821(class_1948.java:201)
	at net.minecraft.class_3215.method_14161(class_3215.java:377)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:322)

-- Thread dumps --
Details:
	Thread dumps: Server thread: 
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
	at net.minecraft.class_5798.method_39936(class_5798.java:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.minecraft.class_5798.method_33564(class_5798.java:82)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:33)
	at net.minecraft.class_3532.method_32751(class_3532.java:946)
	at net.minecraft.class_1948.method_8657(class_1948.java:411)
	at net.minecraft.class_1948.method_8663(class_1948.java:208)
	at net.minecraft.class_1948.method_27821(class_1948.java:201)
	at net.minecraft.class_3215.method_14161(class_3215.java:377)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:322)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Stacktrace:
	at net.minecraft.class_5798.method_33564(class_5798.java:84)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:33)
	at net.minecraft.class_3532.method_32751(class_3532.java:946)
	at net.minecraft.class_1948.method_8657(class_1948.java:411)
	at net.minecraft.class_1948.method_8663(class_1948.java:208)
	at net.minecraft.class_1948.method_27821(class_1948.java:201)
	at net.minecraft.class_3215.method_14161(class_3215.java:377)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:322)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 29 total; [class_3222['Kat_S'/271900, l='ServerLevel[world]', x=608.74, y=47.00, z=2592.70], class_3222['Richuu_kun'/350995, l='ServerLevel[world]', x=6079.56, y=73.26, z=-2588.77], class_3222['DeathDoggo5'/997, l='ServerLevel[world]', x=-759.35, y=63.00, z=5418.98], class_3222['The_Foot_Ninja'/273319, l='ServerLevel[world]', x=1452.47, y=64.00, z=-1408.69], class_3222['uterindestroyer'/370734, l='ServerLevel[world]', x=-3517.53, y=92.00, z=4257.64], class_3222['WittyVolcano63'/378175, l='ServerLevel[world]', x=-965.21, y=72.00, z=5836.32], class_3222['SlobberyAsh'/381074, l='ServerLevel[world]', x=-1020.86, y=52.00, z=6082.85], class_3222['JupiterDaBean'/40437, l='ServerLevel[world]', x=-64.51, y=66.00, z=6341.79], class_3222['NoSocksYouCreep'/224188, l='ServerLevel[world]', x=8959.63, y=58.00, z=307.58], class_3222['slazeishere'/3258, l='ServerLevel[world]', x=4877.12, y=74.49, z=6935.95], class_3222['irishguy2417'/201356, l='ServerLevel[world]', x=-1020.70, y=60.00, z=5731.70], class_3222['FuchsiaJade'/393068, l='ServerLevel[world]', x=-762.71, y=64.00, z=5421.66], class_3222['Titanya_Rose'/350662, l='ServerLevel[world]', x=-1430.67, y=39.00, z=5812.51], class_3222['R0TIS'/399230, l='ServerLevel[world]', x=580.27, y=303.05, z=-452.99], class_3222['Baconnmanz'/120022, l='ServerLevel[world]', x=-850.37, y=104.00, z=4070.39], class_3222['OtterFenic'/341001, l='ServerLevel[world]', x=-510.38, y=86.00, z=6130.59], class_3222['VinzSupreme'/402024, l='ServerLevel[world]', x=1750.91, y=65.00, z=7278.21], class_3222['venus960'/325742, l='ServerLevel[world]', x=-397.54, y=64.00, z=5588.36], class_3222['TypicalGrey'/371204, l='ServerLevel[world]', x=-1157.05, y=69.18, z=5114.36], class_3222['spencercat'/351566, l='ServerLevel[world]', x=-511.90, y=86.00, z=6129.41], class_3222['Shadowp4'/410243, l='ServerLevel[world]', x=-679.81, y=65.56, z=5992.15], class_3222['BearHugger69'/411557, l='ServerLevel[world]', x=6570.66, y=64.00, z=7919.22], class_3222['IMang_o'/385807, l='ServerLevel[world]', x=-138.66, y=155.00, z=373.69], class_3222['D3jvid'/412892, l='ServerLevel[world]', x=-512.18, y=86.00, z=6131.64], class_3222['xHexical'/194868, l='ServerLevel[world]', x=-52.71, y=67.00, z=6350.04], class_3222['Bunchalunch'/414854, l='ServerLevel[world]', x=-734.76, y=63.00, z=6006.87], class_3222['LegitimacyJinx'/329269, l='ServerLevel[world]', x=-7096.14, y=72.00, z=8725.44], class_3222['Eevee_Trainer_'/390228, l='ServerLevel[world]', x=-699.72, y=64.00, z=6007.76], class_3222['Slushy985'/355490, l='ServerLevel[world]', x=-724.50, y=63.00, z=6005.50]]
	Chunk stats: 23962
	Level dimension: minecraft:overworld
	Level spawn location: World: (-720,62,6008), Section: (at 0,14,8 in -45,3,375; chunk contains blocks -720,-64,6000 to -705,319,6015), Region: (-2,11; contains chunks -64,352 to -33,383, blocks -1024,-64,5632 to -513,319,6143)
	Level time: 973606 game time, 595299 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Linux (amd64) version 4.15.0-192-generic
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 8740248312 bytes (8335 MiB) / 12884901888 bytes (12288 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 32
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz
	Identifier: Intel64 Family 6 Model 63 Stepping 2
	Microarchitecture: Haswell (Server)
	Frequency (GHz): 3.20
	Number of physical packages: 2
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: G200eR2
	Graphics card #0 vendor: Matrox Electronics Systems Ltd. (0x102b)
	Graphics card #0 VRAM (MB): 16.00
	Graphics card #0 deviceId: 0x0534
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 137121.34
	Virtual memory used (MB): 212200.78
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 5103.34
	JVM Flags: 2 total; -Xmx12288M -Xms512M
	Fabric Mods: 
		adabranium: Adabranium 2.4.0+1.19.3
		adorn: Adorn 4.0.1+1.19.3
		advancednetherite: Advanced Netherite 1.6.6-1.19.3
		alloy_forgery: Alloy Forgery 2.0.19+1.19.3
		amethyst_core: Amethyst Core 1.0.4+1.19.3
		amethyst_imbuement: Amethyst Imbuement 1.19.3-05
			playerabilitylib: Pal 1.7.0
			structurized-reborn: Structurized Reborn 1.19.3-01
		amethystequipment: Amethyst Equipment 1.0.7
		appleskin: AppleSkin 2.4.2+mc1.19.3
		architectury: Architectury 7.1.70
		balm-fabric: Balm 5.0.2
		betteradvancements: Better Advancements 0.3.1.149
		bhmenu: BHMenu-Fabric 1.19.3-1.3
		bisecthosting: BisectHosting 1.0.3
		block_limit_fix: Block Limit Fix 1.0.3-fabric
		boatoverhaul: BoatOverhaul 2.0.0
		boneequipment: Bone Equipment 1.0.6
		bookshelf: Bookshelf 17.0.3
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.5.1-1.19.3
			maelstrom_library: Maelstrom Library 1.4-1.19.3-rc1
			multipart_entities: MultipartEntities 1.3-1.19.3-rc1
		cardinal-components: Cardinal Components API 5.1.0
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-block: Cardinal Components API (blocks) 5.1.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			cardinal-components-item: Cardinal Components API (items) 5.1.0
			cardinal-components-level: Cardinal Components API (world saves) 5.1.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.1.0
			cardinal-components-world: Cardinal Components API (worlds) 5.1.0
		castleblocks: CastleBlocks 1.21
		cinderscapes: Cinderscapes 3.1.0
			cinderscapes-common: Cinderscapes: Common 3.1.0
			cinderscapes-worldgen: Cinderscapes: World Generation 3.1.0
		clickadv: Clickable Advancements Mod 3.0
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+16
		collective: Collective 6.48
		configured: Configured 2.0.2
		crawl: Crawl 0.11.5
		croptopia: Croptopia 2.2.2
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		darkbindings: DarkBindings - Custom Recipes 1.2.3
		darkcap: DarkCap - Cap Your XP! 1.0.2
		darkflight: DarkFlight - Simple Jetpack 1.0.3
		darkinventory: DarkInventory - Keep Inventory On 1.0.0
		darkloot: DarkLoot - Better Mob Loot 1.0.9
		darkmenu: DarkMenu - DarkRPG Legacy Menu 1.0.2
		darkmining: DarkMining - Better Block Drops 1.0.3
		darkquesting: DarkQuesting - A Quest Mod 1.1.0
		darkrtp: DarkRTP - RTP Teleport 1.0.3
		darkspawn: DarkSpawn - Teleport to Spawn 1.0.0
		darkspins: DarkSpins - XP Casino 1.0.3
		darkstarter: DarkStarter - Starter Items 1.0.0
		darktides: DarkTides - Breathe Underwater 1.0.7
		darkwooly: DarkWooly - Get More Wool 1.0.1
		dawn: Dawn API 4.1.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 5.0.0-beta.1
			terraform-wood-api-v1: Terraform Wood API (v1) 5.0.0-beta.1
		diamondeconomy: Diamond Economy 1.5.4
			org_xerial_sqlite-jdbc: sqlite-jdbc 3.36.0.3
		diamondsauctionhouse: Diamond Auction House 1.1.41.19.3
			sgui: sgui 1.2.1+1.19.3
		dragonloot: DragonLoot 1.1.3
		durability101: Durability101 0.0.4
		emerald_tools: Emerald Tools 1.5.7
		enchanting-table-descriptions: Enchanting Table Descriptions 0.1.0+1.19
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.1
		extraalchemy: Extra Alchemy 1.9.2
		extraorigins: Extra Origins 1.19-3
		fabric-api: Fabric API 0.73.2+1.19.3
			fabric-api-base: Fabric API Base 0.4.21+70be179c85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.1+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185
			fabric-command-api-v1: Fabric Command API (v1) 1.2.22+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.39+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.2.1+06937c4b85
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.41+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.44+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.10+312c329485
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.12+1134c5b885
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.20+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.24+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.14+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.31+49abcf7e85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.1+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.5+1134c5b885
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.3+1134c5b885
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.5+a91e48b785
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+5b9a588b85
		fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.14
		farsight: Farsight Mod 1.19-3.4
			com_github_jctools_jctools_jctools-core: jctools-core v4.0.1
		ferritecore: FerriteCore 5.1.0
		foxboi_two: Kitsune 1.1.9
		fzzy_core: Fzzy Core 0.1.2+1.19.3
		gear_core: Gear Core 0.1.3+1.19.3
		gearifiers: Gearifiers 0.1.4+1.19.3
			reach-entity-attributes: Reach Entity Attributes 2.3.1
		geckolib: Geckolib 4.0.3
			com_eliotlash_mclib_mclib: mclib 20
		getittogetherdrops: Get It Together, Drops! fabric-1.19.3-1.3
		globalpacks: Global Data- & Resourcepacks 1.15.3_fabric
		goml: Get Off My Lawn ReServed 1.7.0+1.19.3
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			hologram-api: Hologram API 0.2.3+1.19.3
			rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		handcrafted: Handcrafted 2.0.4
		harvest_scythes: Harvest Scythes 2.5.5+mc1.19.3
			mm: Manningham Mills 2.3
		healingcampfire: Healing Campfire 5.1
		healthcare: Health Care 1.2.1
			config2brigadier: Config to Brigadier 1.2.1
			server_translations_api: Server Translations API 1.4.19+1.19.3
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		immersive_aircraft: Immersive Aircraft 0.3.0+1.19.3
		immersive_armors: Immersive Armors 1.5.4+1.19.3
		ironchests: Iron Chests 1.7.8
			libgui: LibGui 6.5.0+1.19.3
				jankson: Jankson 5.0.0+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		jade: Jade 9.3.1
		java: Java HotSpot(TM) 64-Bit Server VM 17
		jei: Just Enough Items 12.2.0.17
		journeymap: Journeymap 5.9.3
			journeymap-api-fabric: JourneyMap API 1.19.3-1.9-fabric-SNAPSHOT
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		letmedespawn: Let Me Despawn fabric-1.0.2
		limitedspawners: Limited Spawner 1.0.6
		lithium: Lithium 0.10.4
		lootr: Lootr 0.4.25.65
		magistuarmory: Epic Knights Mod 7.6
		maxhealthfix: MaxHealthFix 9.0.1
		minecraft: Minecraft 1.19.3
		mo_glass: Mo Glass 1.6.1-MC1.19.3
		more_gems: More Gems 1.5.7
			pugh_tools: Pugh Tools 1.4.7
		mythicmetals: Mythic Metals 0.17.2+1.19.3
			additionalentityattributes: Additionalentityattributes 1.2.0+1.19.3
		mythicmetals_decorations: Mythic Metals Decorations 0.5.2+1.19.3
		mythicupgrades: Mythic Upgrades +fabric-1.6-BetaPreview3-1.19.3
		nochatreports: No Chat Reports 1.19.3-v2.0.0
		nohostilesaroundcampfire: No Hostiles Around Campfire 5.1
		origins: Origins 1.8.1
			apoli: Apoli 2.7.1
				calio: Calio 1.8.0
		origins-classes: Origins: Classes 1.5.0
		owo: oωo 0.10.2+1.19.3
			blue_endless_jankson: jankson 1.2.1
		pack_it_up: Pack It Up! 0.3.0+1.19.3
		painters_blocks_wrapper: Painter's Blocks 2.0.0+1.19.3
			painters_blocks: Painter's Blocks 2.0.0+1.19.3
		pehkui: Pehkui 3.6.3+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		pfm: Paladin's Furniture 1.1.2
		promenade: Promenade 3.1.0
		random_ring: Random Ring 1.2.6
		redmorestructure: Reds More Structures 1.0.5-fabric-1.19.3
		resourcefullib: Resourceful Lib 1.2.7
			com_teamresourceful_yabn: yabn 1.0.2
		sdlink: Simple Discord Link 2.2.0
		servercore: ServerCore 1.3.4-1.19.3
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		simple-rpc: Simple RPC 3.2.1
			me_hypherionmc_simplerpc_simple-rpc-common: simple-rpc-common 4.2.10
		simplyswords: Simply Swords 1.43.0-1.19.3
		sit: Sit 1.19.3-22
		smoothboot: Smooth Boot 1.19-1.7.1
		smwyg: Show Me What You Got 1.1.0
		soulsweapons: Marium's Soulslike Weaponry 0.9.8
		stacker: Stacker 3.0.2-1.19.3
			stacc: Stacc 1.4.0
		starlight: Starlight 1.1.1+fabric.ae22326
		t_and_t: Towns and Towers 1.10.1
		terrablender: TerraBlender 2.1.0.134
		terrestria: Terrestria 5.1.1
			terraform-dirt-api-v1: Terraform Dirt API (v1) 5.0.0-beta.1
			terrestria-common: Terrestria: Common 5.1.1
			terrestria-worldgen: Terrestria: World Generation 5.1.1
		thiccpackets: Extra Thicc Packets 1.17-1.19+
		things: Things 0.3.0+1.19.3
		timeoutout: TimeOut Out 1.0.3+1.19.1
		toofast: TooFast 1.0.0
		toolstats: ToolStats 13.0.1
		traverse: Traverse 6.1.2
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 5.0.0-beta.1
			terraform-config-api-v1: Terraform Config API (v1) 5.0.0-beta.1
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 5.0.0-beta.1
			terraform-tree-api-v1: Terraform Tree API (v1) 5.0.0-beta.1
			traverse-common: Traverse: Common 6.1.2
			traverse-worldgen: Traverse: World Generation 6.1.2
		trinkets: Trinkets 3.5.1
		universal_shops: Universal Shops 1.1.2+1.19.3
			common-economy-api: Common Economy API 1.0.0
			placeholder-api: Placeholder API 2.0.0-pre.4+1.19.3
			polymer-core: Polymer (Core) 0.3.5+1.19.3
				polymer-networking: Polymer (Networking) 0.3.5+1.19.3
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.3.5+1.19.3
			polymer-resource-pack: Polymer (Resource Pack) 0.3.5+1.19.3
				polymer-common: Polymer (Common) 0.3.5+1.19.3
		vanityslots: Vanity Slots 1.2.5
		waystones: Waystones 12.0.2
		yosbr: YOSBR 0.1.1
	Server Running: true
	Player Count: 29 / 40; [class_3222['Kat_S'/271900, l='ServerLevel[world]', x=608.74, y=47.00, z=2592.70], class_3222['Richuu_kun'/350995, l='ServerLevel[world]', x=6079.56, y=73.26, z=-2588.77], class_3222['DeathDoggo5'/997, l='ServerLevel[world]', x=-759.35, y=63.00, z=5418.98], class_3222['The_Foot_Ninja'/273319, l='ServerLevel[world]', x=1452.47, y=64.00, z=-1408.69], class_3222['uterindestroyer'/370734, l='ServerLevel[world]', x=-3517.53, y=92.00, z=4257.64], class_3222['WittyVolcano63'/378175, l='ServerLevel[world]', x=-965.21, y=72.00, z=5836.32], class_3222['SlobberyAsh'/381074, l='ServerLevel[world]', x=-1020.86, y=52.00, z=6082.85], class_3222['JupiterDaBean'/40437, l='ServerLevel[world]', x=-64.51, y=66.00, z=6341.79], class_3222['NoSocksYouCreep'/224188, l='ServerLevel[world]', x=8959.63, y=58.00, z=307.58], class_3222['slazeishere'/3258, l='ServerLevel[world]', x=4877.12, y=74.49, z=6935.95], class_3222['irishguy2417'/201356, l='ServerLevel[world]', x=-1020.70, y=60.00, z=5731.70], class_3222['FuchsiaJade'/393068, l='ServerLevel[world]', x=-762.71, y=64.00, z=5421.66], class_3222['Titanya_Rose'/350662, l='ServerLevel[world]', x=-1430.67, y=39.00, z=5812.51], class_3222['R0TIS'/399230, l='ServerLevel[world]', x=580.27, y=303.05, z=-452.99], class_3222['Baconnmanz'/120022, l='ServerLevel[world]', x=-850.37, y=104.00, z=4070.39], class_3222['OtterFenic'/341001, l='ServerLevel[world]', x=-510.38, y=86.00, z=6130.59], class_3222['VinzSupreme'/402024, l='ServerLevel[world]', x=1750.91, y=65.00, z=7278.21], class_3222['venus960'/325742, l='ServerLevel[world]', x=-397.54, y=64.00, z=5588.36], class_3222['TypicalGrey'/371204, l='ServerLevel[world]', x=-1157.05, y=69.18, z=5114.36], class_3222['spencercat'/351566, l='ServerLevel[world]', x=-511.90, y=86.00, z=6129.41], class_3222['Shadowp4'/410243, l='ServerLevel[world]', x=-679.81, y=65.56, z=5992.15], class_3222['BearHugger69'/411557, l='ServerLevel[world]', x=6570.66, y=64.00, z=7919.22], class_3222['IMang_o'/385807, l='ServerLevel[world]', x=-138.66, y=155.00, z=373.69], class_3222['D3jvid'/412892, l='ServerLevel[world]', x=-512.18, y=86.00, z=6131.64], class_3222['xHexical'/194868, l='ServerLevel[world]', x=-52.71, y=67.00, z=6350.04], class_3222['Bunchalunch'/414854, l='ServerLevel[world]', x=-734.76, y=63.00, z=6006.87], class_3222['LegitimacyJinx'/329269, l='ServerLevel[world]', x=-7096.14, y=72.00, z=8725.44], class_3222['Eevee_Trainer_'/390228, l='ServerLevel[world]', x=-699.72, y=64.00, z=6007.76], class_3222['Slushy985'/355490, l='ServerLevel[world]', x=-724.50, y=63.00, z=6005.50]]
	Data Packs: vanilla, fabric, darkrpg_quests, darkrpg_recipes, darkspawn_datapack, disable_crafting_recipes, more_gems, origin_noglin_custom, origin_sculked_magpie, pfm, simplyswords, welcome, darkstarter_datapack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)```

**Comment by apple502j** [comment]
It is probably not our issue, especially if the log doesn't say so.

**Comment by gamerpotion** [comment]
> It is probably not our issue, especially if the log doesn't say so.

Thank you :) 
I just wanted to be fully sure so I know which direction to hunt for it in.  Will explore other areas thanks
