### ISSUE TITLE
Uncaught exception in "main" "virus"

### ISSUE THREAD

**Issue by wcvrry** [FabricMC/fabric#3038]
I can't launch it because this appears. Don't got any mods installed or anything, Im just not able to launch it at all

Uncaught exception in thread "main"
java.lang.RuntimeException: error remapping game jars [C:\Users\2000063369\AppData\Roaming\.minecraft\versions\fabric-loader-0.14.19-1.19.4\fabric-loader-0.14.19-1.19.4.jar]
	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:240)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:313)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.nio.file.FileSystemException: C:\Users\2000063369\AppData\Roaming\monkey 1.13 or sum\.fabric\remappedJars\minecraft-1.19.4-0.14.19\client-intermediary.jar.tmp: Operation did not complete successfully because the file contains a virus or potentially unwanted software
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.checkReadAccess(WindowsFileSystemProvider.java:351)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.checkAccess(WindowsFileSystemProvider.java:380)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:170)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
	at net.fabricmc.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:113)
	at net.fabricmc.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:47)
	at net.fabricmc.tinyremapper.OutputConsumerPath$Builder.build(OutputConsumerPath.java:76)
	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate0(GameProviderHelper.java:294)
	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:238)
	... 4 more

**Comment by Technici4n** [comment]
This is a typical problem with some antivirus software, sadly we can't do anything about it. I'd suggest whitelisting that specific file only.
