### ISSUE TITLE
Crash on Fabric with 1.20

### ISSUE THREAD

**Issue by pgwipeout** [FabricMC/fabric#3107]
```
[02:05:48] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.minecraft.class_3218 net.minecraft.class_3222.method_14220()'
        at org.geysermc.geyser.platform.fabric.world.GeyserFabricWorldManager.lambda$sendLecternData$0(GeyserFabricWorldManager.java:75) ~[Geyser-Fabric.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:05:48] [Server thread/ERROR]: This crash report has been saved to: /opt/minecraft/survival/./crash-reports/crash-2023-06-09_02.05.48-server.txt
```

**Comment by Technici4n** [comment]
Just make sure the mods are correctly updated... Geyser is the problem here.
