### ISSUE TITLE
[1.20.1] fabric-networking-api-v1 -> net.minecraft.class_412 failure

### ISSUE THREAD

**Issue by brysondev** [FabricMC/fabric#3120]
Issue: Attempting to join a paper server [This server is running Paper version git-Paper-18 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 2e363c7)], the game immediately crashes. This happens with and without mods; having only the Fabric API loaded also causes the crash.

API Version: `0.83.0+1.20.1`

Mod List:
```
Fabric API
AppleSkins 
Iris Shaders
Lithium
Mod Menu (7.0.1)
Sodium (0.4.10+build.27)
Xaero's Minimap
Xaero's World Map
Xaero Zoomout
```

Stacktrace:
```java
[08:16:33] [Render thread/ERROR]: Mixin apply for mod fabric-networking-api-v1 failed fabric-networking-api-v1.client.mixins.json:accessor.ConnectScreenAccessor from mod fabric-networking-api-v1 -> net.minecraft.class_412: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching field_2411:Lnet/minecraft/class_2535; in net/minecraft/class_412 for fabric-networking-api-v1.client.mixins.json:accessor.ConnectScreenAccessor from mod fabric-networking-api-v1->@Accessor[FIELD_GETTER]::getConnection()Lnet/minecraft/class_2535; [INJECT Applicator Phase -> fabric-networking-api-v1.client.mixins.json:accessor.ConnectScreenAccessor from mod fabric-networking-api-v1 -> Apply Accessors ->  -> Locate -> fabric-networking-api-v1.client.mixins.json:accessor.ConnectScreenAccessor from mod fabric-networking-api-v1->@Accessor[FIELD_GETTER]::getConnection()Lnet/minecraft/class_2535;]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching field_2411:Lnet/minecraft/class_2535; in net/minecraft/class_412 for fabric-networking-api-v1.client.mixins.json:accessor.ConnectScreenAccessor from mod fabric-networking-api-v1->@Accessor[FIELD_GETTER]::getConnection()Lnet/minecraft/class_2535; [INJECT Applicator Phase -> fabric-networking-api-v1.client.mixins.json:accessor.ConnectScreenAccessor from mod fabric-networking-api-v1 -> Apply Accessors ->  -> Locate -> fabric-networking-api-v1.client.mixins.json:accessor.ConnectScreenAccessor from mod fabric-networking-api-v1->@Accessor[FIELD_GETTER]::getConnection()Lnet/minecraft/class_2535;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:519) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:502) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:476) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1411) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1071) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_500.method_2548(class_500.java:273) ~[client-intermediary.jar:?]
	at net.minecraft.class_500.method_2536(class_500.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_4267$class_4270.method_25402(class_4267.java:435) ~[client-intermediary.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:327) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

**Comment by brysondev** [comment]
API Version: `0.83.1+1.20.1`

The issue is still present.

**Comment by modmuss50** [comment]
Can you please post the full crash report file, when only running fabric-api?

**Comment by brysondev** [comment]
Please see attached
[crash-2023-06-13_08.27.44-client.txt](https://github.com/FabricMC/fabric/files/11734767/crash-2023-06-13_08.27.44-client.txt)

> Can you please post the full crash report file, when only running fabric-api?

Yes, if I use the fabric loader and the fabric API jar with nothing else the issue persists.

**Comment by modmuss50** [comment]
I just tested this my self, using the vanilla launcher and `0.83.1+1.20.1` and was able to join a server just fine. The crash report you posted still has a number of 3rd party mods installed.

**Comment by Technici4n** [comment]
(Could you also try the vanilla launcher? As it could be a Prism problem)

**Comment by brysondev** [comment]
> The crash report you posted still has a number of 3rd party mods installed.

Apologies, that is the initial log file. Please see below:
[crash-2023-06-13_08.40.09-client.txt](https://github.com/FabricMC/fabric/files/11734894/crash-2023-06-13_08.40.09-client.txt)

> (Could you also try the vanilla launcher? As it could be a Prism problem)

Just about to say this. I will do another attempt shortly with the vanilla launcher.

**Comment by modmuss50** [comment]
Thanks, I would try creating a new instance in the prism, if you updated this instance from 1.20 its likely using the old version of intermediary, Prism/MMC has a very long standing bug.

If thats not the cause of this im a little lost, as it make no sense otherwise 😆

**Comment by brysondev** [comment]
> Thanks, I would try creating a new instance in the prism, if you updated this instance from 1.20 its likely using the old version of intermediary, Prism/MMC has a very long standing bug.

Yeah I was confident initially in the bug report because I created a new instance for .1. But yeah it is more than likely a prism issue since they just released 5 days ago and thats what im using...

**Comment by brysondev** [comment]
> (Could you also try the vanilla launcher? As it could be a Prism problem)

This indeed was the issue. I can confirm everything works as expected with the vanilla launcher and `0.83.1+1.20.1`. Apologies for the report, I will move to the Prism Issues page now. 
Thanks so much!
