### ISSUE TITLE
Invalid descriptor on net.fabricmc.fabric.mixins.common.json:events.playerinteraction.MixinServerPlayerInteractionManager

### ISSUE THREAD

**Issue by THEREALWWEFAN231** [FabricMC/fabric#313]
Im not sure if this is the right place to report, but when I go into a single player world(eclipse workspace, using 1.14.4), fabric version, 0.2.7+build.127, and loader version 0.4.8+build.155

I get this
```
[14:46:10] [main/INFO]: Loading Fabric registry [file 1/4]
[14:46:10] [main/INFO]: Loading Fabric registry [file 2/4]
[14:46:10] [main/INFO]: Loading Fabric registry [file 3/4]
[14:46:10] [main/WARN]: Failed to save registry file!
java.io.FileNotFoundException: C:\Users\THEREALWWEFAN231\Desktop\wwe 1.14\run\.\saves\New World (1)\data\fabricRegistry.dat (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_211]
	at java.io.FileOutputStream.open(Unknown Source) ~[?:1.8.0_211]
	at java.io.FileOutputStream.<init>(Unknown Source) ~[?:1.8.0_211]
	at java.io.FileOutputStream.<init>(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.world.WorldSaveHandler.handler$readWorldProperties$zch000(WorldSaveHandler.java:602) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.world.WorldSaveHandler.readProperties(WorldSaveHandler.java) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient.java:1514) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.createLevel(CreateWorldScreen.java:241) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.method_19922(CreateWorldScreen.java:168) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:16) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.gui.widget.AbstractPressableButtonWidget.onClick(AbstractPressableButtonWidget.java:16) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.gui.widget.AbstractButtonWidget.mouseClicked(AbstractButtonWidget.java:145) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:42) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:80) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:430) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:80) ~[minecraft-1.14.4-mapped-1.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at net.minecraft.client.util.Window.waitForFramerateLimit(Window.java:323) [minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.MinecraftClient.updateDisplay(MinecraftClient.java:957) [minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:917) [minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.MinecraftClient.start(MinecraftClient.java:386) [minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:127) [minecraft-1.14.4-mapped-1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170) [fabric-loader-0.4.8+build.155.mapped.yarn.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129) [fabric-loader-0.4.8+build.155.mapped.yarn.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.4.8+build.155.mapped.yarn.1.jar:?]
[14:46:10] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:46:10] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:46:10] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:46:10] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:46:10] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:46:10] [main/FATAL]: Mixin apply failed net.fabricmc.fabric.mixins.common.json:events.playerinteraction.MixinServerPlayerInteractionManager -> net.minecraft.server.network.ServerPlayerInteractionManager: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on net.fabricmc.fabric.mixins.common.json:events.playerinteraction.MixinServerPlayerInteractionManager->@Inject::handler$startBlockBreak$zbn000(Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/math/Direction;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/server/network/packet/PlayerActionC2SPacket$Action;Lnet/minecraft/util/math/Direction;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/math/Direction;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on net.fabricmc.fabric.mixins.common.json:events.playerinteraction.MixinServerPlayerInteractionManager->@Inject::handler$startBlockBreak$zbn000(Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/math/Direction;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/server/network/packet/PlayerActionC2SPacket$Action;Lnet/minecraft/util/math/Direction;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/math/Direction;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:495) ~[sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:425) ~[sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:200) ~[sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:267) ~[sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1199) ~[sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:939) ~[sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:323) ~[sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281) ~[sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[sponge-mixin-0.7.11.36.jar:0.7.11.36+unknown-b0.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:179) ~[fabric-loader-0.4.8+build.155.mapped.yarn.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:142) ~[fabric-loader-0.4.8+build.155.mapped.yarn.1.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:59) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient.java:1534) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.createLevel(CreateWorldScreen.java:241) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.method_19922(CreateWorldScreen.java:168) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:16) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.gui.widget.AbstractPressableButtonWidget.onClick(AbstractPressableButtonWidget.java:16) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.gui.widget.AbstractButtonWidget.mouseClicked(AbstractButtonWidget.java:145) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:42) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:80) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:430) ~[minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:80) ~[minecraft-1.14.4-mapped-1.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at net.minecraft.client.util.Window.waitForFramerateLimit(Window.java:323) [minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.MinecraftClient.updateDisplay(MinecraftClient.java:957) [minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:917) [minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.MinecraftClient.start(MinecraftClient.java:386) [minecraft-1.14.4-mapped-1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:127) [minecraft-1.14.4-mapped-1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170) [fabric-loader-0.4.8+build.155.mapped.yarn.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129) [fabric-loader-0.4.8+build.155.mapped.yarn.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.4.8+build.155.mapped.yarn.1.jar:?]
[14:46:10] [main/INFO]: [STDERR]: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [net.fabricmc.fabric.mixins.common.json:events.playerinteraction.MixinServerPlayerInteractionManager] from phase [DEFAULT] in config [net.fabricmc.fabric.mixins.common.json] FAILED during APPLY
[14:46:10] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
[14:46:10] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
[14:46:10] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
[14:46:10] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:179)
[14:46:10] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:142)
[14:46:10] [main/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[14:46:10] [main/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:59)
[14:46:10] [main/INFO]: [STDERR]: 	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient.java:1534)
[14:46:10] [main/INFO]: [STDERR]: 	at net.minecraft.client.gui.screen.world.CreateWorldScreen.createLevel(CreateWorldScreen.java:241)
[14:46:10] [main/INFO]: [STDERR]: 	at net.minecraft.client.gui.screen.world.CreateWorldScreen.method_19922(CreateWorldScreen.java:168)
[14:46:10] [main/INFO]: [STDERR]: 	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:16)
[14:46:10] [main/INFO]: [STDERR]: 	at net.minecraft.client.gui.widget.AbstractPressableButtonWidget.onClick(AbstractPressableButtonWidget.java:16)
[14:46:10] [main/INFO]: [STDERR]: 	at net.minecraft.client.gui.widget.AbstractButtonWidget.mouseClicked(AbstractButtonWidget.java:145)
[14:46:10] [main/INFO]: [STDERR]: 	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:42)
[14:46:10] [main/INFO]: [STDERR]: 	at net.minecraft.client.Mouse.method_1611(Mouse.java:80)
[14:46:10] [main/INFO]: [STDERR]: 	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:430)
[14:46:10] [main/INFO]: [STDERR]: 	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:80)
[14:46:10] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
[14:46:10] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[14:46:10] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
[14:46:10] [main/INFO]: [STDERR]: 	at net.minecraft.client.util.Window.waitForFramerateLimit(Window.java:323)
[14:46:10] [main/INFO]: [STDERR]: 	at net.minecraft.client.MinecraftClient.updateDisplay(MinecraftClient.java:957)
[14:46:10] [main/INFO]: [STDERR]: 	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:917)
[14:46:10] [main/INFO]: [STDERR]: 	at net.minecraft.client.MinecraftClient.start(MinecraftClient.java:386)
[14:46:10] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:127)
[14:46:10] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:46:10] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:46:10] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:46:10] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[14:46:10] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
[14:46:10] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
[14:46:10] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[14:46:10] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on 
```

**net.fabricmc.fabric.mixins.common.json:events.playerinteraction.MixinServerPlayerInteractionManager->@Inject::handler$startBlockBreak$zbn000(Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/math/Direction;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/server/network/packet/PlayerActionC2SPacket$Action;Lnet/minecraft/util/math/Direction;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/math/Direction;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V**

```
[14:46:10] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:495)
[14:46:10] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:425)
[14:46:10] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:200)
[14:46:10] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:267)
[14:46:10] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1199)
[14:46:10] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:939)
[14:46:10] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:323)
[14:46:10] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281)
[14:46:10] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
[14:46:10] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
[14:46:10] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
[14:46:10] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
[14:46:10] [main/INFO]: [STDERR]: 	... 29 more
[14:46:10] [main/INFO]: Stopping!
```

**Comment by modmuss50** [comment]
You are using a massively old version of fabric. Please update to the 1.14.4 version

**Comment by THEREALWWEFAN231** [comment]
Im using theses, there are the lastest?
```
minecraft_version=1.14.4
	yarn_mappings=1.14.4+build.1
	loader_version=0.4.8+build.155
# Dependencies
	# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric
	fabric_version=0.2.7+build.127
```

**Comment by modmuss50** [comment]
0.2.7 is very old. See, https://modmuss50.me/fabric.html

The example mod is on 1.14.3 but should also help

**Comment by Boundarybreaker** [comment]
This seems to still be happening with 0.3.0+build.200. [Here's](https://gist.github.com/Boundarybreaker/4284db570fe64b0117757adb2222f2fe) a log of it.

**Comment by modmuss50** [comment]
`fabric-events-interaction-v0 0.1.0+59147463` is an older build and not for 1.14.3.
`fabric-events-interaction-v0-0.1.0+ea100f6142` is for 1.14.4 and is included in fabric-api build 200.

One of your mods is including an older version of it.

**Comment by Boundarybreaker** [comment]
Oh boy, transitives. I'll take a look at what's going on.

**Comment by modmuss50** [comment]
Yeah, I should have bumped the version when fixing the compile error, we need to find a better solution to this issue.

**Comment by XeonPowder** [comment]
Hey I am getting this error as well:
https://pastebin.com/H8XrBVqz
