### ISSUE TITLE
Crashing upon loading

### ISSUE THREAD

**Issue by G0lden1** [FabricMC/fabric#320]
When I launch the game, I receive a message saying an unexpected error has occurred. Not sure if it's me doing something wrong, or it's a bug. Thank you for your time

22:27:40.467
Loading for game Minecraft 1.14.4
22:27:47.804

Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:147)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:120)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: litematica requires {malilib @ [>=0.10.0-dev.19]})
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:185)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:508)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:145)
	... 2 more
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	... 4 more
22:27:47.804
Process crashed with exit code 1

**Comment by swordglowsblue** [comment]
You have Litematica installed, but not [MaLiLib](https://www.curseforge.com/minecraft/mc-mods/malilib), which Litematica depends on. If you install MaLiLib, everything should work just fine.
