### ISSUE TITLE
Dedicated server fails to launch on Minecraft 1.2.5

### ISSUE THREAD

**Issue by SpaceWalkerRS** [FabricMC/fabric#3203]
stacktrace:
```
[main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.2.5 with Fabric Loader 0.14.21
[main/ERROR] (FabricLoader) Uncaught exception in thread "main"
 java.lang.RuntimeException: Duplicate addPatchedClasses call: net.minecraft.server.MinecraftServer
        at net.fabricmc.loader.impl.game.patch.GameTransformer.addPatchedClass(GameTransformer.java:54) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.patch.BrandingPatch.process(BrandingPatch.java:47) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.game.patch.GameTransformer.locateEntrypoints(GameTransformer.java:92) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:347) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
```

The error occurs when running `./gradlew :server:runServer` on [this project](https://github.com/OrnitheMC/ornithe-template-mod/tree/fabric/split).

**Comment by SpaceWalkerRS** [comment]
oops this is not the loader repo, sorry
