### ISSUE TITLE
Incompatible mod set! - how to fix it?

### ISSUE THREAD

**Issue by blackrosegod12** [FabricMC/fabric#3386]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'Minecraft' (minecraft) 1.20.1 with any version between 1.20.3- (inclusive) and 1.20.4- (exclusive).
	 - Replace mod 'Fabric Loader' (fabricloader) 0.14.22 with version 0.14.23 or later.
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric-api) 0.90.4+1.20.3 requires version 0.14.23 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.22!
	 - Mod 'Fabric API' (fabric-api) 0.90.4+1.20.3 requires any version between 1.20.3- (inclusive) and 1.20.4- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Linguardium** [comment]
User error. not a fabric api issue. 

download the correct versions of your mods for your minecraft version
