### ISSUE TITLE
Error: Fabric loader: Uncaught exception in thread "main"

### ISSUE THREAD

**Issue by Ghostlyywolf** [FabricMC/fabric#3392]
Uncaught exception in thread "main"
java.lang.NoClassDefFoundError: org/spongepowered/asm/launch/MixinBootstrap
	at net.fabricmc.loader.impl.game.LoaderLibrary.<clinit>(LoaderLibrary.java:41)
	at net.fabricmc.loader.impl.game.LibClassifier.<init>(LibClassifier.java:100)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:173)
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:175)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinBootstrap
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 7 more

I dont know what to do, ive tried everything but it still gives me the same error
What can I do?

**Comment by Linguardium** [comment]
go to the discord, ask for help. the issue tracker is for tracking issues with the fabric api mod itself, not for solving user problems.

**Comment by Ghostlyywolf** [comment]
but the problem isnt with the fabric loader?

**Comment by Linguardium** [comment]
correct. by itself, with no mods the loader works fine. by itself with the proper version of fabric api mod, it works fine as well. it appears you are having another issue

**Comment by Ghostlyywolf** [comment]
Actually, i tested a completelly fresh instance with no mod, just the fabric loader, but it still gave me the same error

**Comment by Linguardium** [comment]
head to the discord, this isnt a forum or open a discussion. the issue tracker is not a forum. if there is an actual fabric api mod issue at play, an issue can be opened for that verified problem

**Comment by Ghostlyywolf** [comment]
oh oka, thanks
