### ISSUE TITLE
Game doesn't start 

### ISSUE THREAD

**Issue by AlphaTristan** [FabricMC/fabric#340]
so i've been wanting to use litematica the last couple of days and it wouldn't work with my normal minecraft launcher and i couldn't seem to find the logs anywhere so i tought maybe using ATLauncher will fix the problems but still the same issue i don't know how to fix it
here is the log thanks anyway!

mods installed
Fabric API
MaLiLib
Litematica
(all have been checked for updates)

[12/8/2019 02:06:24 AM] [main/INFO]: Loading for game Minecraft 1.14.4
[12/8/2019 02:06:32 AM] Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
[12/8/2019 02:06:32 AM] 	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:147)
[12/8/2019 02:06:32 AM] 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:120)
[12/8/2019 02:06:32 AM] 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[12/8/2019 02:06:32 AM] Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: litematica requires {malilib @ [>=0.10.0-dev.19]})
[12/8/2019 02:06:32 AM] 	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:185)
[12/8/2019 02:06:32 AM] 	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:504)
[12/8/2019 02:06:32 AM] 	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:145)
[12/8/2019 02:06:32 AM] 	... 2 more
[12/8/2019 02:06:32 AM] Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
[12/8/2019 02:06:32 AM] 	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
[12/8/2019 02:06:32 AM] 	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
[12/8/2019 02:06:32 AM] 	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
[12/8/2019 02:06:32 AM] 	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
[12/8/2019 02:06:32 AM] 	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
[12/8/2019 02:06:32 AM] 	... 4 more
[12/8/2019 02:06:32 AM] Checking for updated files!

**Comment by kgscialdone** [comment]
Looks like you have either the wrong version of Litematica or the wrong version of MaLiLib. Note the line stating `litematica requires {malilib @ [>=0.10.0-dev.19]}`.

**Comment by modmuss50** [comment]
Not a fabric issue, install the correct version of malilib
