### ISSUE TITLE
I have been having a lot of critical issues related to Netty Epoll IO and the fabric networking api

### ISSUE THREAD

**Issue by TheBestAstroNOT** [FabricMC/fabric#3453]
Me and my friend have been working on a modpack named FantastiCreate
We were trying to make a serverpack but failed to do so, so we tried to use ngrok lan.
The mod worked for a lil bit and then I was met with this error java.lang.IllegalStateException: null
I have experienced this error a lot in all the different versions of our serverpack and netty is always also involved

Link to the modpack used: https://github.com/sombrae/FantastiCreate/releases/tag/v10

Full log:
[22:26:48] [Netty Login IO Thread #1/INFO]: Reloading server config for barteringstation
[22:26:48] [Netty Login IO Thread #1/INFO]: Reloading server config for bettertridents
[22:26:48] [Netty Login IO Thread #1/INFO]: Create Ore Excavation config just got changed on the file system!
[22:26:48] [Netty Login IO Thread #1/INFO]: Reloading server config for tradingpost
[22:26:48] [Netty Login IO Thread #1/INFO]: Reloading server config for leavesbegone
[22:26:48] [Netty Login IO Thread #1/INFO]: [Handshake] Sending client channels
[22:26:48] [Netty Login IO Thread #1/INFO]: Received server config
[22:26:48] [Netty Login IO Thread #1/INFO]: Connected to a modded server.
[22:26:50] [Netty Play IO Thread #10/INFO]: [do_a_barrel_roll] Received config from server
[22:26:50] [Netty Play IO Thread #10/INFO]: Applying server overrides
[22:26:50] [Netty Play IO Thread #10/INFO]: Responding with client values
[22:26:50] [Render thread/INFO]: New minimap session initialized!
[22:26:50] [Render thread/INFO]: New world map session initialized!
[22:26:50] [Render thread/INFO]: Saved lock repository '4.tcp.eu.ngrok.io:18466'
[22:26:50] [Render thread/INFO]: Loaded locks for '4.tcp.eu.ngrok.io:18466'
[22:26:50] [Render thread/INFO]: Reloading pipeline on dimension change: NamespacedId{namespace='parallel_world', name='parallel_overworld'} => NamespacedId{namespace='parallel_world', name='parallel_overworld'}
[22:26:50] [Render thread/INFO]: Destroying pipeline NamespacedId{namespace='parallel_world', name='parallel_overworld'}
[22:26:50] [Render thread/INFO]: Creating pipeline for dimension NamespacedId{namespace='parallel_world', name='parallel_overworld'}
[22:26:50] [Render thread/INFO]: Starting custom uniform resolving
[22:26:51] [Netty Play IO Thread #10/ERROR]: Encountered exception while handling in channel with name "fabric:registry/sync/direct"
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:486) ~[guava-31.0.1-jre.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.packet.DirectRegistryPacketHandler.receivePacket(DirectRegistryPacketHandler.java:165) ~[fabric-registry-sync-v0-0.9.33+9244241690-27f9ee686d914119.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.receivePacket(RegistrySyncManager.java:101) ~[fabric-registry-sync-v0-0.9.33+9244241690-27f9ee686d914119.jar:?]
	at net.fabricmc.fabric.impl.client.registry.sync.FabricRegistryClientInit.lambda$registerSyncPacketReceiver$2(FabricRegistryClientInit.java:40) ~[fabric-registry-sync-v0-0.9.33+9244241690-27f9ee686d914119.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:106) ~[fabric-networking-api-v1-1.2.12+def3f86d90-40dbcfca42bb4b90.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:42) ~[fabric-networking-api-v1-1.2.12+def3f86d90-40dbcfca42bb4b90.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) [fabric-networking-api-v1-1.2.12+def3f86d90-40dbcfca42bb4b90.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:98) [fabric-networking-api-v1-1.2.12+def3f86d90-40dbcfca42bb4b90.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.handler$hlo000$fabric-networking-api-v1$handleCustomPayload(ClientPlayNetworkHandler.java:2522) [client-intermediary.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onCustomPayload(ClientPlayNetworkHandler.java) [client-intermediary.jar:?]
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket.java:60) [client-intermediary.jar:?]
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket.java:8) [client-intermediary.jar:?]
	at net.minecraft.network.ClientConnection.handlePacket(ClientConnection.java:167) [client-intermediary.jar:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection.java:152) [client-intermediary.jar:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection.java:50) [client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[22:26:51] [Netty Play IO Thread #10/ERROR]: Exception occurred in netty pipeline
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:486) ~[guava-31.0.1-jre.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.packet.DirectRegistryPacketHandler.receivePacket(DirectRegistryPacketHandler.java:165) ~[fabric-registry-sync-v0-0.9.33+9244241690-27f9ee686d914119.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.receivePacket(RegistrySyncManager.java:101) ~[fabric-registry-sync-v0-0.9.33+9244241690-27f9ee686d914119.jar:?]
	at net.fabricmc.fabric.impl.client.registry.sync.FabricRegistryClientInit.lambda$registerSyncPacketReceiver$2(FabricRegistryClientInit.java:40) ~[fabric-registry-sync-v0-0.9.33+9244241690-27f9ee686d914119.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:106) ~[fabric-networking-api-v1-1.2.12+def3f86d90-40dbcfca42bb4b90.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:42) ~[fabric-networking-api-v1-1.2.12+def3f86d90-40dbcfca42bb4b90.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.2.12+def3f86d90-40dbcfca42bb4b90.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:98) ~[fabric-networking-api-v1-1.2.12+def3f86d90-40dbcfca42bb4b90.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.handler$hlo000$fabric-networking-api-v1$handleCustomPayload(ClientPlayNetworkHandler.java:2522) ~[client-intermediary.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onCustomPayload(ClientPlayNetworkHandler.java) ~[client-intermediary.jar:?]
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.network.ClientConnection.handlePacket(ClientConnection.java:167) ~[client-intermediary.jar:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection.java:50) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[22:26:51] [Netty Play IO Thread #10/ERROR]: Twilight Forest: Exception occurred in netty pipeline
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:486) ~[guava-31.0.1-jre.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.packet.DirectRegistryPacketHandler.receivePacket(DirectRegistryPacketHandler.java:165) ~[fabric-registry-sync-v0-0.9.33+9244241690-27f9ee686d914119.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.receivePacket(RegistrySyncManager.java:101) ~[fabric-registry-sync-v0-0.9.33+9244241690-27f9ee686d914119.jar:?]
	at net.fabricmc.fabric.impl.client.registry.sync.FabricRegistryClientInit.lambda$registerSyncPacketReceiver$2(FabricRegistryClientInit.java:40) ~[fabric-registry-sync-v0-0.9.33+9244241690-27f9ee686d914119.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:106) ~[fabric-networking-api-v1-1.2.12+def3f86d90-40dbcfca42bb4b90.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:42) ~[fabric-networking-api-v1-1.2.12+def3f86d90-40dbcfca42bb4b90.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.2.12+def3f86d90-40dbcfca42bb4b90.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:98) ~[fabric-networking-api-v1-1.2.12+def3f86d90-40dbcfca42bb4b90.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.handler$hlo000$fabric-networking-api-v1$handleCustomPayload(ClientPlayNetworkHandler.java:2522) ~[client-intermediary.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onCustomPayload(ClientPlayNetworkHandler.java) ~[client-intermediary.jar:?]
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.network.ClientConnection.handlePacket(ClientConnection.java:167) ~[client-intermediary.jar:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection.java:50) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[22:26:51] [Netty Play IO Thread #10/INFO]: Unloading synced configs from server
[22:26:51] [Netty Play IO Thread #10/INFO]: Disconnected from server, resetting proxy config values

**Comment by TheBestAstroNOT** [comment]
For simplicity's sake here u have the log in a pastebin: https://pastebin.com/f8TDyzHB

**Comment by modmuss50** [comment]
Hi, can you post the full log with versions as well? This one is quite odd.

**Comment by akai-hana** [comment]
Hey, lead FantastiCreate dev here.

I've been experiencing the same error that Astro is when trying to play on a server. Although server runs fine, it disconnects people at seemingly random times. At first I thought it had something to do with chunks, but after trying to teleport Astro to another place just after he got kicked out, it would still kick him, so I really don't have any clue about what to do.

I've been playing on this modpack singleplayer for a month now, and haven't faced the error that I do when trying to play on a server.

[Here](https://www.reddit.com/r/ModdedMinecraft/comments/17svl9c/disconnected_error_when_trying_to_join_my_server/)'s a reddit post I made some weeks ago, it includes all logs I could find, and it's the same error Astro is facing.

**Comment by modmuss50** [comment]
> For simplicity's sake here u have the log in a pastebin: https://pastebin.com/f8TDyzHB

This isnt the full log, Id like to see the list of loaded mods.

> I've been experiencing the same error that Astro is when trying to play on a server.

The logs on the reddit post do not seem to match the issue here, and again are not complete. I dont even know what version of Minecraft you are both using.

At the moment I dont think either of these are Fabric API issues, unless you can reproduce this with just FAPI and a simple mod then I think it would be best as a discussion topic.

**Comment by TheBestAstroNOT** [comment]
Here is the full version: https://mclo.gs/uW8Hb94
Ignore the splash text not loaded errors

**Comment by TheBestAstroNOT** [comment]
> > For simplicity's sake here u have the log in a pastebin: https://pastebin.com/f8TDyzHB
> 
> This isnt the full log, Id like to see the list of loaded mods.
> 
> > I've been experiencing the same error that Astro is when trying to play on a server.
> 
> The logs on the reddit post do not seem to match the issue here, and again are not complete. I dont even know what version of Minecraft you are both using.
> 
> At the moment I dont think either of these are Fabric API issues, unless you can reproduce this with just FAPI and a simple mod then I think it would be best as a discussion topic.

Hmm i thought it might be related cause the main error referenced netty libraries and the fabric networking api

**Comment by TheBestAstroNOT** [comment]
> The logs on the reddit post do not seem to match the issue here, and again are not complete. I dont even know what version of Minecraft you are both using.

Its a custom modpack (Minecraft:1.19.2 Fabric:0.14.24) Link: https://github.com/sombrae/FantastiCreate/releases/tag/v10
Somewhere Around 619 Mods
A lot of the mod conflicts that u see in the beggining are fixed in the next release of the mp but issue is still there

**Comment by apple502j** [comment]
@TheBestAstroNOT The error in the first post is missing in the full log?

**Comment by TheBestAstroNOT** [comment]
It is its a bit in b/w because i didnt close the game after the disconnect

**Comment by apple502j** [comment]
@TheBestAstroNOT `Encountered exception while handling in channel with name "fabric:registry/sync/direct"` was not found in https://mclo.gs/uW8Hb94 - the full log file.

Would also like to see the result with `-Dfabric.registry.debug=true` launch arg in the client.

**Comment by TheBestAstroNOT** [comment]
Sure ill add the argument and test
For some reason the last 3 minutes of the log arent being uploaded to the website so im gonna send the whole log as a txt file.
The actual bug itself cant be copied normally for some reason and i had to copy it line by line so 1 or 2 lines might be missing but its whole for the most part
The bug starts at the timestamp **_22:23_**
[fantasticreate_illegal_Exception_serverpackv0.1_modpackv10.txt](https://github.com/FabricMC/fabric/files/13527926/fantasticreate_illegal_Exception_serverpackv0.1_modpackv10.txt)

**Comment by modmuss50** [comment]
Im going to convert this issue to a discussion, with this many mods its impossible to prove its a fabric api issue. The next thing to do will be to try and track down the mods that are causing this.
