### ISSUE TITLE
Crash when hitting an entity 

### ISSUE THREAD

**Issue by Bombbery** [FabricMC/fabric#346]
**Version**: 1.14_combat-0 (Combat Update 2)
**OS**: Windows 10 
**Fabric Build**: fabric-loader-0.4.8+build.159-1.14.4

Hitting an entity, weapon equipped or not, causes a crash in the Combat Test 2 Update.

**Reproduction**
1. Find a Skeleton, Zombie, or other entity.
2. Initiate fighting chosen entity.
3. After a certain number of strikes (or the first strike), the game will crash.

**Log**
`java.lang.NoSuchMethodError: net.minecraft.class_3966.<init>(Lnet/minecraft/class_1297;Lnet/minecraft/class_243;)V
	at net.minecraft.class_3244.handler$onPlayerInteractEntity$zbf000(class_3244.java:2006)
	at net.minecraft.class_3244.method_12062(class_3244.java:1169)
	at net.minecraft.class_2824.method_12251(class_2824.java:70)
	at net.minecraft.class_2824.method_11054(class_2824.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_2600$$Lambda$3072/549455989.run(Unknown Source)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:706)
	at net.minecraft.class_1255.method_18857(class_1255.java:127)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:691)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:646)
	at java.lang.Thread.run(Thread.java:745)`

According to liach (Fabric Discord), the following line needs updated:
https://github.com/FabricMC/fabric/blob/9232ac87a26c31a676ec93231b19b1b684fd81dd/fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/mixin/eventsinteraction/MixinServerPlayNetworkHandler.java#L43

**Comment by modmuss50** [comment]
I dont see us releasing an fabric api for this combat update, possibly one in the future. Sorry.
