### ISSUE TITLE
Crash on start build 208 1.14.4

### ISSUE THREAD

**Issue by Foutje** [FabricMC/fabric#347]
**When I dont have any mods in my mods folder Fabric will start normally. but when I put in fabric api and replay mod it gives this crash report:** 
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 21-8-19 20:55
Description: Initializing game

net.fabricmc.loader.api.EntrypointException: Could not look up entries for entrypoint client!
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:151)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:186)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:151)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:186)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1042694104 bytes (994 MB) / 1342177280 bytes (1280 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.3.1+build.208
		fabric-api-base: fabric-api-base 0.1.0+b494ebeb42
		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
		fabric-commands-v0: fabric-commands-v0 0.1.1+b494ebeb42
		fabric-containers-v0: fabric-containers-v0 0.1.2+b494ebeb42
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+b494ebeb42
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.1+9f55aa7042
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.1+9f55aa7042
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.1+eff46b3d42
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+b494ebeb42
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+ab421b9c42
		fabric-models-v0: fabric-models-v0 0.1.0+5914746342
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+b494ebeb42
		fabric-networking-v0: fabric-networking-v0 0.1.3+9f55aa7042
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9b03381f42
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+9b03381f42
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9b03381f42
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.10+f0fe03ff42
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+b494ebeb42
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.1+39442fc242
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.2+232e294c42
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+b494ebeb42
		fabric-textures-v0: fabric-textures-v0 0.1.4+b494ebeb42
		fabricloader: Fabric Loader 0.4.8+build.159
		replaymod: Replay Mod 1.14.4-2.2.0-b7
	Launched Version: fabric-loader-0.4.8+build.159-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

**### This is the log from that crash:**
[20:55:29] [main/INFO]: Loading for game Minecraft 1.14.4
[20:55:34] [main/WARN]: Mod `replaymod` (1.14.4-2.2.0-b7) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[20:55:34] [main/INFO]: [FabricLoader] Loading 28 mods: fabric-renderer-api-v1@0.1.1+9b03381f42, fabric-networking-blockentity-v0@0.1.1+b494ebeb42, fabric-keybindings-v0@0.1.1+7dfef87c42, fabricloader@0.4.8+build.159, fabric-renderer-indigo@0.1.10+f0fe03ff42, fabric-containers-v0@0.1.2+b494ebeb42, fabric-biomes-v1@0.1.0+896c7fbb42, fabric-events-interaction-v0@0.1.1+9f55aa7042, fabric-crash-report-info-v1@0.1.1+9f55aa7042, fabric-api-base@0.1.0+b494ebeb42, fabric-rendering-v0@0.1.1+6dad974e42, replaymod@1.14.4-2.2.0-b7, fabric-rendering-data-attachment-v1@0.1.0+b494ebeb42, fabric-resource-loader-v0@0.1.2+232e294c42, fabric-textures-v0@0.1.4+b494ebeb42, fabric-content-registries-v0@0.1.1+b494ebeb42, fabric-tag-extensions-v0@0.1.1+b494ebeb42, fabric-rendering-fluids-v1@0.1.1+39442fc242, fabric-commands-v0@0.1.1+b494ebeb42, fabric-registry-sync-v0@0.2.2+9b03381f42, fabric-mining-levels-v0@0.1.0+ab421b9c42, fabric-loot-tables-v1@0.1.0+b494ebeb42, fabric-events-lifecycle-v0@0.1.1+eff46b3d42, fabric@0.3.1+build.208, fabric-models-v0@0.1.0+5914746342, fabric-item-groups-v0@0.1.0+1e69a0a542, fabric-object-builders-v0@0.1.1+9b03381f42, fabric-networking-v0@0.1.3+9f55aa7042
[20:55:34] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/Morris/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.7.11.38/sponge-mixin-0.7.11.38.jar Service=Knot/Fabric Env=CLIENT
[20:55:35] [main/INFO]: Compatibility level set to JAVA_8
[20:55:36] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[20:55:36] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[20:55:40] [main/INFO]: Setting user: Fout
[20:55:57] [main/ERROR]: Exception occured while getting 'client' entrypoints @ replaymod->(0.3.x)com.replaymod.core.ReplayMod
net.fabricmc.loader.api.LanguageAdapterException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:56) ~[fabric-loader-0.4.8+build.159.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:101) ~[fabric-loader-0.4.8+build.159.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:93) ~[fabric-loader-0.4.8+build.159.jar:?]
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:140) [fabric-loader-0.4.8+build.159.jar:?]
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:186) [fabric-loader-0.4.8+build.159.jar:?]
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35) [fabric-loader-0.4.8+build.159.jar:?]
	at net.minecraft.class_310.method_1503(class_310.java) [intermediary-fabric-loader-0.4.8+build.159-1.14.4.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:394) [intermediary-fabric-loader-0.4.8+build.159-1.14.4.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) [intermediary-fabric-loader-0.4.8+build.159-1.14.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170) [fabric-loader-0.4.8+build.159.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129) [fabric-loader-0.4.8+build.159.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.4.8+build.159.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:54) ~[fabric-loader-0.4.8+build.159.jar:?]
	... 15 more
Caused by: com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[gson-2.8.0.jar:?]
	at com.replaymod.core.SettingsRegistry.register(SettingsRegistry.java:64) ~[replaymod-1.14.4-2.2.0-b7.jar:?]
	at com.replaymod.core.ReplayMod.<init>(ReplayMod.java:216) ~[replaymod-1.14.4-2.2.0-b7.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:54) ~[fabric-loader-0.4.8+build.159.jar:?]
	... 15 more

Hope that there's a fix for this. Thanks

**Comment by liach** [comment]
Your replaymod config is corrupted. Delete it and rerun the game. https://github.com/ReplayMod/ReplayMod/blob/94d6e7cb4bbffb9bf2f2f86448fc1e3d15c8946b/src/main/java/com/replaymod/core/SettingsRegistry.java#L64

**Comment by Foutje** [comment]
I deleted the replaymod file, ran the game and it worked fine. I quit the game, downloaded replaymod again and put it in the mods folder. When tried to run the game it crashed with the same reason.

**Comment by liach** [comment]
Delete the config of replaymod, not the replay mod itself. Should be a json file in the configs folder.

**Comment by Foutje** [comment]
It works now. I cant read lol
Thank you.
