### ISSUE TITLE
connecting to a server when mc window is minimised

### ISSUE THREAD

**Issue by Withorcool** [FabricMC/fabric#3499]
[19:51:07] [Thread-2/ERROR] (fabric-screen-api-v1) Attempted to set screen to "net.minecraft.client.gui.screen.ProgressScreen@3941c24b" outside the render thread ("Thread-2"). This will likely follow a crash! Make sure to call setScreen on the render thread.
[19:51:09] [Render thread/ERROR] (Minecraft) Reported exception thrown!
 net.minecraft.util.crash.CrashException: Rendering screen
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:954) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1219) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.IllegalStateException: [fabric-screen-api-v1] The current screen (net.minecraft.client.gui.screen.ProgressScreen) has not been correctly initialised, please send this crash log to the mod author. This is usually caused by calling setScreen on the wrong thread.
	at net.minecraft.client.gui.screen.Screen.ensureEventsAreInitialized(Screen.java:1316) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.gui.screen.Screen.fabric_getBeforeRenderEvent(Screen.java:1339) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeRender(ScreenEvents.java:126) ~[fabric-screen-api-v1-2.0.7+b3afc78b77.jar:?]
	at net.minecraft.client.render.GameRenderer.handler$zbf000$fabric-screen-api-v1$onBeforeRenderScreen(GameRenderer.java:1638) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:945) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	... 7 more
---- Minecraft Crash Report ----
// You're mean.

Time: 2024-01-01 19:51:09
Description: Rendering screen

java.lang.IllegalStateException: [fabric-screen-api-v1] The current screen (net.minecraft.client.gui.screen.ProgressScreen) has not been correctly initialised, please send this crash log to the mod author. This is usually caused by calling setScreen on the wrong thread.
	at net.minecraft.client.gui.screen.Screen.ensureEventsAreInitialized(Screen.java:1316)
	at net.minecraft.client.gui.screen.Screen.fabric_getBeforeRenderEvent(Screen.java:1339)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeRender(ScreenEvents.java:126)
	at net.minecraft.client.render.GameRenderer.handler$zbf000$fabric-screen-api-v1$onBeforeRenderScreen(GameRenderer.java:1638)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:945)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1219)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.ensureEventsAreInitialized(Screen.java:1316)
	at net.minecraft.client.gui.screen.Screen.fabric_getBeforeRenderEvent(Screen.java:1339)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeRender(ScreenEvents.java:126)
	at net.minecraft.client.render.GameRenderer.handler$zbf000$fabric-screen-api-v1$onBeforeRenderScreen(GameRenderer.java:1638)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.ProgressScreen
	Mouse location: Scaled: (337, 508). Absolute: (674.000000, 1016.000000)
	Screen size: Scaled: (960, 529). Absolute: (1920, 1057). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:945)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1219)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric
Stacktrace:
	at net.minecraft.client.resource.ResourceReloadLogger.addReloadSection(ResourceReloadLogger.java:49)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2413)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 694859016 bytes (662 MiB) / 1270874112 bytes (1212 MiB) up to 4135583744 bytes (3944 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x1638
	Graphics card #0 versionInfo: DriverVersion=30.0.13040.13
	Graphics card #1 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2520
	Graphics card #1 versionInfo: DriverVersion=31.0.15.4617
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28061.39
	Virtual memory used (MB): 24351.32
	Swap memory total (MB): 12288.00
	Swap memory used (MB): 1541.02
	JVM Flags: 0 total; 
	Fabric Mods: 
		elementa: Elementa 619
		fabric-api: Fabric API 0.91.0+1.20.1
		fabric-api-base: Fabric API Base 0.4.30+7abfd51577
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
		fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
		fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
		fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
		fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
		fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
		fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
		fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
		fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
		fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
		fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
		fabric-gametest-api-v1: Fabric Game Test API (v1) 1.2.12+b3afc78b77
		fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
		fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
		fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
		fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
		fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
		fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
		fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
		fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
		fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
		fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
		fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
		fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
		fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
		fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
		fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
		fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.14.21
		java: Java HotSpot(TM) 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.1
		universalcraft: UniversalCraft 211
		uteclient: UTEClient 1.0-SNAPSHOT
	Launched Version: Fabric
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.14761 Core Profile Forward-Compatible Context 21.30.40 30.0.13040.13, ATI Technologies Inc.
	Window size: 1920x1057
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 16x AMD Ryzen 7 5800H with Radeon Graphics 
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\onlym\Downloads\UTEClient\run\crash-reports\crash-2024-01-01_19.51.09-client.txt

> Task :runClient FAILED
7 actionable tasks: 4 executed, 3 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command 'D:\Java\jdk-17.0.8\bin\java.exe'' finished with non-zero exit value -1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 31s
7:51:09 PM: Execution finished 'runClient'.

            ServerInfo info = new ServerInfo(I18n.translate("rpc"), ip, false);
            ConnectScreen.connect(MinecraftClient.getInstance().currentScreen, MinecraftClient.getInstance() , ServerAddress.parse(ip), info, true);

**Comment by apple502j** [comment]
@Withorcool Please provide the full source code that we can build.
