### ISSUE TITLE
Error creating Mixin config fabric-block-view-api-v2.client.mixins.json for mod fabric-block-view-api-v2

### ISSUE THREAD

**Issue by xc0ff33** [FabricMC/fabric#3502]
### Discussed in https://github.com/orgs/FabricMC/discussions/3500

<div type='discussions-op-text'>

<sup>Originally posted by **xc0ff33** January  1, 2024</sup>
### Description

I loaded up my mod for the first time using this...

![Screenshot 2024-01-01 165720](https://github.com/FabricMC/fabric/assets/126925753/6ef931fe-6877-4649-8611-8ec8bc79bbe8)

...then this error occurs. I don't think I'm behind it. It seems to be caused by parts of the Fabric API. The problematic API branch changes every time I run it, which is **very weird**.
Two examples of such errors:

```
Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config fabric-block-view-api-v2.client.mixins.json for mod fabric-block-view-api-v2
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config fabric-block-view-api-v2.client.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
	... 4 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'fabric-block-view-api-v2.client.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 7 more
```

```
Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config fabric-object-builder-v1.client.mixins.json for mod fabric-object-builder-api-v1
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config fabric-object-builder-v1.client.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
	... 4 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'fabric-object-builder-v1.client.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 7 more
```

Here is my `fabric.mod.json`:
```
{
	"schemaVersion": 1,
	"id": "gainhearts",
	"version": "${1.0.0}",
	"name": "GainHearts",
	"description": "GainHearts is a small Minecraft mod I built for my cousin. You get hearts when doing things.",
	"authors": [
		"xc0ff33"
	],
	"contact": {
		"homepage": "// there is a link to a private repo",
		"sources": "// there is a link to a private repo"
	},
	"license": "CC0-1.0",
	"icon": "assets/gainhearts/icon.png",
	"environment": "*",
	"entrypoints": {
		"main": [
			"com.gainhearts.GainHearts"
		]
	},
	"mixins": [
		"gainhearts.mixins.json"
	],
	"depends": {
		"fabricloader": ">=0.15.0",
		"minecraft": "~1.20.4",
		"java": ">=17",
		"fabric-api": "*"
	},
	"suggests": {
		"another-mod": "*"
	}
}
```

Here is my `gainhearts.mixins.json`:
```
{
  "required": true,
  "package": "com.gainhearts.mixin",
  "compatibilityLevel": "JAVA_17",
  "mixins": [
    "BlockBreakMixin",
    "EntityKillMixin"
  ],
  "injectors": {
    "defaultRequire": 1
	}
}
```</div>

**Comment by AnAwesomGuy** [comment]
is it because of the `${1.0.0}` as your version?
remove the dollar sign and the surrounding brackets so it is like `1.0.0` and see if it works

**Comment by xc0ff33** [comment]
I did try that because it previously was spitting out an error that it explicitly didn't like the `${1.0.0}`. I have changed it back, the mixin client error still occurs.

It may be also worth mentioning that once when I ran the client, it told me that it could load mixin config for _my_ _mod_. (which might mean this is a Mixin issue)

**Comment by xc0ff33** [comment]
I have now tried updating the fabric API and the fabric loader to the newest version, and I have had gradle install the new versions, however I am not sure on how to get Intellij to use the updated loader. It is downloaded, though, and in the dependencies.

**Comment by AnAwesomGuy** [comment]
Do you have the latest loader, loom, and Gradle versions?
