### ISSUE TITLE
Fabric crash because the system didn't have narrator?

### ISSUE THREAD

**Issue by ray1997** [FabricMC/fabric#3542]
Initially I thought it was some mod, but after I tried disable every single mods, and left with just empty mods folder a game still crash.
This didn't happen on vanilla instance.

Here's a full log: https://mclo.gs/OvqmmAd
```
Snipped from a log:
[00:13:47] [Render thread/ERROR]: Error while loading the narrator
com.mojang.text2speech.Narrator$InitializeException: Failed to load library flite
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:69) ~[text2speech-1.17.9.jar:?]
	at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar:?]
	at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.17.9.jar:?]
	at net.minecraft.client.util.NarratorManager.<init>(NarratorManager.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:684) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[1.20.4-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'flite':
libflite.so: cannot open shared object file: No such file or directory
libflite.so: cannot open shared object file: No such file or directory
```

**Comment by apple502j** [comment]
Try using another launcher or re-creating instances.

**Comment by modmuss50** [comment]
Please try the vanilla Minecraft launcher. I believe this is an issue with the Modrinth launcher and not fabric loader, I'd report it to them. The crash report also appears to be deobfucasted, I'd recommend not doing this as it causes confusing between prod and dev.

**Comment by ray1997** [comment]
@modmuss50 You appear to be correct, as I tried re-install all the mods on new instance, and a game is now work again. 
~~I'll close this issue right away~~ nvm, its already closed

**Comment by ray1997** [comment]
Further tinkering and its appear that the problematic profile just had narrator turn on (narrator:2) on options.txt??
