### ISSUE TITLE
Indigo included in 1.15 Fabric API versions when it only works on below 1.15

### ISSUE THREAD

**Issue by Cynosphere** [FabricMC/fabric#358]
```
Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:159)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:122)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Mod fabric-renderer-indigo depends on mod {minecraft @ [<1.15-]}, but a different version is present: 1.15-alpha.19.36.a!
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:309)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:603)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:157)
	... 2 more
```

Tested with 0.3.2+build.215-1.15, 0.3.2+build.217-1.15 and 0.3.2+build.219-1.15 on loader 0.6.1+build.165 in dev env.

**Comment by grondag** [comment]
Please provide a complete error log.  

The versions of indigo packaged with recent 1.15 builds depend on and operate with Minecraft 1.15 or higher.  I confirmed this directly just now in the .219 distribution:  

```json
 "schemaVersion": 1,
  "id": "fabric-renderer-indigo",
  "version": "0.1.13+b4f62fb546",
  "license": "Apache-2.0",
  "depends": {
    "fabricloader": ">=0.6.1",
    "minecraft": ">=1.15-",
    "fabric-api-base": "*",
    "fabric-renderer-api-v1": "*"
  }
```
So it appears you are somehow attempting to load a 1.14 version of Indigo on 1.15, perhaps because another mod is shadowing it (not recommended) or it is somehow present independently. 

In any case, there's little we can do without more information.

**Comment by Cynosphere** [comment]
Full log:
```
[20:14:21] [main/INFO]: Loading for game Minecraft 19w36a
Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:159)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:122)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Mod fabric-renderer-indigo depends on mod {minecraft @ [<1.15-]}, but a different version is present: 1.15-alpha.19.36.a!
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:309)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:603)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:157)
	... 2 more

Process finished with exit code 1
```

**Comment by coderbot16** [comment]
We will need a list of all mods you have installed

**Comment by Cynosphere** [comment]
https://gitlab.com/Cynosphere/variability-fabric/blob/c4e646ff5fdda0608295d2264663425eb1ebf737/build.gradle mod definitions
https://gitlab.com/Cynosphere/variability-fabric/blob/c4e646ff5fdda0608295d2264663425eb1ebf737/gradle.properties version definitions

**Comment by liach** [comment]
Looks like one of the mods shipped outdated indigo

**Comment by grondag** [comment]
Full log means full log.

**Comment by liach** [comment]
> Full log means full log.

That actually is the full log, starting with `Loading for game Minecraft <version>` as in all development environments, and ending with `
Process finished with exit code #` as all runs from intellij idea.

**Comment by grondag** [comment]
> > Full log means full log.
> 
> That actually is the full log, starting with `Loading for game Minecraft <version>` as in all development environments, and ending with ` Process finished with exit code #` as all runs from intellij idea.

Ah, well, my mistake.

In any case, it's probably a stray entry in some POM file.  This happens to me also when there are many dependencies in dev.  I avoid it by adding something like the following to most of my dependencies:

```gradle
modRuntime ("me.shedaniel.cloth:config-2:${clothconfig_version}") {
        exclude group :"io.github.prospector.modmenu"
        exclude group :"net.fabricmc.fabric-api"
}
```

It's annoying, but it seems to work.
