### ISSUE TITLE
AssertionError in ClientNetworkingImpl.setClientConfigurationAddon during server transfer

### ISSUE THREAD

**Issue by globau** [FabricMC/fabric#3596]
Steps to reproduce:
1. Enable assertions
2. Connect to a multi-instance bungeecord/waterfall server
3. Once connected to the server's lobby, connect to another instance within the server

Crashes with:
```
 java.lang.AssertionError: null
	at net.fabricmc.fabric.impl.networking.client.ClientNetworkingImpl.setClientConfigurationAddon(ClientNetworkingImpl.java:141) ~[fabric-networking-api-v1-3.1.7+2e5ac5484f.jar:?]
	at net.minecraft.client.network.ClientConfigurationNetworkHandler.handler$zgi003$fabric-networking-api-v1$initAddon(ClientConfigurationNetworkHandler.java:550) ~[minecraft-merged-e7cf13955e-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.network.ClientConfigurationNetworkHandler.<init>(ClientConfigurationNetworkHandler.java:49) ~[minecraft-merged-e7cf13955e-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onEnterReconfiguration(ClientPlayNetworkHandler.java:772) ~[minecraft-merged-e7cf13955e-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.network.packet.s2c.play.EnterReconfigurationS2CPacket.apply(EnterReconfigurationS2CPacket.java:23) ~[minecraft-merged-e7cf13955e-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.network.packet.s2c.play.EnterReconfigurationS2CPacket.apply(EnterReconfigurationS2CPacket.java:14) ~[minecraft-merged-e7cf13955e-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:28) ~[minecraft-merged-e7cf13955e-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:149) ~[minecraft-merged-e7cf13955e-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:29) ~[minecraft-merged-e7cf13955e-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:126) ~[minecraft-merged-e7cf13955e-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:120) ~[minecraft-merged-e7cf13955e-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1171) ~[minecraft-merged-e7cf13955e-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:838) ~[minecraft-merged-e7cf13955e-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-merged-e7cf13955e-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]

```

https://github.com/FabricMC/fabric/blob/6dfc9a786d41732780b9543a722a2319cabfeb97/fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientNetworkingImpl.java#L140-L143

I don't _appear_ to experience any issues with assertions disabled (yet; I'm assuming the assert is there for a valid reason).

Minecraft 1.20.4, Fabric 0.96.1+1.20.4

**Comment by apple502j** [comment]
see #3832
