### ISSUE TITLE
ResourceLoader Crash report, 24w11a

### ISSUE THREAD

**Issue by sakura-ryoko** [FabricMC/fabric#3647]
java.lang.NoSuchFieldError: field_25345
        at net.minecraft.resource.ResourcePackManager.handler$zdc000$fabric-resource-loader-v0$construct(ResourcePackManager.java:572)
        at net.minecraft.resource.ResourcePackManager.<init>(ResourcePackManager.java:28)
        at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458)
        at net.minecraft.client.main.Main.main(Main.java:223)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- I was running the game a few times successfully, but now all of a sudden, I cannot.

**Comment by sakura-ryoko** [comment]
[crash-2024-03-14_15.07.00-client.txt](https://github.com/FabricMC/fabric/files/14606995/crash-2024-03-14_15.07.00-client.txt)

**Comment by sakura-ryoko** [comment]
Other Debug log

**Comment by sakura-ryoko** [comment]
[debug.log](https://github.com/FabricMC/fabric/files/14607047/debug.log)
[latest.log](https://github.com/FabricMC/fabric/files/14607048/latest.log)

**Comment by sakura-ryoko** [comment]
gradlew build --refresh-dependencies
fixed the issue
