### ISSUE TITLE
Error launching server fabric-launch-server.jar

### ISSUE THREAD

**Issue by Jubber4442** [FabricMC/fabric#372]
I can't launch my fabric server. All i'm getting is this output:

_[14:25:05] [main/INFO]: Loading for game Minecraft 1.14.4
[14:25:06] [main/INFO]: [FabricLoader] Loading 4 mods: minecraft@1.14.4, fabric-resource-loader-v0@0.1.1+59147463, fabricloader@0.6.2+build.166, quickcarpet@1.12.1+build.2
[14:25:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/home/gs-40405/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[14:25:06] [main/INFO]: Compatibility level set to JAVA_8
[14:25:08] [main/FATAL]: Mixin apply failed quickcarpet.mixins.json:WorldMixin -> net.minecraft.class_1937: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method method_16109 in quickcarpet.mixins.json:WorldMixin was not located in the target class net.minecraft.class_1937. Using refmap quickcarpet-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_16109 in quickcarpet.mixins.json:WorldMixin was not located in the target class net.minecraft.class_1937. Using refmap quickcarpet-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:387) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:363) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:296) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:264) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:244) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1145) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:268) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:874) ~[?:1.8.0_212]
	at net.minecraft.class_2246.<clinit>(class_2246.java:22) ~[intermediary-server.jar:?]
	at net.minecraft.class_2378.method_10237(class_2378.java:77) ~[intermediary-server.jar:?]
	at net.minecraft.class_2378$$Lambda$135.00000000C0C81010.get(Unknown Source) ~[?:?]
	at net.minecraft.class_2378.method_10238(class_2378.java:117) ~[intermediary-server.jar:?]
	at net.minecraft.class_2378$$Lambda$169.00000000C0C1E3A0.accept(Unknown Source) ~[?:?]
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:671) [?:1.8.0_212]
	at net.minecraft.class_2378.<clinit>(class_2378.java:116) [intermediary-server.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:38) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:908) [intermediary-server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]_

**Comment by grondag** [comment]
This appears to be an issue with the QuickCarpet mod and you will need to look to the author of that mod for a resolution.
