### ISSUE TITLE
Error sending packet serverbound/minecraft:chat_session_update

### ISSUE THREAD

**Issue by n0rbyt3** [FabricMC/fabric#3776]
I get the following error when joining a server using Minecraft 1.20.6 with Fabric Loader 0.15.10 and only having "fabric-api 0.98.0+1.20.6" in my mods folder: "Error sending packet serverbound/minecraft:chat_session_update". If I rejoin the server, everything works fine.

Joining the same server with vanilla Minecraft 1.20.6 works without any error on first try.

Shortened log:
```
[15:28:26] [Netty Client IO #6/ERROR]: Error sending packet serverbound/minecraft:chat_session_update
io.netty.handler.codec.EncoderException: Sending unknown packet 'serverbound/minecraft:chat_session_update'
	at net.minecraft.class_9136.method_56426(class_9136.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_9136.encode(class_9136.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:26) ~[client-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:12) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535$2.write(class_2535.java:518) ~[client-intermediary.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:342) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_52917(class_2535.java:337) ~[client-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[15:28:26] [Render thread/WARN]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.EncoderException: Sending unknown packet 'serverbound/minecraft:chat_session_update'
```

**Comment by apple502j** [comment]
Cannot reproduce on a client with Fabric API, when connecting to a dedicated server (both vanilla and Fabric API).

**Comment by apple502j** [comment]
@n0rbyt3 Could you send the server.properties file, client screenshot/video, and the whole client/server log?

**Comment by n0rbyt3** [comment]
@apple502j I do not own the server so I cannot provide any server related files. It's a famous German Minecraft network (GommeHD). I also tried with Hypixel and Cytooxien: both worked on first try.

More interestingly: Joining the network works, however joining a "sub-server" for any specific game doesn't work. They use their own Bungeecord build, so the bug occurs on their site. I'll report it on their support forum directly.

Thank you for testing!
