### ISSUE TITLE
Crashing when Starting game 

### ISSUE THREAD

**Issue by 1upguy** [FabricMC/fabric#378]
It doesn't Launch  and the output says this code
18:03:24.496
Loading for game Minecraft 1.14.4
18:03:30.075

Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:159)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:122)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: raa requires {fabric @ [*]})
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:170)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:603)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:157)
	... 2 more
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:168)
	... 4 more
18:03:30.075
Process crashed with exit code 1

**Comment by 1upguy** [comment]
o nvm i forgot to download the api
