### ISSUE TITLE
Exception thrown when updating world in 1.21

### ISSUE THREAD

**Issue by zly2006** [FabricMC/fabric#3829]
Seems like a simple mixin conflict.

MC version: 1.21 pre3
fabric api: fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.8+0684cd1248

```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/world/chunk/WorldChunk::setBlockEntity(Lnet/minecraft/block/entity/BlockEntity;)V has incompatible changes at opcode 136 in callback fabric-lifecycle-events-v1.client.mixins.json:WorldChunkMixin from mod fabric-lifecycle-events-v1->@Inject::onLoadBlockEntity(Lnet/minecraft/block/entity/BlockEntity;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/entity/BlockEntity;)V.
 Expected: [Lnet/minecraft/util/math/BlockPos;, Lnet/minecraft/block/entity/BlockEntity;]
    Found: [Lnet/minecraft/util/math/BlockPos;, Lnet/minecraft/block/BlockState;]
Available: [Lnet/minecraft/util/math/BlockPos;, Lnet/minecraft/block/BlockState;, Lnet/minecraft/block/BlockState;, Lnet/minecraft/block/entity/BlockEntity;]
	at net.minecraft.world.chunk.WorldChunk.handler$zbh000$fabric-lifecycle-events-v1$onLoadBlockEntity$missing(WorldChunk.java) ~[minecraft-merged-469ace7c49-1.21-pre3-net.fabricmc.yarn.1_21_pre3.1.21-pre3+build.1-v2.jar:?]
	at net.minecraft.world.chunk.WorldChunk.setBlockEntity(WorldChunk.java:398) ~[minecraft-merged-469ace7c49-1.21-pre3-net.fabricmc.yarn.1_21_pre3.1.21-pre3+build.1-v2.jar:?]
	at net.minecraft.world.ChunkSerializer.method_39797(ChunkSerializer.java:413) ~[minecraft-merged-469ace7c49-1.21-pre3-net.fabricmc.yarn.1_21_pre3.1.21-pre3+build.1-v2.jar:?]
	at net.minecraft.world.chunk.WorldChunk.loadEntities(WorldChunk.java:463) ~[minecraft-merged-469ace7c49-1.21-pre3-net.fabricmc.yarn.1_21_pre3.1.21-pre3+build.1-v2.jar:?]
	at net.minecraft.world.chunk.ChunkGenerating.method_60553(ChunkGenerating.java:147) ~[minecraft-merged-469ace7c49-1.21-pre3-net.fabricmc.yarn.1_21_pre3.1.21-pre3+build.1-v2.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 17 more
```

**Comment by apple502j** [comment]
Use the latest Fabric API (note that some mods might have bundled older versions)
