### ISSUE TITLE
20w14infinite fabric API doesn't work

### ISSUE THREAD

**Issue by Davvv1** [FabricMC/fabric#3933]
It seems that the API is looking for exactly 20w14, not 20w14infinite.

```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Fabric API' (fabric) 0.5.7+build.2-20w14infinite with any version that is compatible with:
		 - minecraft 1.16-alpha.20.13.inf
More details:
	 - Mod 'Fabric API' (fabric) 0.5.7+build.2-20w14infinite requires version 1.16-20.w.14 of 'Minecraft' (minecraft), but only the wrong version is present: 1.16-alpha.20.13.inf!
	 - Mod 'Fabric Biomes (v1)' (fabric-biomes-v1) 0.3.0+f01565521d requires version 1.16-20.w.14 of 'Minecraft' (minecraft), but only the wrong version is present: 1.16-alpha.20.13.inf!
	 - Mod 'Fabric Registry Sync (v0)' (fabric-registry-sync-v0) 0.3.0+f01565521d requires version 1.16-20.w.14 of 'Minecraft' (minecraft), but only the wrong version is present: 1.16-alpha.20.13.inf!
	 - Mod 'fabric-particles-v1' (fabric-particles-v1) 0.1.2+f01565521d requires version 1.16-20.w.14 of 'Minecraft' (minecraft), but only the wrong version is present: 1.16-alpha.20.13.inf!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

https://github.com/user-attachments/assets/1c5ff37a-5524-4b5a-b07d-0d802d1fe1da

**Comment by cassiancc** [comment]
As a workaround, this can be resolved by creating a [fabric_loader_dependencies.json](https://github.com/cassiancc/Simply-Infinite/blob/main/config/fabric_loader_dependencies.json) file in your config folder that overrides the Minecraft version Fabric API is looking for. This is what I did for Simply Infinite.

Alternatively, downgrading Fabric Loader to 15.6 will also work.
