### ISSUE TITLE
The game crashes whenever I use the fabric api

### ISSUE THREAD

**Issue by Kagia001** [FabricMC/fabric#398]
I am using multiMC, and after following [the tutorial](https://fabricmc.net/wiki/tutorial:install_with_multimc) to step 3, the game crashes immediatly after launching the instance. If I remove the API from the mods folder, the game works again.

I only have the fabric api in my mods folder.

```
MultiMC version: 0.6.7-1375


Minecraft folder is:
C:/Users/karlg/Programms/MultiMC/instances/Optifine 1.14.4/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


Java is version 1.8.0_191, using 64-bit architecture.


Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/Users/karlg/Programms/MultiMC/instances/Optifine 1.14.4/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/karlg/Programms/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/karlg/Programms/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/karlg/Programms/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/karlg/Programms/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/karlg/Programms/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/karlg/Programms/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/karlg/Programms/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/karlg/Programms/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/karlg/Programms/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/karlg/Programms/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/karlg/Programms/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/karlg/Programms/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/karlg/Programms/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/karlg/Programms/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/karlg/Programms/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/karlg/Programms/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/karlg/Programms/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/karlg/Programms/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/karlg/Programms/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/karlg/Programms/MultiMC/libraries/net/fabricmc/intermediary/1.14.4/intermediary-1.14.4.jar
  C:/Users/karlg/Programms/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.1.1.8/tiny-mappings-parser-0.1.1.8.jar
  C:/Users/karlg/Programms/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.38/sponge-mixin-0.7.11.38.jar
  C:/Users/karlg/Programms/MultiMC/libraries/net/fabricmc/tiny-remapper/0.1.0.40/tiny-remapper-0.1.0.40.jar
  C:/Users/karlg/Programms/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/Users/karlg/Programms/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/ow2/asm/asm/7.1/asm-7.1.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/ow2/asm/asm-analysis/7.1/asm-analysis-7.1.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/ow2/asm/asm-commons/7.1/asm-commons-7.1.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/ow2/asm/asm-tree/7.1/asm-tree-7.1.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/ow2/asm/asm-util/7.1/asm-util-7.1.jar
  C:/Users/karlg/Programms/MultiMC/libraries/net/fabricmc/fabric-loader/0.6.3+build.167/fabric-loader-0.6.3+build.167.jar
  C:/Users/karlg/Programms/MultiMC/libraries/com/mojang/minecraft/1.14.4/minecraft-1.14.4-client.jar

Native libraries:
  C:/Users/karlg/Programms/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/karlg/Programms/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/karlg/Programms/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] fabric-api-0.4.0+build.240-1.14

Params:
  --username  --version MultiMC5 --gameDir C:/Users/karlg/Programms/MultiMC/instances/Optifine 1.14.4/.minecraft --assetsDir C:/Users/karlg/Programms/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 9268


Using onesix launcher.

[17:27:55] [main/INFO]: Loading for game Minecraft 1.14.4
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Mod resolution failed!
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:599)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:157)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:122)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: java.util.zip.ZipError: zip END header not found
	at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1605)
	at com.sun.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1021)
	at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1030)
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at net.fabricmc.loader.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:79)
	at net.fabricmc.loader.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:67)
	at net.fabricmc.loader.discovery.ModResolver$UrlProcessAction.compute(ModResolver.java:453)
	at java.util.concurrent.RecursiveAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Exiting with -1
Process exited with code -1.
```

**Comment by Kagia001** [comment]
After deleting everything (fabric api and multimc) I noticed a bug in firefox causing everything I download to be empty files. After downloading everything with chrome, it works now
