### ISSUE TITLE
[Fabric 1.21] - Issue when launching Fabric 1.21 WITH and WITHOUT mods.

### ISSUE THREAD

**Issue by im-a-dweeb** [FabricMC/fabric#3980]
OS - Arch Linux | badgie DE
Java info:
```
openjdk version "21.0.4" 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7)
OpenJDK 64-Bit Server VM (build 21.0.4+7, mixed mode, sharing)
```
When launching fabric 1.21 with and without mods, this issue appears:
```
Failed to start download.
Name: fabric-loader-0.15.11-1.21.jar
URL: https://piston-data.mojang.com/v1/objects/0e9a07b9bb3390602f977073aa12884a4ce12431/client.jar
Error details: 0x0000000d - generic: Permission denied
Couldn't open file for download
Filename on disk: fabric-loader-0.15.11-1.21.jar
Path: /home/anthony/.minecraft/versions/fabric-loader-0.15.11-1.21/fabric-loader-0.15.11-1.21.jar
Exists: Nonexistent
```

I've tried re-installing fabric and that hasn't worked.

**Comment by modmuss50** [comment]
The Minecraft launcher doesn't have permission to modify the files created by the fabric installer. You likely need to delete these and not run the installer with sudo.

**Comment by im-a-dweeb** [comment]
> The Minecraft launcher doesn't have permission to modify the files created by the fabric installer. You likely need to delete these and not run the installer with sudo.

When I run the command to install fabric, the UI is shown, after I click "install", this error appears:
```
java.nio.file.AccessDeniedException: /home/anthony/.minecraft/versions/fabric-loader-0.15.11-1.21/fabric-loader-0.15.11-1.21.json  at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)  at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)  at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)  at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)  at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:482)  at java.base/java.nio.file.Files.newOutputStream(Files.java:227)  at java.base/java.nio.file.Files.write(Files.java:3492)  at net.fabricmc.installer.client.ClientInstaller.install(ClientInstaller.java:52)  at net.fabricmc.installer.client.ClientHandler.lambda$doInstall$1(ClientHandler.java:105)  at java.base/java.lang.Thread.run(Thread.java:1583)
```

All I could extract from that is a possible write issue to the fabric loader JSON. 

NOTE - I believe this is happening because the files it writes to are root blocked, I'm currently going through and deleting all the root blocked files associated with the install.
