### ISSUE TITLE
[Fabric API 0.101.1] Server crash on start

### ISSUE THREAD

**Issue by Hiusi** [FabricMC/fabric#3997]
When I update fabric api from 0.100.8 to 0.101.1 my server just crashed
```
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2024-08-05 11:22:02
Description: Exception in server tick loop

java.lang.IllegalStateException: Adding duplicate key 'ResourceKey[minecraft:chat_type / minecraft:chat]' to registry
	at net.minecraft.class_2370.method_10272(class_2370.java:133)
	at net.minecraft.class_2378.method_39197(class_2378.java:130)
	at net.minecraft.class_7655.mddfb2d2$fuji$lambda$modifyTheVanillaChatFormat$0$2(class_7655.java:2051)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at net.minecraft.server.MinecraftServer.handler$bnn001$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:6643)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Linux (amd64) version 5.15.0-107-generic
	Java Version: 21.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1160375240 bytes (1106 MiB) / 3439329280 bytes (3280 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700X 8-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 97128.41
	Virtual memory used (MiB): 104075.98
	Swap memory total (MiB): 32768.00
	Swap memory used (MiB): 9032.17
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 99.90, total: 100.00
	Space in storage for workdir (MiB): available: 585996.38, total: 899181.81
	JVM Flags: 2 total; -Xms128M -Xmx10240M
	Fabric Mods: 
		accessories: Accessories 1.0.0-beta.25+1.21
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		adventurez: AdventureZ 1.4.21
		afkplus: AfkPlus 1.5.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		alloy_forgery: Alloy Forgery 2.3.1+1.21
		amplified_nether: Amplified Nether 1.2.5
		appleskin: AppleSkin 3.0.5+mc1.21
		architectury: Architectury 13.0.6
		armoroftheages: Armor of the Ages 1.4.1
		armourers_workshop: Armourer's Workshop 3.0.0-beta.12
		artifacts: Artifacts 12.0.4
			expandability: ExpandAbility 12.0.0
		audioplayer: AudioPlayer 1.21-1.10.2
			admiral: Admiral 0.4.4+1.20.5
		automodpack-bootstrap: AutoModpack bootstrap 1.0.0
			automodpack: AutoModpack 4.0.0-beta12
		badpackets: Bad Packets 0.8.1
		balm-fabric: Balm 21.0.14
			kuma_api: KumaAPI 21.0.4
		bb_preload_world: BB Preload World 1.2
		bclib: BCLib 21.0.10
		beautify: Beautify 1.2.1+1.21
		betterend: Better End 21.0.6
		betterfurniture: Better Furniture 1.21-1.0.5
		betternether: Better Nether 21.0.9
		biomesoplenty: BiomesOPlenty 21.0.0.13
		blabber: Blabber 1.7.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.10.1-1.21
			multipart_entities: MultipartEntities 1.7-1.21
		cardinal-components: Cardinal Components API 6.1.1
			cardinal-components-base: Cardinal Components API (base) 6.1.1
			cardinal-components-block: Cardinal Components API (blocks) 6.1.1
			cardinal-components-chunk: Cardinal Components API (chunks) 6.1.1
			cardinal-components-entity: Cardinal Components API (entities) 6.1.1
			cardinal-components-item: Cardinal Components API (items) 6.1.1
			cardinal-components-level: Cardinal Components API (world saves) 6.1.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 6.1.1
			cardinal-components-world: Cardinal Components API (worlds) 6.1.1
		carryon: Carry On 2.2.1
		charmofundying: Charm of Undying 9.0.0+1.21
			spectrelib: SpectreLib 0.17.1+1.21
		chococraft: Chococraft 4 0.11.5
		chunksending: Chunksending Mod 1.21-2.8
		chunky: Chunky 1.4.16
		cloth-config: Cloth Config v15 15.0.128
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 18.0.0.1
		collective: Collective 7.80
		crafttweaker: CraftTweaker 20.0.19
		craterlib: CraterLib 2.0.2
		creativecore: CreativeCore 2.12.6
			net_neoforged_bus: bus 7.2.0
		cristellib: Cristel Lib 1.2.7
		croptopia: Croptopia 3.0.9
		ctov: ChoiceTheorem's Overhauled Village 3.5.1
		cupboard: cupboard 1.21-2.7
		debugify: Debugify 1.21+1.0
		deuf_refabricated: DEUF Refabricated 1.1.0
		disenchanting_table: Dis-Enchanting Table 3.0.2
		doggytalents: Doggy Talents Next 1.18.27
		dynamiclights: Dynamic Lights 1.8.3+mod
		easy_npc: Easy NPC 5.4.1
		elytraslot: Elytra Slot 9.0.0+1.21
			mixinsquared: MixinSquared 0.1.2-beta.6
		enhancedgroups: Simple Voice Chat Enhanced Groups 1.21-1.6.0
		epherolib: EpheroLib 1.2.0-1.20.6
		fabric-api: Fabric API 0.101.1+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.26+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.15+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.11+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.1+8759e755d1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.14+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.11+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.1+0a3a0057d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.85+b5597344d1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.16.0
			mixinextras: MixinExtras 0.4.0
		fallingtree: FallingTree 1.21.0.6
		fancymenu: FancyMenu 3.2.5
			com_github_keksuccino_japng: japng 0.5.3
			com_github_rtyley_animated-gif-lib-for-java: animated-gif-lib-for-java animated-gif-lib-1.7
		fastasyncworldsave: fastasyncworldsave Mod 1.21-2.0
		faux-custom-entity-data: Faux-Custom-Entity-Data 12.0.1
		ferritecore: FerriteCore 7.0.0
		forgeconfigapiport: Forge Config API Port 21.0.7
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		friendsandfoes: Friends&Foes 2.0.15
		ftblibrary: FTB Library 2100.1.4
		ftbquests: FTB Quests 2100.1.4
			team_reborn_energy: Energy 4.1.0
		ftbteams: FTB Teams 2100.1.0
		fuji: Fuji 1.4.3
			adventure-platform-fabric: adventure-platform-fabric 5.14.0
				net_kyori_adventure-api: adventure-api 4.17.0
				net_kyori_adventure-key: adventure-key 4.17.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.3.3
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.17.0
				net_kyori_adventure-text-serializer-ansi: adventure-text-serializer-ansi 4.17.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.17.0
				net_kyori_adventure-text-serializer-json: adventure-text-serializer-json 4.17.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.17.0
				net_kyori_ansi: ansi 1.0.3
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
				net_kyori_option: option 1.0.0
			com_jayway_jsonpath_json-path: json-path 2.9.0
			commons-io_commons-io: commons-io 2.16.1
			net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.17.0
			net_luckperms_api: api 5.4
			net_minidev_accessors-smart: accessors-smart 2.5.0
			net_minidev_json-smart: json-smart 2.5.0
			org_apache_commons_commons-compress: commons-compress 1.26.2
			org_apache_commons_commons-rng-client-api: commons-rng-client-api 1.6
			org_apache_commons_commons-rng-core: commons-rng-core 1.6
			org_apache_commons_commons-rng-simple: commons-rng-simple 1.6
			org_jetbrains_annotations: annotations 24.0.0
			org_quartz-scheduler_quartz: quartz 2.5.0-rc1
		fwaystones: Fabric Waystones 3.3.3+mc1.21
		geckolib: GeckoLib 4 4.5.7
		glitchcore: GlitchCore 2.0.0.2
			net_jodah_typetools: typetools 0.6.3
		gobber2: Gobber2 2.10.23
			blue_endless_jankson: jankson 1.2.3
			pugh_tools: Pugh Tools 1.8.17
		grassoverhaul: Grass Overhaul 1.0.0
		guarding: Guarding 1.21-2.7.0
		handcrafted: Handcrafted 4.0.1
		hopobettermineshaft: Hopo Better Mineshaft 1.2.7
		hopobetterruinedportal: Hopo Better Ruined Portal 1.4.3
		hopobetterunderwaterruins: Hopo Better Underwater Ruins 1.2.0
		invview: InvView 1.4.15-1.20.5+
		jade: Jade 15.1.5+fabric
		java: OpenJDK 64-Bit Server VM 21
		kiwi: Kiwi Library 15.1.0+fabric
		knightquest: Knight Quest 1.4.2
		konkrete: Konkrete 1.9.9
		letmedespawn: Let Me Despawn 1.3.1
		lithium: Lithium 0.12.7
		lithostitched: Lithostitched 1.2.5
		lootr: Lootr 0.9.35.86
		luckperms: LuckPerms 5.4.137
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
		macawsroofsbop: Macaw's Roofs - BOP 1.21-1.0
		mcwdoors: Macaw's Doors 1.1.1
		mcwfences: Macaw's Fences and Walls 1.1.2
		mcwfencesbop: Macaw's Fences - BOP 1.21-1.0
		mcwfurnitures: Macaw's Furniture 3.3.0
		mcwholidays: Macaw's Holidays 1.1.0
		mcwlights: Macaw's Lights and Lamps 1.1.1
		mcwroofs: Macaw's Roofs 2.3.1
		mcwtrpdoors: Macaw's Trapdoors 1.1.3
		mcwwindows: Macaw's Windows 2.3.2
		melius-vanish: Vanish 1.5.6+1.21
			player-data-api: Player Data API 0.6.0+1.21
		melody: Melody 1.0.10
		mes: Moog's End Structures 1.3.2-1.21-fabric
		midnightlib: MidnightLib 1.5.7
		minecraft: Minecraft 1.21
		mixintrace: MixinTrace 1.1.1+1.17
		mns: Moog's Nether Structures 1.0.2-1.21-fabric
		modernfix: ModernFix 5.19.0+mc1.21
		monolib: MonoLib 1.3.0
		mr_beyondenchant: BeyondEnchant 1.5.0
		mr_catenary: Catenary 1.3
		mr_dungeons_andtaverns: Dungeons and Taverns 1-v4.3
		mr_katters_structures: Katters Structures 2.0
		mr_neoenchant: Neo Enchant+ 5.6.0
		mr_yggdrasil_structure: Yggdrasil 1.4.0
		mru: Mineblock's Repeated Utilities 0.4.4+1.21
			yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
				com_twelvemonkeys_common_common-image: common-image 3.10.0
				com_twelvemonkeys_common_common-io: common-io 3.10.0
				com_twelvemonkeys_common_common-lang: common-lang 3.10.0
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
				org_quiltmc_parsers_gson: gson 0.2.1
				org_quiltmc_parsers_json: json 0.2.1
		mss: Moog's Soaring Structures 1.1.2-1.21-fabric
		mvs: Moog's Voyager Structures 4.1.3-1.21-fabric
		mythicmetals: Mythic Metals 0.20.0+1.21-alpha5
			additionalentityattributes: Additional Entity Attributes 1.8.0+1.21
		natures_spirit: Nature's Spirit 1.6.0-1.21
		naturescompass: Nature's Compass 1.21-2.2.6-fabric
		necronomicon: Necronomicon 1.4.2
		neruina: Neruina 2.1.1
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.17.0
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.17.0
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.17.0
			org_apache_maven_maven-artifact: maven-artifact 3.8.1
			org_kohsuke_github-api: github-api 1.318
		nightautoconfig: Night Auto Config 1.0.6
			com_electronwill_night-config_hocon: hocon 3.8.0
			com_electronwill_night-config_json: json 3.8.0
			com_electronwill_night-config_yaml: yaml 3.8.0
		nochatreports: No Chat Reports 1.21-v2.8.0
		noisium: Noisium 2.2.1+mc1.21
		openpartiesandclaims: Open Parties and Claims 0.23.2
		owo: oωo 0.12.11+1.21
			io_wispforest_endec_jankson: jankson 0.1.3
		packetfixer: Packet Fixer 1.4.1
		paxi: Paxi 1.21-Fabric-5.0.0
		ping-wheel: Ping Wheel 1.9.1
		placeholder-api: Placeholder API 2.4.1+1.21
		polymer-bundled: Polymer 0.9.9+1.21
			polymer-autohost: Polymer (Auto Host) 0.9.9+1.21
				io_netty_netty-codec-http: netty-codec-http 4.1.82
			polymer-blocks: Polymer (Textured Blocks) 0.9.9+1.21
			polymer-common: Polymer (Common) 0.9.9+1.21
				packet_tweaker: Packet Tweaker 0.5.5+1.21
			polymer-core: Polymer (Core) 0.9.9+1.21
				polymer-networking: Polymer (Networking) 0.9.9+1.21
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.9.9+1.21
			polymer-resource-pack: Polymer (Resource Pack) 0.9.9+1.21
			polymer-virtual-entity: Polymer (Virtual Entity) 0.9.9+1.21
		polymorph: Polymorph 1.0.4+1.21
		puzzleslib: Puzzles Lib 21.0.18
		regions_unexplored: Regions Unexplored 0.5.6.1
		repurposed_structures: Repurposed Structures 7.5.4+1.21-fabric
		resourcefullib: Resourceful Lib 3.0.9
			com_teamresourceful_bytecodecs: bytecodecs 1.1.2
			com_teamresourceful_yabn: yabn 1.0.3
		rewardz: RewardZ 1.0.3
		sereneseasons: SereneSeasons 10.0.0.2
		sketch: Sketch 1.21-1.2.0
		smoothchunk: Smooth chunk save Mod 1.21-3.6
		snowrealmagic: Snow! Real Magic! 11.0.2+fabric
		snowundertrees: Snow Under Trees 2.4.0+1.21
		spark: spark 1.10.73
		sparsestructures: SparseStructures 2.2.0
		starterkit: Starter Kit 7.1
		structureessentials: Structure Essentials Mod 1.21-3.4
		t_and_t: Towns and Towers 1.13.2
		tclayer: Accessories Trinkets Compat Layer 3.10.0+beta.5
		tectonic: Tectonic 2.4.0
		terrablender: TerraBlender 4.0.0.1
		totw_modded: Towers of the Wild Modded fabric-1.21-1.0.5
		trashslot: TrashSlot 21.0.2
		travelersbackpack: Traveler's Backpack fabric-1.21-10.0.4
		universal-graves: Universal Graves 3.4.3+1.21
			common-protection-api: Common Protection API 1.0.0
			predicate-api: Predicate API 0.5.1+1.21
			server_translations_api: Server Translations API 2.3.1+1.21-pre2
			sgui: sgui 1.6.0+1.21
		uselessreptile: Useless Reptile 0.7.4.2-1.21
			primitive_multipart_entities: Primitive Multipart Entities 1.1.1
		vanityslots: Vanity Slots 1.4.1+1.21
		veinmining: Vein Mining 5.0.0-beta+1.21
		voicechat: Simple Voice Chat 1.21-2.5.19
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
		worldedit: WorldEdit 7.3.5+6880-8ba3d89
		wover: WorldWeaver 21.0.11
			wover-biome: WorldWeaver - Biome API 21.0.11
			wover-block: WorldWeaver - Block and Item API 21.0.11
			wover-common: WorldWeaver - Common API 21.0.11
			wover-core: WorldWeaver - Core API 21.0.11
			wover-datagen: WorldWeaver - Datagen API 21.0.11
			wover-events: WorldWeaver - Events API 21.0.11
			wover-feature: WorldWeaver - Feature API 21.0.11
			wover-generator: WorldWeaver - World Generator API 21.0.11
			wover-item: WorldWeaver - Item API 21.0.11
			wover-math: WorldWeaver - Math API 21.0.11
			wover-preset: WorldWeaver - World Preset API 21.0.11
			wover-recipe: WorldWeaver - Recipe API 21.0.11
			wover-structure: WorldWeaver - Structure API 21.0.11
			wover-surface: WorldWeaver - Surface API 21.0.11
			wover-tag: WorldWeaver - Tag API 21.0.11
			wover-ui: WorldWeaver - UI API 21.0.11
			wunderlib: WunderLib 21.0.5
		xaerominimap: Xaero's Minimap 24.2.1
		xaeroworldmap: Xaero's World Map 1.38.8
		yungsapi: YUNG's API 1.21-Fabric-5.0.0
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
	Server Running: true
	Player Count: 0 / 100; []
	Active Data Packs: vanilla, fabric, adventurez, armoroftheages (incompatible), artifacts, bclib, betterend, betternether, biomesoplenty (incompatible), bosses_of_mass_destruction, carryon (incompatible), chococraft (incompatible), collective, crafttweaker (incompatible), doggytalents (incompatible), dynamiclights, easy_npc (incompatible), elytraslot (incompatible), fabric-convention-tags-v2, knightquest, mr_beyondenchant, mr_catenary, mr_katters_structures, mr_neoenchant, mr_yggdrasil_structure, neruina (incompatible), regions_unexplored (incompatible), sereneseasons (incompatible), snowrealmagic (incompatible), snowundertrees, t_and_t, terrablender (incompatible), totw_modded, travelersbackpack, uselessreptile, vanityslots, wover-generator, wover-preset, wover-surface, wover-tag, accessories, beautify, disenchanting_table (incompatible), ftbquests, macawsroofsbop, mcwdoors (incompatible), mcwfences (incompatible), mcwfencesbop, mcwholidays (incompatible), mcwroofs (incompatible), mcwtrpdoors (incompatible), server_translations_api, universal-graves, tectonic (incompatible), openpartiesandclaims (incompatible), bundle, balm-fabric (incompatible), mcwlights (incompatible), betterfurniture, charmofundying (incompatible), veinmining (incompatible), ctov, handcrafted, lithostitched (incompatible), repurposed_structures, armourers_workshop, grassoverhaul, additionalentityattributes, alloy_forgery, gobber2, mythicmetals, pugh_tools, fwaystones, melius-vanish, guarding, sketch, audioplayer, mcwfurnitures (incompatible), mcwwindows (incompatible), lootr, friendsandfoes, mr_dungeons_andtaverns, natures_spirit, naturescompass, natures_spirit:modified_savannas (incompatible), natures_spirit:modified_birch_forest (incompatible), natures_spirit:modified_swamp (incompatible), natures_spirit:modified_dark_forest (incompatible), natures_spirit:modified_mountain_biomes (incompatible), natures_spirit:modified_flower_forest (incompatible), natures_spirit:modified_windswept_hills (incompatible), natures_spirit:modified_jungle (incompatible), natures_spirit:modified_desert (incompatible), natures_spirit:modified_badlands (incompatible), amplified_nether (incompatible), croptopia, hopobettermineshaft, hopobetterruinedportal, hopobetterunderwaterruins, mes (incompatible), mns (incompatible), mss (incompatible), mvs (incompatible), starpetals_datapack
	Available Data Packs: vanilla, trade_rebalance, bundle, fabric, accessories, additionalentityattributes, adventurez, alloy_forgery, amplified_nether (incompatible), armoroftheages (incompatible), armourers_workshop, artifacts, audioplayer, balm-fabric (incompatible), bclib, beautify, betterend, betterfurniture, betternether, biomesoplenty (incompatible), bosses_of_mass_destruction, carryon (incompatible), charmofundying (incompatible), chococraft (incompatible), collective, crafttweaker (incompatible), croptopia, ctov, disenchanting_table (incompatible), doggytalents (incompatible), dynamiclights, easy_npc (incompatible), elytraslot (incompatible), fabric-convention-tags-v2, friendsandfoes, ftbquests, fwaystones, gobber2, grassoverhaul, guarding, handcrafted, hopobettermineshaft, hopobetterruinedportal, hopobetterunderwaterruins, knightquest, lithostitched (incompatible), lootr, macawsroofsbop, mcwdoors (incompatible), mcwfences (incompatible), mcwfencesbop, mcwfurnitures (incompatible), mcwholidays (incompatible), mcwlights (incompatible), mcwroofs (incompatible), mcwtrpdoors (incompatible), mcwwindows (incompatible), melius-vanish, mes (incompatible), mns (incompatible), mr_beyondenchant, mr_catenary, mr_dungeons_andtaverns, mr_katters_structures, mr_neoenchant, mr_yggdrasil_structure, mss (incompatible), mvs (incompatible), mythicmetals, natures_spirit, naturescompass, neruina (incompatible), openpartiesandclaims (incompatible), pugh_tools, regions_unexplored (incompatible), repurposed_structures, sereneseasons (incompatible), server_translations_api, sketch, snowrealmagic (incompatible), snowundertrees, t_and_t, terrablender (incompatible), totw_modded, travelersbackpack, universal-graves, uselessreptile, vanityslots, veinmining (incompatible), wover-generator, wover-preset, wover-surface, wover-tag, natures_spirit:modified_swamp (incompatible), natures_spirit:modified_flower_forest (incompatible), natures_spirit:modified_badlands (incompatible), betterend:nourish_extensions, natures_spirit:modified_desert (incompatible), natures_spirit:modified_savannas (incompatible), betterend:patchouli_extensions, natures_spirit:modified_vanilla_trees (incompatible), natures_spirit:modified_jungle (incompatible), natures_spirit:modified_birch_forest (incompatible), betternether:vanilla-hammers_extensions, natures_spirit:modified_mountain_biomes (incompatible), betternether:vanillaexcavators_extensions, natures_spirit:modified_dark_forest (incompatible), natures_spirit:modified_windswept_hills (incompatible), starpetals_datapack, tectonic (incompatible)
	Enabled Feature Flags: minecraft:bundle, minecraft:vanilla
	World Generation: Stable
	World Seed: 4322020094900735437
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by apple502j** [comment]
One of your mod is doing something wrong, this crash is expected. @Patbox It appears you're credited for the buggy code? https://github.com/sakurawald/fuji-fabric/blob/dev/src/main/java/io/github/sakurawald/module/mixin/chat/RegistryLoaderMixin.java#L33

**Comment by Patbox** [comment]
Yeah pretty much you try to override vanilla chat type that already got registered (which is something you should never do, as registries no longer allow for registry replacement). Styled Chat has similar mixin, but it adds a new one instead, so it works fine

**Comment by sakurawald** [comment]
> One of your mod is doing something wrong, this crash is expected. @Patbox It appears you're credited for the buggy code? https://github.com/sakurawald/fuji-fabric/blob/dev/src/main/java/io/github/sakurawald/module/mixin/chat/RegistryLoaderMixin.java#L33

I'm sorry for that, the original code from Patbox is correct, and the modified-version is unstable.
