### ISSUE TITLE
server is running but i can't join when I put mods

### ISSUE THREAD

**Issue by petrzabyak** [FabricMC/fabric#4145]
### Discussed in https://github.com/orgs/FabricMC/discussions/4144

<div type='discussions-op-text'>

<sup>Originally posted by **petrzabyak** October  6, 2024</sup>
### Minecraft Logs

```txt
server@axenthost~ Server is starting...
           |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
           |-- org_quiltmc_parsers_gson 0.2.1
           \-- org_quiltmc_parsers_json 0.2.1
[09:18:46] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/home/container/libraries/net/fabricmc/sponge-mixin/0.15.3+mixin.0.8.7/sponge-mixin-0.15.3+mixin.0.8.7.jar Service=Knot/Fabric Env=SERVER
[09:18:46] [main/INFO]: Compatibility level set to JAVA_17
[09:18:46] [main/INFO]: Preloading Debugify
[09:18:46] [main/WARN]: Reference map 'immersive_paintings-common-refmap.json' for immersive_paintings.mixin.json could not be read. If this is a development environment you can ignore this message
[09:18:46] [main/INFO]: Loaded configuration file for Lithium: 115 options available, 3 override(s) found
[09:18:47] [main/WARN]: Reference map 'memoryleakfix-fabric-1.17+-fabric-refmap.json' for memoryleakfix-fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[09:18:47] [main/INFO]: Loaded configuration file for ModernFix 5.16.1+mc1.20.1: 55 options available, 0 override(s) found
[09:18:47] [main/INFO]: Applying Nashorn fix
[09:18:47] [main/WARN]: Reference map 'molten_metals-common-refmap.json' for molten_metals-common.mixins.json could not be read. If this is a development environment you can ignore this message
[09:18:47] [main/WARN]: Error loading class: net/minecraft/class_906 (java.lang.ClassNotFoundException: net/minecraft/class_906)
[09:18:47] [main/WARN]: @Mixin target net.minecraft.class_906 was not found porting_lib_tool_actions.mixins.json:FishingHookRendererMixin from mod porting_lib_tool_actions
[09:18:47] [main/WARN]: Error loading class: link/infra/indium/renderer/helper/GeometryHelper (java.lang.ClassNotFoundException: link/infra/indium/renderer/helper/GeometryHelper)
[09:18:48] [main/WARN]: Error loading class: net/fabricmc/fabric/impl/client/indigo/renderer/helper/GeometryHelper (java.lang.ClassNotFoundException: net/fabricmc/fabric/impl/client/indigo/renderer/helper/GeometryHelper)
[09:18:48] [main/WARN]: Error loading class: com/firemerald/additionalplacements/common/ConfigCommon (java.lang.ClassNotFoundException: com/firemerald/additionalplacements/common/ConfigCommon)
[09:18:48] [main/WARN]: Error loading class: com/firemerald/additionalplacements/block/AdditionalPlacementBlock (java.lang.ClassNotFoundException: com/firemerald/additionalplacements/block/AdditionalPlacementBlock)
[09:18:48] [main/WARN]: @Mixin target com.firemerald.additionalplacements.block.AdditionalPlacementBlock was not found copycats-common.mixins.json:compat.additionalplacements.PlacementBlockMixin from mod copycats
[09:18:48] [main/WARN]: Error loading class: me/jellysquid/mods/lithium/common/ai/pathing/PathNodeDefaults (java.lang.ClassNotFoundException: me/jellysquid/mods/lithium/common/ai/pathing/PathNodeDefaults)
[09:18:48] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockOcclusionCache)
[09:18:48] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderer (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/BlockRenderer)
[09:18:48] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[09:18:48] [main/WARN]: Force-enabling mixin 'block.hopper.worldedit_compat.WorldChunkMixin' as rule 'mixin.block.hopper.worldedit_compat' (added by mods [lithium-fabric]) enables it
[09:18:48] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[09:18:48] [main/WARN]: Error loading class: net/minecraft/class_5616 (java.lang.ClassNotFoundException: net/minecraft/class_5616)
[09:18:48] [main/WARN]: @Mixin target net.minecraft.class_5616 was not found registrate-fabric.mixins.json:accessor.BlockEntityRenderersAccessor from mod registrate-fabric
[09:18:49] [main/INFO]: [MemoryLeakFix] Will be applying 1 memory leak fixes!
[09:18:49] [main/INFO]: [MemoryLeakFix] Currently enabled memory leak fixes: [biomeTemperatureLeak]
[09:18:49] [main/WARN]: Error loading class: com/firemerald/additionalplacements/block/AdditionalPlacementBlock (java.lang.ClassNotFoundException: com/firemerald/additionalplacements/block/AdditionalPlacementBlock)
[09:18:49] [main/WARN]: Error loading class: com/firemerald/additionalplacements/block/AdditionalPlacementBlock (java.lang.ClassNotFoundException: com/firemerald/additionalplacements/block/AdditionalPlacementBlock)
[09:18:49] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[09:18:53] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=2 on porting_lib_entity.mixins.json:common.LivingEntityMixin from mod porting_lib_entity::handler$ccp000$porting_lib_entity$port_lib$onFinishUsing exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[09:18:53] [main/WARN]: Error loading class: com/firemerald/additionalplacements/block/AdditionalPlacementBlock (java.lang.ClassNotFoundException: com/firemerald/additionalplacements/block/AdditionalPlacementBlock)
[09:18:54] [main/WARN]: Error loading class: com/firemerald/additionalplacements/block/AdditionalPlacementBlock (java.lang.ClassNotFoundException: com/firemerald/additionalplacements/block/AdditionalPlacementBlock)
[09:18:54] [main/WARN]: Error loading class: com/firemerald/additionalplacements/block/AdditionalPlacementBlock (java.lang.ClassNotFoundException: com/firemerald/additionalplacements/block/AdditionalPlacementBlock)
[09:18:54] [main/WARN]: Error loading class: com/firemerald/additionalplacements/block/AdditionalPlacementBlock (java.lang.ClassNotFoundException: com/firemerald/additionalplacements/block/AdditionalPlacementBlock)
[09:18:54] [main/WARN]: Error loading class: com/firemerald/additionalplacements/block/AdditionalPlacementBlock (java.lang.ClassNotFoundException: com/firemerald/additionalplacements/block/AdditionalPlacementBlock)
[09:18:54] [main/INFO]: Injecting BlockStateBase cache population hook into getNeighborPathNodeType from me.jellysquid.mods.lithium.mixin.ai.pathing.AbstractBlockStateMixin
[09:18:54] [main/INFO]: Injecting BlockStateBase cache population hook into getPathNodeType from me.jellysquid.mods.lithium.mixin.ai.pathing.AbstractBlockStateMixin
[09:18:54] [main/INFO]: Injecting BlockStateBase cache population hook into getOpacityIfCached from ca.spottedleaf.starlight.mixin.common.blockstate.BlockStateBaseMixin
[09:18:54] [main/INFO]: Injecting BlockStateBase cache population hook into isConditionallyFullOpaque from ca.spottedleaf.starlight.mixin.common.blockstate.BlockStateBaseMixin
[09:18:54] [main/INFO]: Injecting BlockStateBase cache population hook into getAllFlags from me.jellysquid.mods.lithium.mixin.util.block_tracking.AbstractBlockStateMixin
[09:18:59] [main/WARN]: Static binding violation: PRIVATE @Overwrite method method_21740 in modernfix-common.mixins.json:perf.remove_biome_temperature_cache.BiomeMixin from mod modernfix cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[09:18:59] [main/WARN]: Method overwrite conflict for method_21740 in modernfix-common.mixins.json:perf.remove_biome_temperature_cache.BiomeMixin from mod modernfix, previously written by me.jellysquid.mods.lithium.mixin.world.temperature_cache.BiomeMixin. Skipping method.
[09:18:59] [main/INFO]: Vanilla bootstrap took 9193 milliseconds
[09:19:05] [main/INFO]: Create: Dragon Lib Create Dragon Lib has initialized, ready to support your Create add-ons!
[09:19:05] [main/INFO]: CEI: hyper_experience_orb got converted to hyper_experience_orb
[09:19:05] [main/INFO]: CEI: hyper_experience_bottle got converted to hyper_experience_bottle
[09:19:05] [main/INFO]: Initializing CreateHighPressureMod
[09:19:05] [main/INFO]: Hello 1.20.1 Create!
[09:19:05] [main/INFO]: CreateGoggles init
[09:19:05] [main/INFO]: cgblocks
[09:19:05] [main/INFO]: cgitems
[09:19:05] [main/INFO]: cgblockentities
[09:19:05] [main/INFO]: ResourceKey[minecraft:trim_pattern / creategoggles:goggle]
[09:19:05] [main/INFO]: ResourceKey[minecraft:trim_material / creategoggles:goggle_material]
[09:19:05] [main/INFO]: ResourceKey[minecraft:root / minecraft:trim_pattern]
[09:19:05] [main/INFO]: CGItemModifiers register false
[09:19:05] [main/INFO]: CreateGogglesFabric init
[09:19:05] [main/INFO]: Create addon mod [Create: Crystallized] is loading alongside Create [0.5.1f]!
[09:19:05] [main/INFO]: Create: Crystallized is accessing Porting Lib from the server!
[09:19:05] [main/INFO]: GroupRegister Loaded
[09:19:05] [main/INFO]: ItemRegister Loaded
[09:19:05] [main/INFO]: FluidRegistrate Loaded
[09:19:05] [main/INFO]: Registering Crystallized Resource Pack
[09:19:05] [main/INFO]: Enabled 34 bug fixes: [MC-2025, MC-7569, MC-8187, MC-14923, MC-30391, MC-31819, MC-69216, MC-72151, MC-88371, MC-89146, MC-90084, MC-93018, MC-100991, MC-119417, MC-119754, MC-121706, MC-121903, MC-124117, MC-129909, MC-132878, MC-135971, MC-155509, MC-160095, MC-179072, MC-183990, MC-193343, MC-199467, MC-200418, MC-206922, MC-215530, MC-223153, MC-224729, MC-231743, MC-232869]
[09:19:05] [main/INFO]: Successfully Debugify'd your game!
[09:19:06] [main/INFO]: Registering configs
[09:19:06] [main/INFO]: Registering blocks
[09:19:06] [main/INFO]: Registering items
[09:19:06] [main/INFO]: Registering item groups
[09:19:06] [main/INFO]: Registering entities
[09:19:06] [main/INFO]: Registering tags
[09:19:06] [main/INFO]: Registering event handlers
[09:19:06] [main/INFO]: Compression will use libdeflate (Linux x86_64), encryption will use OpenSSL 3.0.x (Linux x86_64)
[09:19:06] [main/INFO]: Definitely not up to no good
[09:19:06] [main/INFO]: Loaded config molten_metals-common.json
[09:19:07] [main/INFO]: Registered bogey styles from railways
[09:19:07] [main/INFO]: Registering data fixers
[09:19:07] [main/INFO]: Bypassed Mojang DFU
[09:19:07] [main/INFO]: Instantiating Mojang DFU
[09:19:08] [main/INFO]: 0 Datafixer optimizations took 0 milliseconds
[09:19:08] [main/INFO]: Registering tracks for Hex Casting
[09:19:08] [main/INFO]: Registering tracks for Oh The Biomes You'll Go
[09:19:08] [main/INFO]: Registering tracks for Blue Skies
[09:19:08] [main/INFO]: Registering tracks for Twilight Forest
[09:19:08] [main/INFO]: Registering tracks for Biomes O' Plenty
[09:19:08] [main/INFO]: [Fabric Seasons] Trying to read config file...
[09:19:08] [main/INFO]: [Fabric Seasons] A config file was found, loading it..
[09:19:08] [main/INFO]: [Fabric Seasons] Successfully loaded config file.
[09:19:08] [main/INFO]: [Spawn Animations] Loaded Spawn Animations by Tschipcraft successfully!
[09:19:08] [main/INFO]: Registered the FluidEffect with Unique ID of minecraft:water for minecraft:water 81000 with the ID 0
[09:19:08] [main/INFO]: Registered the FluidEffect with Unique ID of minecraft:lava for minecraft:lava 81000 with the ID 1
[09:19:08] [main/INFO]: Registered the FluidEffect with Unique ID of travelersbackpack:potion for travelersbackpack:potion_still 27000 with the ID 2
[09:19:08] [main/INFO]: Registered the FluidEffect with Unique ID of travelersbackpack:milk for travelersbackpack:milk_still 81000 with the ID 3
[09:19:08] [main/INFO]: [voicechat] Compatibility version 18
[09:19:08] [main/INFO]: [voicechat] Loading plugins
[09:19:08] [main/INFO]: [voicechat] Loaded 0 plugin(s)
[09:19:08] [main/INFO]: [voicechat] Initializing plugins
[09:19:08] [main/INFO]: [voicechat] Initialized 0 plugin(s)
[09:19:10] [main/INFO]: Got request to register class com.sk89q.worldedit.fabric.FabricPlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@af994bd]
[09:19:10] [main/INFO]: WorldEdit for Fabric (version 7.2.15+6463-5ca4dff) is loaded
[09:19:10] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'contentcreatorintegration' at 'me.ichun.mods.cci.common.ContentCreatorIntegration'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.5.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.5.jar:?]
Caused by: java.lang.NoSuchFieldError: Class me.lortseam.completeconfig.data.BooleanEntry does not have member field 'boolean checkbox'
        at me.lortseam.completeconfig.data.BooleanEntry.<init>(BooleanEntry.java:26) ~[completeconfig-base-2.4.1-6412c4717b71dbc2.jar:?]
        at me.lortseam.completeconfig.data.Entry.create(Entry.java:42) ~[completeconfig-base-2.4.1-6412c4717b71dbc2.jar:?]
        at me.lortseam.completeconfig.data.EntrySet.lambda$resolve$1(EntrySet.java:31) ~[completeconfig-base-2.4.1-6412c4717b71dbc2.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at me.lortseam.completeconfig.data.EntrySet.resolve(EntrySet.java:32) ~[completeconfig-base-2.4.1-6412c4717b71dbc2.jar:?]
        at me.lortseam.completeconfig.data.Parent.resolveContainer(Parent.java:58) ~[completeconfig-base-2.4.1-6412c4717b71dbc2.jar:?]
        at me.lortseam.completeconfig.data.ClusterSet.resolve(ClusterSet.java:13) ~[completeconfig-base-2.4.1-6412c4717b71dbc2.jar:?]
        at me.lortseam.completeconfig.data.Parent.resolve(Parent.java:108) ~[completeconfig-base-2.4.1-6412c4717b71dbc2.jar:?]
        at me.lortseam.completeconfig.data.Parent.lambda$resolveContainer$6(Parent.java:97) ~[completeconfig-base-2.4.1-6412c4717b71dbc2.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at me.lortseam.completeconfig.data.Parent.resolveContainer(Parent.java:97) ~[completeconfig-base-2.4.1-6412c4717b71dbc2.jar:?]
        at me.lortseam.completeconfig.data.Parent.resolve(Parent.java:110) ~[completeconfig-base-2.4.1-6412c4717b71dbc2.jar:?]
        at me.lortseam.completeconfig.data.Config.lambda$new$0(Config.java:52) ~[completeconfig-base-2.4.1-6412c4717b71dbc2.jar:?]
        at me.lortseam.completeconfig.data.Config.deserialize(Config.java:94) ~[completeconfig-base-2.4.1-6412c4717b71dbc2.jar:?]
        at me.lortseam.completeconfig.data.Config.load(Config.java:121) ~[completeconfig-base-2.4.1-6412c4717b71dbc2.jar:?]
        at me.ichun.mods.cci.common.ContentCreatorIntegration.onInitialize(ContentCreatorIntegration.java:160) ~[ContentCreatorIntegration-1.20.1-Fabric-1.11.1.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.5.jar:?]
        ... 6 more
```

### Description

![image](https://github.com/user-attachments/assets/b4742646-0815-43cc-be72-f954b018f1b1)
</div>

**Comment by DJR-dev** [comment]
modernfix has been having issues, check if thats the cause.
