### ISSUE TITLE
Non-player entities elytra flying causes a crash

### ISSUE THREAD

**Issue by nekoblitz** [FabricMC/fabric#4217]
Summoning an entity that is gliding, both without
`/summon husk ~ ~ ~ {FallFlying:1b}`
And with elytra
`/summon husk ~ ~ ~ {FallFlying:1b,ArmorItems:[{},{},{id:"minecraft:elytra",count:1},{}]}`
Causes the game to crash, as below:
```
java.lang.ClassCastException: class net.minecraft.class_1576 cannot be cast to class net.minecraft.class_1657 (net.minecraft.class_1576 and net.minecraft.class_1657 are in unnamed module of loader 'knot' @28d25987)
	at knot//net.minecraft.class_1309.handler$zoe000$fabric-entity-events-v1$injectElytraCheck(class_1309.java:5440)
	at knot//net.minecraft.class_1309.method_63628(class_1309.java:2989)
	at knot//net.minecraft.class_1309.method_6053(class_1309.java:2962)
	at knot//net.minecraft.class_1309.method_6007(class_1309.java:2897)
	at knot//net.minecraft.class_1308.method_6007(class_1308.java:571)
	at knot//net.minecraft.class_1588.method_6007(class_1588.java:45)
	at knot//net.minecraft.class_1642.method_6007(class_1642.java:264)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2595)
	at knot//net.minecraft.class_1308.method_5773(class_1308.java:371)
	at knot//net.minecraft.class_1642.method_5773(class_1642.java:236)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:761)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:501)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:406)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:376)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1069)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:953)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:713)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
	at java.base/java.lang.Thread.run(Unknown Source)
```
The crash log is attached below. 
[crash-2024-11-08_14.13.19-server.txt](https://github.com/user-attachments/files/17679167/crash-2024-11-08_14.13.19-server.txt)

**Comment by modmuss50** [comment]
Thanks for the clear report, 0.107.3 is now releasing with a fix for this.
