### ISSUE TITLE
<html>RuntimeException: Error creating Mixin config fabric-events-interaction-v0.mixins.json for mod<br>fabric-events-interaction-v0</html>

### ISSUE THREAD

**Issue by Itsmetibo** [FabricMC/fabric#4245]
Caused by: java.lang.IllegalArgumentException: The specified resource 'fabric-events-interaction-v0.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1405) ~[?:?]
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:163) ~[?:?]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:121) ~[?:?]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:108) ~[?:?]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:98) ~[?:?]
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94) ~[?:?]
	... 3 more
Caused by: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at java.base/sun.security.util.SignatureFileVerifier.processImpl(Unknown Source) ~[?:?]
	at java.base/sun.security.util.SignatureFileVerifier.process(Unknown Source) ~[?:?]
	at java.base/java.util.jar.JarVerifier.processEntry(Unknown Source) ~[?:?]
	at java.base/java.util.jar.JarVerifier.update(Unknown Source) ~[?:?]
	at java.base/java.util.jar.JarFile.initializeVerifier(Unknown Source) ~[?:?]
	at java.base/java.util.jar.JarFile.getInputStream(Unknown Source) ~[?:?]
	at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(Unknown Source) ~[?:?]
	at java.base/java.net.URLClassLoader.getResourceAsStream(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.getResourceAsStream(KnotClassLoader.java:95) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.getResourceAsStream(Knot.java:303) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getResourceAsStream(MixinServiceKnot.java:191) ~[?:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1393) ~[?:?]
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:163) ~[?:?]
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:121) ~[?:?]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:108) ~[?:?]
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:98) ~[?:?]
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94) ~[?:?]
	... 3 more

**Comment by Itsmetibo** [comment]
version of mc is 1.21 fabric is 0.16.7
