### ISSUE TITLE
Fabric API crashing the server when interacting (right-clicking) at entity (1.14-combat3)

### ISSUE THREAD

**Issue by rizecookey** [FabricMC/fabric#432]
When right-clicking an entity on a server (1.14-combat3) running the Fabric API, the server crashes with the following error message:

```
 [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.class_3966.<init>(Lnet/minecraft/class_1297;Lnet/minecraft/class_243;)V
        at net.minecraft.class_3244.handler$onPlayerInteractEntity$zbc000(class_3244.java:2006) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12062(class_3244.java:1169) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_12251(class_2824.java:70) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:712) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:706) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:691) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:646) [intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Comment by modmuss50** [comment]
Yeah, we never released a proper version of fabric api for the combat updates.

I didn’t really expect people to actually use it :)

**Comment by rizecookey** [comment]
Yeah, I wanted to use Fabric as a sort-of alternative to other server software to make a combat preview server with a few gamemodes (mainly to do a few things that aren't possible on a vanilla server) for pvp players to test the combat in game modes they know from their standard minigame servers :)
Would releasing a seperate API version for the combat snapshot be hard? There don't seem to many other changes from standard 1.14.4 in that version.

**Comment by modmuss50** [comment]
If you don’t need it you could remove the interaction module from API.

As for releasing a specific version for it I don’t think I’ll do it for this version. As far as I know there is a new combat version coming out next week, I could consider releasing an API version for it.

Now that I know there is a bit of interest in it, it may be worth the time.

**Comment by liach** [comment]
this bug has been in earlier combat versions fyi.

**Comment by modmuss50** [comment]
Closing as I dont think we plan on support the combat snapshots with api
