### ISSUE TITLE
FabricAPI crash

### ISSUE THREAD

**Issue by woozeq** [FabricMC/fabric#451]
when I paste fabricAPI to .minecraft/mods folder, can't start game. w/o api, it starts normally 

---- Minecraft Crash Report ----
// Don't do that.

Time: 02.12.19 20:47
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:55)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.reflect.UndeclaredThrowableException
		at com.sun.proxy.$Proxy22.onInitializeClient(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$1391/1172188074.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:48)
		... 12 more
	Caused by: java.lang.reflect.InvocationTargetException
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at net.fabricmc.loader.util.DefaultLanguageAdapter$1.invoke(DefaultLanguageAdapter.java:122)
		... 15 more
	Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/network/PacketTypes
		at net.fabricmc.fabric.impl.client.gui.ScreenProviderRegistryImpl.init(ScreenProviderRegistryImpl.java:66)
		... 20 more
	Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.network.PacketTypes
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:55)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 726820032 bytes (693 MB) / 1610612736 bytes (1536 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecs: Amecs 1.2.6+1.14.4
		chunkborders: ChunkBorders 0.4.1
		cloth: Cloth Events 0.6.0
		cloth-config2: Cloth Config v2 1.7.3
		fabric: Fabric API 0.4.0+build.240-1.14
		fabric-api-base: Fabric API Base 0.1.2+b7f9825de8
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.0+591e97ae42
		fabric-commands-v0: Fabric Commands (v0) 0.1.1+591e97ae42
		fabric-containers-v0: Fabric Containers (v0) 0.1.2+591e97ae42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.1+591e97ae42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.1+591e97ae42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.0+369ab22e42
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.2+27da48aa46
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825de8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.0+591e97ae42
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+591e97ae42
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.0+591e97ae42
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825de8
		fabric-models-v0: Fabric Models (v0) 0.1.0+591e97ae42
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.0+c877038942
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed975
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.1+591e97ae42
		fabric-particles-v1: fabric-particles-v1 0.1.1+c877038942
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.2+591e97ae42
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+591e97ae42
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.13+591e97ae42
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.1+c877038942
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.2+36f27aa342
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.1+591e97ae42
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.3+591e97ae42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.2+b7f9825de8
		fabric-textures-v0: Fabric Textures (v0) 0.1.4+591e97ae42
		fabricloader: Fabric Loader 0.7.2+build.174
		fiber2cloth: Fiber To Cloth 1.2.1
		malilib: MaLiLib 0.10.0-dev.20
		me_zeroeightsix_fiber: fiber 0.6.0-7
		minecraft: Minecraft 1.14.4
		minihud: MiniHUD 0.19.0-dev.20190825.170729
		mousewheelie: Mouse Wheelie 1.3.6+1.14.4
		roughlyenoughitems: Roughly Enough Items 3.2.8+build.51
		tweed: Tweed API 2.2.8
	Launched Version: fabric-loader-0.7.2+build.174-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

**Comment by liach** [comment]
Try with fabric api 0.4.1+build.245
