### ISSUE TITLE
i cant load minecraft with this mod w/o crashing

### ISSUE THREAD

**Issue by ttdhr-00** [FabricMC/fabric#453]
I use MultiMC for Minecraft. I have the standard `javaw` Java path, I have 7680-8000MB allocated to my instance, I have _optifine_ as a jar mod, and besides FabricAPI, i have _worldedit_, _minihub_, _MaLiLib_, and _litematica_ loaded into a 1.14.4 fabric minecraft instance. Idk whats wrong

### Edit: Here's the Crash Log

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 12/5/19 5:01 PM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_761.<init>(class_761.java:283)
	at net.minecraft.class_310.method_1503(class_310.java:569)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:188)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirect$hookChunkBuildTesselate$zzo000(Lnet/minecraft/class_776;Lnet/minecraft/class_2680;Lnet/minecraft/class_2338;Lnet/minecraft/class_1920;Lnet/minecraft/class_287;Ljava/util/Random;)Z in fabric-renderer-indigo.mixins.json:MixinChunkRenderer failed injection check, (0/1) succeeded. Using refmap fabric-renderer-indigo-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1203)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:939)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:323)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_761.<init>(class_761.java:283)
	at net.minecraft.class_310.method_1503(class_310.java:569)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:188)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7139546216 bytes (6808 MB) / 7829192704 bytes (7466 MB) up to 7829192704 bytes (7466 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms7680m -Xmx8000m
	Fabric Mods: 
		fabric: Fabric API 0.4.1+build.245-1.14
		fabric-api-base: Fabric API Base 0.1.1+2ac73e7242
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.0+591e97ae42
		fabric-commands-v0: Fabric Commands (v0) 0.1.1+591e97ae42
		fabric-containers-v0: Fabric Containers (v0) 0.1.2+591e97ae42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.1+591e97ae42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.1+591e97ae42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.0+369ab22e42
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.1.1+591e97ae42
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.1+591e97ae42
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.0+591e97ae42
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+591e97ae42
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.0+591e97ae42
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.0+591e97ae42
		fabric-models-v0: Fabric Models (v0) 0.1.0+591e97ae42
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.0+c877038942
		fabric-networking-v0: Fabric Networking (v0) 0.1.3+591e97ae42
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.1+591e97ae42
		fabric-particles-v1: fabric-particles-v1 0.1.1+c877038942
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.2+591e97ae42
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+591e97ae42
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.13+591e97ae42
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.1+c877038942
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.2+36f27aa342
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.1+591e97ae42
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.3+591e97ae42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.1+591e97ae42
		fabric-textures-v0: Fabric Textures (v0) 0.1.4+591e97ae42
		fabricloader: Fabric Loader 0.6.4+build.169
		litematica: Litematica 0.0.0-dev.20190720.191654
		malilib: MaLiLib 0.10.0-dev.20
		minecraft: Minecraft 1.14.4
		minihud: MiniHUD 0.19.0-dev.20191007.003640
		worldedit: WorldEdit 7.0.1;61bc012
	Launched Version: MultiMC5
	LWJGL: 3.2.2 build 10
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4642, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Enchantment-Textures, file/Animated-Mobs-Pack
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz

**Comment by modmuss50** [comment]
Is there a crash log?

**Comment by Juuxel** [comment]
> I have *optifine* as a jar mod

I feel like this might cause incompatibilities.

**Comment by modmuss50** [comment]
Ah yeah, that will be the cause. Use OptiFabric if you need optifine

**Comment by ttdhr-00** [comment]
> Ah yeah, that will be the cause. Use OptiFabric if you need optifine

I tried, and it didnt work

**Comment by liach** [comment]
do you mean jar mod by running the optifine installer? you don't run the installer but just dump the optifine jar to mods folder together with optifabric jar

**Comment by ttdhr-00** [comment]
> do you mean jar mod by running the optifine installer?

I disabled the jar mod and added a new optifine jar aswell as the optifabric to the `mods` folder
still didnt work

**Comment by liach** [comment]
> I disabled the jar mod

post the new crash report/log

**Comment by ttdhr-00** [comment]
> post the new crash report/log

_there was no crash log_

### heres the startup log:

MultiMC version: 0.6.7-1375


Minecraft folder is:
C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/instances/1.14.4/.minecraft


Java path is:
C:/ProgramData/Oracle/Java/javapath/javaw.exe


Java is version 1.8.0_151, using 64-bit architecture.


Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/instances/1.14.4/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/net/fabricmc/intermediary/1.14.4/intermediary-1.14.4.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.0.11/tiny-mappings-parser-0.2.0.11.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.38/sponge-mixin-0.7.11.38.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/net/fabricmc/tiny-remapper/0.2.0.52/tiny-remapper-0.2.0.52.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm/7.1/asm-7.1.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-analysis/7.1/asm-analysis-7.1.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-commons/7.1/asm-commons-7.1.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-tree/7.1/asm-tree-7.1.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-util/7.1/asm-util-7.1.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/net/fabricmc/fabric-loader/0.6.4+build.169/fabric-loader-0.6.4+build.169.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.14.4/minecraft-1.14.4-client.jar

Native libraries:
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] fabric-api-0.4.1+build.245-1.14
  [✔️] litematica-fabric-1.14.4-0.0.0-dev.20190720.191654
  [✔️] malilib-fabric-1.14.4-0.10.0-dev.20
  [✔️] minihud-fabric-1.14.4-0.19.0-dev.20191007.003640
  [✔️] optifabric-0.7.0
  [✔️] OptiFine_1.14.4_HD_U_F3
  [✔️] worldedit-fabric-mc1.14.4-7.0.1

Params:
  --username  --version MultiMC5 --gameDir C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/instances/1.14.4/.minecraft --assetsDir C:/My Important Files/Software Files/mmc-stable-win32/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms7680m, -Xmx8000m, -Duser.language=en]


Minecraft process ID: 13324


Using onesix launcher.

[17:26:46] [main/INFO]: Loading for game Minecraft 1.14.4
[17:26:51] [main/INFO]: [FabricLoader] Loading 39 mods: minecraft@1.14.4, fabric-renderer-api-v1@0.1.1+591e97ae42, fabric-networking-blockentity-v0@0.2.0+c877038942, fabric-keybindings-v0@0.1.1+591e97ae42, fabricloader@0.6.4+build.169, org_zeroturnaround_zt-zip@1.13, fabric-renderer-indigo@0.1.13+591e97ae42, fabric-containers-v0@0.1.2+591e97ae42, fabric-dimensions-v1@0.1.0+369ab22e42, fabric-biomes-v1@0.1.0+591e97ae42, fabric-events-interaction-v0@0.1.1+591e97ae42, fabric-crash-report-info-v1@0.1.1+591e97ae42, org_slf4j_slf4j-simple@1.7.29, fabric-api-base@0.1.1+2ac73e7242, fabric-rendering-v0@0.1.1+591e97ae42, mm@1.8, fabric-rendering-data-attachment-v1@0.1.1+c877038942, fabric-resource-loader-v0@0.1.3+591e97ae42, malilib@0.10.0-dev.20, fabric-textures-v0@0.1.4+591e97ae42, fabric-content-registries-v0@0.1.1+591e97ae42, fabric-tag-extensions-v0@0.1.1+591e97ae42, worldedit@7.0.1;61bc012, optifabric@0.7.0, fabric-rendering-fluids-v1@0.1.2+36f27aa342, litematica@0.0.0-dev.20190720.191654, fabric-commands-v0@0.1.1+591e97ae42, fabric-registry-sync-v0@0.2.2+591e97ae42, fabric-mining-levels-v0@0.1.0+591e97ae42, minihud@0.19.0-dev.20191007.003640, fabric-events-lifecycle-v0@0.1.1+591e97ae42, fabric-loot-tables-v1@0.1.0+591e97ae42, fabric@0.4.1+build.245-1.14, org_slf4j_slf4j-api@1.7.29, fabric-item-groups-v0@0.1.0+591e97ae42, fabric-particles-v1@0.1.1+c877038942, fabric-models-v0@0.1.0+591e97ae42, fabric-object-builders-v0@0.1.1+591e97ae42, fabric-networking-v0@0.1.3+591e97ae42
[17:26:51] [main/WARN]: Mod `worldedit` (7.0.1;61bc012) does not respect SemVer - comparison support is limited.
[17:26:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/My%20Important%20Files/Software%20Files/mmc-stable-win32/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.38/sponge-mixin-0.7.11.38.jar Service=Knot/Fabric Env=CLIENT
[17:26:51] [main/INFO]: Compatibility level set to JAVA_8
java.lang.NoSuchMethodError: org.spongepowered.asm.mixin.transformer.ext.ITargetClassContext.getClassNode()Lorg/objectweb/asm/tree/ClassNode;
	at com.chocohead.mm.Extension.postApply(Extension.java:30)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:162)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:706)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:188)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:190)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:188)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main.main(Main.java:155)
	... 15 more
Caused by: java.lang.NoSuchMethodError: org.spongepowered.asm.mixin.transformer.ext.ITargetClassContext.getClassNode()Lorg/objectweb/asm/tree/ClassNode;
	at com.chocohead.mm.Extension.postApply(Extension.java:30)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:162)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:706)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 19 more
Exiting with -1
2019-12-05 17:26:53,898 Client Shutdown Thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
java.lang.NoSuchMethodError: org.spongepowered.asm.mixin.transformer.ext.ITargetClassContext.getClassNode()Lorg/objectweb/asm/tree/ClassNode;
	at com.chocohead.mm.Extension.postApply(Extension.java:30)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:162)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:706)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main$2.run(Main.java:138)
Process exited with code -1.

**Comment by modmuss50** [comment]
You need to update fabric loader.
