### ISSUE TITLE
Fabric API crashes server

### ISSUE THREAD

**Issue by MSandro** [FabricMC/fabric#486]
I am using latest Fabric Server and Fabric API for 1.15.1 but it is crashing.

```
[22:08:33] [main/INFO]: Loading for game Minecraft 1.15.1
[22:08:33] [main/INFO]: [FabricLoader] Loading 33 mods: fabric-renderer-api-v1@0.2.7+f3d8141b95, minecraft@1.15.1, fabric-networking-blockentity-v0@0.2.3+e08a730595, fabric-keybindings-v0@0.1.1+dfdb52d695, fabricloader@0.7.3+build.176, fabric-renderer-indigo@0.2.21+175d0eb895, fabric-containers-v0@0.1.3+b7f9825d95, fabric-dimensions-v1@0.2.3+06c939b395, fabric-biomes-v1@0.1.5+3b05f68e95, fabric-crash-report-info-v1@0.1.2+b7f9825d95, fabric-events-interaction-v0@0.2.7+a1bd311895, fabric-api-base@0.1.2+b7f9825d95, fabric-rendering-v0@1.1.0+5341049095, fabric-rendering-v1@0.1.0+5341049095, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d95, fabric-resource-loader-v0@0.1.10+06c939b395, fabric-textures-v0@1.0.4+821cdba795, fabric-content-registries-v0@0.1.3+b7f9825d95, fabric-tag-extensions-v0@0.1.3+abd9158095, fabric-rendering-fluids-v1@0.1.6+12515ed995, fabric-registry-sync-v0@0.2.6+f3d8141b95, fabric-commands-v0@0.1.2+b7f9825d95, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8995, fabric-mining-levels-v0@0.1.1+b7f9825d95, fabric-renderer-registries-v1@2.0.1+5a0f9a6095, fabric-loot-tables-v1@0.1.5+e08a730595, fabric-events-lifecycle-v0@0.1.2+b7f9825d95, fabric@0.4.27+build.286-1.15, fabric-particles-v1@0.1.1+dfdb52d695, fabric-item-groups-v0@0.1.6+ec40b2e195, fabric-models-v0@0.1.0+dfdb52d695, fabric-networking-v0@0.1.7+12515ed995, fabric-object-builders-v0@0.1.3+e4c9a9c395
[22:08:33] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/home/sandro/Downloads/fabricServer/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_2817 (java.lang.ClassNotFoundException: net/minecraft/class_2817)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_2817 was not found fabric-networking-v0.mixins.json:MixinCustomPayloadC2SPacket
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3898$class_3208 (java.lang.ClassNotFoundException: net/minecraft/class_3898$class_3208)
[22:08:33] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 was not found fabric-networking-v0.mixins.json:MixinEntityTracker
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3324 (java.lang.ClassNotFoundException: net/minecraft/class_3324)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3324 was not found fabric-networking-v0.mixins.json:MixinPlayerManager
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3244 (java.lang.ClassNotFoundException: net/minecraft/class_3244)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3244 was not found fabric-networking-v0.mixins.json:MixinServerPlayNetworkHandler
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3898 (java.lang.ClassNotFoundException: net/minecraft/class_3898)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3898 was not found fabric-networking-v0.mixins.json:MixinThreadedAnvilChunkStorage
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_2586 (java.lang.ClassNotFoundException: net/minecraft/class_2586)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_2586 was not found fabric-networking-blockentity-v0.mixins.json:MixinBlockEntity
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3655 (java.lang.ClassNotFoundException: net/minecraft/class_3655)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3655 was not found fabric-biomes-v1.mixins.json:MixinAddEdgeBiomesLayer
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3648 (java.lang.ClassNotFoundException: net/minecraft/class_3648)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3648 was not found fabric-biomes-v1.mixins.json:MixinAddHillsLayer
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3652 (java.lang.ClassNotFoundException: net/minecraft/class_3652)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3652 was not found fabric-biomes-v1.mixins.json:MixinAddRiversLayer
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_1966 (java.lang.ClassNotFoundException: net/minecraft/class_1966)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_1966 was not found fabric-biomes-v1.mixins.json:MixinBiomeSource
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3640 (java.lang.ClassNotFoundException: net/minecraft/class_3640)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3640 was not found fabric-biomes-v1.mixins.json:MixinSetBaseBiomesLayer
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_2088 (java.lang.ClassNotFoundException: net/minecraft/class_2088)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_2088 was not found fabric-biomes-v1.mixins.json:MixinVanillaLayeredBiomeSource
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_1863 (java.lang.ClassNotFoundException: net/minecraft/class_1863)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_1863 was not found fabric-resource-loader-v0.mixins.json:MixinKeyedResourceReloadListener$Server
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_2989 (java.lang.ClassNotFoundException: net/minecraft/class_2989)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_2989 was not found fabric-resource-loader-v0.mixins.json:MixinKeyedResourceReloadListener$Server
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_2991 (java.lang.ClassNotFoundException: net/minecraft/class_2991)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_2991 was not found fabric-resource-loader-v0.mixins.json:MixinKeyedResourceReloadListener$Server
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_60 (java.lang.ClassNotFoundException: net/minecraft/class_60)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_60 was not found fabric-resource-loader-v0.mixins.json:MixinKeyedResourceReloadListener$Server
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3505 (java.lang.ClassNotFoundException: net/minecraft/class_3505)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3505 was not found fabric-resource-loader-v0.mixins.json:MixinKeyedResourceReloadListener$Server
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3304 (java.lang.ClassNotFoundException: net/minecraft/class_3304)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3304 was not found fabric-resource-loader-v0.mixins.json:MixinReloadableResourceManagerImpl
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3268 (java.lang.ClassNotFoundException: net/minecraft/class_3268)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3268 was not found fabric-resource-loader-v0.mixins.json:MixinDefaultResourcePack
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_1766 (java.lang.ClassNotFoundException: net/minecraft/class_1766)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_1766 was not found fabric-mining-levels-v0.mixins.json:MiningToolItemAccessor
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_1799 (java.lang.ClassNotFoundException: net/minecraft/class_1799)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_1799 was not found fabric-mining-levels-v0.mixins.json:MixinItemStack
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3222 (java.lang.ClassNotFoundException: net/minecraft/class_3222)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3222 was not found fabric-containers-v0.mixins.json:ServerPlayerEntityAccessor
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_2248$class_2251 (java.lang.ClassNotFoundException: net/minecraft/class_2248$class_2251)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_2248$class_2251 was not found fabric-object-builders-v0.mixins.json:BlockSettingsHooks
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3614$class_3615 (java.lang.ClassNotFoundException: net/minecraft/class_3614$class_3615)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3614$class_3615 was not found fabric-object-builders-v0.mixins.json:MaterialBuilderHooks
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_2248 (java.lang.ClassNotFoundException: net/minecraft/class_2248)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_2248 was not found fabric-object-builders-v0.mixins.json:MixinBlock
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_1792 (java.lang.ClassNotFoundException: net/minecraft/class_1792)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_1792 was not found fabric-object-builders-v0.mixins.json:MixinItem
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3494 (java.lang.ClassNotFoundException: net/minecraft/class_3494)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3494 was not found fabric-tag-extensions-v0.mixins.json:MixinTag
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3494$class_3495 (java.lang.ClassNotFoundException: net/minecraft/class_3494$class_3495)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3494$class_3495 was not found fabric-tag-extensions-v0.mixins.json:MixinTagBuilder
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_2586 (java.lang.ClassNotFoundException: net/minecraft/class_2586)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_2586 was not found fabric-rendering-data-attachment-v1.mixins.json:MixinBlockEntity
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_4538 (java.lang.ClassNotFoundException: net/minecraft/class_4538)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_4538 was not found fabric-rendering-data-attachment-v1.mixins.json:MixinViewableWorld
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_1761 (java.lang.ClassNotFoundException: net/minecraft/class_1761)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_1761 was not found fabric-item-groups-v0.mixins.json:MixinItemGroup
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3222 (java.lang.ClassNotFoundException: net/minecraft/class_3222)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3222 was not found fabric-events-interaction-v0.mixins.json:MixinServerPlayerEntity
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3225 (java.lang.ClassNotFoundException: net/minecraft/class_3225)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3225 was not found fabric-events-interaction-v0.mixins.json:MixinServerPlayerInteractionManager
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3244 (java.lang.ClassNotFoundException: net/minecraft/class_3244)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3244 was not found fabric-events-interaction-v0.mixins.json:MixinServerPlayNetworkHandler
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_55$class_56 (java.lang.ClassNotFoundException: net/minecraft/class_55$class_56)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_55$class_56 was not found fabric-loot-tables-v1.mixins.json:LootPoolBuilderHooks
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_52$class_53 (java.lang.ClassNotFoundException: net/minecraft/class_52$class_53)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_52$class_53 was not found fabric-loot-tables-v1.mixins.json:LootSupplierBuilderHooks
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_60 (java.lang.ClassNotFoundException: net/minecraft/class_60)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_60 was not found fabric-loot-tables-v1.mixins.json:MixinLootManager
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_55 (java.lang.ClassNotFoundException: net/minecraft/class_55)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_55 was not found fabric-loot-tables-v1.mixins.json:MixinLootPool
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_52 (java.lang.ClassNotFoundException: net/minecraft/class_52)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_52 was not found fabric-loot-tables-v1.mixins.json:MixinLootSupplier
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_2609 (java.lang.ClassNotFoundException: net/minecraft/class_2609)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_2609 was not found fabric-content-registries-v0.mixins.json:MixinAbstractFurnaceBlockEntity
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_2358 (java.lang.ClassNotFoundException: net/minecraft/class_2358)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_2358 was not found fabric-content-registries-v0.mixins.json:MixinFireBlock
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_1297 (java.lang.ClassNotFoundException: net/minecraft/class_1297)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_1297 was not found fabric-dimensions-v1.mixins.json:EntityHooks
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_1297 (java.lang.ClassNotFoundException: net/minecraft/class_1297)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_1297 was not found fabric-dimensions-v1.mixins.json:MixinEntity
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_1946 (java.lang.ClassNotFoundException: net/minecraft/class_1946)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_1946 was not found fabric-dimensions-v1.mixins.json:MixinPortalForcer
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_2874 (java.lang.ClassNotFoundException: net/minecraft/class_2874)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_2874 was not found fabric-dimensions-v1.mixins.json:idremap.MixinDimensionRawIndexFix
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_31 (java.lang.ClassNotFoundException: net/minecraft/class_31)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_31 was not found fabric-dimensions-v1.mixins.json:idremap.MixinLevelProperties
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_32 (java.lang.ClassNotFoundException: net/minecraft/class_32)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_32 was not found fabric-dimensions-v1.mixins.json:idremap.MixinLevelStorage
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_3324 (java.lang.ClassNotFoundException: net/minecraft/class_3324)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_3324 was not found fabric-dimensions-v1.mixins.json:idremap.MixinPlayerManager
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_27 (java.lang.ClassNotFoundException: net/minecraft/class_27)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_27 was not found fabric-dimensions-v1.mixins.json:idremap.MixinUnmodifiableLevelProperties
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_2966 (java.lang.ClassNotFoundException: net/minecraft/class_2966)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_2966 was not found fabric-registry-sync-v0.mixins.json:MixinBootstrap
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_2361 (java.lang.ClassNotFoundException: net/minecraft/class_2361)
[22:08:33] [main/WARN]: @Mixin target net.minecraft.class_2361 was not found fabric-registry-sync-v0.mixins.json:MixinIdList
[22:08:33] [main/WARN]: Error loading class: net/minecraft/class_2370 (java.lang.ClassNotFoundException: net/minecraft/class_2370)
[22:08:34] [main/WARN]: @Mixin target net.minecraft.class_2370 was not found fabric-registry-sync-v0.mixins.json:MixinIdRegistry
[22:08:34] [main/WARN]: Error loading class: net/minecraft/class_3324 (java.lang.ClassNotFoundException: net/minecraft/class_3324)
[22:08:34] [main/WARN]: @Mixin target net.minecraft.class_3324 was not found fabric-registry-sync-v0.mixins.json:MixinPlayerManager
[22:08:34] [main/WARN]: Error loading class: net/minecraft/class_29 (java.lang.ClassNotFoundException: net/minecraft/class_29)
[22:08:34] [main/WARN]: @Mixin target net.minecraft.class_29 was not found fabric-registry-sync-v0.mixins.json:MixinWorldSaveHandler
[22:08:34] [main/WARN]: Error loading class: net/minecraft/class_128 (java.lang.ClassNotFoundException: net/minecraft/class_128)
[22:08:34] [main/WARN]: @Mixin target net.minecraft.class_128 was not found fabric-crash-report-info-v1.mixins.json:MixinCrashReport
[22:08:34] [main/WARN]: Error loading class: net/minecraft/class_3222 (java.lang.ClassNotFoundException: net/minecraft/class_3222)
[22:08:34] [main/WARN]: @Mixin target net.minecraft.class_3222 was not found fabric-containers-v0.accurate.mixins.json:MixinServerPlayerEntity
[22:08:34] [main/WARN]: Error loading class: net/minecraft/class_1937 (java.lang.ClassNotFoundException: net/minecraft/class_1937)
[22:08:34] [main/WARN]: @Mixin target net.minecraft.class_1937 was not found fabric-events-lifecycle-v0.mixins.json:MixinWorld
[22:08:34] [main/WARN]: Error loading class: net/minecraft/class_3176 (java.lang.ClassNotFoundException: net/minecraft/class_3176)
[22:08:34] [main/WARN]: @Mixin target net.minecraft.class_3176 was not found fabric-commands-v0.mixins.json:MixinMinecraftDedicatedServer
[22:08:34] [main/FATAL]: Mixin apply failed fabric-resource-loader-v0.mixins.json:MixinMinecraftServer -> net.minecraft.server.MinecraftServer: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field field_4595 was not located in the target class net.minecraft.server.MinecraftServer. Using refmap fabric-resource-loader-v0-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_4595 was not located in the target class net.minecraft.server.MinecraftServer. Using refmap fabric-resource-loader-v0-refmap.json
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:610) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:289) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1250) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:539) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_232]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:191) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-resource-loader-v0.mixins.json:MixinMinecraftServer] from phase [DEFAULT] in config [fabric-resource-loader-v0.mixins.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:612)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:564)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:349)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:191)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_4595 was not located in the target class net.minecraft.server.MinecraftServer. Using refmap fabric-resource-loader-v0-refmap.json
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:610)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:289)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264)
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1250)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:539)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
        ... 16 more
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:51)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:107)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:63)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
        ... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:357)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:191)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
        ... 7 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-resource-loader-v0.mixins.json:MixinMinecraftServer] from phase [DEFAULT] in config [fabric-resource-loader-v0.mixins.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:612)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:564)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:349)
        ... 16 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_4595 was not located in the target class net.minecraft.server.MinecraftServer. Using refmap fabric-resource-loader-v0-refmap.json
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:610)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:289)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264)
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1250)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:539)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
        ... 16 more
```

**Comment by liach** [comment]
Try use fabric api 0.4.29+build.290 and Minecraft 1.15.2 (update loader as well) and see if the problem persists.

**Comment by i509VCB** [comment]
Was this resolved by chance? @MSandro

**Comment by liach** [comment]
If this is still a problem after updating, comment here and we will reopen the issue.
