### ISSUE TITLE
Fabric can't start

### ISSUE THREAD

**Issue by VENTO-off** [FabricMC/fabric#490]
`[14:17:20.526 [main] ERROR FabricLoader - Could not find valid game provider!
Exception in thread "main" java.lang.NullPointerException
	at net.fabricmc.loader.game.MinecraftGameProvider.getRawGameVersion(MinecraftGameProvider.java:70)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:93)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)](url)`

How can I solve this problem????

**Comment by liach** [comment]
Looks just like FabricMC/fabric-loader#197. Update loader, and [open new issue](https://github.com/FabricMC/fabric-loader/issues/new) in loader repo if the problem persists.
