### ISSUE TITLE
Crash "Could not execute entrypoint stage 'main' due to errors!" 20w11a version

### ISSUE THREAD

**Issue by Igruola** [FabricMC/fabric#526]
Fabric works fine until I try to play with any mod other than modlist, then it either crashes on startup or crashes when making world. There was the one time it worked, though I can't remember what mod I tried that with.

---- Minecraft Crash Report ----
// There are four lights!
 
Time: 3/12/20 1:49 PM
Description: Initializing game
 
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:55)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
    at net.minecraft.class_310.<init>(class_310.java:399)
    at net.minecraft.client.main.Main.main(Main.java:166)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
    Suppressed: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at paulevs.betternether.structures.StructureNBT.readStructureFromJar(StructureNBT.java:88)
        at paulevs.betternether.structures.StructureNBT.<init>(StructureNBT.java:31)
        at paulevs.betternether.structures.bones.StructureBoneReef.<clinit>(StructureBoneReef.java:13)
        at paulevs.betternether.biomes.NetherBoneReef.<init>(NetherBoneReef.java:12)
        at paulevs.betternether.registers.BiomesRegister.<clinit>(BiomesRegister.java:45)
        at paulevs.betternether.BetterNether.onInitialize(BetterNether.java:30)
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$1444/869085647.accept(Unknown Source)
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:48)
        ... 11 more
    Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [immersive_portals.mixins.json:MixinMinecraftServer] from phase [DEFAULT] in config [immersive_portals.mixins.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
        ... 25 more
    Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onFinishedLoadingAllWorlds could not find any targets matching 'Lnet/minecraft/server/MinecraftServer;method_3735(Ljava/lang/String;Ljava/lang/String;JLnet/minecraft/class_1942;Lcom/google/gson/JsonElement;)V' in net.minecraft.server.MinecraftServer. Using refmap immersive-portals-refmap.json [PREINJECT Applicator Phase -> immersive_portals.mixins.json:MixinMinecraftServer -> Prepare Injections ->  -> handler$zfg000$onFinishedLoadingAllWorlds(Ljava/lang/String;Ljava/lang/String;JLnet/minecraft/class_1942;Lcom/google/gson/JsonElement;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:543)
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:280)
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267)
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:259)
        at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
        at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:139)
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:595)
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1236)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
        ... 25 more
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Render thread
Stacktrace:
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:55)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
    at net.minecraft.class_310.<init>(class_310.java:399)
 
-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.main.Main.main(Main.java:166)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
 
-- System Details --
Details:
    Minecraft Version: 20w11a
    Minecraft Version ID: 20w11a
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2100813696 bytes (2003 MB) / 2650800128 bytes (2528 MB) up to 5368709120 bytes (5120 MB)
    CPUs: 4
    JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
    Fabric Mods:
        betternether: Better Nether 2.3.0
        fabric: Fabric API 0.5.3+build.308-1.16
        fabric-api-base: Fabric API Base 0.1.2+b7f9825d3d
        fabric-biomes-v1: Fabric Biomes (v1) 0.2.1+b7d52fa53d
        fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea893d
        fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d3d
        fabric-containers-v0: Fabric Containers (v0) 0.1.6+0aae0f413d
        fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d3d
        fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3d
        fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+b17265713d
        fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+04b997943d
        fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d3d
        fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.9+5b8a535a3d
        fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d63d
        fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.6+2f56dff23d
        fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+5b8a535a3d
        fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d63d
        fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.4+9421522d3d
        fabric-networking-v0: Fabric Networking (v0) 0.1.8+9421522d3d
        fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.4+b7d52fa53d
        fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d63d
        fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.7+9421522d3d
        fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.11+2f56dff23d
        fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.25+2f56dff23d
        fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a603d
        fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d3d
        fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed93d
        fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104903d
        fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104903d
        fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.12+5b8a535a3d
        fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915803d
        fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba73d
        fabricloader: Fabric Loader 0.7.8+build.187
        immersive_portals: Immersive Portals 0.2
        minecraft: Minecraft 1.16-alpha.20.11.a
        modmenu: Mod Menu 1.10.2+build.1
    Launched Version: fabric-loader-0.7.8+build.187-20w11a
    Backend library: LWJGL version 3.2.2 build 10
    Backend API: NO CONTEXT
    GL Caps:
    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'fabric'
    Type: Client (map_client.txt)
    CPU: <unknown>

**Comment by JamiesWhiteShirt** [comment]
This is an issue with Immersive Portals, not Fabric API.

19w10a broke many mods, and Immersive Portals is probably one of them. This issue affects 19w11a, too.

See if there is a newer version of Immersive Portals that you can use and report any issues you find with it to them.

**Comment by Igruola** [comment]
Got it.
I'll close this, sorry.
