### ISSUE TITLE
20w12a can't unable to start normally

### ISSUE THREAD

**Issue by nicklly** [FabricMC/fabric#540]
Hello!

I downloaded the fabric loading library from the fabric MC website
Game/Mappings version : 20w12a+build5 and 20w12a+build+2 
Loader version: 0.187+build188

When the above loading library is installed and the game is started normally,Fabric Loader is prompt error

 I have two picture and error log, hope fix!

faild to launch picture
![QQ截图20200319201428](https://user-images.githubusercontent.com/17716585/77067196-8c623c00-6a1f-11ea-95e7-973d9636b23f.png)
![QQ截图20200319201445](https://user-images.githubusercontent.com/17716585/77067204-8ec49600-6a1f-11ea-903a-2d40eaebbe36.png)

error log:
> [20:06:58] [main/INFO]: Loading for game Minecraft 20w12a
[20:07:01] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: fabric requires {minecraft @ [~1.15-alpha.19.42.a]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:169) ~[fabric-loader-0.7.8+build.188.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:602) ~[fabric-loader-0.7.8+build.188.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:177) ~[fabric-loader-0.7.8+build.188.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:167) [fabric-loader-0.7.8+build.188.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127) [fabric-loader-0.7.8+build.188.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.8+build.188.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:167) ~[fabric-loader-0.7.8+build.188.jar:?]
	... 5 more

**Comment by nicklly** [comment]
This is true whether it's downloaded from the website or via the launcher
