### ISSUE TITLE
Critical issues with launch

### ISSUE THREAD

**Issue by Kayniedude** [FabricMC/fabric#541]
While launching any fabric version it gives a fatal crash when on MacOS

`net.fabricmc.loader.discovery.ModResolutionException: Mod resolution took too long!
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:595) ~[fabric-loader-0.7.8+build.189.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:177) ~[fabric-loader-0.7.8+build.189.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:167) [fabric-loader-0.7.8+build.189.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127) [fabric-loader-0.7.8+build.189.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.8+build.189.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_241]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`

**Comment by liach** [comment]
hmm, what mods do you have?

**Comment by Kayniedude** [comment]
> hmm, what mods do you have?

I am using ModMenu, but all other mods end up the same

**Comment by liach** [comment]
hmm, did you install fabric api

**Comment by Morfeuschannel** [comment]
i too have this problem on MacOS High Sierra. My mods folder is clear, but Minecraft not starting with Fabric profile. I used Minecraft 1.15.2

**Comment by liach** [comment]
@Morfeuschannel Mind post a log of the game?

**Comment by Morfeuschannel** [comment]
@liach 
`19:06:30.583
Preparing to launch minecraft client for fabric-loader-0.7.9+build.190-1.15.2
19:06:32.051
Checking installations.
19:06:32.052
Minecraft client fabric-loader-0.7.9+build.190-1.15.2 is ready to start.
19:06:32.052
Starting!
19:06:32.096
Using default game log configuration client-1.12.xml (outputs XML)
19:06:33.239
Loading for game Minecraft 1.15.2
19:07:03.679
A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Mod resolution took too long!
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:595)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:177)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:167)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
19:07:03.776

19:07:03.776
Process crashed with exit code 1`

**Comment by liach** [comment]
Hmm, @modmuss50 consider moving this issue to loader repo.

**Comment by liach** [comment]
Guess this is a mac-specific issue then.
