### ISSUE TITLE
Fabric API 0.5.6 build 313 - can't generate worlds

### ISSUE THREAD

**Issue by Boobies** [FabricMC/fabric#543]
As suggested by the title, the client is stuck at 100% when trying to generate a new world. The Fabric API is the only one in the mods directory.

**Comment by modmuss50** [comment]
Does the log have anything in it?

**Comment by Boobies** [comment]
```
[12:35:41] [main/INFO]: Loading for game Minecraft 20w13a
[12:35:44] [main/INFO]: [FabricLoader] Loading 33 mods: fabric-renderer-api-v1@0.2.11+2f56dff2d1, minecraft@1.16-alpha.20.13.a, fabric-networking-blockentity-v0@0.2.4+9421522dd1, fabric-keybindings-v0@0.1.1+dfdb52d6d1, fabricloader@0.7.8+build.189, fabric-renderer-indigo@0.2.26+d249f7b6d1, fabric-containers-v0@0.1.7+d249f7b6d1, fabric-dimensions-v1@0.3.1+d249f7b6d1, fabric-biomes-v1@0.2.1+b7d52fa5d1, fabric-crash-report-info-v1@0.1.2+b7f9825dd1, fabric-events-interaction-v0@0.3.0+04b99794d1, fabric-api-base@0.1.2+b7f9825dd1, fabric-rendering-v0@1.1.0+53410490d1, fabric-rendering-v1@0.1.1+d249f7b6d1, fabric-rendering-data-attachment-v1@0.1.3+b7f9825dd1, fabric-resource-loader-v0@0.1.12+5b8a535ad1, fabric-textures-v0@1.0.4+821cdba7d1, fabric-content-registries-v0@0.1.3+b7f9825dd1, fabric-tag-extensions-v0@0.1.3+abd91580d1, fabric-rendering-fluids-v1@0.1.6+12515ed9d1, fabric-registry-sync-v0@0.2.8+d249f7b6d1, fabric-commands-v0@0.1.2+b7f9825dd1, fabric-blockrenderlayer-v1@1.1.4+c6a8ea89d1, fabric-mining-levels-v0@0.1.2+5b8a535ad1, fabric-renderer-registries-v1@2.0.1+5a0f9a60d1, fabric-loot-tables-v1@0.1.6+2f56dff2d1, fabric-events-lifecycle-v0@0.1.2+b7f9825dd1, fabric@0.5.5+build.311-1.16, fabric-item-groups-v0@0.1.10+d249f7b6d1, fabric-models-v0@0.1.0+dfdb52d6d1, fabric-particles-v1@0.1.1+dfdb52d6d1, fabric-object-builders-v0@0.2.1+ce6dd838d1, fabric-networking-v0@0.1.9+d249f7b6d1
[12:35:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/Bogdan/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[12:35:46] [main/INFO]: Setting user: Bogdan_L4B
[12:35:49] [main/INFO]: [Indigo] Registering Indigo renderer!
[12:35:50] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[12:35:55] [main/INFO]: Narrator library for x64 successfully loaded
[12:35:55] [main/INFO]: Reloading ResourceManager: Default, Fabric Renderer API (v1), Fabric Networking Block Entity (v0), Fabric Key Bindings (v0), Fabric Renderer - Indigo, Fabric Containers (v0), Fabric Biomes (v1), Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric API Base, Fabric Rendering (v0), Fabric Rendering (v1), Fabric Rendering Data Attachment (v1), Fabric Resource Loader (v0), Fabric Textures (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Rendering Fluids (v1), Fabric Registry Sync (v0), Fabric Commands (v0), Fabric BlockRenderLayer Registration (v1), Fabric Mining Levels (v0), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric Events Lifecycle (v0), Fabric API, Fabric Item Groups (v0), Fabric Models (v0), Fabric Object Builders (v0), Fabric Networking (v0)
[12:36:10] [main/INFO]: OpenAL initialized.
[12:36:10] [main/INFO]: Sound engine started
[12:36:10] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[12:36:10] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[12:36:10] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[12:36:10] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[12:36:10] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[12:36:10] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[12:36:10] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[12:36:11] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[12:36:11] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[12:36:11] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[12:36:32] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[12:36:32] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[12:36:32] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[12:36:32] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[12:36:32] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[12:36:34] [Server thread/INFO]: Starting integrated minecraft server version 20w13a
[12:36:34] [Server thread/INFO]: Generating keypair
[12:36:34] [Server thread/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[12:36:34] [Server thread/INFO]: Found new data pack fabric/fabric-mining-levels-v0, loading it automatically
[12:36:34] [Server thread/INFO]: Found new data pack vanilla, loading it automatically
[12:36:34] [Server thread/INFO]: Reloading ResourceManager: Default, Fabric Mining Levels (v0)
[12:36:35] [Server thread/INFO]: Loaded 6 recipes
[12:36:35] [Server thread/INFO]: Loaded 863 advancements
[12:36:39] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[12:36:39] [main/INFO]: Preparing spawn area: 0%
[12:36:39] [main/INFO]: Preparing spawn area: 0%
[12:36:40] [main/INFO]: Preparing spawn area: 1%
[12:36:40] [main/INFO]: Preparing spawn area: 2%
[12:36:41] [main/INFO]: Preparing spawn area: 5%
[12:36:41] [main/INFO]: Preparing spawn area: 6%
[12:36:42] [main/INFO]: Preparing spawn area: 10%
[12:36:42] [main/INFO]: Preparing spawn area: 13%
[12:36:43] [main/INFO]: Preparing spawn area: 17%
[12:36:43] [main/INFO]: Preparing spawn area: 22%
[12:36:44] [main/INFO]: Preparing spawn area: 23%
[12:36:44] [main/INFO]: Preparing spawn area: 23%
[12:36:45] [main/INFO]: Preparing spawn area: 34%
[12:36:45] [main/INFO]: Preparing spawn area: 41%
[12:36:46] [main/INFO]: Preparing spawn area: 45%
[12:36:46] [main/INFO]: Preparing spawn area: 51%
[12:36:47] [main/INFO]: Preparing spawn area: 56%
[12:36:47] [main/INFO]: Preparing spawn area: 58%
[12:36:48] [main/INFO]: Preparing spawn area: 68%
[12:36:48] [main/INFO]: Preparing spawn area: 75%
[12:36:49] [main/INFO]: Preparing spawn area: 81%
[12:36:50] [main/INFO]: Preparing spawn area: 84%
[12:36:50] [main/INFO]: Preparing spawn area: 84%
[12:36:50] [main/INFO]: Time elapsed: 11146 ms
[12:36:50] [Server thread/INFO]: Changing view distance to 11, from 10
[12:36:53] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2310ms or 46 ticks behind
[12:36:53] [Netty Local Client IO #0/ERROR]: Critical injection failure: LVT in net/minecraft/class_634::method_11094(Lnet/minecraft/class_2622;)V has incompatible changes at opcode 23 in callback net/minecraft/class_634::onBlockEntityUpdate.
Expected: [Lnet/minecraft/class_2586;]
   Found: [Lnet/minecraft/class_2338;]
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_634::method_11094(Lnet/minecraft/class_2622;)V has incompatible changes at opcode 23 in callback net/minecraft/class_634::onBlockEntityUpdate.
Expected: [Lnet/minecraft/class_2586;]
   Found: [Lnet/minecraft/class_2338;]
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:487)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:437)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:377)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1273)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at net.minecraft.class_635.method_12588(class_635.java:102)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at net.minecraft.class_2901.method_12594(class_2901.java:43)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at net.minecraft.class_2901.method_11054(class_2901.java:12)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at net.minecraft.class_2535.method_10759(class_2535.java:157)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at net.minecraft.class_2535.method_10770(class_2535.java:148)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at net.minecraft.class_2535.channelRead0(class_2535.java:53)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:304)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:446)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:51)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:404)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[12:36:53] [Netty Local Client IO #0/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:745)
[12:36:53] [Server thread/INFO]: Bogdan_L4B[local:E:d453f01f] logged in with entity id 312 at (-115.5, 63.0, 103.5)
[12:36:53] [Server thread/INFO]: Bogdan_L4B joined the game
[12:36:53] [Server thread/INFO]: Bogdan_L4B lost connection: Internal Exception: java.lang.ClassCastException: net.minecraft.class_3248 cannot be cast to net.minecraft.class_2602
[12:36:53] [Server thread/INFO]: Bogdan_L4B left the game
[12:36:53] [Server thread/INFO]: Stopping singleplayer server as player logged out
[12:36:54] [Server thread/INFO]: Stopping server
[12:36:54] [Server thread/INFO]: Saving players
[12:36:54] [Server thread/INFO]: Saving worlds
[12:36:54] [Server thread/INFO]: Saving chunks for level 'foobar'/minecraft:overworld
[12:36:54] [Server thread/INFO]: ThreadedAnvilChunkStorage (foobar): All chunks are saved
[12:36:54] [Server thread/INFO]: Saving chunks for level 'foobar'/minecraft:the_end
[12:36:54] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:36:54] [Server thread/INFO]: Saving chunks for level 'foobar'/minecraft:the_nether
[12:36:54] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:36:54] [Server thread/INFO]: ThreadedAnvilChunkStorage (foobar): All chunks are saved
[12:36:55] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:36:55] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:38:44] [main/INFO]: Stopping!

```
