### ISSUE TITLE
Build error SocketException end of server about 20w14a build11or 20w15a

### ISSUE THREAD

**Issue by baka4n** [FabricMC/fabric#561]
Caused by: java.net.SocketException: Unexpected end of file from server
I don't know how to solve this,Is that a bug?

**Comment by baka4n** [comment]
`
Exception in thread "pool-33-thread-4" java.lang.RuntimeException: Failed to download: fill1.ogg
	at net.fabricmc.loom.providers.MinecraftAssetsProvider.lambda$provide$0(MinecraftAssetsProvider.java:136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:706)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at net.fabricmc.loom.util.DownloadUtil.downloadIfChanged(DownloadUtil.java:84)
	at net.fabricmc.loom.providers.MinecraftAssetsProvider.lambda$provide$0(MinecraftAssetsProvider.java:134)
	... 3 more
`

**Comment by baka4n** [comment]
Normal development module builds also have problems.

**Comment by baka4n** [comment]
Such as Item registeration failed, Logger info can unable to display properly

**Comment by liach** [comment]
Use a vpn. Also this is related to [loom](https://github.com/FabricMC/fabric-loom), unrelated to the fabric api itself.

**Comment by baka4n** [comment]
> Use a vpn. Also this is related to loom, unrelated to the fabric api itself.

I used vpn, But it's still the same problem now
