### ISSUE TITLE
Fabric just doesn't work.

### ISSUE THREAD

**Issue by hokagen91** [FabricMC/fabric#585]
Well, for about few weeks it just doesn't work, crashes the game 24/7, worked about half a year great and not sure why. (Shiginima client)

2020-04-20 02:25:20,914 main ERROR Unable to move file C:\Users\User\AppData\Roaming\.minecraft\logs\latest.log to C:\Users\User\AppData\Roaming\.minecraft\logs\2020-04-20-7.log: java.nio.file.FileSystemException C:\Users\User\AppData\Roaming\.minecraft\logs\latest.log -> C:\Users\User\AppData\Roaming\.minecraft\logs\2020-04-20-7.log: Proces nie może uzyskać dostępu do pliku, ponieważ jest on używany przez inny proces.

2020-04-20 02:25:20,925 main ERROR Unable to delete file C:\Users\User\AppData\Roaming\.minecraft\logs\latest.log: java.nio.file.FileSystemException C:\Users\User\AppData\Roaming\.minecraft\logs\latest.log: Proces nie może uzyskać dostępu do pliku, ponieważ jest on używany przez inny proces.

[02:25:21] [main/INFO]: Loading for game Minecraft 1.14.4
[02:25:24] [main/WARN]: Mod `mm` (1.6) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[02:25:24] [main/INFO]: [FabricLoader] Loading 37 mods: minecraft@1.14.4, fabric-renderer-api-v1@0.1.1+591e97ae42, fabric-networking-blockentity-v0@0.2.0+c877038942, fabric-keybindings-v0@0.1.1+591e97ae42, fabricloader@0.8.2+build.194, org_zeroturnaround_zt-zip@1.13, fabric-renderer-indigo@0.1.13+591e97ae42, fabric-containers-v0@0.1.2+591e97ae42, fabric-dimensions-v1@0.1.0+369ab22e42, fabric-biomes-v1@0.1.0+591e97ae42, org_slf4j_slf4j-simple@1.7.26, fabric-crash-report-info-v1@0.1.1+591e97ae42, fabric-events-interaction-v0@0.1.1+591e97ae42, net_fabricmc_stitch@0.2.1.61, fabric-api-base@0.1.1+2ac73e7242, fabric-rendering-v0@0.1.1+591e97ae42, fabric-rendering-data-attachment-v1@0.1.1+c877038942, mm@1.6, fabric-resource-loader-v0@0.1.3+591e97ae42, fabric-textures-v0@0.1.4+591e97ae42, fabric-content-registries-v0@0.1.1+591e97ae42, fabric-tag-extensions-v0@0.1.1+591e97ae42, optifabric@0.5.2, fabric-rendering-fluids-v1@0.1.2+36f27aa342, fabric-commands-v0@0.1.1+591e97ae42, fabric-registry-sync-v0@0.2.2+591e97ae42, fabric-mining-levels-v0@0.1.0+591e97ae42, fabric-events-lifecycle-v0@0.1.1+591e97ae42, fabric-loot-tables-v1@0.1.0+591e97ae42, wurst@v7.0pre18-MC1.14.4, fabric@0.4.1+build.245-1.14, org_slf4j_slf4j-api@1.7.26, fabric-particles-v1@0.1.1+c877038942, fabric-models-v0@0.1.0+591e97ae42, fabric-item-groups-v0@0.1.0+591e97ae42, fabric-networking-v0@0.1.3+591e97ae42, fabric-object-builders-v0@0.1.1+591e97ae42
[02:25:24] [main/WARN]: Mod `net_fabricmc_stitch` (0.2.1.61) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[02:25:24] [main/WARN]: Mod `wurst` (v7.0pre18-MC1.14.4) does not respect SemVer - comparison support is limited.
[02:25:24] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/User/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[02:25:27] [main/ERROR]: Error encountered during mixin config postInit step'mixins.mm.json': Failed to setup optifine
java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:37) ~[optifabric-0.5.2.jar:?]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:289) ~[54a31128-8c5f-4e29-96e6-170e94830674.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.8.2+build.194.jar:0.8+build.18+unknown-b18.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.8.2+build.194.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_211]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:190) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.2+build.194.jar:?]
Caused by: java.lang.NoClassDefFoundError: org/spongepowered/asm/lib/ClassWriter
	at me.modmuss50.optifabric.mod.OptifineVersion.getJarType(OptifineVersion.java:66) ~[optifabric-0.5.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifineVersion.findOptifineJar(OptifineVersion.java:35) ~[optifabric-0.5.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:46) ~[optifabric-0.5.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:25) ~[optifabric-0.5.2.jar:?]
	... 16 more
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.lib.ClassWriter
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161) ~[fabric-loader-0.8.2+build.194.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at me.modmuss50.optifabric.mod.OptifineVersion.getJarType(OptifineVersion.java:66) ~[optifabric-0.5.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifineVersion.findOptifineJar(OptifineVersion.java:35) ~[optifabric-0.5.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:46) ~[optifabric-0.5.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:25) ~[optifabric-0.5.2.jar:?]
	... 16 more
java.lang.NoSuchMethodError: org.spongepowered.asm.mixin.transformer.ext.ITargetClassContext.getClassNode()Lorg/spongepowered/asm/lib/tree/ClassNode;
	at com.chocohead.mm.Extension.postApply(Extension.java:30)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:167)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:574)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Exception in thread "Client thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main.main(Main.java:155)
	... 7 more
Caused by: java.lang.NoSuchMethodError: org.spongepowered.asm.mixin.transformer.ext.ITargetClassContext.getClassNode()Lorg/spongepowered/asm/lib/tree/ClassNode;
	at com.chocohead.mm.Extension.postApply(Extension.java:30)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:167)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:574)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 14 more
2020-04-20 02:25:27,957 Client Shutdown Thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
java.lang.NoSuchMethodError: org.spongepowered.asm.mixin.transformer.ext.ITargetClassContext.getClassNode()Lorg/spongepowered/asm/lib/tree/ClassNode;
	at com.chocohead.mm.Extension.postApply(Extension.java:30)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:167)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:574)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main$2.run(Main.java:138)
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by liach** [comment]
try removing optifine and optifabric

**Comment by shedaniel** [comment]
He has outdated optifabric

**Comment by liach** [comment]
Closing as the issue reporter didn't respond in a while.
