### ISSUE TITLE
1.15.2 crashes when destroying Shulker Box with tool

### ISSUE THREAD

**Issue by mkromann** [FabricMC/fabric#591]
Crashes immediately when attempting to destroy Shulker Box with tool (at least pickaxe and shovel).

`---- Minecraft Crash Report ----
// There are four lights!

Time: 4/22/20 7:32 PM
Description: Unexpected error

org.spongepowered.asm.mixin.injection.callback.CancellationException: The call method_7370 is not cancellable.
	at org.spongepowered.asm.mixin.injection.callback.CallbackInfo.cancel(CallbackInfo.java:101)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable.setReturnValue(CallbackInfoReturnable.java:106)
	at net.minecraft.class_1661.handler$zdm000$actMiningSleed(class_1661.java:771)
	at net.minecraft.class_1661.method_7370(class_1661.java)
	at net.minecraft.class_1657.method_7351(class_1657.java:767)
	at net.minecraft.class_2248.method_9594(class_2248.java:616)
	at net.minecraft.class_2680.method_11589(class_2680.java:174)
	at net.minecraft.class_636.method_2910(class_636.java:163)
	at net.minecraft.class_310.method_1536(class_310.java:1307)
	at net.minecraft.class_310.method_1508(class_310.java:1595)
	at net.minecraft.class_310.method_1574(class_310.java:1445)
	at net.minecraft.class_310.method_1523(class_310.java:964)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.injection.callback.CallbackInfo.cancel(CallbackInfo.java:101)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable.setReturnValue(CallbackInfoReturnable.java:106)
	at net.minecraft.class_1661.handler$zdm000$actMiningSleed(class_1661.java:771)
	at net.minecraft.class_1661.method_7370(class_1661.java)
	at net.minecraft.class_1657.method_7351(class_1657.java:767)
	at net.minecraft.class_2248.method_9594(class_2248.java:616)
	at net.minecraft.class_2680.method_11589(class_2680.java:174)
	at net.minecraft.class_636.method_2910(class_636.java:163)
	at net.minecraft.class_310.method_1536(class_310.java:1307)
	at net.minecraft.class_310.method_1508(class_310.java:1595)

-- Affected level --
Details:
	All players: 1 total; [class_746['Infuscu'/26962, l='MpServer', x=-249.05, y=65.50, z=12.25]]
	Chunk stats: Client Chunk Cache: 729, 441
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -4698509878233113638
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-240,69,49), Chunk: (at 0,4,1 in -15,3; contains blocks -240,0,48 to -225,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 129393 game time, 44995592 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:450)
	at net.minecraft.class_310.method_1587(class_310.java:1921)
	at net.minecraft.class_310.method_1514(class_310.java:639)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1439733856 bytes (1373 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.5.13+build.297-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+003643510c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.4+ec951ea40c
		fabric-particles-v1: fabric-particles-v1 0.1.2+ad2f81bd0c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+003643510c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.0.0+ec951ea40c
		fabricloader: Fabric Loader 0.8.2+build.194
		minecraft: Minecraft 1.15.2
	Launched Version: fabric-loader-0.8.2+build.194-1.15.2
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Intel HD Graphics 5000 OpenGL Engine GL version 2.1 INTEL-12.10.16, Intel Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: file/VanillaTweaks_r246731, vanilla
	Current Language: English (United Kingdom)
	CPU: 4x Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz`

**Comment by shedaniel** [comment]
Update Fabric API

**Comment by mkromann** [comment]
> Update Fabric API

I am using build 296 which seems to be the latest for 1.15.2. 

Where is the newer version located?

**Comment by mkromann** [comment]
Seems like there is a discrepancy between the filename and the log versioning?

File (from Curseforge):
`fabric-api-0.5.12+build.296-1.15.jar`

Log:
`fabric: Fabric API 0.5.13+build.297-1.15`

**Comment by shedaniel** [comment]
Oh nvm, we took down the problematic versions, can you go download https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/2935111 again just to be sure

**Comment by mkromann** [comment]
Tested again but same issue.

**Comment by LemmaEOF** [comment]
We'll be fixing this shortly, hopefully. I messed up when writing this update.

**Comment by LemmaEOF** [comment]
@liach Shedaniel is fixing this right now over in #589.

**Comment by shedaniel** [comment]
Well this should be fixed in the latest fabric api as the method that is being cancelling now actually have a cancellable = true flag

**Comment by Player3324** [comment]
I pushed a fix for this shortly after the problem originally surfaced, build 298 (for 1.15) or later should work
