### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by KingDems26** [FabricMC/fabric#877]
**Hello, I am making a server for me and my friends and after I upload the mods we want to use it won't start here is what is says.**

[main/FATAL]: Failed to start the minecraft server

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'torchkey'!

at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]

at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]

at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]

at net.minecraft.server.Main.main(Main.java:125) [intermediary-server.jar:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-server-launch.jar:?]

at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]

at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]

at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]

at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]

Caused by: java.lang.NoClassDefFoundError: net.minecraft.class_304

at net.torchkey.Torchkey.onInitialize(Torchkey.java:24) ~[torchkey-1.0.1.jar:?]

at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer$$Lambda$2295.000000009DE49030.accept(Unknown Source) ~[?:?]

at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]

... 17 more

Caused by: java.lang.ClassNotFoundException: net.minecraft.class_304

at java.net.URLClassLoader.findClass(URLClassLoader.java:591) ~[?:1.8.0_212]

at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:946) ~[?:1.8.0_212]

at java.lang.ClassLoader.loadClass(ClassLoader.java:891) ~[?:1.8.0_212]

at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_212]

at java.lang.ClassLoader.loadClass(ClassLoader.java:874) ~[?:1.8.0_212]

at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]

at java.lang.ClassLoader.loadClass(ClassLoader.java:874) ~[?:1.8.0_212]

at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161) ~[fabric-server-launch.jar:?]

at java.lang.ClassLoader.loadClass(ClassLoader.java:874) ~[?:1.8.0_212]

at net.torchkey.Torchkey.onInitialize(Torchkey.java:24) ~[torchkey-1.0.1.jar:?]

at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer$$Lambda$2295.000000009DE49030.accept(Unknown Source) ~[?:?]

at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]

... 17 more

**Comment by Earthcomputer** [comment]
You are trying to load a mod "TorchKey" which does not run on the dedicated server. If this is meant to be a client-side mod, remove it from the server mods folder. Otherwise, report it to the author of "TorchKey".

**Comment by KingDems26** [comment]
thx I will test that

**Comment by KingDems26** [comment]
It fixed it thanx soo much for your help
