### ISSUE TITLE
When "ti" typed into mod search bar the game crashes

### ISSUE THREAD

**Issue by Random375** [FabricMC/fabric#966]
This is the crash report details:

---- Minecraft Crash Report ----
// There are four lights!

Time: 29/07/20 16:22
Description: charTyped event handler

java.lang.NoClassDefFoundError: me/shedaniel/clothconfig2/api/ConfigEntryBuilder
	at me.sargunvohra.mcmods.autoconfig1u.gui.DefaultGuiProviders.<clinit>(DefaultGuiProviders.java:33)
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig$ClientOnly.<clinit>(AutoConfig.java:81)
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig.getConfigScreen(AutoConfig.java:71)
	at me.sargunvohra.mcmods.autoconfig1u.example.ExampleModMenuCompat.lambda$getModConfigScreenFactory$0(ExampleModMenuCompat.java:19)
	at me.sargunvohra.mcmods.autoconfig1u.example.ExampleModMenuCompat$$Lambda$2219/1212178180.create(Unknown Source)
	at io.github.prospector.modmenu.ModMenu.hasConfigScreenFactory(ModMenu.java:45)
	at io.github.prospector.modmenu.util.ModListSearch.passesFilters(ModListSearch.java:40)
	at io.github.prospector.modmenu.util.ModListSearch.lambda$search$0(ModListSearch.java:25)
	at io.github.prospector.modmenu.util.ModListSearch$$Lambda$3121/904187660.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.github.prospector.modmenu.util.ModListSearch.search(ModListSearch.java:26)
	at io.github.prospector.modmenu.gui.ModListWidget.filter(ModListWidget.java:141)
	at io.github.prospector.modmenu.gui.ModListWidget.filter(ModListWidget.java:121)
	at io.github.prospector.modmenu.gui.ModsScreen.lambda$init$0(ModsScreen.java:104)
	at io.github.prospector.modmenu.gui.ModsScreen$$Lambda$3099/2095166462.accept(Unknown Source)
	at net.minecraft.class_342.method_1874(class_342.java:146)
	at net.minecraft.class_342.method_1867(class_342.java:141)
	at net.minecraft.class_342.method_25400(class_342.java:353)
	at io.github.prospector.modmenu.gui.ModsScreen.method_25400(ModsScreen.java:241)
	at net.minecraft.class_309.method_1458(class_309.java:424)
	at net.minecraft.class_309$$Lambda$3120/1112264034.run(Unknown Source)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_309.method_1457(class_309.java:424)
	at net.minecraft.class_309.method_22677(class_309.java:439)
	at net.minecraft.class_309$$Lambda$3119/888879515.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_309.method_22675(class_309.java:439)
	at net.minecraft.class_309$$Lambda$2424/575967643.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:39)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1041)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.ClassNotFoundException: me.shedaniel.clothconfig2.api.ConfigEntryBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 49 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.sargunvohra.mcmods.autoconfig1u.gui.DefaultGuiProviders.<clinit>(DefaultGuiProviders.java:33)
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig$ClientOnly.<clinit>(AutoConfig.java:81)
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig.getConfigScreen(AutoConfig.java:71)
	at me.sargunvohra.mcmods.autoconfig1u.example.ExampleModMenuCompat.lambda$getModConfigScreenFactory$0(ExampleModMenuCompat.java:19)
	at me.sargunvohra.mcmods.autoconfig1u.example.ExampleModMenuCompat$$Lambda$2219/1212178180.create(Unknown Source)
	at io.github.prospector.modmenu.ModMenu.hasConfigScreenFactory(ModMenu.java:45)
	at io.github.prospector.modmenu.util.ModListSearch.passesFilters(ModListSearch.java:40)
	at io.github.prospector.modmenu.util.ModListSearch.lambda$search$0(ModListSearch.java:25)
	at io.github.prospector.modmenu.util.ModListSearch$$Lambda$3121/904187660.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.github.prospector.modmenu.util.ModListSearch.search(ModListSearch.java:26)
	at io.github.prospector.modmenu.gui.ModListWidget.filter(ModListWidget.java:141)
	at io.github.prospector.modmenu.gui.ModListWidget.filter(ModListWidget.java:121)
	at io.github.prospector.modmenu.gui.ModsScreen.lambda$init$0(ModsScreen.java:104)
	at io.github.prospector.modmenu.gui.ModsScreen$$Lambda$3099/2095166462.accept(Unknown Source)
	at net.minecraft.class_342.method_1874(class_342.java:146)
	at net.minecraft.class_342.method_1867(class_342.java:141)
	at net.minecraft.class_342.method_25400(class_342.java:353)
	at io.github.prospector.modmenu.gui.ModsScreen.method_25400(ModsScreen.java:241)
	at net.minecraft.class_309.method_1458(class_309.java:424)
	at net.minecraft.class_309$$Lambda$3120/1112264034.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: io.github.prospector.modmenu.gui.ModsScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_309.method_1457(class_309.java:424)
	at net.minecraft.class_309.method_22677(class_309.java:439)
	at net.minecraft.class_309$$Lambda$3119/888879515.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_309.method_22675(class_309.java:439)
	at net.minecraft.class_309$$Lambda$2424/575967643.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:39)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1041)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1030499488 bytes (982 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 2.2.0
		dynamicfps: Dynamic FPS 1.1.4
		fabric: Fabric API 0.15.0+build.379-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f7c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a977402
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad602
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.3+013e49d202
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e02
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.9.0+build.204
		lithium: Lithium 0.5.1
		logical_zoom: Logical Zoom 0.0.4
		minecraft: Minecraft 1.16.1
		modmenu: Mod Menu 1.14.5+build.30
		phosphor: Phosphor 0.6.0+build.7
		sodium: Sodium 0.1.0
		worldedit: WorldEdit 7.2.0-beta-01+0eb9ac7
		xaerominimap: Xaero's Minimap 20.17.0
	Launched Version: fabric-loader-0.9.0+build.204-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics GL version 4.4.0 - Build 20.19.15.5107, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Pentium(R) CPU N3700 @ 1.60GHz

**Comment by liach** [comment]
fabric api does not add a mod search bar. this looks like some issue with autoconfig and cloth config.

**Comment by uiytt** [comment]
Can someone close this please ?
