### ISSUE TITLE
Registry Sync Fails?

### ISSUE THREAD

**Issue by TheBrokenRail** [FabricMC/fabric#967]
The datapacks fail to load and the safe mode screen shows:
```
[15:07:58] [main/WARN] (Minecraft) Failed to load datapacks, can't proceed with server load
 java.lang.IndexOutOfBoundsException: Index (1) is greater than or equal to list size (0)
	at it.unimi.dsi.fastutil.objects.ObjectArrayList.set(ObjectArrayList.java:352) ~[fastutil-8.2.1.jar:?]
	at net.minecraft.util.registry.SimpleRegistry.remap(SimpleRegistry.java:844) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:281) ~[fabric-registry-sync-v0-0.4.0+bf0e62bda7@net.fabricmc.yarn.1_16_2_pre1.1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.world.level.storage.LevelStorage$Session.fabric_readIdMapFile(LevelStorage.java:588) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.world.level.storage.LevelStorage$Session.handler$zda000$readWorldProperties(LevelStorage.java:664) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.world.level.storage.LevelStorage$Session.readLevelProperties(LevelStorage.java) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.createSaveProperties(MinecraftClient.java:1679) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.method_29604(MinecraftClient.java:1902) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient.java:1749) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient.java:1693) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.start(WorldListWidget.java:407) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.play(WorldListWidget.java:317) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.mouseClicked(WorldListWidget.java:254) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.gui.widget.EntryListWidget.mouseClicked(EntryListWidget.java:331) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:27) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:92) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:435) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:92) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.Mouse.method_22686(Mouse.java:162) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:94) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.Mouse.method_22684(Mouse.java:162) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127) [minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1043) [minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:653) [minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.0+build.204@net.fabricmc.yarn.1_16_2_pre1.1.16.2-pre1+build.1-v2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.0+build.204@net.fabricmc.yarn.1_16_2_pre1.1.16.2-pre1+build.1-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.0+build.204@net.fabricmc.yarn.1_16_2_pre1.1.16.2-pre1+build.1-v2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]

```

**Comment by modmuss50** [comment]
What minecraft version? And can I have the full log please?

**Comment by TheBrokenRail** [comment]
Sorry, I am running 1.16.2-Pre1 in a dev environment, API version: ```0.16.1+build.387-1.16```

Log:
```
[15:04:25] [main/INFO] (FabricLoader) Loading for game Minecraft 1.16.2-pre1
[15:04:25] [main/INFO] (Fabric|Loader) [FabricLoader] Loading 46 mods: minecraft@1.16.2-beta.1, fabric-renderer-api-v1@0.2.13+eae12eb8a7, fabric-networking-blockentity-v0@0.2.5+b50ffc7ba7, fabric-screen-handler-api-v1@1.1.0+87249841a7, fabric-keybindings-v0@0.2.0+3fa9f7c5a7, modmenu@1.14.5+build.30, fabric-command-api-v1@1.0.8+5ce53398a7, cloth-basic-math@0.5.1, fabricloader@0.9.0+build.204, energonrelics@0.0.1, fabric-tool-attribute-api-v1@1.2.0+d21d4635a7, fabric-renderer-indigo@0.3.4+5d32f583a7, fabric-containers-v0@0.1.8+045df74fa7, fabric-object-builder-api-v1@1.5.6+ba4afa57a7, fabric-biomes-v1@1.0.2+d3726004a7, fabric-item-api-v1@1.0.0+16acbe5ba7, fabric-crash-report-info-v1@0.1.2+b7f9825da7, fabric-events-interaction-v0@0.3.3+7066030fa7, fabric-game-rule-api-v1@1.0.0+deaf4831a7, fabric-api-base@0.1.3+12a8474ca7, fabric-rendering-v0@1.1.0+53410490a7, fabric-key-binding-api-v1@1.0.1+730711c6a7, fabric-rendering-v1@1.1.2+346247d7a7, cloth-config2@4.7.0-unstable, fabric-rendering-data-attachment-v1@0.1.3+b7f9825da7, fabric-resource-loader-v0@0.2.8+35e08e33a7, autoconfig1u@3.2.0-unstable, fabric-textures-v0@1.0.4+eae12eb8a7, fabric-content-registries-v0@0.1.9+059ea866a7, fabric-tag-extensions-v0@1.0.1+35e08e33a7, fabric-rendering-fluids-v1@0.1.8+b7084faaa7, fabric-registry-sync-v0@0.4.0+bf0e62bda7, fabric-commands-v0@0.2.0+52d30836a7, fabric-blockrenderlayer-v1@1.1.4+c6a8ea89a7, fabric-lifecycle-events-v1@1.1.0+3b4b2c13a7, fabric-mining-levels-v0@0.1.2+b764ce99a7, fabric-renderer-registries-v1@2.0.1+5a0f9a60a7, fabric-loot-tables-v1@1.0.0+fac8f366a7, fabric-events-lifecycle-v0@0.2.0+16acbe5ba7, fabric@0.16.1+build.387-1.16, libstructure@1.4.1, fabric-item-groups-v0@0.2.0+438f9636a7, fabric-particles-v1@0.2.1+0a6f2a70a7, fabric-models-v0@0.1.0+dfdb52d6a7, fabric-networking-v0@0.1.10+e00ecb5fa7, fabric-object-builders-v0@0.6.1+ba4afa57a7
[15:04:25] [main/INFO] (mixin) SpongePowered MIXIN Subsystem Version=0.8 Source=file:/home/connor/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.8+build.18/af077ad2845a00cde186fa2c99c4dd32bd2a2766/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[15:04:25] [main/INFO] (Fabric|MixinBootstrap) Loaded Fabric development mappings for mixin remapper!
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-networking-v0-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-networking-blockentity-v0-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-biomes-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-screen-handler-api-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-lifecycle-events-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-containers-v0-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-renderer-indigo-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-rendering-data-attachment-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-item-api-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-events-interaction-v0-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-loot-tables-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-object-builder-api-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-renderer-registries-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-textures-v0-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-registry-sync-v0-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-models-v0-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-blockrenderlayer-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-renderer-api-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-containers-v0-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-rendering-fluids-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-resource-loader-v0-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-game-rule-api-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-particles-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap libstructure-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-object-builders-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-tag-extensions-v0-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-tool-attribute-api-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-rendering-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-item-groups-v0-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-content-registries-v0-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-command-api-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-crash-report-info-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-key-binding-api-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap fabric-renderer-api-v1-refmap.json using remapper chain
[15:04:26] [main/INFO] (mixin) Remapping refMap modmenu.refmap.json using remapper chain
[15:04:26] [main/WARN] (mixin) @Mixin target net/minecraft/server/world/ThreadedAnvilChunkStorage$EntityTracker is public in fabric-networking-v0.mixins.json:MixinEntityTracker and should be specified in value
[15:04:26] [main/WARN] (mixin) @Mixin target net/minecraft/client/render/block/BlockModelRenderer$AmbientOcclusionCalculator is public in fabric-renderer-indigo.mixins.json:MixinAmbientOcclusionCalculator and should be specified in value
[15:04:26] [main/WARN] (mixin) @Mixin target net/minecraft/client/render/chunk/ChunkBuilder$BuiltChunk$RebuildTask is public in fabric-renderer-indigo.mixins.json:MixinChunkRebuildTask and should be specified in value
[15:04:26] [main/WARN] (mixin) @Mixin target net/minecraft/server/command/GameRuleCommand$1 is public in fabric-game-rule-api-v1.mixins.json:GameRuleCommandVisitorMixin and should be specified in value
[15:04:26] [main/WARN] (mixin) @Mixin target net/minecraft/client/gui/screen/world/EditGameRulesScreen$RuleListWidget$1 is public in fabric-game-rule-api-v1.mixins.json:client.RuleListWidgetVisitorMixin and should be specified in value
[15:04:26] [main/WARN] (mixin) @Mixin target net/minecraft/client/particle/ParticleManager$SimpleSpriteProvider is public in fabric-particles-v1.mixins.json:ParticleManagerAccessor$SimpleSpriteProviderAccessor and should be specified in value
[15:04:26] [main/WARN] (mixin) @Mixin target net/minecraft/tag/Tag$1 is public in fabric-tag-extensions-v0.mixins.json:MixinTagImpl and should be specified in value
[15:04:26] [main/WARN] (mixin) Error loading class: net/minecraft/tag/GlobalTagAccessor$CachedTag (java.lang.ClassNotFoundException: net/minecraft/tag/GlobalTagAccessor$CachedTag)
[15:04:26] [main/WARN] (mixin) @Mixin target net/minecraft/tag/GlobalTagAccessor$CachedTag was not found fabric-tag-extensions-v0.mixins.json:MixinTagImpl
[15:04:26] [main/WARN] (mixin) @Mixin target net/minecraft/client/gui/widget/EntryListWidget$Entries is public in mixins.modmenu.json:MixinEntryListWidgetEntries and should be specified in value
[15:04:33] [main/INFO] (Minecraft) Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[15:04:33] [main/INFO] (Minecraft) Setting user: Player293
[15:04:34] [main/INFO] (Indigo) [Indigo] Registering Indigo renderer!
[15:04:34] [main/INFO] (Minecraft) Backend library: LWJGL version 3.2.2 build 10
[15:04:38] [main/INFO] (Minecraft) Narrator library successfully loaded
[15:04:39] [main/INFO] (Minecraft) Reloading ResourceManager: Default, Fabric Renderer API (v1), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Fabric Key Bindings (v0), Mod Menu, Fabric Loader, EnergonRelics, Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Containers (v0), Fabric Object Builder API (v1), Fabric Biomes (v1), Fabric Item API (v1), Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Cloth Config v4, Fabric Rendering Data Attachment (v1), Fabric Resource Loader (v0), Auto Config v1 Updated, Fabric Textures (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Rendering Fluids (v1), Fabric Registry Sync (v0), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Mining Levels (v0), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric Events Lifecycle (v0), Fabric API, Fabric Item Groups (v0), Fabric Models (v0), Fabric Networking (v0), Fabric Object Builders (v0)
[15:04:41] [Realms Notification Availability checker #1/INFO] (Minecraft) Could not authorize you against Realms server: Invalid session id
[15:04:47] [main/INFO] (Minecraft) OpenAL initialized.
[15:04:47] [main/INFO] (Minecraft) Sound engine started
[15:04:48] [main/INFO] (Minecraft) Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[15:04:48] [main/INFO] (Minecraft) Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[15:04:48] [main/INFO] (Minecraft) Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[15:04:48] [main/INFO] (Minecraft) Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[15:04:48] [main/INFO] (Minecraft) Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[15:04:48] [main/INFO] (Minecraft) Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[15:04:48] [main/INFO] (Minecraft) Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[15:04:49] [main/INFO] (Minecraft) Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[15:04:49] [main/INFO] (Minecraft) Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[15:04:49] [main/INFO] (Minecraft) Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[15:05:03] [main/WARN] (Minecraft) Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[15:05:03] [main/WARN] (Minecraft) Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:05:03] [main/WARN] (Minecraft) Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:05:03] [main/WARN] (Minecraft) Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[15:05:03] [main/WARN] (Minecraft) Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:05:03] [main/INFO] (Minecraft) Reloading ResourceManager: Default, Fabric Renderer API (v1), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Fabric Key Bindings (v0), Mod Menu, Fabric Loader, EnergonRelics, Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Containers (v0), Fabric Object Builder API (v1), Fabric Biomes (v1), Fabric Item API (v1), Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Cloth Config v4, Fabric Rendering Data Attachment (v1), Fabric Resource Loader (v0), Auto Config v1 Updated, Fabric Textures (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Rendering Fluids (v1), Fabric Registry Sync (v0), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Mining Levels (v0), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric Events Lifecycle (v0), Fabric API, Fabric Item Groups (v0), Fabric Models (v0), Fabric Networking (v0), Fabric Object Builders (v0), Fabric Tool Attribute API (v1), EnergonRelics
[15:05:03] [main/INFO] (Minecraft) Loaded 7 recipes
[15:05:03] [main/INFO] (Minecraft) Loaded 927 advancements
[15:05:03] [main/WARN] (Minecraft) Failed to load datapacks, can't proceed with server load
 java.lang.IndexOutOfBoundsException: Index (1) is greater than or equal to list size (0)
	at it.unimi.dsi.fastutil.objects.ObjectArrayList.set(ObjectArrayList.java:352) ~[fastutil-8.2.1.jar:?]
	at net.minecraft.util.registry.SimpleRegistry.remap(SimpleRegistry.java:844) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:281) ~[fabric-registry-sync-v0-0.4.0+bf0e62bda7@net.fabricmc.yarn.1_16_2_pre1.1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.world.level.storage.LevelStorage$Session.fabric_readIdMapFile(LevelStorage.java:588) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.world.level.storage.LevelStorage$Session.handler$zda000$readWorldProperties(LevelStorage.java:664) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.world.level.storage.LevelStorage$Session.readLevelProperties(LevelStorage.java) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.createSaveProperties(MinecraftClient.java:1679) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.method_29604(MinecraftClient.java:1902) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient.java:1749) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient.java:1693) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.start(WorldListWidget.java:407) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.play(WorldListWidget.java:317) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.mouseClicked(WorldListWidget.java:254) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.gui.widget.EntryListWidget.mouseClicked(EntryListWidget.java:331) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:27) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:92) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:435) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:92) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.Mouse.method_22686(Mouse.java:162) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:94) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.Mouse.method_22684(Mouse.java:162) ~[minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127) [minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1043) [minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:653) [minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [minecraft-1.16.2-pre1-mapped-net.fabricmc.yarn-1.16.2-pre1+build.1-v2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.0+build.204@net.fabricmc.yarn.1_16_2_pre1.1.16.2-pre1+build.1-v2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.0+build.204@net.fabricmc.yarn.1_16_2_pre1.1.16.2-pre1+build.1-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.0+build.204@net.fabricmc.yarn.1_16_2_pre1.1.16.2-pre1+build.1-v2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```

**Comment by modmuss50** [comment]
can confirm, working on a fix.

**Comment by modmuss50** [comment]
Easy fix, will be out in the next version shortly

**Comment by TheBrokenRail** [comment]
Thanks!
